### PR TITLE
Fix shell history creation regression

### LINKED ISSUE #3482: Shell history file does not get created if it does not exist
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Fedora 39

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

`~/.config/dosbox/shell_history.txt` does not get initially created if it does not already exist.  I have not done a full bisect but it was working before #3093 got merged so I'm 95% sure it is a regression in that PR somewhere.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Delete `~/.config/dosbox/shell_history.txt`
2.  Start Dosbox
3. Type a command
4.  Exit Dosbox
5.  Shell history does not get saved

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by MeAreJeenius**
# Description

When moving the shell history to its own class, I opted to have the path cleared if the ifstream failed to open. This was because if the file couldn't be read but could still be written to (ie. strange file permissions), it would delete whatever was in the history file.

Seems that I failed to consider the obvious case where the file doesn't exist in the first place.

This fix includes a check to ensure that the file exists before clearing the path when the ifstream fails. 

## Related issues

Should resolve #3482

# Manual testing

Added a manual test to ensure a shell history file is created if none exists.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/shell/shell_history.cpp [hunk 1]
```diff
@@ -81,7 +81,9 @@ ShellHistory::ShellHistory() : path(get_shell_history_path())
 	}
 	auto history_file = std::ifstream(path);
 	if (!history_file) {
-		path.clear();
+		if (std::filesystem::exists(path)) {
+			path.clear();
+		}
 		return;
 	}
```
Comment (weirddan455) [inline src/shell/shell_history.cpp:88]: >  When moving the shell history to its own class, I opted to have the path cleared if the ifstream failed to open. This was because if the file couldn't be read but could still be written to (ie. strange file permissions), it would delete whatever was in the history file.

I don't follow this logic.  `std::ofstream` truncates by default so we are always erasing and replacing the contents of the file.  If you want to handle invalid permissions, maybe log a warning but I don't see what clearing the path accomplishes.

**Comment by weirddan455** [comment]
@johnnovak PVS is trying to run on this PR since your recent change but it looks like it's failing to read a license file or something.

**Review by johnnovak — APPROVED** [review]

**Comment by johnnovak** [comment]
Thanks for the quick fix @MeAreJeenius.

File: src/shell/shell_history.cpp (hunk 1 above)
Comment (weirddan455) [reply src/shell/shell_history.cpp:88]: That's fair.  I would still suggest logging a warning when this happens instead of silently failing.

**Comment by johnnovak** [comment]
> @johnnovak Just so you know, the CI jobs are running on my fork whenever I synchronize or push an update. I have a strong feeling that's not intended.

They absolutely must run, it's intended. If they didn't run, any number of warnings could slip through from non-core member contributions—we don't want that, of course.

What bothers me is that the PVS-Studio workflow apparently can't run on contributor-raised PRs. Something to do with secrets, most likely (the license keys are stored as a GitHub Actions secret). Hopefully we can figure out a solutions for this later because know we just don't know if your PR will introduce extra PVS-Studio warnings... That's not great.

**Review by weirddan455 — APPROVED** [review]
I doubt this PR will introduce PVS warnings but we should figure out what's going on there.

In any case, this fix looks good to me now.  Thanks for the quick fix @MeAreJeenius

**Comment by johnnovak** [comment]
> @johnnovak I don't mean running on the PR to this repo, that's obviously intended.
> 
> What I'm talking about is in my forked repository. When I synchronize my main branch to this repo, the jobs are run on the HEAD commit. When I made the branch, the jobs were run before I even made the PR.

@MeAreJeenius Okay, I got it now. Thanks for bringing this to my attention. I've done some reading, and I think I better understand the workflow situation with forked PRs.

> This wasn't happening before this PR (unless I'm going crazy).

It must have always behaved the same way as we haven't made fundamental changes to these workflows lately. Maybe you were just not really paying attention to it.

> I don't know much about the project's CI situation or GitHub actions in general, but it feels a bit like it's open for abuse. Anyone who forks the repo is getting free compute power courtesy of dosbox-staging. If there are any CI usage limits, anyone could just blow past them.

So I've looked into it, and if any random contributor raises a forked PR, a core team member with write or admin access to the DOSBox Staging repo must manually approve the workflow runs first. Nothing will run unless that approval is granted. I did run into this a couple of times in the past weeks from first-time contributors, and I can confirm it works as expected. That's a good first line of defence against random forked PRs or "PR bombing".

In your case, you are on our trusted list of collaborators with "read" access, which is probably why the workflows run without manual approval in your forked PRs.

In any case, if we notice any abusive patterns from random people, there's a handy ban feature so we can swiftly terminate the user's rights to any future interaction with our repos 😎 Luckily, we needed to use that feature very rarely so far 🤞🏻

> Again, I'm not knowledgeable on dosbox-staging's CI pipeline, so it's entirely possible I'm misreading the situation.

It's all good—I think we've both learned something from this.

In other news, I think I solved the PVS-Studio problem with forked PRs. Can you rebase off main once again please? [This change of mine](https://github.com/dosbox-staging/dosbox-staging/commit/9a04ee9bcb2a859400ec7f338a7303665b61bbab) should take care of the problem.

**Comment by johnnovak** [comment]
The PVS-Studio workflow ran successfully, yay! 🎉 Merging (the broken macOS workflow is a known issue, we'll fix that in the coming days and it's unrelated).
