### PR TITLE
Avoid dropping the last character when appending shell commands

### LINKED ISSUE #623: Environment variables not resolved properly in AUTOEXEC
**Describe the bug**
It seems that environment variables are not resolved properly if used with autoexec section in config file, specifically it doesn't parse slashes properly.

**To Reproduce**
Add the following entry to autoexec section in config:
```
set PATH=%PATH%;C:\TEST\
```
PATH defaults to ``Z:\``  but if you use it here, the command will discard everything after a slash and end up setting PATH to ``Z:``.

**Expected behaviour**
PATH variable is set to ``Z:\;C:\TEST\``.

**Additional context**

- Issue does not happen if I fire this command in the actual DosBox command line after it launched.
- Issue does not happen if I don't use an env var and put this into autoexec instead:
```
set PATH=Z:\;C:\TEST\
```
- Issue does not happen in upstream so this is a regression.

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #623 

**Tests:**
- Pre-expansion
- Post-expansion
- Multi-char expansion
- With and without trailing backslash
- Single character variables

``` ini
[autoexec]
mount c .
set PATH=%PATH%;C:\
PATH
set PATH=%PATH%;A;B;D
PATH
set PATH=%PATH%;E:
PATH
set PATH=F:\;%PATH%;G:\
PATH
```

**Produces:**

Tested countless other typical commands (both inside `[autoexec]` and entered at runtime), including: `mount`, `imgmount`, `cd`, `echo`, `@echo off`, `autotype`, `exit`, batch execution w/ `choice.exe` and `goto` statements -- all without  regressions.

@NicknineTheEagle, can you give this a whirl?

### CODE REVIEW

**Comment by NicknineTheEagle** [comment]
Alright, my original issue seems to be fixed:
image

**Comment by kcgen** [comment]
Thanks for the quick confirmation @NicknineTheEagle.

**Comment by dreamer** [comment]
> Alright, my original issue seems to be fixed:
> image

That's the behaviour *without* this PR change as well (at least on Linux).

**Comment by NicknineTheEagle** [comment]
> 
> 
> > Alright, my original issue seems to be fixed:
> > image
> 
> That's the behaviour _without_ this PR change as well (at least on Linux) - both in autoexec and when typed in shell.

You can't see it here but I have %PATH% in my config file which expands properly now as seen in the screenshot.

File: src/shell/shell_batch.cpp [hunk 1]
```diff
@@ -124,8 +124,9 @@ bool BatchFile::ReadLine(char * line) {
 	auto append_cmd_write = [&cmd_write, &line](const char *src) {
 		const auto src_len = strlen(src);
 		const auto req_len = cmd_write - line + static_cast<int>(src_len);
-		if (req_len < CMD_MAXLINE - 1) {
-			safe_strncpy(cmd_write, src, src_len);
+		if (src_len && req_len < CMD_MAXLINE - 1) {
+			// include the terminating null in the source length
+			safe_strncpy(cmd_write, src, src_len + 1);
```
Comment (dreamer) [inline src/shell/shell_batch.cpp:129]: Eh, I spent a few minutes not understanding why this fix works at all… because I had a mental model of using our `safe_strncpy(dst, src)` (backed up by `snprintf`), and it confused me...

Turns out, we both made the mistake when writing/reviewing this lambda expression.

```C++
// include the terminating null in the source length
```
This comment is a little bit misleading, because it suggests that `safe_strncpy` does not append the terminating null (it does). If I were to write accurate comment, it would be something like: *"pretend that string is one byte longer when using fake buffer len in 3rd parameter, so that safe_strncpy won't overwrite the last byte of copied string with null byte"*.

The real problem in here is different:
```C++
safe_strncpy(cmd_write, src, src_len + 1);
```
This line is incorrect. 3rd parameter to `safe_strncpy` is supposed to be *size of the available buffer*, not *length of the string we are putting into the buffer*. We don't have buffer overflow because of lines 126 and 127.

I'm not sure how the proper fix should look like ATM (using `req_len` as the third parameter to `safe_strncpy(d,s,n)` might be ok).

The root-cause of the problem is that `safe_strncpy` macro is, in fact, *not really that safe*, and confusing to use :(


--
I had this warning pop out to me in GCC some time ago (I haven't paid attention to it back then, because it disappears when compiling with -Wall, which *might be a bug in GCC, because this warning indicates exactly the bug we have in here*).



```
shell_batch.cpp: In member function ‘virtual bool BatchFile::ReadLine(char*)’:
shell_batch.cpp:125:30: note: length computed here
  125 |   const auto src_len = strlen(src);
      |                        ~~~~~~^~~~~
In file included from ../../include/dos_system.h:29,
                 from ../../include/dos_inc.h:27,
                 from ../../include/programs.h:27,
                 from ../../include/shell.h:28,
                 from shell_batch.cpp:23:
In lambda function,
    inlined from ‘virtual bool BatchFile::ReadLine(char*)’ at shell_batch.cpp:149:21:
../../include/support.h:146:41: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  146 | #define safe_strncpy(a,b,n) do { strncpy((a),(b),(n)-1); (a)[(n)-1] = 0; } while (0)
      |                                  ~~~~~~~^~~~~~~~~~~~~~~
shell_batch.cpp:129:4: note: in expansion of macro ‘safe_strncpy’
  129 |    safe_strncpy(cmd_write, src, src_len + 1);
      |    ^~~~~~~~~~~~
shell_batch.cpp: In member function ‘virtual bool BatchFile::ReadLine(char*)’:
shell_batch.cpp:125:30: note: length computed here
  125 |   const auto src_len = strlen(src);
      |                        ~~~~~~^~~~~
```

Comment (kcgen) [reply src/shell/shell_batch.cpp:129]: Yes, I found that without including the terminating null in the allowed length, that the string copy would drop the last character.  Including the null allows the last character to be copied.

But indeed, if we can fix this even deeper in `safe_strncopy` -- then even better!

It looks like this has bit us a couple times too:

``` c++
src/dos/cdrom_image.cpp: safe_strncpy(tmp, file, len+1);
src/dos/drive_cache.cpp: safe_strncpy(tmp,path,len+1);
src/shell/shell.cpp: safe_strncpy(buf2, buf.c_str(), n + 1);
src/shell/shell.cpp: safe_strncpy(buf2, buf.c_str(), n + 1);
src/shell/shell_batch.cpp: safe_strncpy(cmd_write, src, src_len + 1);
```

Comment (dreamer) [reply src/shell/shell_batch.cpp:129]: It's damn shame this GCC warning does not work reliably :( the only way I can trigger it is if I don't use any GCC compilation flags at all.

For this PR: I suggest using `safe_strncpy(cmd_write, src, req_len);` (or `req_len - 1`? damn - not sure).

Simply turning the `safe_strncpy` macro into a function call won't help, we still depend on user passing the correct parameters :( I think as follow up we need to review all uses of this macro and replace with safer alternatives whenever possible (e.g. in cross.cpp:142 we can use `safe_strcpy`), in other places maybe append std::string, etc. 

Unfortunately, we can't even get rid of it, because upstream uses this macro in new code they write :/

Comment (kcgen) [reply src/shell/shell_batch.cpp:129]: > For this PR: I suggest using safe_strncpy(cmd_write, src, req_len); (or req_len - 1? damn - not sure).

Heading into the parser loop on line 135, `cmd_write` is equal to `line`, meaning they cancel each other out in this expressions: `const auto req_len = cmd_write - line + static_cast<int>(src_len);`

Therefore, `req_len` is thus equal to `src_len`, and we're back to square one.

The problem will re-manifest on line 149, which can call the macro on the first pass through the parse loop when `cmd_write` is equal to `line`.

However,  `req_len` _will_ work once we've made it one round through the loop because `cmd_write` will be advanced by one on line 143), in which case the `req_len` calculation will be equal to `1 + src_len`.

So it gets us part way.

If we added one to `req_len`, this would solve the first pass problem and we could drop the `+ 1` in the `if (req_len < CMD_MAXLINE + 1)` check, as follows:

``` c++
		const auto req_len = cmd_write - line + static_cast<int>(src_len) + 1;
		if (req_len < CMD_MAXLINE) {
			// include the terminating null in the source length
			safe_strncpy(cmd_write, req_len);
			cmd_write += src_len;
		}
```

Comment (kcgen) [reply src/shell/shell_batch.cpp]: Update inbound with clarified commit message and body.
Same tests ran and passing with the change.

**Review by dreamer — APPROVED** [review]
Great :)

I think it's time to start reviewing other `safe_strncpy` uses and replace them whenever possible.

**Comment by dreamer** [comment]
@kcgen thanks for investigation and fix!
@NicknineTheEagle thanks for the report and testing!

Let's merge this in :)
