### PR TITLE
Fix command line parser bug where an extension-less file prevents execution

### LINKED ISSUE #4179: Overkill fails to launch due to having files "OVERKILL" and "OVERKILL.EXE" in the same directory
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

v0.82.0

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

Debian 12 KDE

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

I'm only reporting this as it was mentioned on Discord.  I haven't tested this myself yet.

Root problem appears to be that if we have say `FOO` and `FOO.EXE` in the same directory, then typing `FOO` prints an error message and does not launch `FOO.EXE`.  Explicitly typing `FOO.EXE` is reported to still work.

It is reported that DOSBox-X does not have this behavior.  @NicknineTheEagle reported that he tested on real MS-DOS 6.22 and it also does not have this behavior.

We probably have a bug in our command line parser somewhere.

### Steps to reproduce the behaviour

Explain in detail how to reproduce the bug. Assume no familiarity with the software.
1. Install Overkill
2. CD into the installed directory
3. Run `OVERKILL` and get an error (must run `OVERKILL.EXE` to actually launch the game).

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

Regression from 1ebea7216206f79e37a9e5712c824199c39f51b4 - Passed wrong pointer into execute_binary_file()
From the same PR ffd952cc6c0c7a28d7d1cfe8835610ff41c67f8a - Code detecting extension-less files was removed

If a directory contains both DOOM and DOOM.EXE and a user runs the command DOOM, this was previously thowing an error.

We should try appending (in order) .COM, .EXE, and .BAT if and only if the command contains no extension.

## Related issues

Fixes #4179

# Release notes

Fixed a bug where an extension-less file with the same name as an executable incorrectly threw an "Invalid command" error when attempting to launch the executable from the command line.

# Manual testing

- Create empty file `DOOM` in the same directory as `DOOM.EXE`.
- Type `DOOM` in the command line.
- Previously this threw invalid command error.  Now it doesn't.

Also confirmed Overkill fails to launch on `main` and works after this PR.

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/shell/shell_misc.cpp [hunk 1]
```diff
@@ -486,6 +486,19 @@ void CommandPrompt::SetCursor(const std::string::size_type index)
...
+{
+	constexpr size_t ExtensionSize = 4;
+	if (filename.size() <= ExtensionSize) {
+		return "";
+	}
+	const auto dot_position = filename.size() - ExtensionSize;
+	if (filename[dot_position] != '.') {
+		return "";
+	}
+	return filename.substr(dot_position);
```
Comment (johnnovak) [inline src/shell/shell_misc.cpp:499]: So if there's a file called `A.B` that's stored internally as `A       .B  ` (space-padded to 8.3 chars)?
Or maybe it's `A.B  ` (so only the extension is space-padded to 3 chars)?

If so, and you're 100% sure about that padding is always performed, maybe put a comment there explaining this assumption.

But I'd guess I'd prefer if this code was a bit more generic and resilient to change.

Comment (johnnovak) [reply src/shell/shell_misc.cpp:499]: Lol, I still have no idea how the 8.3 filenames are stored internally (space padded or not). I assume it's an inconsistent mess and all variations can occur 😂 

Found this, so there's at least a function that can space-pad filenames to the 8.3 format. But no clue about the contents of this `std::string_view filename` function arg; that can be anything.

https://github.com/dosbox-staging/dosbox-staging/blob/aacca00a25d72cbd02991651f99cb76b76d6d109/src/dos/dos_files.cpp#L1343-L1346

I wish all such functions used `DosFilename`:
https://github.com/dosbox-staging/dosbox-staging/blob/aacca00a25d72cbd02991651f99cb76b76d6d109/include/dos_system.h#L97-L100

And I also wish it was defined like this to remove all ambiguity:

```cpp
struct DosFilename {
    // space-padded
    char name[8] = {};

    // space-padded
    char ext[3]  = {};
};
```

Then we could just have a few simple functions that operate on `DosFilename` structs (equality check, ordering, etc.)

Comment (weirddan455) [reply src/shell/shell_misc.cpp:499]: DOS files can have spaces? O.o

We don't care about 1-2 char extension sizes here.  This function is only called by `ExecuteProgram()` and if it's anything other than `.BAT` `.COM` and `.EXE`, it's supposed to fail.

Comment (johnnovak) [reply src/shell/shell_misc.cpp:499]: > DOS files can have spaces? O.o
> 
> We don't care about 1-2 char extension sizes here. This function is only called by `ExecuteProgram()` and if it's anything other than `.BAT` `.COM` and `.EXE`, it's supposed to fail.

In that case the `get_extension()` function name is lying and it's misleading. I strongly suggest to refactor it then to `has_executable_extension()` and simply return a bool as this is way too misleading.

Comment (weirddan455) [reply src/shell/shell_misc.cpp:499]: >  I think extension-less filenames are also allowed but would need to test.

Yes, they are.  That's the reason this PR exists 😆 

>  But yeah, at the FAT data level I'm pretty sure everything is space-padded to 8.3.

I'm pretty sure this function is not dealing with names at that level.  We really only care about FAT for FAT images and that's a whole separate area of the code (`drive_fat.cpp` or something).

>  In that case the get_extension() function name is lying and it's misleading. I strongly suggest to refactor it then to has_executable_extension() and simply return a bool as this is way too misleading.

Yeah, I can rename it.  This doesn't need to be some super generic thing.  If we had one of those, I would have used it.  It's called in exactly the 2 places you see in this PR.

Comment (weirddan455) [reply src/shell/shell_misc.cpp:503]: I renamed the function and added a comment.

I looked at the calling code for `ExecuteProgram()`.  The filename strings are coming from the command line or from a batch file.  Spaces aren't valid as the line has already been trimmed and separated into arguments before we get here.  We're also not dealing with internal DOS structures at this point.

Comment (johnnovak) [reply src/shell/shell_misc.cpp:503]: > Yeah, I can rename it. This doesn't need to be some super generic thing. If we had one of those, I would have used it. It's called in exactly the 2 places you see in this PR.

Thanks, that's fine. But don't we have a generic `get_extension` function somewhere in the codebase already? Can't we just use that and check if the returned extension is an executable extension?

Comment (weirddan455) [reply src/shell/shell_misc.cpp:503]: I searched and did not find one.  The closest I saw was this:

https://github.com/dosbox-staging/dosbox-staging/blob/33a83fb77173a590b6a89be35bc22cc6bb867806/src/dos/dos_classes.cpp#L425-L433

But that's not suitable because

1. It's a member method of the `DOS_DTA` class which I'm not using here.
2. `ExecuteProgram()` is handling shell arguments.  Above `GetExtension()` function would parse `.\OVERKILL' as having an extension of '\OVERKILL' and we do the wrong thing.

**Comment by johnnovak** [comment]
Just ran into this regression with **Ski or Die**.  The main executable is called `SKI.EXE` but there is also a `SKI` data file without extension in the same directory.

File: src/shell/shell_misc.cpp (hunk 1 above)
Comment (johnnovak) [reply src/shell/shell_misc.cpp:503]: Ok this is fine then for now, let's not overdo it 😄

**Review by johnnovak — APPROVED** [review]
Nice fix @weirddan455, ship it! :shipit:

**Comment by johnnovak** [comment]
@Python-Exoproject 

This is a regression where at least **Overkill** and **Ski or Die** couldn't be started in Staging. Will be fixed in 0.82.1.
