### PR TITLE
Unify IMGMOUNT and MOUNT into a single command

### LINKED ISSUE #2511: Misleading log messages using IMGMOUNT to mount CD-ROMs
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

See attached Screenshots and resulting log messages.

image

When i specifiy the CUE as 'SWDF104.CUE' the log also shows 'found CUE on mounted drive'.

Bildschirmfoto_2023-05-22_um_10 57 53

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### LINKED ISSUE #3527: Improve the help text of the `MOUNT` command
The `MOUNT` command's help text needs some improvements. The help text of all commands should be complete. The information might be succinct, and the User Manual would probably contain more detailed info for all commands, but the commands' help text should not omit any settings or parameters.

This is the list of things to be added:

- The `-pr` option needs to be documented.
image

- The `-t overlay` option's description needs more detail (e.g., why would anyone want to use this? how can it help?)

- `-size` needs to be documented (we can take it from the [README](https://github.com/dosbox-staging/dosbox-staging/blob/main/README))

- The physical CD-ROM mounting options also need to be documented:

image

- The following sentence needs to be removed from the help text:

image

### PR DESCRIPTION
**Pull request by dividebysandwich**
# Description

Merge ```IMGMOUNT``` and ```MOUNT``` into a single command and a single source file. ```IMGMOUNT``` remains as a stub for compatibility but forwards all parameters 1:1 to MOUNT. 

MOUNT gains the -chs parameter which allows for the more familiar specification of geometry as ```Cylinders,Heads,Sectors```.

Running either ```MOUNT``` or ```IMGMOUNT``` now return all mounts. It is no longer possible to list only the mounted images, as this distinction makes no sense anymore.

The command line help has been expanded to cover all implemented functions and parameters.

## Related issues

Fixes #3527
Fixes #2511

# Release notes

* IMGMOUNT and MOUNT are now just MOUNT

The commands ```IMGMOUNT``` and ```MOUNT``` have been merged into a single ```MOUNT``` command that supports all types of mounts: directories, disk images, bootable images, overlays, etc.
The ```IMGMOUNT``` command remains available for compatibility. Note that running ```IMGMOUNT``` to list all mounted images now always lists all types of mounts, as there is no need to distinguish between image mounts and non-image mounts.

# Manual testing

Bootables:
```
mount 2 hd250.img -fs none -t hdd -size 512,63,16,489 -ro
boot c:
```

```
imgmount 2 hd250.img -fs none -t hdd -size 512,63,16,489 -ro
boot c:
```

Misc:
```
mount c /home/user/DOS
mount c hd250.img -t hdd -size 512,63,16,489
mount c hd250.img -t hdd -chs 489,16,63
mount d cdrom.img -t iso -ide
mount c ~/DOS
mount a /home/user/floppydir
mount a /home/user/floppydir -t floppy
mount a ~/DOS/disk01.img -t floppy -label TEST
mount a ~/DOS/disk01.img -t floppy
mount a subdir/disk01.img -t floppy -pr
```

Overlay:
```
mount a ~/DOS/disk01.img -t floppy -ro
mount a ~/DOS/floppyoverlay -t overlay
```

CUE:
```
cd TIECD
mount e SWTIECD.CUE -t cdrom
```

All these commands should work the same using ```imgmount``` instead of ```mount```

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [X] Linux

# Checklist

I have:

- [X] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [X] performed a self-review of my code.
- [X] commented on the particularly hard-to-understand areas of my code.
- [X] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [X] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [X] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/tools/compile-commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [X] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [X] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by dividebysandwich** [comment]
Note that the existing code has not been updated to current dosbox-staging practices - i.e. to use std::filesystem instead of raw c file handling, remove platform specific #ifdef, std::string instead of C string functions, fix integer types, etc.

I am happy to perform these tasks while we're substantially reworking mount.cpp anyway, but I'd like to check first before doing something that could go into a separate PR.

**Comment by MasterO2** [comment]
@dividebysandwich, does mounting `.cue` files work as well?  This is needed especially for games that use CD Audio as well as for when games check for the CD to be inserted or the game does not run at all.

**Comment by dividebysandwich** [comment]
> @dividebysandwich, does mounting `.cue` files work as well? This is needed especially for games that use CD Audio as well as for when games check for the CD to be inserted or the game does not run at all.

@MasterO2 Thanks for the catch, that was indeed borked. Fixed and added to the tests.

File: src/dos/drive_fat.cpp [hunk 1]
```diff
@@ -842,6 +842,8 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
 	if (bytesector != BytePerSector) {
 		/* Non-standard sector sizes not implemented */
 		created_successfully = false;
+		LOG_MSG("Non-standard sector size detected: %u bytes per sector",
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: Use the `DOS: MOUNT - ` prefix for all this, and make them warnings. All log statements must have prefixes.

We already use this pattern elsewhere:

Image

File: src/dos/drive_fat.cpp [hunk 2]
```diff
@@ -917,17 +921,57 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
...
+		return;
+	}
+	if (bootbuffer.sectorspercluster == 0) {
+		created_successfully = false;
+		LOG_MSG("Loaded image has zero sectors per cluster!");
+		return;
+	}
+	if (bootbuffer.rootdirentries == 0) {
+		created_successfully = false;
+		LOG_MSG("Loaded image has zero root directory entries!");
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: It's fine to log success messages, but turn them into `LOG_DEBUG` please, and maybe add an option to ifdef them out (e.g., check out `// #define DEBUG_VGA_DRAW` in `vga_draw.cpp`; that's a common pattern we do).

**Comment by Torinde** [comment]
I like that you're merging the two commands.

As for https://github.com/dosbox-staging/dosbox-staging/issues/3527:
- `-size ` has different parameters per the [README](https://github.com/dosbox-staging/dosbox-staging/commit/0994084908b752e71b9b424c68346e6b46a76b63#diff-9f72e452a312f68782cb3ec9dd27cce7ff3be5ffbac861501da84ff71e07f382L585) (I don't know if current behavior matches that)
image

- I don't see "The physical CD-ROM mounting options"
- there are further options which are also not shown in MOUNT /h, e.g. `-freesize` (which works) and others (for which I don't know if current behavior matches them)


Current PR:
image
image

**Comment by dividebysandwich** [comment]
@Torinde Thanks for looking over this PR!

-freesize was indeed missing in the help. Added.

Physical cd-rom mounting options were not implemented, so there was nothing for me to move over.

-size parameters are wrongly named in the readme, but they were also wrongly named in my help text. And they are also wrong in the implementation :)
The problem is that the implementation mixes disk geometry and filesystem specifics. SectorsPerCluster and HeadsPerCluster have nothing to do with the disk geometry because Clusters only exist in a filesystem. This is especially troublesome if paired with the ```-nofs``` parameter.  See also: https://en.wikipedia.org/wiki/Cylinder-head-sector
Since the same code is used for both images with and without filesystem, there's no easy way  to fix this. So instead of going down a rabbithole and solving a problem nobody else has noticed before, I'd say let's defer this to another PR in the future. I have made the help text consistent with the implementation for now.

File: src/dos/drive_fat.cpp (hunk 2 above)
Comment (dividebysandwich) [reply src/dos/drive_fat.cpp]: There are actually errors. In the future I'd like those to be shown to the user, but that will require some refactoring (and as you noted in the contribution guidelines, exception handling in this language is a trainwreck) so LOG_ERR it is for now. But I wanted at least some way of telling WHY an image didn't mount.

**Comment by Torinde** [comment]
I tried also `-label` and it works, is in README, but isn't described in /h
Maybe there are other parameters in the source that I don't know about?

Based on https://github.com/dosbox-staging/dosbox-staging/issues/3602 I thought physical CD-ROMs are supported?
> 			// Following options were relevant only for physical CD-ROM support:
>			for (auto opt : {"-noioctl", "-ioctl", "-ioctl_dx", "-ioctl_mci", "-ioctl_dio"})

**Comment by dividebysandwich** [comment]
@Torinde Unfortunately these options are not supported in the current main:

```
			// Following options were relevant only for physical CD-ROM support:
			for (auto opt : {"-noioctl", "-ioctl", "-ioctl_dx", "-ioctl_mci", "-ioctl_dio"}) {
				if (cmd->FindExist(opt, false))
					WriteOut(MSG_Get("MSCDEX_WARNING_NO_OPTION"), opt);
			}
```

**Comment by johnnovak** [comment]
> @Torinde Unfortunately these options are not supported in the current main:
> 
> ```
> 			// Following options were relevant only for physical CD-ROM support:
> 			for (auto opt : {"-noioctl", "-ioctl", "-ioctl_dx", "-ioctl_mci", "-ioctl_dio"}) {
> 				if (cmd->FindExist(opt, false))
> 					WriteOut(MSG_Get("MSCDEX_WARNING_NO_OPTION"), opt);
> 			}
> ```

And won't be. CD-ROMs are dead.

**Comment by Torinde** [comment]
Am I reading https://github.com/dosbox-staging/dosbox-staging/issues/3602 wrongly? It seems physical CDs were supported half an year ago under Linux and Windows and ticket for adding support to macOS is currently open...

**Comment by johnnovak** [comment]
> Am I reading #3602 wrongly? It seems physical CDs were supported half an year ago under Linux and Windows and ticket for adding support to macOS is currently open...

Yeah okay, I misremembered. It's supported on Linux and Windows only, still. More info:

- https://github.com/dosbox-staging/dosbox-staging/pull/3591

File: src/dos/drive_fat.cpp (hunk 2 above)
Comment (johnnovak) [reply src/dos/drive_fat.cpp]: @dividebysandwich 
LOG_WARNING is better, btw. We reserve LOG_ERR for "serious" stuff when something in the bowels of the emulator code itself is seriously wrong (e.g., we tried to load the Sound Canvas plugin, but it failed, or we failed to init the audio or the OpenGL window, etc.)

If a command misbehaves due to a runtime condition, e.g., the disk image is invalid, those should be warnings, not errors.

Kind of like 500 Internal Server Error vs 4xx class HTTP client errors. LOG_ERR is the Internal Server Error equivalent. If the user provided some rubbish datafile or params or whatever, that can only be a "40x class" warning.

File: src/dos/drive_fat.cpp (hunk 1 above)
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: Should be warning, and use the DOS log prefix.

File: src/dos/drive_fat.cpp [hunk 3]
```diff
@@ -905,6 +907,8 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
 			} else {
 				/* Unknown format */
 				created_successfully = false;
+				LOG_MSG("Unknown floppy format detected (media descriptor 0x%02x)!",
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: Should be warning, and use the DOS log prefix.

**Comment by dividebysandwich** [comment]
I have implemented the ability to mount bootable images (-fs none) using the drive letter as well as the number. This only makes sense because the actual boot command also takes a drive letter.

File: src/dos/programs/mount.cpp [hunk 4]
```diff
@@ -590,6 +591,33 @@ void MOUNT::Run(void) {
...
+				drive           = '2';
+				is_drive_number = true;
+				break;
+			case 'D':
+				drive           = '3';
+				is_drive_number = true;
+				break;
+			default:
+				// Don't allow booting from E:, F:, etc.
+				WriteOut(MSG_Get("PROGRAM_IMGMOUNT_SPECIFY2"));
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: All warning messages printed out by the command should use the notification subsystem rather than simply printing to the console: 

https://github.com/dosbox-staging/dosbox-staging/blob/01d16d2672fd17b830161ae27c2c3e5d56255bed/src/misc/notifications.h#L213

That way the warnings will show up in the logs as well. Important when such commands are executed from the autoexec section of the config.

Converting all existing console-only warnings to use notifications is a big ongoing job, but new code must use notifications where it makes sense.

File: src/dos/programs/mount.cpp [hunk 5]
```diff
@@ -1,43 +1,58 @@
...
 
 void MOUNT::ListMounts()
 {
 	const std::string header_drive = MSG_Get("PROGRAM_MOUNT_STATUS_DRIVE");
-	const std::string header_type = MSG_Get("PROGRAM_MOUNT_STATUS_TYPE");
+	const std::string header_type  = MSG_Get("PROGRAM_MOUNT_STATUS_TYPE");
 	const std::string header_label = MSG_Get("PROGRAM_MOUNT_STATUS_LABEL");
 
-	const int term_width = real_readw(BIOSMEM_SEG, BIOSMEM_NB_COLS);
+	const int term_width   = real_readw(BIOSMEM_SEG, BIOSMEM_NB_COLS);
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: `console_width` ?

File: src/dos/programs/mount.cpp [hunk 6]
```diff
@@ -69,138 +91,542 @@ void MOUNT::ShowUsage()
...
+	             std::make_move_iterator(expanded_paths.end()));
+
+	return true;
+}
+
+bool MOUNT::MountImage(char drive, const std::vector<std::string>& paths,
+                       const std::string& type, const std::string& fstype,
+                       uint16_t* sizes, bool roflag, bool wants_ide,
+                       int8_t ide_index, bool is_second_cable_slot,
+                       std::function<void(std::string)> logger)
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Ugh... In these cases it's best to introduce a struct for the params and pass that in.

File: src/dos/programs/mount.cpp [hunk 7]
```diff
@@ -69,138 +91,542 @@ void MOUNT::ShowUsage()
...
+		}
+
+		if ((drive == '2' || drive == '3') && is_hdd) {
+			updateDPT();
+		}
+
+		log_fmt(MSG_Get("PROGRAM_IMGMOUNT_MOUNT_NUMBER").c_str(),
+		        drv_idx,
+		        paths[0].c_str());
+	}
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:341]: This method is huuuuuge 😅 Please refactor it into multiple smaller methods with a well-defined scope and name.

File: src/dos/programs/mount.cpp [hunk 8]
```diff
@@ -211,167 +637,279 @@ void MOUNT::Run(void) {
...
+
+		// Ensure consistency between type and fstype if user didn't
+		// override -fs
+		if (type == "floppy" && fstype == "fat") {
+			mediaid = MediaId::Floppy1_44MB;
 		}
 
-		if (temp_line[temp_line.size() - 1] != CROSS_FILESPLIT) temp_line += CROSS_FILESPLIT;
-		auto int8_tize = static_cast<uint8_t>(sizes[1]);
+		bool success = this->MountImage(drive,
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Please drop `this` from everywhere. Using it should be a resort.

File: src/dos/programs/mount.h [hunk 9]
```diff
@@ -19,8 +19,16 @@ class MOUNT final : public Program {
 	    }
 	    void ListMounts();
 	    void Run() override;
+	    static bool AddWildcardPaths(const std::string& path_arg,
+	                                 std::vector<std::string>& paths);
+	    static bool MountImage(char drive, const std::vector<std::string>& paths,
```
Comment (johnnovak) [inline src/dos/programs/mount.h]: Why static? Can we de-static them?

File: src/dos/programs/mount.h [hunk 10]
```diff
@@ -19,8 +19,16 @@ class MOUNT final : public Program {
...
+	                           const std::string& type, const std::string& fstype,
+	                           uint16_t* sizes, bool roflag, bool wants_ide,
+	                           int8_t ide_index, bool is_second_cable_slot,
```
Comment (johnnovak) [inline src/dos/programs/mount.h]: Please, introduce a struct for this laundry list of boops and numbers and whatnot, and pass that in 😆 Super error prone to pass in multiple bool args like this.

File: src/dos/drive_fat.cpp [hunk 11]
```diff
@@ -917,17 +921,57 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
...
+	}
+	/* Check geometry values */
+	if (bootbuffer.headcount == 0) {
+		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has zero heads per cylinder!");
+		return;
+	}
+	if (bootbuffer.headcount > headscyl) {
+		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has more heads per cylinder (%u) than the disk geometry allows (%u)!",
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: Would these log messages appear immediately after mounting the image via the `MOUNT` command? If so, they should be notifications so they appear in both the console and the logs.

If these can be triggered much later, e.g. when accessing the drive after a program has been started, then they should stay as log warnings.

File: src/dos/programs/mount.cpp [hunk 12]
```diff
@@ -211,167 +637,279 @@ void MOUNT::Run(void) {
...
+		                                type,
+		                                fstype,
+		                                sizes,
+		                                readonly,
+		                                wants_ide,
+		                                ide_index,
+		                                is_second_cable_slot,
+		                                [this](std::string msg) {
+			                                this->WriteOut_NoParsing(msg);
+		                                });
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Why do we need this indirection at all? Warnings at mount time should use notifications:

https://github.com/dosbox-staging/dosbox-staging/blob/01d16d2672fd17b830161ae27c2c3e5d56255bed/src/misc/notifications.h#L213

File: src/dos/programs/mount.cpp [hunk 13]
```diff
@@ -69,138 +91,542 @@ void MOUNT::ShowUsage()
...
+}
+
+bool MOUNT::MountImage(char drive, const std::vector<std::string>& paths,
+                       const std::string& type, const std::string& fstype,
+                       uint16_t* sizes, bool roflag, bool wants_ide,
+                       int8_t ide_index, bool is_second_cable_slot,
+                       std::function<void(std::string)> logger)
+{
+	// Format strings like WriteOut does, but sending to the provided logger
+	auto log_fmt = [&](const char* format, ...) {
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: You should just use notifications:

https://github.com/dosbox-staging/dosbox-staging/blob/01d16d2672fd17b830161ae27c2c3e5d56255bed/src/misc/notifications.h#L213

I believe you used it for the disknoise warnings in the past? The notification functions take printf-like varargs, just like the logger functions and WriteOut. You don't need to write extra code for formatting like this; it's all done for you in the notification functions.

You can find plenty of usage examples, e.g. check out my `MIXER` command or `mixer.cpp`.

File: src/dos/programs/mount.cpp (hunk 4 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp]: Well this isn't strictly speaking new code. I can change this of course, but just keep in mind that you're mostly reviewing existing dosbox code (with exceptions of course)

File: src/dos/drive_fat.cpp (hunk 11 above)
Comment (dividebysandwich) [reply src/dos/drive_fat.cpp]: I would like to keep this to a separate PR. drive_fat.cpp would require the whole AddMessage dance and this is going well beyond the goal of this PR.

**Comment by johnnovak** [comment]
@dividebysandwich 
Just tried the debug build on macOS with `--noprimaryconf` and `--nolocalconf` — crash at startup.

image

File: src/dos/drive_fat.cpp (hunk 11 above)
Comment (johnnovak) [reply src/dos/drive_fat.cpp]: Sure 😄

**Comment by dividebysandwich** [comment]
@johnnovak Fixed and also cleared up a variable overloading/naming issue.

File: src/dos/programs/mount.h [hunk 14]
```diff
@@ -1,27 +1,71 @@
...
+	char drive                     = '\0';
+	std::vector<std::string> paths = {};
+	std::string type               = "dir";
+	std::string fstype             = "fat";
+	std::string label              = "";
+
+	// Geometry: [0]=BytesPerSector, [1]=Sectors, [2]=Heads, [3]=Cylinders
+	std::array<uint16_t, 4> sizes = {0, 0, 0, 0};
+
+	bool roflag               = false;
```
Comment (johnnovak) [inline src/dos/programs/mount.h:24]: is_readonly

File: src/dos/programs/mount.h [hunk 15]
```diff
@@ -1,27 +1,71 @@
...
+	bool wants_ide            = false;
+	int8_t ide_index          = -1;
+	bool is_second_cable_slot = false;
+	uint8_t mediaid           = 0;
```
Comment (johnnovak) [inline src/dos/programs/mount.h:28]: media_id

File: src/dos/programs/mount.h [hunk 16]
```diff
@@ -1,27 +1,71 @@
...
+	std::vector<std::string> paths = {};
+	std::string type               = "dir";
+	std::string fstype             = "fat";
+	std::string label              = "";
+
+	// Geometry: [0]=BytesPerSector, [1]=Sectors, [2]=Heads, [3]=Cylinders
+	std::array<uint16_t, 4> sizes = {0, 0, 0, 0};
+
+	bool roflag               = false;
+	bool wants_ide            = false;
```
Comment (johnnovak) [inline src/dos/programs/mount.h]: Why not just `is_ide`?

File: src/dos/programs/mount.h [hunk 17]
```diff
@@ -1,27 +1,71 @@
...
+	void ParseArguments(MountParameters& params, bool& explicit_fs,
+	                    bool& path_relative_to_last_config);
+	void ParseGeometry(MountParameters& params);
+	bool ParseDrive(MountParameters& params, bool explicit_fs);
+	bool ProcessPaths(MountParameters& params, bool path_relative_to_last_config);
+	void MountLocal(MountParameters& params, const std::string& local_path);
+
+	bool MountImageFat(MountParameters& params);
+	bool MountImageIso(MountParameters& params);
+	bool MountImageRaw(MountParameters& params);
```
Comment (johnnovak) [inline src/dos/programs/mount.h:64]: Can at least some of these `MountParameters` args be `const`?

File: src/dos/drive_fat.cpp [hunk 18]
```diff
@@ -905,6 +907,8 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
 			} else {
 				/* Unknown format */
 				created_successfully = false;
+				LOG_WARNING("DOS: MOUNT - Unknown floppy format detected (media descriptor 0x%02x)!",
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: Maybe we drop the exclamation marks 😄 It certainly adds a dramatic flair to the warning, but we don't do that 😏

File: src/dos/drive_fat.cpp [hunk 19]
```diff
@@ -917,17 +921,57 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
...
-	    (bootbuffer.rootdirentries == 0) ||
-	    (bootbuffer.fatcopies == 0) ||
-	    (bootbuffer.headcount == 0) ||
-	    (bootbuffer.headcount > headscyl) ||
-	    (bootbuffer.sectorspertrack == 0) ||
-	    (bootbuffer.sectorspertrack > cylsector)) {
+	if (bootbuffer.sectorsperfat == 0) {
+		/* Possibly a FAT32 or non-FAT filesystem */
+		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has zero sectors per FAT! FAT32 and non-FAT filesystems are not supported.");
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp:927]: No exclamation mark, please.

File: src/dos/drive_fat.cpp [hunk 20]
```diff
@@ -917,17 +921,57 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
...
+	}
+	if (bootbuffer.fatcopies == 0) {
+		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has zero FAT copies!");
+		return;
+	}
+	/* Check geometry values */
+	if (bootbuffer.headcount == 0) {
+		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has zero heads per cylinder!");
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: Let's drop all exclamation marks from the warnings. We don't do that.

File: src/dos/programs/mount.cpp [hunk 21]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
-	std::string label                   = {};
-	std::string umount                  = {};
+// A helper function that expands wildcard paths from the given argument and
+// adds them to the given paths. Returns true if the expansion succeeded.
+bool MOUNT::AddWildcardPaths(const std::string& path_arg,
+                             std::vector<std::string>& paths)
+{
+	// Expand the given path argument
+	constexpr auto only_expand_files        = true;
+	constexpr auto skip_native_path         = true;
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: OnlyExpandFiles and SkipNativePath by convention for constexprs

File: src/dos/programs/mount.cpp [hunk 22]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
 
-	//Hack To allow long commandlines
-	ChangeToLongCmd();
-	/* Parse the command line */
-	/* if the command line is empty show current mounts */
-	if (!cmd->GetCount()) {
-		ListMounts();
-		return;
+	// Sort wildcards with natural ordering
+	constexpr auto npos      = std::string::npos;
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: Yeah, let's not do this 😄 Just inline it.

File: src/dos/programs/mount.cpp [hunk 23]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+}
+
+void MOUNT::WriteMountStatus(const char* image_type,
+                             const std::vector<std::string>& images, char drive_letter)
+{
+	constexpr auto end_punctuation        = "";
+	const auto images_str                 = join_with_commas(images,
+                                                 MSG_Get("CONJUNCTION_AND"),
+                                                 end_punctuation);
+	const std::string type_and_images_str = image_type + std::string(" ") +
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:132]: Newline above this, please, then reformat to get rid of the funky indenting.

File: src/dos/programs/mount.cpp [hunk 24]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+	             std::make_move_iterator(expanded_paths.begin()),
+	             std::make_move_iterator(expanded_paths.end()));
+
+	return true;
+}
+
+void MOUNT::WriteMountStatus(const char* image_type,
+                             const std::vector<std::string>& images, char drive_letter)
+{
+	constexpr auto end_punctuation        = "";
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: EndPunctuation

File: src/dos/programs/mount.cpp [hunk 25]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+		                      "PROGRAM_IMGMOUNT_CANT_CREATE");
+		return false;
+	}
+
+	// Update DriveManager
+	DriveManager::AppendFilesystemImages(drive_index(params.drive), fat_images);
+	DriveManager::InitializeDrive(drive_index(params.drive));
+
+	// Set the correct media byte in the table
+	mem_writeb(RealToPhysical(dos.tables.mediaid) + drive_index(params.drive) * 9,
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: What is the 9?

File: src/dos/programs/mount.cpp [hunk 26]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+
+	// Print status message (success)
+	WriteOut(MSG_Get("MSCDEX_SUCCESS"));
+	WriteMountStatus(MSG_Get("MOUNT_TYPE_ISO").c_str(), params.paths, params.drive);
+	return true;
+}
+
+bool MOUNT::MountImageRaw(MountParameters& params)
+{
+	FILE* new_disk = fopen_wrap_ro_fallback(params.paths[0], params.roflag);
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: auto

File: src/dos/programs/mount.cpp [hunk 27]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+	}
+	const auto sz = stdio_size_kb(new_disk);
+	if (sz < 0) {
+		fclose(new_disk);
+		NOTIFY_DisplayWarning(Notification::Source::Console,
+		                      "MOUNT",
+		                      "PROGRAM_IMGMOUNT_INVALID_IMAGE");
+		return false;
+	}
+	uint32_t imagesize = check_cast<uint32_t>(sz);
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: auto

File: src/dos/programs/mount.cpp [hunk 28]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+	// 0=A:, 1=B:, 2=C:, 3=D:
+	const bool is_hdd = (params.drive >= '2');
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: auto

File: src/dos/programs/mount.cpp [hunk 29]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+
+	// Parse -fs (filesystem type)
+	if (params.type == "iso") {
+		params.fstype = "iso";
+	}
+	explicit_fs = cmd->FindString("-fs", params.fstype, true);
+
+	// Parse -ide
+	std::string ide_value = {};
+	params.wants_ide      = cmd->FindString("-ide", ide_value, true) ||
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: newline above, reformat

File: src/dos/programs/mount.cpp [hunk 30]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+void MOUNT::ParseGeometry(MountParameters& params)
+{
+	std::string str_size = "";
+	std::string str_chs  = "";
+
+	// Default sizing logic based on type
+	if (params.type == "floppy") {
+		str_size       = "512,1,2880,2880";
+		params.mediaid = MediaId::Floppy1_44MB;
+	} else if (params.type == "dir" || params.type == "overlay") {
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:471]: newline above for readability

File: src/dos/programs/mount.cpp [hunk 31]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
-		cmd->FindString("-size",str_size,true);
-		char number[21] = { 0 };const char * scan = str_size.c_str();
-		Bitu index = 0;Bitu count = 0;
-		/* Parse the str_size string */
+	// Apply str_size string to sizes array
+	if (!str_size.empty()) {
+		char number[21]  = {0};
+		const char* scan = str_size.c_str();
+		Bitu index       = 0;
+		Bitu count       = 0;
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Get rid of Bitu and just use `int`?

File: src/dos/programs/mount.cpp [hunk 32]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
-						real_path.c_str(),
-						temp_line.c_str());
+	// Check first path
+	struct stat test;
+	bool stat_ok       = (stat(path_arg_1.c_str(), &test) == 0);
+	bool target_is_dir = stat_ok && S_ISDIR(test.st_mode);
+	bool explicit_image_type = (params.type == "hdd" || params.type == "iso" ||
+	                            params.type == "floppy");
+
+	bool is_image_mode = false;
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: auto 'em all 😄

File: src/dos/programs/mount.cpp [hunk 33]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
-	return;
+		         final_path.c_str(),
+		         params.drive);
+	}
+
+	// check if volume label is given and don't allow it to updated in the
+	// future
+	if (!params.label.empty()) {
+		newdrive->dirCache.SetLabel(params.label.c_str(), false, false);
+	} else if (params.type == "dir" || params.type == "overlay") {
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:992]: newline above for readability

File: src/dos/programs/mount.cpp [hunk 34]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+		// For hard drives set the label to DRIVELETTER_Drive.
+		// For floppy drives set the label to DRIVELETTER_Floppy.
+		// This way every drive except cdroms should get a label.
+		params.label = params.drive;
+		params.label += "_DRIVE";
+		newdrive->dirCache.SetLabel(params.label.c_str(), false, false);
+	} else if (params.type == "floppy") {
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:1000]: newline above for readability

File: src/dos/programs/mount.cpp [hunk 35]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+	if (params.type == "floppy") {
+		incrementFDD();
+	}
+}
+
+void MOUNT::Run(void)
+{
+	MountParameters params;
+
+	// Hack To allow long commandlines
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: to, command lines

File: src/dos/programs/mount.cpp [hunk 36]
```diff
@@ -69,399 +92,1063 @@ void MOUNT::ShowUsage()
...
+
+	// Parse command line arguments
+	ParseArguments(params, explicit_fs, path_relative_to_last_config);
+	ParseGeometry(params);
+
+	if (!ParseDrive(params, explicit_fs)) {
+		return;
+	}
+
+	// Parse Paths and execute (MountImage or MountLocal)
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor typo: paths

File: src/dos/programs/mount.h [hunk 37]
```diff
@@ -1,27 +1,71 @@
...
+#include <array>
+#include <string>
+#include <vector>
+
+// Struct to hold all parameters required for a mount operation
+struct MountParameters {
+	char drive                     = '\0';
+	std::vector<std::string> paths = {};
+	std::string type               = "dir";
+	std::string fstype             = "fat";
```
Comment (johnnovak) [inline src/dos/programs/mount.h:18]: Would be nicer to use enums, but I guess you've just moved stuff around in this PR.

File: src/dos/drive_fat.cpp (hunk 11 above)
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: No exclamation mark

File: src/dos/drive_fat.cpp [hunk 38]
```diff
@@ -917,17 +921,57 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
...
+	if (bootbuffer.headcount > headscyl) {
+		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has more heads per cylinder (%u) than the disk geometry allows (%u)!",
+		        bootbuffer.headcount,
+		        headscyl);
+		return;
+	}
+	if (bootbuffer.sectorspertrack == 0) {
+		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has zero sectors per track!");
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: No exclamation mark

File: src/dos/drive_fat.cpp [hunk 39]
```diff
@@ -917,17 +921,57 @@ fatDrive::fatDrive(const char* sysFilename, uint32_t bytesector,
...
+		return;
+	}
+	if (bootbuffer.sectorspertrack > cylsector) {
 		created_successfully = false;
+		LOG_WARNING("DOS: MOUNT - Loaded image has more sectors per track (%u) than the disk geometry allows (%u)!",
```
Comment (johnnovak) [inline src/dos/drive_fat.cpp]: No exclamation mark

**Comment by johnnovak** [comment]
Nice work overall! 🎉 Left a few relatively superficial comments. If you'd like to clean up the existing messy code a bit in a subsequent PR, that would be most welcome, but I think there a few things that need to be done in this PR first.

- When using `IMGMOUNT`, we should a log a deprecation warning and instruct people to migrate to using `MOUNT`.
- Could you apply consistent colour-coding and casing to the list of arguments like you did for `MAKEIMG`? You've kinda doing it for the first half, but not the rest.
- I'm trying to read the help text as a clueless user 😄, and quite a few thing are ambiguous or could be better explained. Here's a list of the biggest issues as I see it:

---

image

This is ambigous, and I _think_ you've made an improvement so drive letters can also be used for booting? So it's not even accurate? Plus compared to the old message, this is less helpful and more vague:

image

--- 

image

We're also losing information compared to the previous text:

image

It would prefer to keep this. I think it's enough to mention it in the notes section that people can use wildcards. It just confuses things to turn that into a new line in the Usage section IMO.

---

image

That's true for `PATH` mounts, but not for `IMAGEFILE ` mounts. The image can be on a directory-mounted DOS drive, too. E.g., put some ISO files in a directory, mount it as the C drive, then do `mount d C:\BLAH.ISO -t iso` — it will work, I've just tested it.

Would be best to clarify:

- `PATH` — directory on the host OS (absolute path or relative to the working directory)
- `IMAGEFILE` — image file on the host (absolute path or relative to the working directory), or on a mounted DOS drive (e.g.: C:\GAME.ISO)

---

image

Maybe "to mount multiple swappable images at the same drive letter, e.g.:"

---

image

This is not entirely true (but the old description was bad, too). We don't _have_ to use wildcards; explicitly listing `A.ISO B.ISO C.ISO` works too, or putting them into `drives/d/` for auto-mounting and not even touching the `MOUNT` command or using wildcards — Ctrl/Cmd+F4 will still swap between them.

So with this in mind, can you rephrase it? E.g., "Ctrl+F4 cycles between multiple images mounted at the same drive letter". Maybe add "Useful for swapping disk images while a game is running."

---

image

Can we simplify this and drop the `size_in_mb | size_in_kb` part? That's just confusing and doesn't really serve a purpose.

"This is a simpler version of -size" — I don't think that's true, and it's confusing to put that here. `-freesize` is used for directory mounts to "fake" the free available size, and it doesn't make much sense to use it with images that have a fixed size (would that even work? I think not).

Without specifying `-freesize`, HDD directory mounts default to around 250MB or something, and no idea about floppy images but probably they default to something too. Maybe you could find those values out and put that info here?

The explanation "Sets the amount..." is good, but start with lowercase `S` for consistency, and mention this is only for directory mounts to fake the available size seen by DOS.

---

image

Maybe just "unmounts DRIVE", and DRIVE in white?

---

image

Nice addition! A few typos:

"with an attached IDE CD-ROM drive; useful for..."
"via a bootable HDD image."

---

image

I don't think we need this _and_ the detailed `-t overlay` description as well. There's a lot of overlap between the two, seems redundant. Either keep just `-t overlay` as-is and drop this note, or make the `-t overlay` description really brief and keep the detailed note.

---

image

Nice addition, but please fix the wrapping to 80 cols.

---

image

Can we explain tilde-expansion in the notes section? Especially for Windows users, this needs an explanation.

**Comment by dividebysandwich** [comment]
@johnnovak Aye aye, and yeah I didn't want to clean up all the existing code in the current PR. I kinda had to start to be able to break up the various functions, but my main goal was to get this working without too much regression risk. I am pretty busy with other things today and tomorrow so I will probably not get to it before Friday. I'll let you know when I've finished my tests after the changes.

**Comment by johnnovak** [comment]
> @johnnovak Aye aye, and yeah I didn't want to clean up all the existing code in the current PR. I kinda had to start to be able to break up the various functions, but my main goal was to get this working without too much regression risk. I am pretty busy with other things today and tomorrow so I will probably not get to it before Friday. I'll let you know when I've finished my tests after the changes.

No rush, you can do it next week, or the week after too 👍🏻 😃  Thanks for the patience.

File: src/dos/drive_fat.cpp (hunk 20 above)
Comment (dividebysandwich) [reply src/dos/drive_fat.cpp]: image

File: src/dos/programs/mount.cpp (hunk 22 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp]: My first instinct is always to just import std but I know that's a no-no (for no good reason) ;)

File: src/dos/programs/mount.h (hunk 17 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.h:64]: Nope, they're being modified. I could split this up but IMO this would feel a bit excessive.

File: src/dos/programs/mount.h (hunk 37 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.h:18]: Yep, and there's plenty of other stuff that could use cleaning up.

**Comment by dividebysandwich** [comment]
> We're also losing information compared to the previous text:
> image
> 
> It would prefer to keep this. I think it's enough to mention it in the notes section that people can use wildcards. It just confuses things to turn that into a new line in the Usage section IMO.

I am going to admit that as a new user, I would have no idea what "CUE+ISO+FLAC/OPUS/OGG/MP3/WAV" means, and how I would apply that to the mount command. I have made some changes, let me know what you think.

> Would be best to clarify:
> 
>     * `PATH` — directory on the host OS (absolute path or relative to the working directory)
> 
>     * `IMAGEFILE` — image file on the host (absolute path or relative to the working directory), or on a mounted DOS drive (e.g.: C:\GAME.ISO)

Added.

> image
> 
> This is not entirely true (but the old description was bad, too). We don't _have_ to use wildcards; explicitly listing `A.ISO B.ISO C.ISO` works too, or putting them into `drives/d/` for auto-mounting and not even touching the `MOUNT` command or using wildcards — Ctrl/Cmd+F4 will still swap between them.

I put all that into the notes, what do you think?

> So with this in mind, can you rephrase it? E.g., "Ctrl+F4 cycles between multiple images mounted at the same drive letter". Maybe add "Useful for swapping disk images while a game is running."

Added.

> image
> 
> Can we simplify this and drop the `size_in_mb | size_in_kb` part? That's just confusing and doesn't really serve a purpose.
> 
> "This is a simpler version of -size" — I don't think that's true, and it's confusing to put that here. `-freesize` is used for directory mounts to "fake" the free available size, and it doesn't make much sense to use it with images that have a fixed size (would that even work? I think not).
> 
> Without specifying `-freesize`, HDD directory mounts default to around 250MB or something, and no idea about floppy images but probably they default to something too. Maybe you could find those values out and put that info here?
> 
> The explanation "Sets the amount..." is good, but start with lowercase `S` for consistency, and mention this is only for directory mounts to fake the available size seen by DOS.

Done.

> image
> 
> Nice addition, but please fix the wrapping to 80 cols.

I'll try, it's easy to mess this up.

> image
> 
> Can we explain tilde-expansion in the notes section? Especially for Windows users, this needs an explanation.

Windows users never see this.  I don't know if adding this to the notes is a good idea because then, Windows users WILL see it.


Regarding the coloring: I am happy to apply any rule, but I am not sure what those rules are. It should be noted that this is still based on the original help text. 
Also I am running into the size restriction of the message handler, leading to the dreaded invalid message error. For example I cannot add another line of text. But maybe the changes are sufficient, please let me know.

File: src/dos/programs/mount.cpp (hunk 22 above)
Comment (johnnovak) [reply src/dos/programs/mount.cpp]: > that's a no-no (for no ~good~ reason) ;)

Fixed it for ya! 😝

**Comment by johnnovak** [comment]
Cheers, I'll have a look shortly.

> I'll try, it's easy to mess this up.

Yeah, the "standard way" for now is to recompile, test, manually reindent, recompile, test, etc. until it looks right. It's a pain when colour is involved, so we should introduce auto wrapping. A contributor gave it a go until the collective team bikeshedding made him run away at 50 km/h in the direction he came from 😅 I guess I'll do it at some point 🤷🏻‍♂️ 

> Windows users never see this. I don't know if adding this to the notes is a good idea because then, Windows users WILL see it.

There is way around that. The previous MOUNT or IMGMOUNT command has platform-specific examples, check it out in main.

> Regarding the coloring: I am happy to apply any rule, but I am not sure what those rules are.

You check out a bunch of existing commands, and you know the rules then 😆 That's the best way, just make it consistent.

> It should be noted that this is still based on the original help text.

Yeah, I was thinking the help text clean up should be part of this PR. Sure, the non-functional code clean up come later, but merging the commands without getting the help text in shape seems like a half-job.

My problem with not finishing "whole logical units of work" in a single PR is that you might get busy, or lose interest, then we end up with a half solution in main.

> Also I am running into the size restriction of the message handler, leading to the dreaded invalid message error. For example I cannot add another line of text. But maybe the changes are sufficient, please let me know.

That's no problem, just bump up the max size. It would be wise to increase it by 150% now if we're at the edge with this help message because of the translations (the translations are usually longer than the English original).

**Comment by dividebysandwich** [comment]
> > Regarding the coloring: I am happy to apply any rule, but I am not sure what those rules are.
> 
> You check out a bunch of existing commands, and you know the rules then 😆 That's the best way, just make it consistent.

Ok so makeimg shows just a few core parameters in the first line and then [PARAMETERS], which is detailed further down.  
So instead of
```[color=light-green]mount[reset] [color=white]DRIVE[reset] [color=light-cyan]PATH[reset] [-t TYPE] [-label LABEL] [-fs FS] [-chs C,H,S] -pr -ro```
We would have
```[color=light-green]mount[reset] [color=white]DRIVE[reset] [color=light-cyan]PATH[reset] [-t TYPE] [PARAMETERS]```

I could do that, or I could leave it as it is now.

Also regarding the parameters down below, I can bring that up to parity by doing something like this:
``` -chs C,H,S```
...along with the coloring and such. But I may need more room than the current 11-character justification allows, is that okay? For example "-freesize" would need another character to fit a parameter character afterwards.

> Yeah, I was thinking the help text clean up should be part of this PR.

I agree of course. This change will be very visible to users so it should be well-documented.

> > Also I am running into the size restriction of the message handler, leading to the dreaded invalid message error. For example I cannot add another line of text. But maybe the changes are sufficient, please let me know.
> 
> That's no problem, just bump up the max size. It would be wise to increase it by 150% now if we're at the edge with this help message because of the translations (the translations are usually longer than the English original).

Where is that defined?

File: src/dos/programs/mount.cpp [hunk 40]
```diff
@@ -69,399 +92,1105 @@ void MOUNT::ShowUsage()
...
+	        "             sets the amount of free space available on a drive mounted from\n"
+	        "             a host OS directory.\n"
+	        "  -ro        mount as read-only\n"
+	        "  -pr        path is relative to the configuration file location\n"
+	        "  -t overlay mounts the directory as an overlay on top of an existing drive.\n"
 	        "\n"
 	        "Notes:\n"
-	        "  - '-t overlay' redirects writes for mounted drive to another directory.\n"
-	        "  - '-ro' mounts the drive as read-only.\n"
+	        "  - Use wildcards or multiple image files to mount them the same drive letter,\n"
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: "at the same drive"
"cycle between them." (remove one dot from the end of the sentence)

File: src/dos/programs/mount.cpp [hunk 41]
```diff
@@ -69,399 +92,1105 @@ void MOUNT::ShowUsage()
...
-	        "  SIZE       free space for the virtual drive (KB for floppies, MB otherwise)\n"
-	        "  LABEL      drive label name to use\n"
+	        "  [color=white]DRIVE[reset]      drive letter (A-Z) to mount to\n"
+	        "  [color=light-cyan]PATH[reset]       directory on the host OS (absolute or relative path)\n"
+	        "  [color=light-cyan]IMAGEFILE[reset]  image file on the host OS (absolute or relative path)\n"
+	        "             or on a mounted DOS drive (e.g. C:\\GAME.ISO)\n"
+	        "  [color=light-cyan]IMAGE-SET[reset]  ISO, CUE+BIN, CUE+ISO, or CUE+ISO+FLAC/OPUS/OGG/MP3/WAV\n"
+	        "  TYPE       type of mount: [color=light-cyan]dir[reset], [color=light-cyan]overlay[reset], [color=light-cyan]floppy[reset], [color=light-cyan]hdd[reset], [color=light-cyan]iso[reset] (or [color=light-cyan]cdrom[reset])\n"
+	        "  FS         filesystem: [color=light-cyan]fat[reset], [color=light-cyan]iso[reset], or [color=light-cyan]none[reset] (for bootable images)\n"
+	        "  LABEL      volume label to assign to the mounted drive\n"
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Can we make TYPE, FS, and LABEL white here and in the usage section. Just at least then some of the main params stand out.

Also, list them like this, just like you did in `MAKEIMG` not so long ago 😄 Consistency 😏 

```
-t TYPE
-fs FS
-label LABEL
```

So only TYPE, FS, LABEL in white.

File: src/dos/programs/mount.cpp [hunk 42]
```diff
@@ -69,399 +92,1105 @@ void MOUNT::ShowUsage()
...
+	        "  -ide       attach as IDE device (for CD-ROM/HDD images)\n"
+	        "  -chs       specify geometry (Cylinders,Heads,Sectors) for HDD images\n"
+	        "  -size      specify geometry (BytesPerSector,Sectors,Heads,Cylinders)\n"
+	        "             Alternative to -chs for HDD images\n"
+	        "  -freesize  size (in kB for floppy, in MB for hard disk)\n"
+	        "             sets the amount of free space available on a drive mounted from\n"
+	        "             a host OS directory.\n"
+	        "  -ro        mount as read-only\n"
+	        "  -pr        path is relative to the configuration file location\n"
+	        "  -t overlay mounts the directory as an overlay on top of an existing drive.\n"
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Make "overlay" cyan, too.

Also, two spaces between `-t overlay` and `mounts the...`. The rule is two spaces separate the "args colum" from the "descriptions column" (check other commands).

Drop the dot from the end.

File: src/dos/programs/mount.cpp [hunk 43]
```diff
@@ -69,399 +92,1105 @@ void MOUNT::ShowUsage()
...
+	        "  [color=white]DRIVE[reset]      drive letter (A-Z) to mount to\n"
+	        "  [color=light-cyan]PATH[reset]       directory on the host OS (absolute or relative path)\n"
+	        "  [color=light-cyan]IMAGEFILE[reset]  image file on the host OS (absolute or relative path)\n"
+	        "             or on a mounted DOS drive (e.g. C:\\GAME.ISO)\n"
+	        "  [color=light-cyan]IMAGE-SET[reset]  ISO, CUE+BIN, CUE+ISO, or CUE+ISO+FLAC/OPUS/OGG/MP3/WAV\n"
+	        "  TYPE       type of mount: [color=light-cyan]dir[reset], [color=light-cyan]overlay[reset], [color=light-cyan]floppy[reset], [color=light-cyan]hdd[reset], [color=light-cyan]iso[reset] (or [color=light-cyan]cdrom[reset])\n"
+	        "  FS         filesystem: [color=light-cyan]fat[reset], [color=light-cyan]iso[reset], or [color=light-cyan]none[reset] (for bootable images)\n"
+	        "  LABEL      volume label to assign to the mounted drive\n"
+	        "  -ide       attach as IDE device (for CD-ROM/HDD images)\n"
+	        "  -chs       specify geometry (Cylinders,Heads,Sectors) for HDD images\n"
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: By all means, do it just like in `MAKEIMG`, so `-chs C,H,S`.

File: src/dos/programs/mount.cpp [hunk 44]
```diff
@@ -69,399 +92,1105 @@ void MOUNT::ShowUsage()
...
+	        "  -size      specify geometry (BytesPerSector,Sectors,Heads,Cylinders)\n"
+	        "             Alternative to -chs for HDD images\n"
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: `;` after the closing parenthesis, `alternative` with lowercase `a`

File: src/dos/programs/mount.cpp [hunk 45]
```diff
@@ -69,399 +92,1105 @@ void MOUNT::ShowUsage()
...
+	        "  -freesize  size (in kB for floppy, in MB for hard disk)\n"
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: No dot at the end, `-freesize SIZE`, `SIZE` in white.

File: src/dos/programs/imgmount.cpp [hunk 46]
```diff
@@ -8,6 +8,9 @@
 // IMGMOUNT is a stub that forwards execution to the unified MOUNT command.
 void IMGMOUNT::Run(void)
 {
+	// Print deprecation notice
+	WriteOut(MSG_Get("PROGRAM_IMGMOUNT_DEPRECATED"));
```
Comment (johnnovak) [inline src/dos/programs/imgmount.cpp]: Use `NOTIFY_DisplayWarning`, please. That will print this to the console _and_ the logs when you invoke this from the console, and only to the logs if the old mount command is executed from the autoexec section.

We also want to notify people who use mounting from the autoexec via log warnings.

**Comment by johnnovak** [comment]
Great progress, we're getting there. The individual argument descriptions and the notes now look good (just left a few minor comments about some typos).

> We would have `[color=light-green]mount[reset] [color=white]DRIVE[reset] [color=light-cyan]PATH[reset] [-t TYPE] [PARAMETERS]`
> 
> I could do that, or I could leave it as it is now.

I've come to the same conclusion, yeah. That's for the best.

I think we should do this to create some order and structure here, and make things less formidable. Even I am intimidated by this huge infodump of options, I'm almost afraid to use the command now 😅 

So how about:

```
Usage:
  mount DRIVE PATH [PARAMETERS]
  mount DRIVE IMAGEFILE [IMAGEFILE2] [PARAMETERS]
  mount DRIVE IMAGE-SET [PARAMETERS]
  mount -u DRIVE  (unmounts DRIVE)
```

And then group things by category: common, dir mount only, image only. The below example is _not_ exhaustive, but halfway there. Please work out the details.

```
Parameters:
  DRIVE  ...
  PATH  ...
  IMAGEFILE  ...
  IMAGE-SET ...
  
  Common parameters:
    TYPE ...
    FS ...
    LABEL ...
    -t TYPE ...
    -fs FS  ...
    
  Directory mount parameters:
    -freesize SIZE ...
    -t overlay ....

  Image only parameters:
    -ide ...
```

> Also regarding the parameters down below, I can bring that up to parity by doing something like this:
> -chs C,H,S
> ...along with the coloring and such.

Yes please; I've commented on that in the PR now too.

> But I may need more room than the current 11-character justification allows, is that okay? For example "-freesize" would need another character to fit a parameter character afterwards.

Yeah, there's no "11-charadter rule". All commands have different arg and description "column widths". Just the there should be a 2-space "gutter" between the two columns, that's all!

> I agree of course. This change will be very visible to users so it should be well-documented.

We're in agreement 😄 💯 

> Also I am running into the size restriction of the message handler, leading to the dreaded invalid message error. For example I cannot add another line of text. 

Actually, I've just triplicated your help message 3 times, and it works still fine. I think you came to the wrong conclusion; you must have made a formatting error or something in the message, and that gave you the invalid message error. The length should not be a problem, I've just proven that.

Lastly, this tool I did today should help you with the formatting stuff:

https://www.dosbox-staging.org/tools/ansi-editor/

You'll figure out how to use it :) Copy paste the C++ string into it, then use the copy as C++ button when you're done and it paste it back into the source. The vertical line in the preview shows the 80-char boundary.

**Comment by dividebysandwich** [comment]
I still need to segment the parameters, sorry I missed that.

**Comment by johnnovak** [comment]
@dividebysandwich Thanks, this is starting to look really good! 🎉 You got the colouring 100% right now, great 🥳 

Okay, finishing touches, and if you one-shot this last round, I'm pressing the merge button. Thanks for the patience 🫡 😎 🎖️ 

---

1. First line should read: `Mount a directory or an image file to a drive letter.` (we've discussed it can mount CD images from DOS directory mounts, too)

2.  `Common parameters:` (lowercase `p`)

3. For `-freesize`, let's wrap this into a single paragraph, and change the text slightly plus inform the user about an important default value: `; sets the amount of free space available on the drive (~250 MB by default for HDD directory mounts)`
 
4. For `-ide`: `(for CD-ROM and HDD images)` (I'm picky, I know 😎 )

5. Notes: `then press Cmd+F4...` (to get rid of using "use" twice). `This is useful for programs...` ("use" again, but OK 😄 ), and wrap the entire bullet point for wildcards as a single paragraph.

6. `-ide` notes: I find this a bit confusing. Shouldn't it be `attached IDE HDD and CD-DROM drive`? If I understand it correctly, you need both in this use case?

7.  For the last overlay note, wrap the entire bullet point as a single paragraph. For clarity, let's add `It mounts PATH on the host OS as a write layer...` (just write layer, no hyphen)

8. `(~ is expanded to your home directory)`

**Comment by dividebysandwich** [comment]
Done. Regarding point 8... we should avoid "you" in technical documentation ;)

**Comment by johnnovak** [comment]
> Done.

Cheers!

> Regarding point 8... we should avoid "you" in technical documentation ;)

Me and the "Google developer documentation style guide" disagree 😏 

https://developers.google.com/style/person

> In general, address the reader of your documents using the second person instead of the first person: use you or your instead of we, our, or us. Assume that the reader is the person who's doing the tasks or making the decisions. Use the word user only to refer to the user of the software that your reader is developing.

It's a style thing for sure. I much prefer the more "Intimate" and simpler style of talking "to the user" vs the awkward and impersonal passive 3rd person forms, so I agree with the guide in general and that's the style I follow in the getting started guide too. Feels like a conversation, much more engaging and "human", and the sentence structures are simpler and shorter.

Pretty much all the tech writers I worked with had the same view, so I'll take it 😆

**Comment by dividebysandwich** [comment]
Well I'm not going to fight over this, so there's your "you" ;)

**Comment by johnnovak** [comment]
> Well I'm not going to fight over this, so there's your "you" ;)

It's not a fight 😏 Cheers!

**Comment by johnnovak** [comment]
@dividebysandwich Got most of it right, thanks. Pushed a final touchup commit to fix some remaining stuff; it was much faster this way and I'm sure you're sick of this back and forth already 😆 

Please tidy up the commit history a bit, then we're merging. 

- `Fix #2511 implement proper wildcard handling for images` — just drop the GitHub ticket number and update the message; we don't reference those
- Then all commits after this can be squashed into one (e.g., `Improve MOUNT command help text`)

I think the rest is good as-is.

Management thanks you for your meritorious efforts 🧐

**Comment by Torinde** [comment]
@johnnovak, previous time I asked a similar question you said it's not helpful, so hesitantly asking now:

Should separate Issues be made for:
> Would these log messages appear immediately after mounting the image via the MOUNT command? If so, they should be notifications so they appear in both the console and the logs.

- https://github.com/dosbox-staging/dosbox-staging/pull/4683#discussion_r2701779228

> existing code has not been updated to current dosbox-staging practices - i.e. to use std::filesystem instead of raw c file handling, remove platform specific #ifdef, std::string instead of C string functions, fix integer types, etc.

- https://github.com/dosbox-staging/dosbox-staging/pull/4683#issuecomment-3723320961
seems related to:
  - https://github.com/dosbox-staging/dosbox-staging/pull/4678#discussion_r2691790556, 
  - https://github.com/dosbox-staging/dosbox-staging/pull/4678#issuecomment-3737736215, 
  - https://github.com/dosbox-staging/dosbox-staging/pull/4678#discussion_r2684039736

**Comment by johnnovak** [comment]
> Should separate Issues be made for:

I believe @dividebysandwich is planning to do further such cleanup/improvements in a follow-up PR.

Raising such tickets is not helpful because we could raise 532 cleanup tickets; most of the codebase could "need rework". Rather, we gradually clean things up piecewise when add features or fix things.

Features and fixes should be the driving force for such changes, otherwise why waste time massaging working code?

Also, probably it would be a risky move to substantially rewrite MOUNT before 0.83 is released in less than a month.

**Comment by dividebysandwich** [comment]
@Torinde I hear ya, but as @johnnovak said doing this now adds risk. I want to do it, but in a separate PR and not right away. We may run into subtle issues post 0.83 release and then we don't know if the problem was caused unification or the cleanup.

**Comment by Torinde** [comment]
HDD images created with MAKEIMG can't be mounted. FDD images are OK.
image
image

**Comment by dividebysandwich** [comment]
@Torinde I did not touch the code that tries to auto-determine image sizes. You have to specify the geometry.
Note that it is not really possible to determine the geometry automatically, though ideally mount would make the same assumptions as makeimg.
image
