### PR TITLE
Fix AUTOEXEC.BAT being deleted on disk swap

### LINKED ISSUE #4358: Swapping disks prevents further execution of [autoexec] section
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

_No response_

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

Using Ctrl+F4 to swap disk images causes DOSBox to "forget" any remaining `[autoexec]` commands or commands given with the `-c` command line argument. See reproduction section below.

### Steps to reproduce the behaviour

Put the following into your [autoexec] section in dosbox-staging.conf. The images can be anything, either floppy or cdrom. The game can be anything as well (just using doom as an example):

```
[autoexec]
imgmount a /path/to/disk01.img /path/to/disk02.img -t floppy
mount c /path/to/dosroot
c:
cd doom_se
doom
exit
```

While your game is running, press Ctrl+F4 to swap images then exit the game, The act of swapping images causes DOSBox to forget about any commands remaining in `[autoexec]`. In this case, `exit` does not get run but this is reproducible for any command. If you do not Ctrl+F4, `exit` gets run as expected once Doom exits.

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

Root cause regression from f466410f49e7c7cae31c743878258723b35859a7
Further regression in 09722228235850c56c0e36b8f90c47dbfdd4dae5 - This caused the [autoexec] section to stop execution on disk swap

Virtual_Drive::EmptyCache() deletes and re-creates all files in Z:\ autoexec.cpp relied on an internal boolean to decide whether to update or re-create AUTOEXEC.bat This boolean is invalided by clearing the cache

Fix by attemping the update first and if the file does not exist, create a new one

Also removed some std::move shenaigans that weren't implemented properly to begin with. I'm pretty sure the receiving function needs to take a && for std::move to do any good.

## Related issues

Fixes #4358

# Release notes

Swapping disks with Ctrl+F4 no longer breaks AUTOEXEC.BAT

# Manual testing

Reproduction steps in #4358

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
> Also removed some std::move shenaigans that weren't implemented properly to begin with. I'm pretty sure the receiving function needs to take a && for std::move to do any good.

That was a contributor called MeeAreJenius (lol 😂) who was "vehemently" arguing for using more advanced features like `std::move` and some other stuff. The problem is, `std::move` adds considerable mental overhead and like everything in C++, there are arcane and non-intuitive rules around its usage. My view is only use it when it makes a significant difference (e.g., moving vs copying megabytes of data), not for something as trivial as string manipulation in the filesystem code... But even then, I'd try hard to use plain old references instead.

I still don't fully understand whether his use of `std::move` is 100% correct or not, but what is certain, we're still fixing regressions introduced by his cleanup years later (there were at least 4-5 similar regressions so far).

File: include/dos_system.h [hunk 1]
```diff
@@ -419,7 +419,7 @@ void VFILE_Register(const char *name,
                     const char *dir = "");
 void VFILE_Register(const char* name, const std::vector<uint8_t>& blob,
                     const char* dir = "");
-void VFILE_Update(const char* name, std::vector<uint8_t> blob, const char* dir = "");
+bool VFILE_Update(const char* name, const std::vector<uint8_t> &blob, const char* dir = "");
```
Comment (johnnovak) [inline include/dos_system.h]: Can you rename `blob` to something actually meaningful while you're at it? Please 😅 

All these names carry the exact same amount of information (zero):

- blob
- data
- theThing
- asdf
- bytes
- ...

Although "data" is kinda crap, at least rename it to "data" as this ends up in the "data" member of some struct?

**Review by johnnovak — APPROVED** [review]
Change looks okay, thanks for fixing it. It's pretty much impossible to reason about these things by just looking at the code alone, so approving if it works now 😅

**Comment by weirddan455** [comment]
> > Also removed some std::move shenaigans that weren't implemented properly to begin with. I'm pretty sure the receiving function needs to take a && for std::move to do any good.
> 
> That was a contributor called MeeAreJenius (lol 😂) who was "vehemently" arguing for using more advanced features like `std::move` and some other stuff. The problem is, `std::move` adds considerable mental overhead and like everything in C++, there are arcane and non-intuitive rules around its usage. My view is only use it when it makes a significant difference (e.g., moving vs copying megabytes of data), not for something as trivial as string manipulation in the filesystem code... But even then, I'd try hard to use plain old references instead.
> 
> I still don't fully understand whether his use of `std::move` is 100% correct or not, but what is certain, we're still fixing regressions introduced by his cleanup years later (there were at least 4-5 similar regressions so far).

It was @FeralChild64 that wrote these instances of `std::move`.

The short of it is `std::move` is just a cast from, for example, `std::vector` to `std::vector &&`. The optimization magic happens on the receiving end. Ex: `std::string a = std::move(b);` is only able to optimize out the copy because the standard library provides an operator overload that takes an R-value reference `&&`.

In this case, we're calling one of our own functions that was actually pass by value for the `blob` parameter. The `std::move` cast doesn't do what we want because it has to construct a new `std::vector` anyway.

**Comment by johnnovak** [comment]
> It was @FeralChild64 that wrote these instances of `std::move`.

Okay, MeAreJeenius is off the hook then in this case. Maybe 😛 

> In this case, we're calling one of our own functions that was actually pass by value for the `blob` parameter. The `std::move` cast doesn't do what we want because it has to construct a new `std::vector` anyway.

Makes sense, thanks for the explanation.

File: include/dos_system.h (hunk 1 above)
Comment (weirddan455) [reply include/dos_system.h]: Renamed to data

**Comment by FeralChild64** [comment]
[edit] OK, I was too quick with my concerns - although the comment claims we shouldn't run `create_autoexec_bat_utf8` more than once (and it is going to be run now with every disk swap), it uses static strings, so it won't change the file length. Yet, I think we could simplify the whole implementation.

My proposal:
- `AUTOEXEC_RegisterFile` and `AUTOEXEC_NotifyNewCodePage` should get unified into one function, I'm going to call it `AUTOEXEC_Regenerate` here (but feel free to invent a better name)
- `Add_VFiles` should call `AUTOEXEC_Regenerate` always, the `add_autoexec` argument shouldn't be needed
- `is_vfile_registered` variable should disappear

The `AUTOEXEC_Regenerate` should do as follows:
- if `shutdown_requested` is set - we are shutting down, do nothing, quit
- if `autoexec_module` (pointer to the `AutoExecModule` object) is still null - we are to early during the startup, we don't have all the information to generate the `AUTOEXEC.BAT` yet, quit
- if the UTF-8 variant of the `AUTOEXEC.BAT` hasn't been created yet - create it by calling `create_autoexec_bat_utf8` (this should be done only once during the emulator lifecycle)
- call `create_autoexec_bat_dos` to generate `AUTOEXEC.BAT` translated to the current code page, update the virtual file if it exists, create it otherwise (just like with your change)

The optimization:

```C++
	const auto code_page = get_utf8_code_page();
	if (code_page == vfile_code_page) {
		return;
	}
```

is not crucial - feel free to leave it out if you find it problematic.

**Comment by FeralChild64** [comment]
@weirddan455 Since I was the one who originally wrote the code, it was easier for me to do the rework - I did in on top of your fix: https://github.com/dosbox-staging/dosbox-staging/tree/fc/autoexec-tmp-1

So maybe just merge the changes and I'll submit my cleanup PR afterwards.

**Review by FeralChild64 — APPROVED** [review]

**Comment by weirddan455** [comment]
@FeralChild64 I was just now working through your comment.  I agree with your proposed changes but I'll let you take it from here since you're more familiar with this code.

**Comment by johnnovak** [comment]
@weirddan455 Nice work 🎉 Could you be a bit more specific in the release notes, though?
