### PR TITLE
Fix debugger keypresses not being registered on Windows

### LINKED ISSUE #4089: Dosbox Debugger does not react on key presses
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Windows 10

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

(already discussed on discord but having a real issue is better then some comments somewhere)

the builtin debugger of dosbox does not react to keypresses - that worked in former releases (and also under linux)

minor: also the [x] close icon doesn't close the debugger-window

on discord: interloper98 found the relevant commit: 

https://github.com/dosbox-staging/dosbox-staging/commit/d225c9a619fc69de19a68da473dcfa244862582d

that seems to break the keys in the debugger

### Steps to reproduce the behaviour.

1. build Dosbox with config.h `#define C_DEBUG 1`
2. start dosbox
3. in console `debug attrib.com` then the debug windows comes up
4. press F5(run) or F10(single step) - nothing happens

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

Regression from either d225c9a619fc69de19a68da473dcfa244862582d or 0b1f510683b36d46440a781f8e151b7f942a9f23 Latter commit would not build so I can't confirm

One of those locale changes changed the behavior of the toupper() function Wrote my own ascii_to_upper() function to match expectations in the debugger code

## Related issues

Fixes #4089

# Release notes

Don't think this was ever in a release

# Manual testing

_Please describe the tests that you ran to verify your changes._

_Provide clear instructions so the reviewers can reproduce and verify your results._

_Include relevant details for your test configuration, operating system, etc._

_Ideally, you would also test your changes with a [sanitizer build](https://github.com/dosbox-staging/dosbox-staging/blob/main/BUILD.md#make-a-sanitizer-build) and confirm no issues were found._

_Non-trivial changes **must be** tested on all three OSes we support. If you can't test on a particular OS, ask the team or contributors for help._

The change has been manually tested on:

- [x] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: include/support.h [hunk 1]
```diff
@@ -65,6 +65,27 @@ constexpr uint16_t dos_pagesize = 4096;
 // is in-range of a char and returns it as such.
 char int_to_char(int val);
 
+// A change in one of these 2 commits changed the behavior of toupper() on Windows with MSVC
```
Comment (FeralChild64) [inline include/support.h:68]: According to Microsoft, the `toupper` should only be called for ASCII characters, otherwise the results might be unexpected: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/toupper-toupper-towupper-toupper-l-towupper-l?view=msvc-170#remarks

It seems when I started asking the standard C++ library about various locale formats, the Microsoft implementation (and only this one) changed the `toupper` behavior.

The comment needs to be updated, and we need to check all the other `toupper` calls in DOSBox Staging.

File: include/support.h [hunk 2]
```diff
@@ -65,6 +65,27 @@ constexpr uint16_t dos_pagesize = 4096;
...
+// It passes in values larger than an 8 bit char can hold and needs those to stay intact
+
+// Not even sure if this is defined behavior (might be one of those janky C functions that casts int to char)
+// There are several other instances of toupper() throughout the code that should be looked at
+// This is a workaround for the specific case of the debugger for now
+// We may choose to remove this code later or use it elsewhere where only ascii letters should be considered
+constexpr int ascii_to_upper(int c)
+{
+	if (c >= 'a' && c <= 'z') {
+		constexpr int UpperDiff = 'a' - 'A';
```
Comment (FeralChild64) [inline include/support.h:83]: I think this `constexpr` is an overkill. `return c - 'a' + 'A'` should be enough.

Comment (weirddan455) [reply include/support.h:83]: Yeah, that's probably better.  I was going to write `return c - 32;` at first but thought better of it.

Comment (johnnovak) [reply include/support.h:83]: Yeah, it must be one of those old dirty C functions that cheerfully assume ASCII, no doubt 😆

File: include/support.h (hunk 1 above)
Comment (johnnovak) [reply include/support.h:68]: Honestly, when weird shit like this surfaces I wish DOSBox was written in Java 😎 

No, really. Our build issues would go away and all the platform specific bullshit.

I'm like I'm transported back to the 60s when I see messy dodgy stuff like this... 😆 These are solved problems since Java 1.0 in the 90s.

Comment (weirddan455) [reply include/support.h:68]: >  I wish DOSBox was written in Java

stinky-clint-eastwood

**Review by johnnovak — APPROVED** [review]
Looks fine to me @weirddan455 , thanks for fixing this.

**Comment by LowLevelMahn** [comment]
works for me - also Alt+Pause for jumping into the debugger is working

File: include/support.h (hunk 1 above)
Comment (weirddan455) [reply include/support.h:68]: I looked at where `getch()` gets they key code from.  It's a PDCurses function that goes through a couple levels of parsing but ultimately the data comes from SDL events.  I don't think this should be affected by the locale changes so this is correct for the debugger.

I think it's best to merge this for now to fix the debugger problem.  I wrote that lengthy comment so we could go back and examine other uses of `toupper()` at a later date.

Comment (weirddan455) [reply include/support.h:68]: I'll also echo what @FeralChild64 said in that this usecase of `toupper()` was probably a bug all along that just accidentally worked until the locale changed.  Not everything it passes is even a character (ex. the F5 key which is above the 255 that an 8 bit int can even hold).

If this turns out to be an edge case only applicable to the debugger, we can consider moving this function to `debug.cpp` and not worry about it elsewhere.

**Comment by johnnovak** [comment]
I'm confused. Did we break Alt+Pause and/or the debugger handling again on `main`?

**Alt+Pause** doesn't bring up the debugger in this recent build off `main`:
https://github.com/dosbox-staging/dosbox-staging/actions/runs/12591377678

All the while **Alt+Pause** _does_ bring up the debugger in 0.82.0. I'm testing on Win 10 Pro.

**Comment by weirddan455** [comment]
Discussed on Discord but just putting here for reference:  The mapper on a non-debugger build does not set the debugger hotkey.  Instead it sets Alt + Pause to "Pause emulator".  Solution is to either delete the old mapper file or use the mapper to set the Debugger hotkey from a debugger build.

I think the issue in #4140 is unrelated to this.  Mapper still works fine for me in `main`.
