### PR TITLE
Fix GUS hang in KQ4 enhanced

### LINKED ISSUE #4728: Kings Quest IV enhanced regression
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

_No response_

### What operating system are you using?

Windows 11

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

Ive identified what I believe to be a GUS issue caused by https://github.com/dosbox-staging/dosbox-staging/pull/3977 or https://github.com/dosbox-staging/dosbox-staging/pull/3755.

The NewRisingSun KQ4 enhancement patch (what we called the KQ4 ultimate in exodos) merges the resources of multiple PC releases and the Amiga version. 

To play the different sounds from the versions all together NRS hacked together a driver that initialises the SB, the GUS, and the MT32 all at the same time and uses each device to play different parts of the audio. 

In other forks and upto staging 81.1 the KQ4 ultimate works without issue with sb on base 220 and gus on base 240, but something changed between 81.1 and 82 so that in staging 82 the game now freezes on a black screen at the start when its initialising the devices. I am lead to believe its the GUS as if I change the GUS base to 220 the game no longer freezes and launches, however there is no game audio.

The only thing that looks like it may have caused the issue I can identify is one of those merged fixes, one of which even links to this ticket regarding KQ4 ultimate edition https://github.com/dosbox-staging/dosbox-staging/issues/3645

### Steps to reproduce the behaviour

Explain in detail how to reproduce the bug. Assume no familiarity with the software.
1. Run KQ4 enhanced in Staging 82 or higher (can be sourced from eXoDOS, found in \eXo\eXoDOS\KQ4\patch\NEW)
2.
3.

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by kklobe**
# Description

Allow 64k GUS transfers.

## Related issues

Fixes #4728 

# Manual testing

Ran KQ4 enhanced and verified music and environmental sounds on the beach screen, along with several other games and demos: Quake, Sunflower, Future Crew Unreal and Second Reality, moralhardcandy, multikolor, and toontown.

The change has been manually tested on:

- [x] Windows
- [x] macOS
- [ ] Linux

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/tools/compile-commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by weirddan455** [comment]
This PR gives me a crash with an assert failure immediately after launching KQ4.

```
2026-02-25 15:52:37.825 | GUS: Speex resampler is on, input rate: 44100 Hz, output rate: 48000 Hz
2026-02-25 15:52:37.825 | GUS: Activated 14 voices at 44100 Hz
dosbox: /home/daniel/code/dosbox-staging/src/misc/support.h:160: constexpr cast_t check_cast(check_t) [with cast_t = short unsigned int; check_t = long unsigned int]: Assertion `sizeof(check_t) < sizeof(cast_t) || static_cast<next_int_t<check_t>>(in) <= static_cast<next_int_t<cast_t>>( std::numeric_limits<cast_t>::max())' failed.

Thread 1 "dosbox" received signal SIGABRT, Aborted.
0x00007ffff76a7a2c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff76a7a2c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff764d1a0 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff76345fe in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7635697 in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff76450b2 in __assert_fail () from /usr/lib/libc.so.6
#5  0x0000555555d2e406 in check_cast<unsigned short, unsigned long> (in=65536)
    at /home/daniel/code/dosbox-staging/src/misc/support.h:160
#6  0x0000555555fefd45 in perform_dma_io (direction=DmaDirection::Read, spage=458752, mem_address=0, 
    data_start=0x7fffe42ac010, num_words=65536, is_dma16=0 '\000')
    at /home/daniel/code/dosbox-staging/src/hardware/dma.cpp:58
#7  0x0000555555ff0e64 in DmaChannel::ReadOrWrite (this=0x555559798cb0, direction=DmaDirection::Read, 
    words=65536, buffer=0x7fffe42ac010 "") at /home/daniel/code/dosbox-staging/src/hardware/dma.cpp:434
#8  0x0000555555ff0d21 in DmaChannel::Read (this=0x555559798cb0, words=65536, dest_buffer=0x7fffe42ac010 "")
    at /home/daniel/code/dosbox-staging/src/hardware/dma.cpp:409
#9  0x0000555555ec6442 in Gus::SizedDmaTransfer<(SampleSize)0> (this=0x5555597b9db0)
    at /home/daniel/code/dosbox-staging/src/hardware/audio/gus.cpp:684
#10 0x0000555555eccdd3 in std::__invoke_impl<bool, bool (Gus::*&)(), Gus*&> (
    __f=@0x55555a209d10: (bool (Gus::*)(Gus * const)) 0x555555ec62ac <Gus::SizedDmaTransfer<(SampleSize)0>()>, __t=@0x55555a209d20: 0x5555597b9db0) at /usr/include/c++/15.2.1/bits/invoke.h:76
#11 0x0000555555eccaeb in std::__invoke<bool (Gus::*&)(), Gus*&> (
    __fn=@0x55555a209d10: (bool (Gus::*)(Gus * const)) 0x555555ec62ac <Gus::SizedDmaTransfer<(SampleSize)0>()>) at /usr/include/c++/15.2.1/bits/invoke.h:98
#12 0x0000555555ecc28b in std::_Bind<bool (Gus::*(Gus*))()>::__call<bool, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x55555a209d10, __args=...) at /usr/include/c++/15.2.1/functional:515
#13 0x0000555555ecbc3f in std::_Bind<bool (Gus::*(Gus*))()>::operator()<, bool>() (this=0x55555a209d10)
    at /usr/include/c++/15.2.1/functional:600
#14 0x0000555555ecb5d6 in std::__invoke_impl<bool, std::_Bind<bool (Gus::*(Gus*))()>&>(std::__invoke_other, std::_Bind<bool (Gus::*(Gus*))()>&) (__f=...) at /usr/include/c++/15.2.1/bits/invoke.h:63
#15 0x0000555555ecaef8 in std::__invoke_r<bool, std::_Bind<bool (Gus::*(Gus*))()>&>(std::_Bind<bool (Gus::*(Gus*))()>&) (__fn=...) at /usr/include/c++/15.2.1/bits/invoke.h:116
#16 0x0000555555ec9f6f in std::_Function_handler<bool (), std::_Bind<bool (Gus::*(Gus*))()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/15.2.1/bits/std_function.h:292
#17 0x0000555555ec55f0 in std::function<bool()>::operator() (this=0x5555597b9ed8)
    at /usr/include/c++/15.2.1/bits/std_function.h:593
#18 0x0000555555ec0399 in gus_dma_event () at /home/daniel/code/dosbox-staging/src/hardware/audio/gus.cpp:739
#19 0x000055555600aac5 in PIC_RunQueue () at /home/daniel/code/dosbox-staging/src/hardware/pic.cpp:550
#20 0x0000555555bdf407 in normal_loop () at /home/daniel/code/dosbox-staging/src/dosbox.cpp:118
#21 0x0000555555bdfaf2 in DOSBOX_RunMachine () at /home/daniel/code/dosbox-staging/src/dosbox.cpp:422
#22 0x0000555555d05e36 in CALLBACK_RunRealInt (intnum=33 '!')
    at /home/daniel/code/dosbox-staging/src/cpu/callback.cpp:111
#23 0x0000555556155e9f in run_binary_executable (fullname="sciv.EXE", args="")
    at /home/daniel/code/dosbox-staging/src/shell/shell_misc.cpp:663
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x0000555556155087 in DOS_Shell::ExecuteProgram (this=0x55555a16e9c0, name="sciv", args="")
    at /home/daniel/code/dosbox-staging/src/shell/shell_misc.cpp:527
#25 0x0000555555c7c677 in DOS_Shell::DoCommand (this=0x55555a16e9c0, line=0x7fffffffb1a4 "")
    at /home/daniel/code/dosbox-staging/src/shell/shell_cmds.cpp:238
#26 0x000055555613e790 in DOS_Shell::ParseLine (this=0x55555a16e9c0, line=0x7fffffffb1a0 "sciv")
    at /home/daniel/code/dosbox-staging/src/shell/shell.cpp:361
#27 0x000055555613eda8 in DOS_Shell::RunBatchFile (this=0x55555a16e9c0)
    at /home/daniel/code/dosbox-staging/src/shell/shell.cpp:418
#28 0x000055555613f67c in DOS_Shell::Run (this=0x55555a16e9c0)
    at /home/daniel/code/dosbox-staging/src/shell/shell.cpp:488
#29 0x00005555561491c4 in SHELL_InitAndRun () at /home/daniel/code/dosbox-staging/src/shell/shell.cpp:1363
#30 0x0000555555bd76c1 in main (argc=1, argv=0x7fffffffe3d8)
    at /home/daniel/code/dosbox-staging/src/main.cpp:691
```

**Comment by kklobe** [comment]
Thanks @weirddan455, that'll teach me to skip testing with a debug build. Should be fine now.

**Comment by johnnovak** [comment]
Nice job @kklobe. I've tested the following with the GUS:

- **King's Quest IV Ultimate** (with GUS sound + MT-32 music)
- **[Atlantis by Riot](https://www.pouet.net/prod.php?which=12690)** demo
- **[Stars: Wonders of the World by NoooN](https://www.pouet.net/prod.php?which=301)** demo
- **Soltys**
- **HELL: A Cyberpunk Thriller** (there's music in the intro, and speech in-game, but no music which is expected)

I was about to ask about the (presumably LLM-generated comment) about the DMA controller expecting 0xFFFF for 65,536 byte transfers (so always the actual transfer size minus one), but I've noticed you've removed the comment since 😆 

I was a bit concerned that we might massage one-by-off errors and we have a "two wrongs result in one right" scenario (for this bug), but seems like our DMA functions expect the actual sizes, not the off-by-one value the actual hardware controller seems to use at the register level (assuming the LLM was right about that at all and wasn't confidently lying to our face 😆 I did not fact-check that claim...)

File: src/hardware/audio/gus.cpp [hunk 1]
```diff
@@ -664,14 +664,14 @@ bool Gus::SizedDmaTransfer()
 	LOG_MSG("GUS DMA event: max %u bytes. DMA: tc=%u mask=0 cnt=%u",
 	        BYTES_PER_DMA_XFER,
 	        dma_channel->has_reached_terminal_count ? 1 : 0,
-	        dma_channel->curr_count + 1);
+	        static_cast<uint32_t>(dma_channel->curr_count + 1u));
```
Comment (johnnovak) [inline src/hardware/audio/gus.cpp]: minor: `1u` is a bit weird, `1` would suffice 😄

File: src/hardware/audio/gus.cpp [hunk 2]
```diff
@@ -664,14 +664,14 @@ bool Gus::SizedDmaTransfer()
...
 #endif
 
 	// Get the current DMA offset relative to the block of GUS memory
 	const auto offset = GetDmaOffset();
 
 	// Get the pending DMA count from channel
-	const uint16_t desired = dma_channel->curr_count + 1;
+	const uint32_t desired = dma_channel->curr_count + 1u;
```
Comment (johnnovak) [inline src/hardware/audio/gus.cpp]: Same here.

File: src/hardware/dma.cpp [hunk 3]
```diff
@@ -79,14 +82,14 @@ static void perform_dma_io(const DmaDirection direction, const PhysPt spage,
 
 		// Copy the data from the page address into the data pointer
 		if (direction == DmaDirection::Read) {
-			for (auto i = 0; i < chunk_bytes; ++i) {
+			for (uint32_t i = 0; i < chunk_bytes; ++i) {
```
Comment (johnnovak) [inline src/hardware/dma.cpp:85]: Man, that always throws me off... `int` uses the "native width" in Nim, so int64 on 64-bit builds. But in C land, it's always int32, even on 64-bit 😅

File: src/hardware/audio/gus.cpp (hunk 1 above)
Comment (kklobe) [reply src/hardware/audio/gus.cpp]: I thought I'd leave it in there just for you
