### PR TITLE
Handle OEM102 and ABNT1 keyboard scancodes

### LINKED ISSUE #2199: Pressing right side Command key inserts / character
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Mac OS

### If Other OS, please describe

macOS 12.6.2/x86-64

### Relevant hardware info

2017 15" MacBook Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When pressing right side Command key the key press is registered but also inserts / character.

### Steps to reproduce the behaviour.

1. Start DOSBox Staging 0.80.1.
2. Press right side Command key.
3. Observe / character being inserted on the command line.

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
The mapper, keyboard, and BIOS tables are expanded to handle the `oem102` and `abnt1` keys (found on Brazilian ABNT2 keyboards).

The left and right windows keys are given their correct scancodes (91 and 92).

Ref: http://www.quadibloc.com/comp/scan.htm, thanks to @FeralChild64 for this.

Non-functional changes:
 - The BIOS table of keys is moved inside an accessor function where the lookup index is validated.

 - Each key in the BIOS table of keys is prefixed with its index as a comment. This can be used as a debugging aid, for example: you can directly lookup the key being used by printing the index.

 - Type narrowing is fixed and checked (as a separate commit)

Fixes #2199

### CODE REVIEW

**Comment by kcgen** [comment]
@Grounded0 , @johnnovak, @kklobe - hoping you can check if ``origin/kc/improve-intl1-key-1` no longer spams `////`s when hitting your right-⌘ key. Thanks!

@rsribeiro , @ ThomasEricB, hoping you can test your ABNT2 keyboards, if you can build this branch: `origin/kc/improve-intl1-key-1` -- much thanks for the feedback!

File: include/bios.h [hunk 1]
```diff
@@ -112,8 +112,11 @@
 #define BIOS_DEFAULT_IRQ2_LOCATION		(RealMake(0xf000,0xff55))
 #define BIOS_DEFAULT_RESET_LOCATION		(RealMake(0xf000,(machine==MCH_PCJR)?0x0043:0xe05b))
 
-/* maximum of scancodes handled by keyboard bios routines */
-#define MAX_SCAN_CODE 0x59
+// The maximum "normal key" scancode value handled by keyboard bios routines.
+// This should match the maximum return value set in KEYBOARD_AddKey()'s switch
+// statement. The scan code is read from an 8-bit register (reg_al) and
+// therefore limited to handling 255 keys.
+constexpr uint8_t MAX_SCAN_CODE = 115;
```
Comment (johnnovak) [inline include/bios.h:119]: Nice comment 👍🏻

File: src/ints/bios_keyboard.cpp [hunk 2]
```diff
@@ -33,103 +31,146 @@ static callback_number_t call_irq6  = 0;
...
+};
+
+static const KeyCodes& get_key_codes_for(const uint8_t scan_code)
+{
+	// LOG_MSG("BIOS: Scan code %u (0x%xh) requested", scan_code, scan_code);
+
+	// clang-format off
+	// Ref: http://www.quadibloc.com/comp/scan.htm, Set 1 layout
+	static constexpr KeyCodes keyboard[] = {
+		// index   normal   shift control     alt
```
Comment (johnnovak) [inline src/ints/bios_keyboard.cpp:48]: minor: `control` is slightly misaligned

File: src/ints/bios_keyboard.cpp [hunk 3]
```diff
@@ -33,103 +31,146 @@ static callback_number_t call_irq6  = 0;
...
+		/* 106 */ { /* placeholder */ }, /* F23 */
+		/* 107 */ { /* placeholder */ }, /* F24 */
+		/* 108 */ { /* placeholder */ },
+		/* 109 */ { /* placeholder */ },
+		/* 110 */ { /* placeholder */ },
+		/* 111 */ { /* placeholder */ },
+		/* 112 */ { /* placeholder */ },
+		/* 113 */ { /* placeholder */ }, /* Attn  */
+		/* 114 */ { /* placeholder */ }, /* CrSel */
+		/* 115 */ {   0x352f, 0x353f, none,   none }  /* International Key 3  */
```
Comment (johnnovak) [inline src/ints/bios_keyboard.cpp:164]: Very nice 🎉

**Comment by johnnovak** [comment]
> @Grounded0 , @johnnovak, @kklobe - hoping you can check if `origin/kc/improve-intl1-key-1` no longer spams `////`s when hitting your right-⌘ key. Thanks!
> 
> @rsribeiro , @ ThomasEricB, hoping you can test your ABNT2 keyboards, if you can build this branch: `origin/kc/improve-intl1-key-1` -- much thanks for the feedback!

Yep, first checked with `main`; pressing Right-Command generated `/` characters.
Then tried the same with this branch; the fix seems to be working.

Haven't regression tested the keyboard input extensively, though. We'll regression test it anyway in the coming weeks / months.

So looks good, ship it 😄 🚢

**Review by johnnovak — APPROVED** [review]

**Comment by Grounded0** [comment]
This fix reminds me of another overengineered product: 🙂
https://www.youtube.com/watch?v=lZhXFhSiQVc

**Comment by rsribeiro** [comment]
Just had an opportunity to test it on a brazilian ABNT2 keyboard and the slash/question mark key is not working

File: src/ints/bios_keyboard.cpp (hunk 2 above)
Comment (kcgen) [reply src/ints/bios_keyboard.cpp]: good catch!

**Comment by kcgen** [comment]
> Just had an opportunity to test it on a brazilian ABNT2 keyboard and the slash/question mark key is not working

Thanks for the quick test, @rsribeiro.

I've made another commit to try to fix it: using SDL's INTL 1 scan code instead of INTL 3 (even though, according to  http://www.quadibloc.com/comp/scan.htm, the key is called INTL 3).

Fingers crossed this does the trick.

**Comment by rsribeiro** [comment]
> > Just had an opportunity to test it on a brazilian ABNT2 keyboard and the slash/question mark key is not working
> 
> Thanks for the quick test, @rsribeiro.
> 
> I've made another commit to try to fix it: using SDL's INTL 1 scan code instead of INTL 3 (even though, according to http://www.quadibloc.com/comp/scan.htm, the key is called INTL 3).
> 
> Fingers crossed this does the trick.

Still not working :(

**Comment by kcgen** [comment]
Darn; I will add some logging around the SDL event side and the emulated BIOS side, and try to figure this out.  Will let you know when that's ready (hopefully tomorrow).

**Comment by kcgen** [comment]
@rsribeiro , 

In the `main` branch, a new SDL key-logger has been added under the `contrib/sdl_key_logger` directory:

It's a small stand-alone tool that hopefully will help us figure out the connection between the extra ABNT2 keys and how SDL identifies them.

Notes here:

https://github.com/dosbox-staging/dosbox-staging/tree/main/contrib/sdl_key_logger

Sample output:

```
INFO: DOSBox Staging SDL key logger
INFO: Quit by tapping ESC or close the GUI window
INFO:  
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: Left Ctrl     224 e0h | Left Ctrl     1073742048 400000e0h |    64   40h | no
INFO: Left Alt      226 e2h | Left Alt      1073742050 400000e2h |   256  100h | no
INFO: Space          44 2ch | Space                 32       20h |     0    0h | no
INFO: Right Alt     230 e6h | Right Alt     1073742054 400000e6h |   512  200h | no
INFO: Right Ctrl    228 e4h | Right Ctrl    1073742052 400000e4h |   128   80h | no
INFO: PageUp         75 4bh | PageUp        1073741899 4000004bh |     0    0h | no
INFO: Up             82 52h | Up            1073741906 40000052h |     0    0h | no
INFO: PageDown       78 4eh | PageDown      1073741902 4000004eh |     0    0h | no
INFO: Right Shift   229 e5h | Right Shift   1073742053 400000e5h |     2    2h | no
INFO: Left Shift    225 e1h | Left Shift    1073742049 400000e1h |     1    1h | no
INFO: Z              29 1dh | Z                    122       7ah |     0    0h | no
INFO: X              27 1bh | X                    120       78h |     0    0h | no
INFO: C               6  6h | C                     99       63h |     0    0h | no
INFO: V              25 19h | V                    118       76h |     0    0h | no
INFO: B               5  5h | B                     98       62h |     0    0h | no
INFO:  
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: N              17 11h | N                    110       6eh |     0    0h | no
INFO: M              16 10h | M                    109       6dh |     0    0h | no
INFO: ,              54 36h | ,                     44       2ch |     0    0h | no
INFO: .              55 37h | .                     46       2eh |     0    0h | no
INFO: /              56 38h | /                     47       2fh |     0    0h | no
INFO: Right Shift   229 e5h | Right Shift   1073742053 400000e5h |     2    2h | no
INFO: CapsLock       57 39h | CapsLock      1073741881 40000039h |  8192 2000h | no
```


If you can run it for your bottom two rows:
 - Left shift, ... through Right Shift, then
 - Left Ctrl ... through Right Ctrl)

And post the results, hopefully it helps progress this. Thanks!

**Comment by kcgen** [comment]
Moving this PR to draft for now, pending feedback from @rsribeiro , @ThomasEricB  (or anything else with an ABNT2 keyboard who can get some data from it, mentioned here: <https://github.com/dosbox-staging/dosbox-staging/pull/2209#issuecomment-1383016104>

**Comment by rsribeiro** [comment]
```
INFO: DOSBox Staging SDL key logger
INFO: Quit by tapping ESC or close the GUI window
INFO:
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: Left Shift    225 e1h | Left Shift    1073742049 400000e1h |  4097 1001h | no
INFO:               100 64h | \                     92       5ch |  4096 1000h | no
INFO: Z              29 1dh | Z                    122       7ah |  4096 1000h | no
INFO: X              27 1bh | X                    120       78h |  4096 1000h | no
INFO: C               6  6h | C                     99       63h |  4096 1000h | no
INFO: V              25 19h | V                    118       76h |  4096 1000h | no
INFO: B               5  5h | B                     98       62h |  4096 1000h | no
INFO: N              17 11h | N                    110       6eh |  4096 1000h | no
INFO: M              16 10h | M                    109       6dh |  4096 1000h | no
INFO: ,              54 36h | ,                     44       2ch |  4096 1000h | no
INFO: .              55 37h | .                     46       2eh |  4096 1000h | no
INFO: /              56 38h | ;                     59       3bh |  4096 1000h | no
INFO:               135 87h | /                     47       2fh |  4096 1000h | no
INFO: Right Shift   229 e5h | Right Shift   1073742053 400000e5h |  4098 1002h | no
INFO: Left Ctrl     224 e0h | Left Ctrl     1073742048 400000e0h |  4160 1040h | no
INFO:
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: Left Windows  227 e3h | Left Windows  1073742051 400000e3h |  5120 1400h | no
INFO: Left Alt      226 e2h | Left Alt      1073742050 400000e2h |  4352 1100h | no
INFO: Space          44 2ch | Space                 32       20h |  4096 1000h | no
INFO: Left Ctrl     224 e0h | Left Ctrl     1073742048 400000e0h |  4160 1040h | no
INFO: Right Alt     230 e6h | Right Alt     1073742054 400000e6h |  4672 1240h | no
INFO: Menu          101 65h | Menu          1073741925 40000065h |  4096 1000h | no
INFO: Right Ctrl    228 e4h | Right Ctrl    1073742052 400000e4h |  4224 1080h | no
INFO: Left Alt      226 e2h | Left Alt      1073742050 400000e2h |  4352 1100h | no
INFO: Q              20 14h | Q                    113       71h |  4352 1100h | no
INFO: W              26 1ah | W                    119       77h |  4352 1100h | no
INFO: Escape         41 29h | Escape                27       1bh |  4096 1000h | no
```

This is the slash/question mark key:
```
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO:               135 87h | /                     47       2fh |  4096 1000h | no
```

**Comment by kcgen** [comment]
Thanks you, @rsribeiro !

**Comment by ThomasEricB** [comment]
Unfortunately, I don't know how to enable ABNT 2 on the Steam Deck... Here is my keyboard's default keys in ABNT1:

```
[deck@arch sdl_key_logger]$ ./build/logger
INFO: DOSBox Staging SDL key logger
INFO: Quit by tapping ESC or close the GUI window
INFO:  
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: `              53 35h | '                     39       27h |     0    0h |yes
INFO: 1              30 1eh | 1                     49       31h |     0    0h | no
INFO: 2              31 1fh | 2                     50       32h |     0    0h | no
INFO: 3              32 20h | 3                     51       33h |     0    0h | no
INFO: 4              33 21h | 4                     52       34h |     0    0h | no
INFO: 5              34 22h | 5                     53       35h |     0    0h | no
INFO: 6              35 23h | 6                     54       36h |     0    0h | no
INFO: 7              36 24h | 7                     55       37h |     0    0h | no
INFO: 8              37 25h | 8                     56       38h |     0    0h | no
INFO: 9              38 26h | 9                     57       39h |     0    0h | no
INFO: 0              39 27h | 0                     48       30h |     0    0h | no
INFO: -              45 2dh | -                     45       2dh |     0    0h | no
INFO: =              46 2eh | =                     61       3dh |     0    0h | no
INFO: Backspace      42 2ah | Backspace              8        8h |     0    0h | no
INFO: Tab            43 2bh | Tab                    9        9h |     0    0h | no
INFO: Q              20 14h | Q                    113       71h |     0    0h | no
INFO: W              26 1ah | W                    119       77h |     0    0h | no
INFO: E               8  8h | E                    101       65h |     0    0h | no
INFO: R              21 15h | R                    114       72h |     0    0h | no
INFO: T              23 17h | T                    116       74h |     0    0h | no
INFO: Y              28 1ch | Y                    121       79h |     0    0h | no
INFO: U              24 18h | U                    117       75h |     0    0h | no
INFO: I              12  ch | I                    105       69h |     0    0h | no
INFO: O              18 12h | O                    111       6fh |     0    0h | no
INFO: P              19 13h | P                    112       70h |     0    0h | no
INFO: [              47 2fh | '                     39       27h |     0    0h | no
INFO: ]              48 30h | [                     91       5bh |     0    0h | no
INFO: Return         40 28h | Return                13        dh |     0    0h | no
INFO: CapsLock       57 39h | CapsLock      1073741881 40000039h |  8192 2000h | no
INFO: A               4  4h | A                     97       61h |  8192 2000h | no
INFO: S              22 16h | S                    115       73h |  8192 2000h | no
INFO: D               7  7h | D                    100       64h |  8192 2000h | no
INFO: F               9  9h | F                    102       66h |  8192 2000h | no
INFO: G              10  ah | G                    103       67h |  8192 2000h | no
INFO: H              11  bh | H                    104       68h |  8192 2000h | no
INFO: J              13  dh | J                    106       6ah |  8192 2000h | no
INFO: K              14  eh | K                    107       6bh |  8192 2000h | no
INFO: L              15  fh | L                    108       6ch |  8192 2000h | no
INFO: ;              51 33h | ç                   231       e7h |  8192 2000h | no
INFO: '              52 34h | ~                    126       7eh |  8192 2000h | no
INFO: \              49 31h | ]                     93       5dh |  8192 2000h | no
INFO: Left Shift    225 e1h | Left Shift    1073742049 400000e1h |  8193 2001h | no
INFO:               100 64h | \                     92       5ch |  8192 2000h | no
INFO: Z              29 1dh | Z                    122       7ah |  8192 2000h | no
INFO: X              27 1bh | X                    120       78h |  8192 2000h | no
INFO: C               6  6h | C                     99       63h |  8192 2000h | no
INFO: V              25 19h | V                    118       76h |  8192 2000h | no
INFO: B               5  5h | B                     98       62h |  8192 2000h | no
INFO: N              17 11h | N                    110       6eh |  8192 2000h | no
INFO: M              16 10h | M                    109       6dh |  8192 2000h | no
INFO: ,              54 36h | ,                     44       2ch |  8192 2000h | no
INFO: .              55 37h | .                     46       2eh |  8192 2000h | no
INFO: /              56 38h | ;                     59       3bh |  8192 2000h | no
INFO:               135 87h | /                     47       2fh |  8192 2000h | no
INFO: Right Shift   229 e5h | Right Shift   1073742053 400000e5h |  8194 2002h | no
INFO: Left Ctrl     224 e0h | Left Ctrl     1073742048 400000e0h |  8256 2040h | no
INFO: Left Alt      226 e2h | Left Alt      1073742050 400000e2h |  8448 2100h | no
INFO: Space          44 2ch | Space                 32       20h |  8192 2000h | no
INFO: Right Alt     230 e6h | Right Alt     1073742054 400000e6h |  8704 2200h | no
INFO: Menu          101 65h | Menu          1073741925 40000065h |  8192 2000h | no
INFO: Right Ctrl    228 e4h | Right Ctrl    1073742052 400000e4h |  8320 2080h | no
INFO: F1             58 3ah | F1            1073741882 4000003ah |  8192 2000h | no
INFO: F2             59 3bh | F2            1073741883 4000003bh |  8192 2000h | no
INFO: F3             60 3ch | F3            1073741884 4000003ch |  8192 2000h | no
INFO: F4             61 3dh | F4            1073741885 4000003dh |  8192 2000h | no
INFO: F5             62 3eh | F5            1073741886 4000003eh |  8192 2000h | no
INFO: F6             63 3fh | F6            1073741887 4000003fh |  8192 2000h | no
INFO: F7             64 40h | F7            1073741888 40000040h |  8192 2000h | no
INFO: F8             65 41h | F8            1073741889 40000041h |  8192 2000h | no
INFO: F9             66 42h | F9            1073741890 40000042h |  8192 2000h | no
INFO: F10            67 43h | F10           1073741891 40000043h |  8192 2000h | no
INFO: F11            68 44h | F11           1073741892 40000044h |  8192 2000h | no
INFO: F12            69 45h | F12           1073741893 40000045h |  8192 2000h | no
INFO: Up             82 52h | Up            1073741906 40000052h |  8192 2000h | no
INFO: Down           81 51h | Down          1073741905 40000051h |  8192 2000h | no
INFO: Left           80 50h | Left          1073741904 40000050h |  8192 2000h | no
INFO:  
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: Right          79 4fh | Right         1073741903 4000004fh |  8192 2000h | no
INFO: Keypad 0       98 62h | Keypad 0      1073741922 40000062h |  8192 2000h | no
INFO: Keypad 1       89 59h | Keypad 1      1073741913 40000059h |  8192 2000h | no
INFO: Keypad 2       90 5ah | Keypad 2      1073741914 4000005ah |  8192 2000h | no
INFO: Keypad 3       91 5bh | Keypad 3      1073741915 4000005bh |  8192 2000h | no
INFO: Keypad 4       92 5ch | Keypad 4      1073741916 4000005ch |  8192 2000h | no
INFO: Keypad 5       93 5dh | Keypad 5      1073741917 4000005dh |  8192 2000h | no
INFO: Keypad 6       94 5eh | Keypad 6      1073741918 4000005eh |  8192 2000h | no
INFO: Keypad 7       95 5fh | Keypad 7      1073741919 4000005fh |  8192 2000h | no
INFO: Keypad 8       96 60h | Keypad 8      1073741920 40000060h |  8192 2000h | no
INFO: Keypad 9       97 61h | Keypad 9      1073741921 40000061h |  8192 2000h | no
INFO: Numlock        83 53h | Numlock       1073741907 40000053h | 12288 3000h | no
INFO: Keypad /       84 54h | Keypad /      1073741908 40000054h | 12288 3000h | no
INFO: Keypad *       85 55h | Keypad *      1073741909 40000055h | 12288 3000h | no
INFO: Keypad -       86 56h | Keypad -      1073741910 40000056h | 12288 3000h | no
INFO: Keypad +       87 57h | Keypad +      1073741911 40000057h | 12288 3000h | no
INFO: Keypad Enter   88 58h | Keypad Enter  1073741912 40000058h | 12288 3000h | no
INFO: AudioPlay     261 105h | AudioPlay     1073742085 40000105h | 12288 3000h | no
INFO: AudioNext     258 102h | AudioNext     1073742082 40000102h | 12288 3000h | no
INFO: AudioPrev     259 103h | AudioPrev     1073742083 40000103h | 12288 3000h | no
INFO: AudioStop     260 104h | AudioStop     1073742084 40000104h | 12288 3000h | no
INFO: Numlock        83 53h | Numlock       1073741907 40000053h | 12288 3000h | no
INFO: ScrollLock     71 47h | ScrollLock    1073741895 40000047h | 45056 b000h | no
INFO: Pause          72 48h | Pause         1073741896 40000048h | 45056 b000h | no
INFO: Insert         73 49h | Insert        1073741897 40000049h | 45056 b000h | no
INFO: Home           74 4ah | Home          1073741898 4000004ah | 45056 b000h | no
INFO: PageUp         75 4bh | PageUp        1073741899 4000004bh | 45056 b000h | no
INFO: Delete         76 4ch | Delete               127       7fh | 45056 b000h | no
INFO: End            77 4dh | End           1073741901 4000004dh | 45056 b000h | no
INFO: PageDown       78 4eh | PageDown      1073741902 4000004eh | 45056 b000h | no
INFO: Escape         41 29h | Escape                27       1bh | 45056 b000h | no
```

@rsribeiro If you could provide the keys between P and Enter, L and Enter, M and Right Shift + t for @kcgen that would be great!

firefox_32IwKMQplJ

**Comment by rsribeiro** [comment]
```
INFO: DOSBox Staging SDL key logger
INFO: Quit by tapping ESC or close the GUI window
INFO:
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: 0              39 27h | 0                     48       30h |  4096 1000h | no
INFO: -              45 2dh | -                     45       2dh |  4096 1000h | no
INFO: =              46 2eh | =                     61       3dh |  4096 1000h | no
INFO: Backspace      42 2ah | Backspace              8        8h |  4096 1000h | no
INFO: P              19 13h | P                    112       70h |  4096 1000h | no
INFO: [              47 2fh | ´                   180       b4h |  4096 1000h | no
INFO: ]              48 30h | [                     91       5bh |  4096 1000h | no
INFO: Return         40 28h | Return                13        dh |  4096 1000h | no
INFO: ;              51 33h | ç                   231       e7h |  4096 1000h | no
INFO: '              52 34h | ~                    126       7eh |  4096 1000h | no
INFO: \              49 31h | ]                     93       5dh |  4096 1000h | no
INFO: ,              54 36h | ,                     44       2ch |  4096 1000h | no
INFO: .              55 37h | .                     46       2eh |  4096 1000h | no
INFO: /              56 38h | ;                     59       3bh |  4096 1000h | no
INFO:               135 87h | /                     47       2fh |  4096 1000h | no
INFO:
INFO: SCANCODE      val hex | SDLK                 val       hex |  KMOD   hex | remapped?
INFO: ~~~~~~~~~~~~~ ~~~ ~~~ | ~~~~~~~~~~~~~ ~~~~~~~~~~ ~~~~~~~~~ | ~~~~~ ~~~~~ | ~~~~~~~~~
INFO: Right Shift   229 e5h | Right Shift   1073742053 400000e5h |  4098 1002h | no
INFO: `              53 35h | '                     39       27h |  4096 1000h | no
INFO: Escape         41 29h | Escape                27       1bh |  4096 1000h | no
```

**Comment by kcgen** [comment]
@FeralChild64 , I've rebased on the KBD_KEYS groupings.  

I placed the OEM102 (`\|`) and ABNT1 (`/?`) keys along with the other symbols:

```c++

KBD_grave, KBD_minus, KBD_equals, KBD_backslash,
KBD_leftbracket, KBD_rightbracket,
KBD_semicolon, KBD_quote,
KBD_oem102, KBD_period, KBD_comma, KBD_slash, KBD_abnt1,

```
Placed on the 4th row at start and end like on the keyboard:

**Comment by FeralChild64** [comment]
@kcgen Sure, I just wanted to have a readable list.

**Comment by kcgen** [comment]
## Add handling for a new key

Graphical depiction corresponding to the notes included with the SDL key logger (open fullscreen in 4k):

guide_to_adding_keys

**Comment by kcgen** [comment]
Notes for using the "ticks" dead-key, to the right of P:
 - Ensure you're using codepage 860 or have started up with the Brazilian language: `dosbox -lang br`.
 - Press the "ticks" key once followed by any character (or space). A back-tick will be produced along-side the character.
 - Use Shift + the "ticks" key followed by any character (or space) to produce an inward-tick.

**Comment by kcgen** [comment]
Thanks for testing this, @ThomasEricB!
Let's merge.
