### PR TITLE
Make restart_dosbox() go through the normal shutdown routine

### LINKED ISSUE #4318: Command history is not preserved when restarting with `CONFIG -R`
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

_No response_

### What operating system are you using?

Windows 10

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

1. Change some setting that requires a restart, e.g. `windowresolution 1200x700`
2. `CONFIG -R`
3. Press the up arrow and note `windowresolution 1200x700` is not in the command history.

Basically, the command history is not preserved when `CONFIG -R` is issued like it is on exit.

### Steps to reproduce the behaviour

_No response_

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

Restarting either by `config -r` or by Ctrl+Alt+Home hotkey now goes through the normal shutdown procedure. A child process gets created that waits for the parent process to terminate before continuing.

What caused me to look into this was the command line history not being saved on restart but I was concerned about other clean-up routines not being run (ex. some of the file system meta-data doesn't get written until close).

This ensures that restart is the same as a normal shutdown. It also delays init of the new process until the old process is fully terminated.

## Related issues

Fixes #4318

# Release notes

Restarting DOSBox now correctly saves the command line history.

# Manual testing

Command line history is now saved after restart on Windows and Linux. Log output confirms the parent process gets fully shutdown before the child process starts init.

The change has been manually tested on:

- [x] Windows
- [x] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
> It's hipster Unix and they're too cool to have a `/proc` apparently.

Erm, excuse me? 😂 

https://www.opengroup.org/openbrand/register/brand3710.htm

It's _more_ Unix than Linux, mate 😎🤘🏻 Well, at least it's certified (whatever that means, lol 😂)

And some actual info to make my comment not only participation-award worthy:
https://superuser.com/a/631696

Happy to test stuff if you find a viable macOS solution.

UPDATE: Can't you just use `waitpid()`? 

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/waitpid.2.html

**Comment by weirddan455** [comment]
> UPDATE: Can't you just use waitpid()?

`waitpid()` only works when you're the parent waiting on a child. We're doing the reverse (child waiting on the parent).

If I try it the other way, it segfaults. SDL/X11/PulseAudio don't like it when a new child process tries to take over for the parent so the child process has to be the one that calls `execvp()` and the parent has to clean up after itself.

I'm still going to look into this more later.

**Comment by johnnovak** [comment]
@weirddan455 We could always use the filesystem on macOS: generate a "pid" file in `/tmp`, delete the file on exit, then poll that file in the child process until it gets deleted.

**Comment by weirddan455** [comment]
> @weirddan455 We could always use the filesystem on macOS: generate a "pid" file in `/tmp`, delete the file on exit, then poll that file in the child process until it gets deleted.

But when is "on exit"? The last bit of our code that runs from what I can tell is `atexit(QuitSDL);` but then global destructors still run after that.

If I had a defined exit point in our code, I would just defer `execvp()` until then rather than making a temp file but it's more complicated than that.

**Comment by johnnovak** [comment]
@weirddan455 Magic AI generated answer how to do this on a BSD (macOS is a BSD, effectively). @kklobe is now proud of me, I'm sure 😛 

Maybe it's all humbug, but hey, took me 5 seconds 😆 

Btw, I was thinking even before looking this up to programatically query the parent PID from the child process, then you don't need to pass it along. Maybe just detect at runtime if the current Staging process has a parent process. I'm sure there is a Windows API call for getting the parent PID as well.


image

image

image

**Comment by weirddan455** [comment]
I'll give AI half-credit. `kill()` with a signal of 0 is pretty clever and works on Linux as well.

> Btw, I was thinking even before looking this up to programatically query the parent PID from the child process, then you don't need to pass it along. Maybe just detect at runtime if the current Staging process has a parent process. I'm sure there is a Windows API call for getting the parent PID as well.

This doesn't really work. At least on Linux, a process always has a parent. If the parent DOSBox process has terminated already, it gets re-parented but not always to PID 1. On my system, `systemd --user` became the parent with a PID of over 1000. We would have to query the parent process for more information and decide whether it's DOSBox or a system process and that seems error-prone and OS specific.

A way I could avoid sending the PID is to do the `kill()` + wait loop after `fork()` and before `execvp()` but I don't think there's a way to do this on Windows since there's no real `fork()` alternative. We're using `CreateProcess()`.

**Comment by johnnovak** [comment]
> This doesn't really work. At least on Linux, a process always has a parent.

Ah, that's right. I'm sure it's the same on all OSes, actually. I'm just not a systems programmer so it didn't really occur to me when I wrote that 😄 

> A way I could avoid sending the PID is to do the kill() + wait loop after fork() and before execvp() but I don't think there's a way to do this on Windows since there's no real fork() alternative. We're using CreateProcess().

Nah, just pass it then. That works and it's 100% reliable.

**Comment by weirddan455** [comment]
Ready for review. Updated toplevel comment, Added and tested Windows codepath. Mac will take the same codepath as Linux but I need a Mac user to test.

File: src/gui/sdlmain.cpp [hunk 1]
```diff
@@ -4774,6 +4774,33 @@ int sdl_main(int argc, char* argv[])
...
+			// Waits for the process to terminate.
+			// If we failed to open it, it's probably already dead.
+			WaitForSingleObject(process, INFINITE);
+			CloseHandle(process);
+		}
+		#else
+		while (1) {
+			// Signal of 0 does not actually send a signal.
+			// It only checks for existance and permissions of the PID.
+			constexpr int SIGNAL = 0;
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp]: Signal

File: src/gui/sdlmain.cpp [hunk 2]
```diff
@@ -4774,6 +4774,33 @@ int sdl_main(int argc, char* argv[])
...
+		constexpr BOOL InheritHandles = FALSE;
+		HANDLE process = OpenProcess(DesiredAccess, InheritHandles, *arguments->wait_pid);
+		if (process) {
+			// Waits for the process to terminate.
+			// If we failed to open it, it's probably already dead.
+			WaitForSingleObject(process, INFINITE);
+			CloseHandle(process);
+		}
+		#else
+		while (1) {
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp]: No love for `for (;;)`? 😎

File: src/gui/sdlmain.cpp [hunk 3]
```diff
@@ -4774,6 +4774,33 @@ int sdl_main(int argc, char* argv[])
...
+			// It only checks for existance and permissions of the PID.
+			constexpr int SIGNAL = 0;
+			int ret = kill(*arguments->wait_pid, 0);
+			// ESRCH means PID does not exist.
+			if (ret == -1 && errno == ESRCH) {
+				break;
+			}
+			Delay(50);
+		}
+		#endif
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp]: Nice explanatory comments 🎖️ 

Just do a Clang reformat on this block, please; that will pull the ifdefs to the start of the lines.

File: src/gui/sdlmain.cpp [hunk 4]
```diff
@@ -4570,11 +4570,38 @@ static int edit_primary_config()
...
+					// The integer value should be the next element following "--waitpid".
+					// If we found an integer, remove it as well.
+					it = parameters.erase(it);
+				}
+			}
+		} else {
+			++it;
+		}
+	}
+}
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:4591]: I think we should use `CommandLine::FindRemoveIntArgument()` instead.

Ah, or maybe we can't use that here...

File: src/gui/sdlmain.cpp [hunk 5]
```diff
@@ -4570,11 +4570,38 @@ static int edit_primary_config()
...
+
+void restart_dosbox(std::vector<std::string> &parameters)
+{
 
 	control->ApplyQueuedValuesToCli(parameters);
 
+	// Remove any existing --waitpid paramaters.
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp]: typo: parameters

File: src/gui/sdlmain.cpp [hunk 6]
```diff
@@ -4646,13 +4673,24 @@ void restart_dosbox(std::vector<std::string> &parameters) {
...
+	int ret = fork();
+	switch (ret) {
+		case -1:
+			LOG_ERR("Restart failed: fork failed: %s", strerror(errno));
+			break;
+		case 0:
+			// Newly created child process immediately executes a new instance of DOSBox.
+			// It is not safe for a child process in a multi-threaded program to do much else.
+			if (execvp(newargs[0], newargs) == -1) {
+				E_Exit("Restart failed: execvp failed: %s", strerror(errno));
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:4688]: Any reason for the hard exit? Wouldn't `LOG_ERR` be better?

File: src/gui/sdlmain.cpp (hunk 4 above)
Comment (weirddan455) [reply src/gui/sdlmain.cpp:4591]: I had looked at that before I wrote this. It's tied to the CommandLine class and doesn't do exactly what I need anyway.

File: src/gui/sdlmain.cpp (hunk 6 above)
Comment (weirddan455) [reply src/gui/sdlmain.cpp:4688]: This is in the child process. It crashes if you try to do a normal exit. The parent process will do a normal exit regardless if we've gotten this far. If the child fails `execvp()`, we have to kill it.

File: src/gui/sdlmain.cpp [hunk 7]
```diff
@@ -4570,11 +4570,38 @@ static int edit_primary_config()
...
-void restart_dosbox(std::vector<std::string> &parameters) {
+static void remove_waitpid(std::vector<std::string> &parameters)
+{
+	auto it = parameters.begin();
+	while (it != parameters.end()) {
+		if (*it == "-waitpid" || *it == "--waitpid") {
+			it = parameters.erase(it);
+			if (it != parameters.end()) {
+				auto &pid = *it;
+				if (!pid.empty() && pid[0] >= '0' && pid[0] <= '9') {
```
Comment (FeralChild64) [inline src/gui/sdlmain.cpp]: `std::isdigit(pid[0])`?

File: src/gui/sdlmain.cpp (hunk 1 above)
Comment (weirddan455) [reply src/gui/sdlmain.cpp]: fixed

File: src/gui/sdlmain.cpp (hunk 2 above)
Comment (weirddan455) [reply src/gui/sdlmain.cpp]: I don't really have a preference. I changed it for you :smile:

File: src/gui/sdlmain.cpp (hunk 3 above)
Comment (weirddan455) [reply src/gui/sdlmain.cpp]: Formatted

File: src/gui/sdlmain.cpp (hunk 5 above)
Comment (weirddan455) [reply src/gui/sdlmain.cpp]: fixed

File: src/gui/sdlmain.cpp (hunk 7 above)
Comment (weirddan455) [reply src/gui/sdlmain.cpp]: Sure. Changed.

File: src/gui/sdlmain.cpp (hunk 4 above)
Comment (johnnovak) [reply src/gui/sdlmain.cpp:4591]: Fair enough.

File: src/gui/sdlmain.cpp (hunk 2 above)
Comment (johnnovak) [reply src/gui/sdlmain.cpp]: Haha, I'm just used to it 😆

File: src/gui/sdlmain.cpp (hunk 6 above)
Comment (johnnovak) [reply src/gui/sdlmain.cpp:4688]: Yeah ok, that makes sense.

**Comment by johnnovak** [comment]
Is there anything outstanding on this @weirddan455 ? I've confirmed it works on macOS as expected.

**Comment by weirddan455** [comment]
> Is there anything outstanding on this @weirddan455 ? I've confirmed it works on macOS as expected.

Nope, this just slipped my mind. Merged.
