### PR TITLE
Fix edge case where CDROM mixer hangs at the end of a track

### LINKED ISSUE #4296: Tomb Raider 1: sound disappears when CD audio track ends
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

_No response_

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

Fedora Kinoite (KDE), dosbox-staging from flathub

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

Intel 6th gen with iGPU, likely irrelevant

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

When playing Tomb Raider 1 (pulled from GOG release) on 0.82.1, sound disappears after a CD audio track ends. The sound reappears when exiting to menu, but further playing will make the sound disappear again.

I'm using 3dfx patch, but it doesn't seem to be different without it.

I have tried disabling sbmixer or mess around with buffer sizes without any difference. Same goes with cycles, albeit I haven't gone under 60k for playability reasons.

I tried a downgrade 0.81.0 (https://github.com/flathub/io.github.dosbox-staging/commit/00b2655f3206747b8e69a13705c422bfdb6e1511) and that actually helped. Downgrade just to 0.82.0 (https://github.com/flathub/io.github.dosbox-staging/commit/a6644490a56670ed5abff9b3b2a1ea5750bed6d4) didn't help. I hope to not stick to 0.81 because of way inferior voodoo experience there though :)

I can't really tell if it is specific to TR1 or not, but I have also played Magic Carpet Plus (The same SB16 config for sound, albeit with MIDI instead of TR1's CD audio for music) on the same setup extensively without any sound issues so at least it's not everywhere.

### Steps to reproduce the behaviour

1. Start dosbox-staging
2. mount the gog disk image (mixed CUE with music in mp3)
3. run the game
4. start the first level and wait a little over 2 minutes (the length of the CD audio track played at that point).
5. the whole sound is gone. Pulling pistols and shooting makes no sound at all. 
Loading later save has identical behaviour. Haven't tried past the first level with this though.

### Download URL of affected game or software

https://www.gog.com/en/game/tomb_raider_123

### Your configuration

```ini
Generated default except for setting midi device to fluidsynth instead of auto and setting GeneralUser soundfont.
```

### Provide a log

```text
Nothing in log seems relevant - no warnings or errors
```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

When the track got to the end, it was doing some back-and-forth logic going between time and sector number to figure out where to seek next.

It can hang if either the conversion is slightly off or the MP3 decoder returns slightly fewer frames that it was expecting.

Even on MP3 files where it didn't hang, it sometimes did 10+ seeks back-to-back each seeking to the last second of the file.

New code skips all that conversion business and just goes to the start of the next track :)

## Related issues

Fixes #4296

# Release notes

Fix audio hanging after about 2 minutes of play in the GOG version of Tomb Raider

# Manual testing

Tested both MP3 and .bin audio of Tomb Raider. Tested both with and without the 2 second pregap.

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/dos/cdrom_image.cpp [hunk 1]
```diff
@@ -766,15 +745,53 @@ bool CDROM_Interface_Image::PlayAudioSector(uint32_t start, uint32_t len)
...
+	if (len == 0 || track == tracks.end()) {
+		StopAudio();
+#ifdef DEBUG
+		LOG_MSG("CDROM: PlayAudioSector => sanity check failed");
+#endif
+		return false;
+	}
+	// If the request falls into the pregap, which is prior to the track's
+	// actual start but not so earlier that it falls into the prior track's
+	// audio, then we simply skip the pre-gap (beacuse we can't negatively
```
Comment (johnnovak) [inline src/dos/cdrom_image.cpp:771]: typo: because

File: src/dos/cdrom_image.cpp [hunk 2]
```diff
@@ -1001,13 +1015,28 @@ bool CDROM_Interface_Image::ReadSectorsHost(void *buffer, bool raw, unsigned lon
...
+void CDROM_Interface_Image::PlayNextAudioTrack()
+{
+	if (currentTrackNumber >= tracks.size()) {
+		StopAudio();
+		return;
+	}
+
+	// track number is index + 1 so current track number == next track index
+	const auto &next_track = tracks[currentTrackNumber];
+	assert(next_track.number == currentTrackNumber + 1);
```
Comment (johnnovak) [inline src/dos/cdrom_image.cpp:1027]: Hmm, why don't we store `currentTrackIndex` instead internally, then things would become more obvious, perhaps?

**Comment by johnnovak** [comment]
@weirddan455 Rebasing to master should fix the PVS issue I think.

Does this only affect the MP3 encoded audio track path? If I understand it correctly, seeking is not affected in general, just the case when we move from one track to the next? Maybe it would be worthwhile to test a few more games before merging? 

I've tried to look up in the history why this complicated seeking was implemented, but haven't found much. Maybe this one is related, but can't be certain:

https://github.com/dosbox-staging/dosbox-staging/commit/eaeb001

**Comment by weirddan455** [comment]
> Does this only affect the MP3 encoded audio track path?

MP3 is the only way I've been able to reproduce the bug but it could theoretically affect everything. It likely depends on decoder implementation details. Ex: We seek to "end - N seconds" or less. If the decoder gives us 0 audio frames, we get stuck in an infinite loop. The real bug is what I fixed in the higher level code to eliminate that as a possibility.

> If I understand it correctly, seeking is not affected in general, just the case when we move from one track to the next?

Yes. The only way for a DOS game to seek is through `PlayAudioSector()`. That remains unchanged save for extracting some shared code out to a new function. We just don't want to call that function on track change or we can end up seeking back into the same track the decoder just returned 0 frames on.

> I've tried to look up in the history why this complicated seeking was implemented, but haven't found much. Maybe this one is related, but can't be certain

My assumption is that whoever wrote it wanted to avoid code duplication with `PlayAudioSector()` since that takes care of resetting some player variables.

File: src/dos/cdrom_image.cpp (hunk 2 above)
Comment (weirddan455) [reply src/dos/cdrom_image.cpp:1027]: Internally where? I don't know what you mean by that.

**Comment by johnnovak** [comment]
> > Does this only affect the MP3 encoded audio track path?
> 
> MP3 is the only way I've been able to reproduce the bug but it could theoretically affect everything. It likely depends on decoder implementation details. Ex: We seek to "end - N seconds" or less. If the decoder gives us 0 audio frames, we get stuck in an infinite loop. The real bug is what I fixed in the higher level code to eliminate that as a possibility.
> 
> > If I understand it correctly, seeking is not affected in general, just the case when we move from one track to the next?
> 
> Yes. The only way for a DOS game to seek is through `PlayAudioSector()`. That remains unchanged save for extracting some shared code out to a new function. We just don't want to call that function on track change or we can end up seeking back into the same track the decoder just returned 0 frames on.
> 
> > I've tried to look up in the history why this complicated seeking was implemented, but haven't found much. Maybe this one is related, but can't be certain
> 
> My assumption is that whoever wrote it wanted to avoid code duplication with `PlayAudioSector()` since that takes care of resetting some player variables.

Cheers, it seems rather safe then. I was just thinking whether is it worth backporting this to 0.82.2 or is it too risky.

File: src/dos/cdrom_image.cpp (hunk 2 above)
Comment (weirddan455) [reply src/dos/cdrom_image.cpp:1027]: Oh, number to index. That's the part I didn't see. Yeah I can do that.

File: src/dos/cdrom_image.cpp (hunk 1 above)
Comment (weirddan455) [reply src/dos/cdrom_image.cpp]: fixed

File: src/dos/cdrom_image.cpp (hunk 2 above)
Comment (weirddan455) [reply src/dos/cdrom_image.cpp]: done

**Comment by johnnovak** [comment]
@Python-Exoproject I'm not too sure if you use MP3 audio tracks for any of your games. I've spot checked about 10 and all seem to be using CUE/BIN with a single BIN file, which is a solid choice 👍🏻 Tagging you anyway so you're aware of the potential issue.
