### PR TITLE
Fix lockup involving specific mount order

### LINKED ISSUE #2304: Floppy drive access through imgmount causes DOSBox to hang if mounted before CDROM folder mounting
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

Intel Gen 12, embedded intel GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm trying to mount both a directory with type CDROM and a floppy image using imgmount.
The order of mounting produces different results:
If I mount the floppy (imgmount) after mounting the CDROM - no issues.
But if I mount the floppy image before mounting the CDROM, reading from the floppy causes staging to crash.
It's enough to create a simple batch file on that image that has a single `echo test` command - the actual logic doesn't seem to matter.
Note that I can even `type` the content of that batch file and it shows the correct content (though if I do that, it's enough for a `dir` command to crash staging).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. create a floppy image that contains a single batch file with a single line: `echo test`
2. imgmount the floppy image as drive B
3. mount any HD folder as a CDROM
4. navigate to drive B
5. execute the batch file
6. crash

Note that in my case the mount/imgmount commands were in the staging config file.

### Your configuration

```ini
output             = opengl
machine            = svga_s3
memsize            = 16
aspect             = true
core      = auto
cputype   = auto
cycles    = auto
sbtype              = sb16
sbbase              = 220
irq                 = 7
dma                 = 1
hdma                = 5
xms                   = true
ems                   = true
umb                   = true
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #2304, which reports that Staging locks up when a floppy image is mounted before a CDROM image, followed by accessing the mounted floppy drive.

This lockup is caused by the device scanning routine added in 598de87, which enters and endless loop. 

This PR adds some basic routines to walk and query the DOS device linked list, and uses them in function to replace the one that locks up.

To prove that we can trust the replacement function, an intermediate commit compares its results against the original function'd results using asserts (which indeed pass in all of the tests I've thrown at it, including scanning the win 3.11 device drivers). 

Finally the PR pivots to use the replacement function, along with making use of the new functions in the MSCDEX code.

Thanks to @distantvale for catching this.

### CODE REVIEW

File: src/dos/dos_devices.cpp [hunk 1]
```diff
@@ -420,6 +430,93 @@ void DOS_DelDevice(DOS_Device * dev) {
...
+{
+	auto rp = dos_infoblock.GetDeviceChain();
+
+	while (!DOS_IsLastDevice(rp)) {
+		rp = DOS_GetNextDevice(rp);
+	}
+	return rp;
+}
+
+// Append the device at the given segment to the end of the DOS device linked list
```
Comment (johnnovak) [inline src/dos/dos_devices.cpp:470]: At the given address? (address = seg:offs)

File: src/dos/dos_devices.cpp [hunk 2]
```diff
@@ -420,6 +430,93 @@ void DOS_DelDevice(DOS_Device * dev) {
...
+uint16_t DOS_GetDeviceInterrupt(const RealPt rp)
+{
+	constexpr auto interrupt_pos = 0x08; // see dev structure table above
+	return real_readw(RealSeg(rp), RealOff(rp) + interrupt_pos);
+}
+
+bool DOS_DeviceHasName(const RealPt rp, const std::string_view req_name)
+{
+	constexpr auto name_pos   = 0x0a; // see dev structure table above
+	constexpr size_t name_len = 8;    // see dev structure table above
```
Comment (johnnovak) [inline src/dos/dos_devices.cpp:500]: Would it be an improvement to turn these into namespaced constants defined at a single location, which would obviate the need for these comments at every single usage?

E.g.

```cpp
// Structure of internal DOS tables, Device Driver
// Ref: https://www.infradeaorg/devload/DOSTables.html, Appendix 2

namespace DeviceDriverInfo {

constexpr uint8_t next_rpt_offset = 00h; // DWORD, points to next driver in
                                         // chain (x:FFFF means end)
constexpr uint8_t attributes_offset = 04h; // WORD, device attributes offset
constexpr uint8_t strategy_offset   = 06h; // WORD, device strategy routine
                                           // offset.
constexpr uint8_t interrupt_offset = 08h;  // WORD, device interrupt
                                           // routine offset.
constexpr uint8_t name_offset = 0ah;       // 8 bytes, device name padded with
                                           // spaces.
} // namespace DeviceDriverInfo
```

File: src/dos/dos_devices.cpp [hunk 3]
```diff
@@ -191,54 +191,64 @@ uint8_t DOS_ExtDevice::GetStatus(bool input_flag)
 	return 0x00;
 }
 
-uint32_t DOS_CheckExtDevice(const char *name, bool already_flag)
+// Walk the DOS devices and return the real pointer to the device matching the
+// given name, provided itsn't not an existing driver (if indicated).
```
Comment (johnnovak) [inline src/dos/dos_devices.cpp:195]: "provided it's not"

**Review by johnnovak — APPROVED** [review]
Looks good @kcgen

File: src/dos/dos_devices.cpp (hunk 2 above)
Comment (kcgen) [reply src/dos/dos_devices.cpp]: Added right under the comment block; easier to reference and more consistent in the functions - thanks, @johnnovak !

**Comment by kcgen** [comment]
Thanks for the detailed review @johnnovak - much improved.
