### PR TITLE
Ensure physical host buttons only perform one bound event

### LINKED ISSUE #4051: Where in the World is Carmen Sandiego (1986) locks up when pressing F12 to change to composite
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Latest official

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When loading the game "Where in the World is Carmen Sandiego 1986" Once the police officer begins to walk across the screen Tap F12 on the CGA machine setting to change into composite video. This will change to composite but lock the game.
I only wrote this as a bug because F12 does nothing on Dosbox-x. If you start the game in composite mode it works fine with more colors.
Same with PCJr and Tandy. This is the only composite game I've seen that locks when changing this.

I hope this isn't too small of a nitpick for a bug report.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the game in CGA machine mode.
2. Wait for graphics to appear and press F12.
3. It locks and can't be unlocked.

### Download URL of affected game or software

_No response_

### Your configuration

```ini
CGA
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by interloper98**
# Description

This PR makes sure that physical host buttons only trigger one logical event. 

For example, if you map the 'F10' key to the screenshot action, then this PR will knock out the 'F10' key's prior logical event of passing the 'F10' keystroke to the DOS program. So now the F10 key would only perform the screenshot action and the DOS program won't get an F10 keypress.

An amber warning in the mapper UI now informs the user when a physical event's prior logical event is dropped (see screenshot below).

This "displacement" also happens when event handlers are programmatically bound to physical buttons, like how the CGA composite code binds the F10, F11, and F12 physical keys to composite actions:

```
MAPPER: Host button 'F10' now performs 'hand_select' instead of 'key_f10'
MAPPER: Host button 'F11' now performs 'hand_incval' instead of 'key_f11'
MAPPER: Host button 'F12' now performs 'hand_cgacomp' instead of 'key_f12'
```

This fixes the problem in Carmen San Diego when switching to composite mode using the F12 also locked the game when it was simultaneously processing the F12 keystroke in the same moment as the video mode switch. 

## Related issues

Fixes #4051.

# Release notes

When using the mapper, only one logical event can be bound to a given physical host button.  For example, if you map the 'F10' key to the screenshot action, then the F10 key will now perform the screenshot action and the DOS program won't get an F10 keypress.

An amber warning in the mapper UI will inform you when a prior logical event is dropped:

remap-in-ui

When booting with `machine = cga`, this change prevents the 1986 edition of Where in the World is Carmen San Diego from locking up when switching to composite video using the F12 key.

# Manual testing

- Tested mapping multiple (unique) physical host buttons to a single logical events (works).
- Tested mapping the same physical host button to multiple logical events (no longer allowed; prior events are dropped).
- Tested and confirmed that with a default configuration and mapping, Carmen San Diego now can switch to composite mode using F12.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/gui/sdl_mapper.cpp [hunk 1]
```diff
@@ -2035,6 +2038,49 @@ static void SetActiveBind(CBind *new_active_bind)
 	update_active_bind_ui();
 }
 
+// Drop other bound events for the given primary binding to ensure a given host
```
Comment (johnnovak) [inline src/gui/sdl_mapper.cpp:2043]: What does "primary binding" mean? I've searched `sdl_mapper.cpp` for the term, and it looks like it's a new concept you introduced.

Is this new concept necessary, and if yes, would you explain it in a comment? Can't we just call it "binding" and that's it?

File: src/gui/sdl_mapper.cpp [hunk 2]
```diff
@@ -2096,6 +2096,10 @@ static void SetActiveEvent(CEvent * event) {
 		mapper.abindit=event->bindlist.begin();
 		if (mapper.abindit!=event->bindlist.end()) {
 			SetActiveBind(*(mapper.abindit));
+
+			const auto primary = dynamic_cast<CKeyBind*>(*mapper.abindit);
```
Comment (johnnovak) [inline src/gui/sdl_mapper.cpp:2102]: Why primary? Why not just "new_binding"?

File: src/gui/sdl_mapper.cpp [hunk 3]
```diff
@@ -1892,6 +1892,8 @@ class CHandlerEvent final : public CTriggeredEvent {
 		        defmod & MMOD1 ? " mod1" : "",
 		        defmod & MMOD2 ? " mod2" : "",
 		        defmod & MMOD3 ? " mod3" : "");
+
```
Comment (johnnovak) [inline src/gui/sdl_mapper.cpp:1895]: Very nice informative commit message as always 🥇

**Comment by johnnovak** [comment]
Very nice high-value improvement @interloper98 that luckily only required a few surgical changes to the mapper 🎉 

Would it make sense to mention the affected game in the release notes?

**Review by johnnovak — APPROVED** [review]
Very nice small but high-value change @interloper98. Merge away when ready! 🎉
