### PR TITLE
Fix HDD disk noises being played for floppies v2

### LINKED ISSUE #4611: `floppy_disk_noise = on` not enabled despite img and dir mounted floppies (A and B drives)
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

Latest source

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

When enabling the floppy disk noise feature with:

```ini
[disknoise]
floppy_disk_noise = on
```

I see the following in the log:
```
DISKNOISE: Operating at 22050 Hz and upsampling to the output rate
DISKNOISE: Disk noise emulation disabled
```

When I query the state of the feature by typing `floppy_disk_noise` at the `Z:\>` prompt, it reports: **"on"**.

However, when launching a game from either a dir mounted floppy or an image mounted floppy, neither produces any floppy disk noises.

I've attached a zip below.

### Steps to reproduce the behaviour

1.  Download and unzip:  [aaow.zip](https://github.com/user-attachments/files/23952912/aaow.zip)

2.  Launch `/your/dosbox --working-dir aaow`

3. Observe that floppies A and B are mounted (A from a dir, B from img), the mixer shows `DISKNOISE` is at 100% volume, and the `floppy_disk_noise` config is reporting `on`. 

4. Select either `a` or `b` at the choice menu to launch from either the dir or img mounted floppy; in either case, notice that no floppy sounds are heard.

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by dividebysandwich**
# Description

This PR introduces an enum for the MediaByte, with MediaIDs for various floppy types as well as HDD. 

The disk "type" can mean two different things in dosbox: The type of source for the disk data (directory, image file, etc), or the media type.
The logic for selecting the MediaByte in mount.cpp is now based on the drive number, i.e. A and B are assumed to be floppies, the rest is  assumed to be a HDD. This mirrors what is done in other parts of dosbox-staging already.

drive_fat.cpp now reports the MediaByte based on the same logic.

Any uses of magic numbers have been replaced with the MediaId enum.

To fix bootable images not playing any disk noise, callbacks in bios_disk.cpp have been added.

These callbacks may be called before the graphics system is ready, so a check for DOS_IsGuestOsBooted() has been added to DOS_PerformDiskIoDelay() and DOS_PerformDiskIoDelayByHandle() in dos.cpp

The floppy spin sample by @johnnovak has been cherry-picked.

TSan warning fixes discussed in the [first PR](https://github.com/dosbox-staging/dosbox-staging/pull/4617) have been cherry-picked, switching the initialization order in disk_noise.cpp as well as adding a mutex.

## Related issues

Fixes #4611

# Manual testing

Tested locally on linux using local files and disk images.

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [X] Linux

# Checklist

I have:

- [X] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [X] performed a self-review of my code.
- [X] commented on the particularly hard-to-understand areas of my code.
- [X] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [X] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [X] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
@dividebysandwich Good news, all TSAN warnings are gone now in my initial testing 🥳 

Will review in detail tomorrow then we'll get it in. Thanks for the perseverance.

**Comment by johnnovak** [comment]
I've tested it some more and still looks good. Noticed a few things (probably unrelated to this PR, though):

- No floppy sounds when using built-in commands (e.g. when copying files from one floppy in the A: drive to another in the B: drive). Probably because our built-ins bypass a few emulation layers.
- `floppy_disk_speed` doesn't seem to work correctly, it's waaaaay too fast. Copies a bunch of image files onto a mounted floppy image, then launched an image viewer (QPV) to view them. Well, I could flip through the images just as it was a mounted HDD, it was blazingly fast even on `slow`, and the floppy sounds were minimal. On `medium` and `fast` it was basically as fast as the HDD. Maybe it's a limitation of our disk emulation approach, so it could be you can't do much about it.

Still no TSAN warnings in sight, that's good news.

File: src/audio/disk_noise.cpp [hunk 1]
```diff
@@ -38,34 +38,34 @@ DiskNoises::DiskNoises(const DiskNoiseMode floppy_disk_noise_mode,
...
+    // Start audio thread
+    MIXER_LockMixerThread();
+    const auto mixer_callback = std::bind(&DiskNoises::AudioCallback,
+                                          this,
+                                          std::placeholders::_1);
+    mix_channel = MIXER_AddChannel(mixer_callback,
+                                   DiskNoiseSampleRateInHz,
+                                   ChannelName::DiskNoise,
+                                   {ChannelFeature::Stereo});
+    mix_channel->Enable(true);
```
Comment (johnnovak) [inline src/audio/disk_noise.cpp]: You don't need to do this, channels are enabled by default. We don't enable channels explicitly like this in other audio devices.

File: src/audio/disk_noise.cpp [hunk 2]
```diff
@@ -38,34 +38,34 @@ DiskNoises::DiskNoises(const DiskNoiseMode floppy_disk_noise_mode,
...
+    MIXER_UnlockMixerThread();
+    float vol_gain = percentage_to_gain(100);
+    mix_channel->SetAppVolume({vol_gain, vol_gain});
```
Comment (johnnovak) [inline src/audio/disk_noise.cpp]: Same comment, just leave the app volume alone. It's set to 100% by default, no need to mess with it.

File: src/audio/disk_noise.cpp [hunk 3]
```diff
@@ -78,38 +78,41 @@ DiskNoises* DiskNoises::GetInstance()
 
 void DiskNoises::AudioCallback(const int num_frames_requested)
 {
+	// Check if callback runs before mix_channel is assigned.
+	if (!mix_channel) {
+        return;
+    }
```
Comment (johnnovak) [inline src/audio/disk_noise.cpp]: That's a bit dirty if you need this; you should ensure proper init order. You can do `assert(mix_channel)` though. I don't even think you need this at all, so replace it with the assert and try it.

File: src/audio/disk_noise.cpp [hunk 4]
```diff
@@ -78,38 +78,41 @@ DiskNoises* DiskNoises::GetInstance()
...
 	// stereo interleaved buffer
 	static std::vector<AudioFrame> out = {};
 	out.clear();
 
 	// Mix audio frames from all active devices
 	for (auto i = 0; i < num_frames_requested; ++i) {
 		AudioFrame mixed_sample = {};
-		for (const auto& device : disk_noises->active_devices) {
+		for (const auto& device : active_devices) {
 			AudioFrame sample = device->GetNextFrame();
```
Comment (johnnovak) [inline src/audio/disk_noise.cpp]: minor: `auto sample`

File: src/audio/disk_noise.cpp [hunk 5]
```diff
@@ -384,7 +385,8 @@ DiskNoiseDevice::DiskNoiseDevice(const DiskType disk_type,
 		return;
 	}
 
-	spin.loop = loop_spin_sample;
+	// Only hard disk noises loop the spin sample
+	(disk_type == DiskType::HardDisk) ? spin.loop = true : spin.loop = false;
```
Comment (johnnovak) [inline src/audio/disk_noise.cpp]: That's a weird pattern, gave me a pause 😄 Let's do this:

```
spin.loop = (disk_type == DiskType::HardDisk);
```

File: src/dos/programs/mount.cpp [hunk 6]
```diff
@@ -119,15 +119,27 @@ void MOUNT::Run(void) {
...
 		} else if (type=="dir" || type == "overlay") {
 			// 512*32*32765==~500MB total size
 			// 512*32*16000==~250MB total free size
 			str_size="512,32,32765,16000";
-			mediaid=0xF8;		/* Hard Disk */
+			mediaid=MediaId::HardDisk;		/* Hard Disk */
+
+			// If drive mounted to A or B, set mediaid to floppy
+			// This is preferable to using type because floppies can be 
+			// auto-mounted as type"dir"
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: typo: type "dir" (space)

File: src/audio/disk_noise.cpp (hunk 3 above)
Comment (dividebysandwich) [reply src/audio/disk_noise.cpp]: I keep the assert in. Not for now, but for the future.

File: src/audio/disk_noise.cpp (hunk 1 above)
Comment (dividebysandwich) [reply src/audio/disk_noise.cpp]: If I don't enable the channel, I get no sound.

File: src/audio/disk_noise.cpp (hunk 2 above)
Comment (dividebysandwich) [reply src/audio/disk_noise.cpp]: Same as above, if I don't set the volume, I get no sound.

File: src/audio/disk_noise.cpp (hunk 1 above)
Comment (dividebysandwich) [reply src/audio/disk_noise.cpp]: I checked MIXER_AddChannel and the default is chan->Enable(false) and chan->SetAppVolume(1.0f, 1.0f)
However as you said, gus.cpp for example doesn't have to enable or set the AppVolume. What's also weird is that I have to both enable AND SetAppVolume, or I get no sound. I can't find what's overriding these things.

**Comment by dividebysandwich** [comment]
>     * No floppy sounds when using built-in commands (e.g. when copying files from one floppy in the A: drive to another in the B: drive). Probably because our built-ins bypass a few emulation layers.

Yes. It's unfortunate because this was working with the wrapper.
 
>     * `floppy_disk_speed` doesn't seem to work correctly, it's waaaaay too fast. Copies a bunch of image files onto a mounted floppy image, then launched an image viewer (QPV) to view them. Well, I could flip through the images just as it was a mounted HDD, it was blazingly fast even on `slow`, and the floppy sounds were minimal. On `medium` and `fast` it was basically as fast as the HDD. Maybe it's a limitation of our disk emulation approach, so it could be you can't do much about it.

I found the reason for this: I added a check for DOS_IsGuestOsBooted because I thought this was related to some TSan warning. There's several conditions where DOS_IsGuestOsBooted never becomes true.
I can't reproduce the warning after removing this check, could you maybe check? The disk delay should now work as intended.

**Comment by johnnovak** [comment]
> I can't reproduce the warning after removing this check, could you maybe check? The disk delay should now work as intended.

I will, but maybe a more thorough testing cycle from you is in order as well 😄 I've been testing my WIP monitor controls PR for 2 weeks now, and I'm finding issues and edge cases, etc. I'm doing that for 1-2 hours daily, there's a lot to cover. I'm only moving it out of draft once I've confirmed it's solid, to the best of my abilities.

We should make sure our stuff is 100% solid when we raise PRs and not rely on the reviewer's testing 😄 That means pretty much retesting the whole thing after every non-trivial code change as the ways of DOSBox are mysterious! 😎

File: src/audio/disk_noise.cpp (hunk 1 above)
Comment (johnnovak) [reply src/audio/disk_noise.cpp]: Yeah, I'm not entirely sure about the volume. I'll have a look today.

The GUS and many other audio channels use the Sleep channel feature, and start the audio callback with a WakeUp call that enables the channel, I've just realised. That isn't really necessary here as we're not doing CPU heavy emulation. So it's ok to manually enable, after all.

**Comment by dividebysandwich** [comment]
> I will, but maybe a more thorough testing cycle from you is in order as well 😄 I've been testing my WIP monitor controls PR for 2 weeks now, and I'm finding issues and edge cases, etc. I'm doing that for 1-2 hours daily, there's a lot to cover. I'm only moving it out of draft once I've confirmed it's solid, to the best of my abilities.
> 

Want me to set this PR to draft? 
And yeah sorry for missing that regression, my mind just blamed that on removing the wrapper.

I have spent an hour testimg on multiple systems but it's christmas ;)
I will of course continue testing too.

File: src/audio/disk_noise.cpp (hunk 1 above)
Comment (johnnovak) [reply src/audio/disk_noise.cpp]: Yeah, so you'll need Enable, but AppVolume is redundant. You'll just need to cherry pick my commit (see big comment below).

**Comment by johnnovak** [comment]
@dividebysandwich It's all good and mistakes happen, I'm just saying don't rush it. Take your time and make sure it's solid from every angle before presenting it to us.

I wanted to push my fixup/improvement commits in a separate branch and let you to cherry-pick, but I pushed it directly to your branch by mistake. Wasn't my original intention, hope you don't mind 😄 

## Test results

- Floppy sounds are playing fine with mounted floppy images via `IMGMOUNT` 🍏 
- Floppy sounds are playing fine when booting from a floppy via `BOOT` 🍏
- Floppy sounds are NOT playing at all for directory mounts via `MOUNT` 🛑 
- HDD sounds are playing fine 🍏 (only tested with directory mounts)
- `seek-only` works fine both for FDD and HDD sounds 🍏
- We get crashes when setting `hard_drive_speed` or `floppy_drive_speed` to `maximum` after mounting a floppy image or when accessing the HDD. An assert will be tripped in my newly added enum asserts. 🛑 

So these failures must be fixed, I see these as non-negotiable, especially the crash.

# Further notes

## Crash repro notes

### Repro case 1

1. Set `floppy_drive_speed = maximum` and enable FDD sounds.
2. `imgmount a: disk.img -t floppy`
3. Assert is tripped:

```

2025-12-25 13:43:12.317 | IMGMOUNT: Path 'disk.img' found
Assertion failed: ((void)("Invalid DiskType enum"), false), file D:\Work\Code\dosbox-staging\src\dos\dos.cpp, line 352
```

Similar thing happens for the HDD once the HDD is accessed.

### Repro case 2

1. Use my KQ1 config and set `floppy_drive_speed = maximum` in the config.
2. Start Staging => assert gets tripped.

## Formatting

Formatting is all over the place. Please read the contributor's guide how to format individual commits:

https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#compile-commits

Ideally, you'd use interactive rebase, stop at every commit for editing, run the formatter script, add changes (if any), continue with rebase to proceed to the next commit, GOTO 10. But that might results in conflicts in your case. It's okay to do a last full reformat on `disk_noise.cpp` as a very last commit when we're done with all the testing & fixups, but please keep this in mind for the next time to format all your commits.

If you don't know how to rebase with Git, I can help with this final touch up at the end.

## Speed emulation issues

_This can be done outside of the scope of this PR. It's not even _that_ important because the main use-case for FDD sounds is playing booter games, I think. Listening to FDD sounds while installing games from floppies is cool, but not that essential. I'm happy to treat this in a separate PR, and in fact, I'd prefer that to keep things moving._

When copying a 110 kB image file from HDD to a mounted floppy image in DOS Navigator, the copying takes ~30 seconds with `floppy_disk_speed = fast`, and about ~50 seconds with `floppy_disk_speed = medium`.

That just doesn't add up; the help text sayd medium should result in ~60 kB/s and fast in ~120 kB/s.

Then when I start QPV to view the images from the same mounted floppy image, the 110 kB image gets loaded in 9 seconds with `floppy_disk_speed = medium`, for instance.

Another test: when viewing a 32 kB image with the built-in `SHOWPIC` command from a mounted floppy image, loading takes several _minutes_! That just doesn't seem right at all. In QPV it's a second even with the `slow` speed.

File: src/dos/dos.cpp [hunk 7]
```diff
@@ -373,6 +377,8 @@ void DOS_PerformCdRomIoDelay(uint16_t data_transferred_bytes)
 	double scalar;
 
 	switch (disk_settings.cdrom_disk_speed) {
+	case DiskSpeed::Maximum:
```
Comment (johnnovak) [inline src/dos/dos.cpp]: Ok, I see now that I broke your code by adding the asserts to the default case 😄 

But what you did was misleading: you handled all enum values _except_ for `Maximum`, which was handled in the default branch.

We much prefer handling all enum values exhaustively and reserve the default block for the assert. Much clearer and it makes the linter happy, too 😄

**Comment by dividebysandwich** [comment]
>     * We get crashes when setting `hard_drive_speed` or `floppy_drive_speed` to `maximum` after mounting a floppy image or when accessing the HDD. An assert will be tripped in my newly added enum asserts. 🛑

You added asserts in defaults. But I agree that the switches should handle all enums explicitly. I have added the relevant branches so the default is now ok to call assert.

>     * Floppy sounds are NOT playing at all for directory mounts via `MOUNT` 🛑

I cannot reproduce this. I am doing ```mount b /somepath/floppy -t floppy```  and it works fine on 3 different machines + a VM.

> Formatting is all over the place. Please read the contributor's guide how to format individual commits:

I am having severe issues with the formatting script - it often insists on formatting completely unrelated parts of code that I never touched. I have seen this behavior about 4 out of 10 times. I admit I sometimes forget to run the script too. I will go through formatting when squashing and if there's anything out of the ordinary I will fix it.

> ## Speed emulation issues
> When copying a 110 kB image file from HDD to a mounted floppy image in DOS Navigator, the copying takes ~30 seconds with `floppy_disk_speed = fast`, and about ~50 seconds with `floppy_disk_speed = medium`.

There's a big difference between directory mounts and floppy image mounts:

directory mount reads:
* big chunk
* big chunk
* big chunk
* big chunk

image mount reads:
* 512 bytes
* 512 bytes
* 512 bytes
* 512 bytes
* 512 bytes
* big chunk
* 512 bytes
* 512 bytes
* 512 bytes
* 512 bytes

I found and will fix another issue - the delay was using the PIC timing, not real time. But that's not the cause for the inconsistency between images and directory mounts.

I will continue to investigate this, and I do think the inconsistent delay needs to be fixed because otherwise some disk operations become unbearably slow (several minutes) which is annoying.

EDIT: I found a solution for the redundant delays. I have not yet been able to reproduce the missing sounds on directory mounts via mount. I'll continue testing.

File: src/dos/dos.cpp (hunk 7 above)
Comment (dividebysandwich) [reply src/dos/dos.cpp]: Yep, and I agree. No worries.

**Comment by johnnovak** [comment]
> I cannot reproduce this. I am doing `mount b /somepath/floppy -t floppy` and it works fine on 3 different machines + a VM.

I'll retest tomorrow.



> I am having severe issues with the formatting script - it often insists on formatting completely unrelated parts of code that I never touched. I have seen this behavior about 4 out of 10 times

Can't say I've experienced that, and I'm using it heavily 🤷🏻 😄 

> I admit I sometimes forget to run the script too. I will go through formatting when squashing and if there's anything out of the ordinary I will fix it.

Sounds good, let's keep it simple.

> I found and will fix another issue - the delay was using the PIC timing, not real time.

Using "emulated time" ("PIC time") is most definitely the correct thing to do. Using real-time is wrong, don't do that.

Think of it like this: when you engage fast forward ("Speedlock" hotkey in the mapper), the entire emulation is sped up, _including_ the I/O delays! If you used realtime somehow, then the disk delay wouldn't be sped up, and that's wrong. Emulated time ("PIC time") coincides with real-time in non-fast-forward mode anyway, so I don't quite see what you are hoping to achieve by not using PIC timing.

**Comment by dividebysandwich** [comment]
> Using "emulated time" ("PIC time") is most definitely the correct thing to do. Using real-time is wrong, don't do that.
> 
> Think of it like this: when you engage fast forward ("Speedlock" hotkey in the mapper), the entire emulation is sped up, _including_ the I/O delays! If you used realtime somehow, then the disk delay wouldn't be sped up, and that's wrong. Emulated time ("PIC time") coincides with real-time in non-fast-forward mode anyway, so I don't quite see what you are hoping to achieve by not using PIC timing.

Drat, I did not consider that. Yes that does make sense.

**Comment by johnnovak** [comment]
@dividebysandwich 

Repro case for the no floppy sounds on mounted directories bug:

[disknoise-test.zip](https://github.com/user-attachments/files/24342579/disknoise-test.zip)

Start this up with the bundled config, then:

1. `cd a:` then `dir` — we get floppy sounds (as there's a mounted image in drive A:)
2. `cd b:` then `dir` — no floppy sounds (as that's a directory mount; I think it's also a lot faster than it should be)

Check out the config for the details of the setup.

The B: drive seems to have the correct type when running the `MOUNT` command (gets auto-labeled to `BFLOPPY` as I passed `-t floppy` to the `MOUNT` command and the disk has no label):

image

**Comment by dividebysandwich** [comment]
@johnnovak 

> Start this up with the bundled config, then:
> 
>     1. `cd a:` then `dir` — we get floppy sounds (as there's a mounted image in drive A:)
> 
>     2. `cd b:` then `dir` — no floppy sounds (as that's a directory mount; I think it's also a lot faster than it should be)

Ah, that's not a bug.

There are 4 different types of Disk IO in dosbox-staging, some of them are layered, some of them are not, and some are layered only in certain situations. We have the DOS int21 handler, the bios handler, the drive type implementations (which are partly layered with each other and/or int21) and finally the shell commands which bypass all of that. On top of that we got DriveManager which is sometimes used, sometimes not. Implementing disk noises and IO delay for all of them and making them 100% consistent across the board will require a complete rewrite of the entire disk emulation first. 

Directory operations from built-in shell commands currently do not call the new handlers. I did not want to touch ALL disk operations in one go because as you know this is a fickle beast. I can see that this would improve the feel, however I'd like to ask you how far you want to go as part of this PR. We have several options:

a) We could do this in a different PR.

b) I can add the relevant callbacks for FindFirst and FindNext, for both the shell commands and the INT21 handler. This should be safe because the shell commands happen "outside" of anything critical as long as it's done after reading the DTA, and adding the handler call to the INT21 handler works the same as read/write. This is a small change.

c) There's no IO overhead or noise for other operations that might benefit from this: directory operations, unlink, etc. - This would of course further improve the authenticity, but I would definitely recommend putting that into a separate PR.

Let me know what you would prefer and I'll be happy to implement it.

EDIT: Just to make it clear how small the change for point b is:

```
diff --git a/src/dos/dos.cpp b/src/dos/dos.cpp
index ea3ccf6f7..e2fc75991 100644
--- a/src/dos/dos.cpp
+++ b/src/dos/dos.cpp
@@ -54,11 +54,6 @@ static struct DiskSettings disk_settings = {};

 extern void DOS_ClearLaunchedProgramNames();

-constexpr auto EstimatedFileCreationIoOverheadInBytes = 2048;
-constexpr auto EstimatedFileOpenIoOverheadInBytes     = 1024;
-constexpr auto EstimatedFileCloseIoOverheadInBytes    = 512;
-constexpr auto EstimatedFileSeekIoOverheadInBytes    = 512;
-
 void DOS_NotifyBooting()
 {
        is_guest_booted = true;
diff --git a/src/dos/dos.h b/src/dos/dos.h
index 5ab757611..b0044b907 100644
--- a/src/dos/dos.h
+++ b/src/dos/dos.h
@@ -122,6 +122,11 @@ extern DOS_Device * Devices[DOS_DEVICES];

 extern uint8_t dos_copybuf[0x10000];

+constexpr auto EstimatedFileCreationIoOverheadInBytes = 2048;
+constexpr auto EstimatedFileOpenIoOverheadInBytes     = 1024;
+constexpr auto EstimatedFileCloseIoOverheadInBytes    = 512;
+constexpr auto EstimatedFileSeekIoOverheadInBytes    = 512;
+constexpr auto EstimatedFindFileIoOverheadInBytes    = 512;

 void DOS_SetError(uint16_t code);

diff --git a/src/shell/shell_cmds.cpp b/src/shell/shell_cmds.cpp
index 50be35015..819be9d96 100644
--- a/src/shell/shell_cmds.cpp
+++ b/src/shell/shell_cmds.cpp
@@ -890,6 +890,9 @@ void DOS_Shell::CMD_DIR(char* args)
        do { // File name and extension
                DOS_DTA::Result result = {};
                dta.GetResult(result);
+               DOS_PerformDiskIoDelay(EstimatedFindFileIoOverheadInBytes,
+                                       DOS_GetDiskTypeFromMediaByte(
+                                       Drives[drive_idx]->GetMediaByte()));

                // Skip non-directories if option AD is present,
                // or skip dirs in case of A-D
```

**Comment by johnnovak** [comment]
> Implementing disk noises and IO delay for all of them and making them 100% consistent across the board will require a complete rewrite of the entire disk emulation first.

Yeah let's not do that in this PR 😆 

> Directory operations from built-in shell commands currently do not call the new handlers. I did not want to touch ALL disk operations in one go because as you know this is a fickle beast.

Good call, and thanks for the explanation! It kind of makes more sense now. I've tested directory mounted floppy drives with actual DOS programs that call the DOS interrupts now, and the floppy sounds work, indeed 👍🏻 

Yeah let's not do anything else to attempt to improve the situation in this PR. The most common use-case for floppy usage is to use mounted images. The biggest benefit of floppy sounds is playing booter games with authentic floppy sounds. Secondary benefit is installing games from floppy images. Maybe one day we could try to rework things and make all the different mount types use floppy sounds, and the shell commands as well, but the payoff is low and risk is high. I think we've hit a local maximum here, so let's call it a day, clean up the PR, then merge it 😄

If you think you're done with the code changes, it's probably time to squash some commits, do a final reformat, then it's good to go I think. I'm thinking these should be kept separate:

- Fix media byte handling for images and bootables
- Add floppy spin sound sample

Then probably a couple of more logical commits for the actual fixes you've done.

**Comment by dividebysandwich** [comment]
> If you think you're done with the code changes, it's probably time to squash some commits, do a final reformat, then it's good to go I think. I'm thinking these should be kept separate:
>     * Fix media byte handling for images and bootables
>     * Add floppy spin sound sample
> 
> Then probably a couple of more logical commits for the actual fixes you've done.

Alright, I hope I did everything correctly. I get queasy when git commands start to include --exec...

File: src/audio/disk_noise.cpp [hunk 8]
```diff
@@ -38,34 +38,34 @@ DiskNoises::DiskNoises(const DiskNoiseMode floppy_disk_noise_mode,
...
+
+	// Start audio thread
+	MIXER_LockMixerThread();
+	const auto mixer_callback = std::bind(&DiskNoises::AudioCallback,
+	                                      this,
+	                                      std::placeholders::_1);
+	mix_channel               = MIXER_AddChannel(mixer_callback,
+                                       DiskNoiseSampleRateInHz,
+                                       ChannelName::DiskNoise,
+	                                             {ChannelFeature::Stereo});
```
Comment (johnnovak) [inline src/audio/disk_noise.cpp]: Formatting is off.

**Comment by johnnovak** [comment]
@dividebysandwich I gave it a final testing with the TSAN build, all looking good! 🥳 

This is ready for merging, just let's tidy up the commit history a bit. These three commits

- Fix media byte handling for images and bootables
- Fix issues with boot images
- Optimize disknoise mixer init

could be squashed into one as they're a bit random, mixing functional changes with cleanup commits, and the split doesn't really help. The resulting squashed commit could be given a better name:

`Fix floppy sounds not playing when booting from floppy images`

To explain: very specific commit messages are fine if your commits are very narrow, but you're doing a lot of things in these (functional changes, cleanup, etc.), so better to give them a high-level description of the task you're solving.

The rest of the commits are fine content-wise, but I'd suggest renaming a few to end with four commits like this:

- `Fix floppy sounds not playing when booting from floppy images`
- `Add floppy spin sound sample`
- `Improve DiskNoise enum handling & improve logging`
- `Remove redundant delay calls when emulating disk noises`

The reason I'm going on about commit names is to make it easier to search for "disk noise" or "disknoise" in the git history.

There are still a few minor formatting problems in `disk_noise.cpp` (see below), so you might wanna do a final reformat and integrate it into your last commit or something.

After this, we're good to go! Let me know if you need help with massaging the git history, I'm quite proficient with splitting, reordering, merging, etc. commits with interactive rebase! 😎 

image

**Comment by dividebysandwich** [comment]
@johnnovak Done. I used the script on all commits.
