### PR TITLE
Force pixel-perfect to respect aspect.ratio setting

### LINKED ISSUE #544: Pixel-perfect mode does not respect render.aspect setting (was: Incorrect aspect ratio in Waxworks)
**To Reproduce**
config:
    fullscreen=true
    fullresolution=1920x1080
    output=texturepp
launch Waxworks game

**Expected behaviour**
aspect ratio in fullscreen mode should match aspect ratio in window mode (press alt-enter to compare)
BTW, fullresolution=1024x768 gives correct aspect ratio.

**Environment (please complete the following information):**
- Windows 10
- AMD Ryzen 7 2700

**Version of dosbox-staging:**
0.75.0

**Additional context**
Add any other context or details about the problem you might found relevant
(e.g. screenshots, other dosbox versions impacted, etc).
waxworks1
waxworks2

```
dosbox-staging version 0.75.0
---
CONFIG: Loading primary file C:\Users\yura\AppData\Local\OGDBL\dosbox.conf
CONFIG: Unknown option fulldouble
CONFIG: Unknown option autolock
CONFIG: Unknown option usescancodes
CONFIG: Loading additional file D:\Games\_DOS\waxworks\wax.dosbox
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Emulator resolution: 1920x1080
MAIN: Pixel-perfect scaling (2x2): 640x480 (PAR 1.00) -> 1280x960 (PAR 1.00)
SDL: Using driver "direct3d" for texture renderer
SDL: Mouse will move seamlessly without being captured.
MIXER: Got different values from SDL: freq 44100, blocksize 1024
MIDI: Opened device:win32
MAPPER: Found no joysticks
MAPPER: Loaded default key bindings
SDL: captured the mouse
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
MAIN: Emulator resolution: 1920x1080
MAIN: Pixel-perfect scaling (2x2): 640x400 (PAR 1.20) -> 1280x800 (PAR 1.00)
SDL: Using driver "direct3d" for texture renderer
MAIN: Draw resolution: 320x200, double-width, double-height, pixel aspect ratio: 1.20
MAIN: Emulator resolution: 1920x1080
MAIN: Pixel-perfect scaling (4x5): 320x200 (PAR 1.20) -> 1280x1000 (PAR 1.25)
SDL: Using driver "direct3d" for texture renderer
MAIN: Draw resolution: 320x200, double-width, double-height, pixel aspect ratio: 1.20
MAIN: Emulator resolution: 320x240
MAIN: Pixel-perfect scaling (1x1): 320x200 (PAR 1.20) -> 320x200 (PAR 1.00)
SDL: Using driver "direct3d" for texture renderer
SDL: released the mouse
```

### PR DESCRIPTION
**Pull request by dreamer**
When user sets aspect.ratio to false (meaning: use square pixels), the
pixel-perfect implementation should not emulate non-square pixels.

Fixes #544

### CODE REVIEW

File: src/gui/render.cpp [hunk 1]
```diff
@@ -441,19 +441,25 @@ static void RENDER_Reset( void ) {
...
-	#if C_OPENGL
-		GFX_SetShader(render.shader_src);
-	#endif
-	gfx_flags=GFX_SetSize(width,height,gfx_flags,gfx_scalew,gfx_scaleh,&RENDER_CallBack,par);
+#if C_OPENGL
+	GFX_SetShader(render.shader_src);
+#endif
+
+	// The pixel aspect ratio of the source image, assuming 4:3 screen
+	const double real_par = 3.0 / 4.0 * width / height;
```
Comment (kcgen) [inline src/gui/render.cpp:457]: The PAR calculation is a bit tricky to read with two divisions ( `# / # / #` ), which the original line also had.
Suggest something like this, which is a bit more intuitive on first glance:
``` c++
const double real_par = (3.0 * width) / (4.0 * height);
```

Comment (dreamer) [reply src/gui/render.cpp:457]: Good point; I'll go with a slightly different version, grouping respective widths and heights together.

```C++
const double real_par = (width / 4.0) / (height / 3.0);
```

Interesting tidbit: your version and both mine versions are numerically more stable than the original code was: for 320x200, in our versions the result is exactly 1.2 while old code was calculating 1.20000000000000022204. :)

**Comment by dreamer** [comment]
@kcgen Thanks for the review :)
