### PR TITLE
Fix COM data memory leak

### LINKED ISSUE #1152: COM data for internal programs is leaked

### PR DESCRIPTION
**Pull request by kcgen**
Fixes  #1152.

### Reproduction Steps

1. Build with ASAN and UBSAN instrumentation (GCC or Clang):

    ``` text
    meson setup \
        -Dbuildtype=debugoptimized \
        -Db_sanitize=address,undefined \
        -Db_lundef=false \
        -Dc_args=-fsanitize-recover=all \
        -Dcpp_args=-fsanitize-recover=all \
        -Ddefault_library=static \
        -Dfluidsynth:enable-floats=true \
        -Dfluidsynth:try-static-deps=true \
        build/aubsan
    
    meson compile -C build/aubsan
    ```

1. Launch and exit with default settings.

### CODE REVIEW

File: src/misc/programs.cpp [hunk 1]
```diff
@@ -39,43 +41,51 @@ Bitu call_program;
...
-	0xcd,0x21,						//INT 0x21
+constexpr uint8_t exe_block[] = {
+        0xbc, 0x00, 0x04,       // MOV SP,0x400  Decrease stack size
+        0xbb, 0x40, 0x00,       // MOV BX,0x040  For memory resize
+        0xb4, 0x4a,             // MOV AH,0x4A   Resize memory block
+        0xcd, 0x21,             // INT 0x21
+        0xFE, 0x38, 0x00, 0x00, // 12th position is the CALLBack number
+        0xb8, 0x00, 0x4c,       // Mov ax,4c00
+        0xcd, 0x21,             // INT 0x21
 };
```
Comment (kcgen) [inline src/misc/programs.cpp:53]: No functional changes.. 
`Bit8u` -> `uint8_t`, and formatted the comments.

File: src/misc/programs.cpp [hunk 2]
```diff
@@ -39,43 +41,51 @@ Bitu call_program;
...
 
-#define CB_POS 12
+// COM data constants
+constexpr int callback_pos = 12;
+constexpr int com_data_size = 32;
```
Comment (kcgen) [inline src/misc/programs.cpp:56]: Previously `32` here was a magic number to size the malloc(); now given a name.

File: src/misc/programs.cpp [hunk 3]
```diff
@@ -39,43 +41,51 @@ Bitu call_program;
...
-void PROGRAMS_MakeFile(char const * const name,PROGRAMS_Main * main) {
-	Bit8u * comdata=(Bit8u *)malloc(32); //MEM LEAK
+void PROGRAMS_MakeFile(const char *name, PROGRAMS_Main *main)
+{
+	com_data_t comdata = std::make_unique<uint8_t[]>(com_data_size);
+	assert(comdata);
 
-	if (comdata == nullptr) {
-		E_Exit("Could not allocate memory for com-file data.");
-	}
```
Comment (kcgen) [inline src/misc/programs.cpp:62]: Here's where we replace malloc with a smart pointer.
`make_unique` with throw a `bad_alloc` exception if it fails, so we can drop error-checking and `E_Exit()`.

File: src/misc/programs.cpp [hunk 4]
```diff
@@ -39,43 +41,51 @@ Bitu call_program;
...
+	comdata[callback_pos] = static_cast<uint8_t>(call_program & 0xff);
+	comdata[callback_pos + 1] = static_cast<uint8_t>((call_program >> 8) & 0xff);
 
-	memcpy(comdata,&exe_block,sizeof(exe_block));
-	comdata[CB_POS]=(Bit8u)(call_program&0xff);
-	comdata[CB_POS+1]=(Bit8u)((call_program>>8)&0xff);
+	// Save the current program's vector index in its COM data
+	assert(internal_progs.size() <= UINT8_MAX);
+	const auto index = static_cast<uint8_t>(internal_progs.size());
+	comdata[sizeof(exe_block)] = index;
```
Comment (kcgen) [inline src/misc/programs.cpp:75]: All functionally identical.
Note the `.get()` call on `comdata` gets the raw memory of the smart pointer, so we can use memcpy, etc on it.

File: src/misc/programs.cpp [hunk 5]
```diff
@@ -39,43 +41,51 @@ Bitu call_program;
...
-	internal_progs.push_back(main);
-
-	memcpy(&comdata[sizeof(exe_block)],&index,sizeof(index));
-	Bit32u size=sizeof(exe_block)+sizeof(index);	
-	VFILE_Register(name,comdata,size);	
-}
+	// Register the COM program with the Z:\ virtual filesystem
+	const auto file_size = static_cast<uint32_t>(sizeof(exe_block) +
+	                                             sizeof(index));
+	VFILE_Register(name, comdata.get(), file_size);
```
Comment (kcgen) [inline src/misc/programs.cpp:80]: Functionally identical.

File: src/misc/programs.cpp [hunk 6]
```diff
@@ -39,43 +41,51 @@ Bitu call_program;
...
 
+	// Register the COM data's unique_ptr to prevent it from going out of scope
+	internal_progs_comdata.push_back(std::move(comdata));
```
Comment (kcgen) [inline src/misc/programs.cpp:84]: Our `comdata` smart-pointer will free it's memory as soon as it goes out of scope - which normally would be the end of this function.  So instead, we move it into the `internal_progs_comdata` global vector to prevent `comdata` from going out of scope.  Eventually when the entire program is shutdown, the vector then destroys all of its elements and then frees its own space.

File: src/misc/programs.cpp (hunk 3 above)
Comment (kklobe) [reply src/misc/programs.cpp:62]: any desire to go further with the C++, such as:
```
constexpr std::array<uint8_t, 19> exe_block = ...
```
and 
```
	std::copy(exe_block.begin(), exe_block.end(), comdata.get());
```

and `exe_block.size()` vs. `sizeof(exe_block)`, etc.?

File: src/misc/programs.cpp (hunk 4 above)
Comment (kklobe) [reply src/misc/programs.cpp:75]: any desire to go further with the C++? For example:
```
constexpr std::array<uint8_t, 19> exe_block = {...}
```
then
```
	std::copy(exe_block.begin(), exe_block.end(), comdata.get());
```
and
```
	PhysPt reader=PhysMake(dos.psp(),256+exe_block.size());
```

etc.

Comment (kcgen) [reply src/misc/programs.cpp:75]: Thanks for the suggestion! Yes, let's go for it. 

There's only upside to `std::copy` - handles any data type or container (fails to compile when something's not right), and will match or exceed `memcpy()` in terms of performance.

fixups inbound.

Comment (kcgen) [reply src/misc/programs.cpp]: - switched `exec_block` to `std::array`
 - switched `comdata` from a `unique_ptr` allocation to a `vector`
    - I thought about using `std::array` for comdata too, but `vector` lets us "push_back" and is also `std::move`-able into the global container, where as `std::array` would need to be copied. 
    - We can initialize a std::vector from begin() to end(), so turns out std::copy wasn't needed

Overall safer and roughly the same in terms of readability :+1: 
Thanks, @kklobe!

**Comment by kcgen** [comment]
Re-tested with ASAN and UBSAN, and launching all Z:\*.COM programs.

File: src/misc/programs.cpp [hunk 7]
```diff
@@ -53,33 +54,27 @@ constexpr uint8_t exe_block[] = {
...
+	comdata_t comdata(exe_block.begin(), exe_block.end());
+	comdata.at(callback_pos) = static_cast<uint8_t>(call_program & 0xff);
+	comdata.at(callback_pos + 1) = static_cast<uint8_t>((call_program >> 8) & 0xff);
 
 	// Save the current program's vector index in its COM data
-	assert(internal_progs.size() <= UINT8_MAX);
-	const auto index = static_cast<uint8_t>(internal_progs.size());
-	comdata[sizeof(exe_block)] = index;
+	const auto index = internal_progs.size();
+	assert(index <= UINT8_MAX); // saving the index into an 8-bit space
```
Comment (kklobe) [inline src/misc/programs.cpp:71]: `UINT8_MAX` -> `std::numeric_limits<uint8_t>::max()`?

Comment (kcgen) [reply src/misc/programs.cpp:71]: This came up in some early reviews, and @dreamer's take was that this is less readable - and I agree.

It's a bloated eyeful to get the same number from the compiler. 

However I fully agree this is useful whenever the type isn't clear (such as using a typedef), or when using templates.

**Comment by kcgen** [comment]
Will get that new windows warning fixed up shortly.

**Comment by kklobe** [comment]
Should I be able to repro #1152 on master with this command? I'm unable to on macOS.

**Comment by kcgen** [comment]
> Should I be able to repro #1152 on master with this command? I'm unable to on macOS.

Maybe this will trigger it? 

`dosbox -conf /dev/null -c "ipx true" -c exit`

(Not sure if macOS has `/dev/null`, but it's a fake empty file to guarantee default conf settings.)

The dynamic nature of the `ipxnet.com` should trigger the leak.

**Comment by kklobe** [comment]
Address Sanitizer does not detect leaks on maOS. I used the command-line `leaks` tool after rebuilding the binary with `meson setup build-debug -Doptimization=0 -Dbuildtype=debug` since the compiler was optimizing away the leak.

I was able to confirm the leak on master and the fix here.

**Review by kklobe — APPROVED** [review]
confirmed leak on master and fix using macOS `leaks` tool.

**Comment by kcgen** [comment]
Thank you for reproducing the issue and confirming the fix, @kklobe -- and figuring out how support leak-testing on macOS systems!
