### PR TITLE
Remove fullscreen_mode=original config option

### LINKED ISSUE #4588: `fullscreen_mode = original` is broken
# Overview

Looks like we've broken `fullscreen_mode = original` which we kept around for the niche use case of using Staging with CRT monitors. All the below information has been reported by **elbkhm** on Discord.

## 0.82.2 test results

Just wanted to put my settings for using a real CRT with DOSBox-Staging out there, in case anybody else wanted to use it. For my setup, I'm using a modern PC, with a second video card (a GTX 970) which has DVI-I for analogue video output. I'm using a $5 passive DVI-to-VGA adapter, and have it plugged in to my Dell E773c monitor, as a secondary monitor in Windows 11. I have custom resolutions configured in the nvidia driver (see https://docs.google.com/spreadsheets/d/14lErgFWuaZU-_D24G-2RwXOhE0VANBO2y5mb5i0V49A/edit?gid=0#gid=0)

Using DOSBox-staging 82.2, I set the following lines in my config files to get it to work.

```ini
[sdl]
output = texturenb
fullscreen = yes
fullresolution = 640x400
display = 1

[render]
aspect = false 
```

The downside with this approach is that if a game changes resolutions, that conflicts with my hard-coding the resolution in the config file. But most games don't do that. And if I use fullresolution=original, aspect=auto, or output=opengl, I get weird scaling issues. But for now, this works for me. 
The other modern forks of DOSbox that I've looked at seem to have abandoned exclusive fullscreen modes entirely, so I'm happy that DOSbox-staging has kept it so far.

## 0.83.0-alpha test results

Tested using Prince of Persia demo, DOSBox-staging version  0.83.0-alpha

### Test 1

```ini
output = texturenb
fullscreen      = yes
fullresolution	= 640x400
display		    = 1
aspect          = false
```

- Non-exclusive fullscreen (borderless)
- CRT remained at Windows resolution (1024x768)
- DOSBox log reported "DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz, scaled to 1024x640 pixels with 1:1 (1:1) pixel aspect ratio"

### Test 2

```ini
output = texturenb
fullscreen      = yes 
fullscreen_mode = original
fullresolution	= 640x400
display		    = 1
aspect          = false
```

- Non-exclusive fullscreen (borderless)
- CRT remained at Windows resolution (1024x768)
- DOSBox log reported "DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz, scaled to 1024x640 pixels with 1:1 (1:1) pixel aspect ratio"

```
  Thought this was weird, looked at the log some more.
  2025-11-06 21:09:44.459 | CONFIG: Deprecated setting 'fullresolution'
  2025-11-06 21:09:44.460 | CONFIG: The 'fullresolution' setting is deprecated but still accepted; please use 'fullscreen_mode' instead.
  2025-11-06 21:09:44.497 | CONFIG: Invalid 'fullscreen_mode' setting: '640x400'; using 'standard'
  2025-11-06 21:09:44.710 | SDL: Error setting fullscreen mode to 2560x1440, falling back to desktop mode
```

### Test 3

```ini
output = texturenb
fullscreen      = yes 
fullscreen_mode = original
display		    = 1
aspect          = false
```

- Removed fullresolution from config
- Ok, back into exclusive fullscreen mode. But screen reports 800x600, instead of 640x400. And tabbing out and back in breaks the exclusive fullscreen
  
```
025-11-06 21:13:13.602 | SDL: Error setting fullscreen mode to 2560x1440, falling back to desktop mode
2025-11-06 21:13:14.580 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz, scaled to 800x500 pixels with 1:1 (1:1) pixel aspect ratio
```

### Test 4

```ini
output = opengl
fullscreen      = yes 
fullscreen_mode = original
display		    = 1
aspect          = false
```

- Scaled to 800x500 for some reason, not exclusive fullscreen, appears in top right corner of screen, with desktop visible beneath it

```
2025-11-06 21:16:16.135 | SDL: Error setting fullscreen mode to 2560x1440, falling back to desktop mode
2025-11-06 21:16:16.600 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz, scaled to 800x500 pixels with 1:1 (1:1) pixel aspect ratio
```

### Test 5

```ini
output = texturenb
fullscreen      = yes 
fullscreen_mode = original
display		    = 1
aspect          = false
viewport	    = 640x400
```

- Shows the correct scaling in the log, but not exclusive fullscreen, and again,  top right corner of screen, with desktop visible beneath it

```
2025-11-06 21:19:45.385 | SDL: Error setting fullscreen mode to 2560x1440, falling back to desktop mode
2025-11-06 21:19:45.871 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz, scaled to 640x400 pixels with 1:1 (1:1) pixel aspect ratio
```

### Test 6

```ini
output = texturenb
fullscreen      = yes 
fullscreen_mode = original
fullresolution	= 640x400
display		    = 0
aspect          = false
```

- Changed my CRT be my primary monitor in Windows.
- Didn't get the error setting fullscreen mode to 2560x1440.
- But screen reports 800x600, and scaled to 800x500 for some reason.

```
2025-11-06 21:33:48.065 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz, scaled to 800x500 pixels with 1:1 (1:1) pixel aspect ratio
```

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

As discussed in #4588 the feature is pretty broken so we're killing it. Also removed all calls to `SDL_SetWindowDisplayMode()` which only makes sense in exclusive fullscreen. Separated that into small commits on the off-chance there's regressions (I very much doubt there will be but still).

## Related issues

Fixes #4588

# Release notes

fullresolution is dead. Long live fullscreen_mode. You can have either standard or the Windows hack "forced-borderless".

# Manual testing

Doom runs.

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/gui/sdl_gui.cpp [hunk 1]
```diff
@@ -2666,11 +2659,6 @@ static void init_sdl_config_settings(SectionProp& section)
 	auto pbool = section.AddBool("fullscreen", Always, false);
 	pbool->SetHelp("Start in fullscreen mode ('off' by default).");
 
-	pstring = section.AddString("fullresolution", DeprecatedButAllowed, "");
-	pstring->SetHelp(
-	        "The [color=light-green]'fullresolution'[reset] setting is deprecated but still accepted;\n"
-	        "please use [color=light-green]'fullscreen_mode'[reset] instead.");
-
```
Comment (johnnovak) [inline src/gui/sdl_gui.cpp:2667]: It would be better keep this with `Deprecated`:

```cpp
	pstring = section.AddString("fullresolution", Deprecated, "");
	pstring->SetHelp(
	        "The [color=light-green]'fullresolution'[reset] setting has been removed.");
```

File: resources/translations/pl.po [hunk 2]
```diff
@@ -2691,16 +2691,6 @@ msgstr ""
...
-#: src/config/setup.cpp:274
-#, fuzzy, c-format, no-wrap
-msgctxt "CONFIG_FULLRESOLUTION"
-msgid ""
-"The [color=light-green]'fullresolution'[reset] setting is deprecated but still accepted;\n"
-"please use [color=light-green]'fullscreen_mode'[reset] instead."
-msgstr ""
-"Rozdzielczość pełnego ekranu: 'original', 'desktop' (domyślne) lub konkretna\n"
-"rozdzielczość, np. 1024x768."
-
```
Comment (johnnovak) [inline resources/translations/pl.po:2703]: Not strictly necessary to remove this from the `.po` files as those will need to be regenerated anyway to sync them up with the code, but I guess it doesn't hurt in this case.

**Comment by johnnovak** [comment]
Works fine on macOS & Windows. Tested both `fullscreen_mode = standard` and `forced-borderless` on Windows. Even switching from borderless to standard works while in fullscreen mode.

File: resources/translations/pl.po (hunk 2 above)
Comment (weirddan455) [reply resources/translations/pl.po:2703]: I don't know how these translation files work. If I make the change you suggested of leaving it deprecated with different help text would it be better to keep them or delete them?

If I keep them, they'll be out of date and need to be re-translated at some point. Do we have a way to flag translation strings out of date?

Comment (johnnovak) [reply resources/translations/pl.po:2703]: This might answer your questions:
https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/TRANSLATING.md

If not, ask @FeralChild64 😄 

I never paid much attention to translations. Previously, we always left them in a broken or semi-broken state until the guy maintaining the translations for a particular language did the syncing/updating (usually a few weeks or a month before the release, so yeah, we should give them a heads-up before cutting the RC). From a high-level perspective, that's not gonna change, otherwise we'd be constantly bottlenecked by translator availability whenever we change any message. That's simply not practical.

File: src/gui/sdl_gui.cpp (hunk 1 above)
Comment (weirddan455) [reply src/gui/sdl_gui.cpp:2667]: Yeah I guess that's better. I kept the line saying to use `fullscreen_mode` instead. That way the user gets a more helpful log message.

File: resources/translations/pl.po (hunk 2 above)
Comment (weirddan455) [reply resources/translations/pl.po:2703]: I left the translation files as-is in my latest push.

**Comment by weirddan455** [comment]
Let me know if that's good. I snuck in a change from an assert that was annoying me to a log message.

File: resources/translations/pl.po (hunk 2 above)
Comment (weirddan455) [reply resources/translations/pl.po:2703]: Went back and read the translating guide. The commands to create an updated .po file will contain the new English text (tested that myself). If the translators do a `diff`, they'll know it's been changed. It's supposed to also remove un-used strings so I guess we don't ever need to touch these files unless we're translating.

Comment (FeralChild64) [reply resources/translations/pl.po:2703]: Updating the `po` file removes the translated strings which are not used anymore, there is no need to remove them manually.

What you can do is to update the string ID if config item is renamed, for example change `CONFIGITEM_GLSHADER` to `CONFIGITEM_SHADER` in all the translated files - the translation system can't handle such change by itself.

Comment (johnnovak) [reply resources/translations/pl.po:2703]: Thanks @FeralChild64 , that's useful info to keep in mind.

File: src/gui/sdl_gui.cpp [hunk 3]
```diff
@@ -2006,7 +2006,7 @@ static void notify_sdl_setting_updated(SectionProp& section,
 		}
 
 	} else {
-		assertm(false, "Unhandled [sdl] section setting");
+		LOG_WARNING("SDL: Runtime change unhandled for property: '%s'", prop_name.c_str());
```
Comment (johnnovak) [inline src/gui/sdl_gui.cpp:1921]: Yeah this is better. In simpler modules I'm doing a full reinit by default in the catch-all else branch, and do more fine-grained reinits for specific settings where I can.

Just with the SDL GUI module a full reinit is not viable anymore (the previous full reinit approach was very heavy handed, and didn't even work with many settings).

File: src/gui/sdl_gui.cpp (hunk 1 above)
Comment (weirddan455) [reply src/gui/sdl_gui.cpp:2667]: I messed this up. I didn't see there was both `DeprecatedButAllowed` and plain old `Deprecated` enum variants. Changing to the latter.
