### PR TITLE
Make parameter addresses properly sized in ppc64le dynrec (fixes #3686)

### LINKED ISSUE #3686: SIGSEV if the code is compiled with PIE
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.1

### What Operating System are you using?

Linux ppc64le

### If Other OS, please describe

Fedora 40

### Relevant hardware info

IBM POWER9

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Reported in Fedora at https://bugzilla.redhat.com/show_bug.cgi?id=2276363

TL;DR; the Fedora's default `LDFLAGS` which has `-specs=/usr/lib/rpm/redhat/redhat-hardened-ld` option that would makes the app prone to `SIGSEV` error whenever running any DOS game

The content of `/usr/lib/rpm/redhat/redhat-hardened-ld` spec file is:

```
*self_spec:
+ %{!static:%{!shared:%{!r:-pie}}}
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set `LDFLAGS='-specs=/usr/lib/rpm/redhat/redhat-hardened-ld'` then ` /usr/bin/meson setup --buildtype=plain  --wrap-mode=nodownload --auto-features=enabled . build && cd build && meson compile`  
2. Run `./dosbox`
3. Run any game and would get SIGSEV:

```
Thread 1 "dosbox" received signal SIGSEGV, Segmentation fault.
0x0000000100121518 in CPU_READ_CRX (cr=<optimized out>, retvalue=<error reading variable: Cannot access memory at address 0x1bfa2b0>) at ../src/cpu/cpu.cpp:1670
1670		retvalue=CPU_GET_CRX(cr);
(gdb) bt
#0  0x0000000100121518 in CPU_READ_CRX (cr=<optimized out>, retvalue=<error reading variable: Cannot access memory at address 0x1bfa2b0>) at ../src/cpu/cpu.cpp:1670
#1  0x00007fff9d814c6c in ??? ()
#2  0x00000001001503f4 in CPU_Core_Dynrec_Run () at ../src/cpu/core_dynrec.cpp:278
#3  0x00000001000a66b4 in Normal_Loop () at ../src/dosbox.cpp:146
#4  0x0000000100118194 in DOSBOX_RunMachine () at ../src/dosbox.cpp:322
#5  CALLBACK_RunRealInt (intnum=<optimized out>) at ../src/cpu/callback.cpp:114
#6  0x0000000100472ee0 in run_binary_executable (fullname=Python Exception <class 'gdb.error'>: value has been optimized out
, args="") at ../src/shell/shell_misc.cpp:620
#7  DOS_Shell::ExecuteProgram (this=<optimized out>, name=Python Exception <class 'gdb.error'>: value has been optimized out
, args=Python Exception <class 'gdb.error'>: value has been optimized out
) at ../src/shell/shell_misc.cpp:493
#8  0x0000000100449d74 in DOS_Shell::DoCommand (this=this@entry=0x103264f80, line=0x7fffffffbb15 " /VGAMODE", line@entry=0x7fffffffbb0d "PCPBENCH /VGAMODE")
    at ../src/shell/shell_cmds.cpp:205
#9  0x0000000100449f84 in DOS_Shell::ParseLine (this=0x103264f80, line=0x7fffffffbb0d "PCPBENCH /VGAMODE") at ../src/shell/shell.cpp:335
#10 0x000000010045a5b0 in DOS_Shell::CMD_CALL (this=0x103264f80, args=0x7fffffffbb0c " PCPBENCH /VGAMODE") at ../src/shell/shell_cmds.cpp:1678
#11 DOS_Shell::CMD_CALL (this=0x103264f80, args=0x7fffffffbb0c " PCPBENCH /VGAMODE") at ../src/shell/shell_cmds.cpp:1675
#12 0x0000000100447608 in DOS_Shell::ExecuteShellCommand (this=0x103264f80, name=<optimized out>, arguments=0x7fffffffbb0c " PCPBENCH /VGAMODE")
    at ../src/shell/shell_cmds.cpp:171
#13 0x0000000100449cfc in DOS_Shell::DoCommand (this=this@entry=0x103264f80, line=0x7fffffffbb0c " PCPBENCH /VGAMODE", line@entry=0x7fffffffbb08 "CALL PCPBENCH /VGAMODE")
    at ../src/shell/shell_cmds.cpp:201
#14 0x0000000100449f84 in DOS_Shell::ParseLine (this=this@entry=0x103264f80, line=line@entry=0x7fffffffbb08 "CALL PCPBENCH /VGAMODE") at ../src/shell/shell.cpp:335
#15 0x000000010044abfc in DOS_Shell::RunBatchFile (this=this@entry=0x103264f80) at ../src/shell/shell.cpp:382
#16 0x000000010044c2f8 in DOS_Shell::Run (this=0x103264f80) at ../src/shell/shell.cpp:445
#17 0x000000010044e220 in SHELL_Init () at ../src/shell/shell.cpp:1453
#18 0x00000001002bcfc0 in Config::StartUp (this=<optimized out>) at ../src/misc/setup.cpp:1533
#19 sdl_main (argc=<optimized out>, argv=<optimized out>) at ../src/gui/sdlmain.cpp:5010
#20 0x0000000100077ee8 in main (argc=<optimized out>, argv=<o
```

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

```text
CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection '
export CFLAGS
CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection '
export CXXFLAGS
FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection -I/usr/lib64/gfortran/modules '
export FFLAGS
FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection -I/usr/lib64/gfortran/modules '
export FCFLAGS
VALAFLAGS=-g
export VALAFLAGS
RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Clink-arg=-specs=/usr/lib/rpm/redhat/redhat-package-notes --cap-lints=warn'
export RUSTFLAGS
LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '
export LDFLAGS
LT_SYS_LIBRARY_PATH=/usr/lib64:
export LT_SYS_LIBRARY_PATH
CC=gcc
export CC
CXX=g++
export CXX
/usr/bin/meson setup --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . redhat-linux-build

tle@shrimp-paste:~/Work/dosbox-staging$ gdb dosbox
GNU gdb (Fedora Linux) 14.2-1.fc40
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from dosbox...
Reading symbols from /usr/lib/debug/usr/bin/dosbox-0.81.0-1.fc41.ppc64le.debug...
(gdb) r
Starting program: /usr/bin/dosbox 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]                                                                                                                                  
Using host libthread_db library "/lib64/libthread_db.so.1".
Downloading separate debug info for /lib64/libgomp.so.1                                                                                                                        
date       time         |                                                                                                                                                      
2024-04-20 00:43:50.353 | arguments: /usr/bin/dosbox
2024-04-20 00:43:50.353 | Current dir: /home/tle/Work/dosbox-staging
2024-04-20 00:43:50.353 | stderr verbosity: 0
2024-04-20 00:43:50.353 | -----------------------------------
2024-04-20 00:43:50.353 | dosbox-staging version f14378e
2024-04-20 00:43:50.353 | ---
2024-04-20 00:43:50.353 | LOG: Loguru version 2.1.0 initialised
2024-04-20 00:43:50.354 | CONFIG: Invalid option 'window_titlebar'
2024-04-20 00:43:50.354 | CONFIG: Invalid option 'vmem_delay'
2024-04-20 00:43:50.354 | CONFIG: Invalid option 'vga_render_per_scanline'
2024-04-20 00:43:50.355 | CONFIG: Invalid option 'cms'
2024-04-20 00:43:50.355 | CONFIG: Invalid option 'opl_remove_dc_bias'
2024-04-20 00:43:50.355 | CONFIG: Invalid option 'pcjr_memory_config'
2024-04-20 00:43:50.355 | CONFIG: Loaded primary config file '/home/tle/.config/dosbox/dosbox-staging.conf'
2024-04-20 00:43:50.355 | LANG: Using internal English language messages
[New Thread 0x7ffff020ef60 (LWP 401904)]                                                                                                                                       
[New Thread 0x7fffef80ef60 (LWP 401905)]
[New Thread 0x7fffeee0ef60 (LWP 401906)]
[New Thread 0x7fffee40ef60 (LWP 401907)]                                                                                                                                       
[New Thread 0x7fffeda0ef60 (LWP 401908)]
[New Thread 0x7fffed00ef60 (LWP 401910)]                                                                                                                                       
[New Thread 0x7ffff3faef60 (LWP 401911)]
2024-04-20 00:43:51.059 | SDL: version 2.30.1 initialised (wayland video and pulseaudio audio)
2024-04-20 00:43:51.059 | DISPLAY: Initialised 1067x800 windowed mode using bilinear scaling on display-0
[New Thread 0x7fffda00ef60 (LWP 401915)]                                                                                                                                       
[New Thread 0x7fffd960ef60 (LWP 401916)]
[New Thread 0x7fffd8c0ef60 (LWP 401917)]
[New Thread 0x7fffcfe0ef60 (LWP 401918)]
[New Thread 0x7fffcf40ef60 (LWP 401919)]
[New Thread 0x7fffcea0ef60 (LWP 401920)]
[New Thread 0x7fffce00ef60 (LWP 401921)]
[New Thread 0x7fffcd60ef60 (LWP 401922)]
[New Thread 0x7fffccc0ef60 (LWP 401923)]
[Thread 0x7fffccc0ef60 (LWP 401923) exited]
[Thread 0x7fffcd60ef60 (LWP 401922) exited]
[Thread 0x7fffce00ef60 (LWP 401921) exited]
[Thread 0x7fffd8c0ef60 (LWP 401917) exited]
[Thread 0x7fffcfe0ef60 (LWP 401918) exited]
[Thread 0x7fffcf40ef60 (LWP 401919) exited]
[Thread 0x7fffcea0ef60 (LWP 401920) exited]
[Thread 0x7fffd960ef60 (LWP 401916) exited]
[Thread 0x7fffda00ef60 (LWP 401915) exited]
[New Thread 0x7fffda00ef60 (LWP 401924)]                                                                                                                                       
[New Thread 0x7fffd960ef60 (LWP 401925)]
[New Thread 0x7fffcea0ef60 (LWP 401926)]
[New Thread 0x7fffcf40ef60 (LWP 401927)]
[New Thread 0x7fffd8c0ef60 (LWP 401928)]
[New Thread 0x7fffcfe0ef60 (LWP 401929)]
[New Thread 0x7fffce00ef60 (LWP 401930)]
[New Thread 0x7fffcd00ef60 (LWP 401931)]                                                                                                                                       
[New Thread 0x7fffb7e0ef60 (LWP 401932)]
[New Thread 0x7fffb740ef60 (LWP 401933)]
[New Thread 0x7fffb6a0ef60 (LWP 401934)]
[New Thread 0x7fffb600ef60 (LWP 401935)]
[New Thread 0x7fffb560ef60 (LWP 401936)]
2024-04-20 00:43:52.059 | OPENGL: Vendor: AMD
2024-04-20 00:43:52.059 | OPENGL: Version: 4.6 (Compatibility Profile) Mesa 24.0.5
2024-04-20 00:43:52.059 | OPENGL: GLSL version: 4.60
2024-04-20 00:43:52.059 | OPENGL: NPOT textures supported
2024-04-20 00:43:52.067 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
2024-04-20 00:43:52.078 | RENDER: Auto-switched to shader 'crt/hercules'
2024-04-20 00:43:52.078 | VGA: Pixel doubling enabled
2024-04-20 00:43:52.078 | VIDEO: Using the DOS video mode's frame rate
2024-04-20 00:43:52.081 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0x7fffaae00010
2024-04-20 00:43:52.081 | VGA: Double scanning VGA video modes enabled
2024-04-20 00:43:52.090 | FPU: Using reduced-precision floating-point emulation
2024-04-20 00:43:52.090 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2024-04-20 00:43:52.092 | VOODOO: Initialized with 4 MB of RAM, multithreading, and no bilinear filtering
[New Thread 0x7fffaac0ef60 (LWP 401937)]
[New Thread 0x7fffaa20ef60 (LWP 401938)]
[New Thread 0x7fffa980ef60 (LWP 401939)]
2024-04-20 00:43:52.093 | CAPTURE: Image capturer started
[New Thread 0x7fffa8e0ef60 (LWP 401940)]
2024-04-20 00:43:52.170 | MIXER: Negotiated 2-channel 48000 Hz audio of 512-frame blocks
2024-04-20 00:43:52.170 | MIXER: Master compressor enabled
2024-04-20 00:43:52.172 | MIDI:ALSA: No available MIDI devices found
2024-04-20 00:43:52.172 | MIDI: Can't find device: 'auto', MIDI is not available
2024-04-20 00:43:52.172 | MPU-401: Running in intelligent mode on ports 330h and 331h
2024-04-20 00:43:52.172 | OPL: Operating at 48000 Hz without resampling
2024-04-20 00:43:52.172 | OPL: Running OPL3 on ports 220h and 388h
2024-04-20 00:43:52.172 | SB16: Sound Blaster 16 OPL output filter enabled
2024-04-20 00:43:52.172 | DMA: Initialised primary controller
2024-04-20 00:43:52.172 | DMA: Initialised secondary controller
2024-04-20 00:43:52.172 | SB: Operating at 22050 Hz and upsampling to the output rate
2024-04-20 00:43:52.173 | SB16: Modern DAC output filter enabled
2024-04-20 00:43:52.173 | SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
2024-04-20 00:43:52.173 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2024-04-20 00:43:52.173 | PCSPEAKER: Operating at 48000 Hz without resampling
2024-04-20 00:43:52.173 | PCSPEAKER: Initialised discrete model
2024-04-20 00:43:52.173 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2024-04-20 00:43:52.173 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2024-04-20 00:43:52.173 | MOUSE: Will be captured after the first left or right button click
2024-04-20 00:43:52.173 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2024-04-20 00:43:52.173 | MOUSE (PS/2): Standard, 3 buttons
2024-04-20 00:43:52.202 | DOS: Loaded modern locale for country 1, 'United States'
2024-04-20 00:43:52.202 | SLIRP: Slirp version: 4.7.0
2024-04-20 00:43:52.202 | SLIRP: Successfully initialized
2024-04-20 00:43:52.202 | NE2000: Initialised on port 300h and IRQ 3
2024-04-20 00:43:52.203 | CONFIG: Loaded auto-mounted drive config file '/usr/share/dosbox-staging/drives/y.conf'
2024-04-20 00:43:52.268 | MAPPER: No joysticks found                                                                                                                           
2024-04-20 00:43:52.269 | MAPPER: Failed loading mapperfile 'mapper-sdl2-0.82.0-alpha.map' directly or from resources
2024-04-20 00:43:52.269 | MAPPER: Loaded default key bindings
[New Thread 0x7fff9fe0ef60 (LWP 401944)]                                                                                                                                       
2024-04-20 00:43:52.325 | RENDER: Auto-switched to shader 'crt/vga-1080p'
2024-04-20 00:43:52.325 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
[New Thread 0x7fff9f40ef60 (LWP 401945)]
[New Thread 0x7fff9ea0ef60 (LWP 401946)]
2024-04-20 00:43:52.353 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 1067x800 pixels with 1:1.35 (20:27) pixel aspect ratio
[Thread 0x7fffce00ef60 (LWP 401930) exited]
2024-04-20 00:43:52.371 | MOUNT: Path '/usr/share/dosbox-staging/drives/y' found
[Thread 0x7fffeee0ef60 (LWP 401906) exited]
2024-04-20 00:44:48.366 | MOUNT: Path '~/Games/DOS' found
2024-04-20 00:45:08.696 | DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.

Thread 1 "dosbox" received signal SIGSEGV, Segmentation fault.
0x0000000100121518 in CPU_READ_CRX (cr=<optimized out>, retvalue=<error reading variable: Cannot access memory at address 0x1bfa2b0>) at ../src/cpu/cpu.cpp:1670
1670		retvalue=CPU_GET_CRX(cr);
(gdb) bt
#0  0x0000000100121518 in CPU_READ_CRX (cr=<optimized out>, retvalue=<error reading variable: Cannot access memory at address 0x1bfa2b0>) at ../src/cpu/cpu.cpp:1670
#1  0x00007fff9d814c6c in ??? ()
#2  0x00000001001503f4 in CPU_Core_Dynrec_Run () at ../src/cpu/core_dynrec.cpp:278
#3  0x00000001000a66b4 in Normal_Loop () at ../src/dosbox.cpp:146
#4  0x0000000100118194 in DOSBOX_RunMachine () at ../src/dosbox.cpp:322
#5  CALLBACK_RunRealInt (intnum=<optimized out>) at ../src/cpu/callback.cpp:114
#6  0x0000000100472ee0 in run_binary_executable (fullname=Python Exception <class 'gdb.error'>: value has been optimized out
, args="") at ../src/shell/shell_misc.cpp:620
#7  DOS_Shell::ExecuteProgram (this=<optimized out>, name=Python Exception <class 'gdb.error'>: value has been optimized out
, args=Python Exception <class 'gdb.error'>: value has been optimized out
) at ../src/shell/shell_misc.cpp:493
#8  0x0000000100449d74 in DOS_Shell::DoCommand (this=this@entry=0x103264f80, line=0x7fffffffbb15 " /VGAMODE", line@entry=0x7fffffffbb0d "PCPBENCH /VGAMODE")
    at ../src/shell/shell_cmds.cpp:205
#9  0x0000000100449f84 in DOS_Shell::ParseLine (this=0x103264f80, line=0x7fffffffbb0d "PCPBENCH /VGAMODE") at ../src/shell/shell.cpp:335
#10 0x000000010045a5b0 in DOS_Shell::CMD_CALL (this=0x103264f80, args=0x7fffffffbb0c " PCPBENCH /VGAMODE") at ../src/shell/shell_cmds.cpp:1678
#11 DOS_Shell::CMD_CALL (this=0x103264f80, args=0x7fffffffbb0c " PCPBENCH /VGAMODE") at ../src/shell/shell_cmds.cpp:1675
#12 0x0000000100447608 in DOS_Shell::ExecuteShellCommand (this=0x103264f80, name=<optimized out>, arguments=0x7fffffffbb0c " PCPBENCH /VGAMODE")
    at ../src/shell/shell_cmds.cpp:171
#13 0x0000000100449cfc in DOS_Shell::DoCommand (this=this@entry=0x103264f80, line=0x7fffffffbb0c " PCPBENCH /VGAMODE", line@entry=0x7fffffffbb08 "CALL PCPBENCH /VGAMODE")
    at ../src/shell/shell_cmds.cpp:201
#14 0x0000000100449f84 in DOS_Shell::ParseLine (this=this@entry=0x103264f80, line=line@entry=0x7fffffffbb08 "CALL PCPBENCH /VGAMODE") at ../src/shell/shell.cpp:335
#15 0x000000010044abfc in DOS_Shell::RunBatchFile (this=this@entry=0x103264f80) at ../src/shell/shell.cpp:382
#16 0x000000010044c2f8 in DOS_Shell::Run (this=0x103264f80) at ../src/shell/shell.cpp:445
#17 0x000000010044e220 in SHELL_Init () at ../src/shell/shell.cpp:1453
#18 0x00000001002bcfc0 in Config::StartUp (this=<optimized out>) at ../src/misc/setup.cpp:1533
#19 sdl_main (argc=<optimized out>, argv=<optimized out>) at ../src/gui/sdlmain.cpp:5010
#20 0x0000000100077ee8 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:30

Continuing.

Loguru caught a signal: SIGSEGV
Stack trace:
18      0x7ffff6e3116c __libc_start_main + 428
17      0x7ffff6e30f2c /lib64/libc.so.6(+0x30f2c) [0x7ffff6e30f2c]
16         0x100077ee8 main + 24
15         0x1002bcfc0 sdl_main(int, char**) + 9376
14         0x10044e220 SHELL_Init() + 4752
13         0x10044c2f8 DOS_Shell::Run() + 744
12         0x10044abfc DOS_Shell::RunBatchFile() + 236
11         0x100449f84 DOS_Shell::ParseLine(char*) + 356
10         0x100449cfc DOS_Shell::DoCommand(char*) + 316
9          0x100447608 DOS_Shell::ExecuteShellCommand(char const*, char*) + 248
8          0x10045a5b0 DOS_Shell::CMD_CALL(char*) + 176
7          0x100449f84 DOS_Shell::ParseLine(char*) + 356
6          0x100449d74 DOS_Shell::DoCommand(char*) + 436
5          0x100472ee0 DOS_Shell::ExecuteProgram(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >) + 2480
4          0x100118194 CALLBACK_RunRealInt(unsigned char) + 116
3          0x1000a66b4 /usr/bin/dosbox(+0xa66b4) [0x1000a66b4]
2          0x1001503f4 CPU_Core_Dynrec_Run() + 244
1       0x7fff9d814c6c [0x7fff9d814c6c]
0          0x100121518 CPU_READ_CRX(unsigned long, unsigned int&) + 136
2024-04-20 00:46:39.242 | Signal: SIGSEGV

Thread 1 "dosbox" received signal SIGSEGV, Segmentation fault.
0x0000000100121518 in CPU_READ_CRX (cr=<optimized out>, retvalue=<error reading variable: Cannot access memory at address 0x1bfa2b0>) at ../src/cpu/cpu.cpp:1670
1670		retvalue=CPU_GET_CRX(cr);
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by classilla**
# Description

Fixes #3686 

The `ppc64le` dynrec erroneously clamps address parameters in function calls to 32-bit because I missed that call when rewriting it from the 32-bit PowerPC dynrec. This caused no problems previously because it was never built with PIE and was unlikely to be passed a 64-bit address, but that's not true for PIE.

This bug is obviously not in the 32-bit PowerPC JIT and does not affect other platforms, nor does the fix affect other platforms (entirely within the `ppc64le` dynrec). There is no detectable impact to performance.

# Manual testing

Tested in both debug and release builds against my usual suite of benchmarks, Doom, Descent and Duke Nukem 3D. No other platforms are touched by this code.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [X] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [X] performed a self-review of my code.
- [X] commented on the particularly hard-to-understand areas of my code.
- [X] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [X] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [X] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [X] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [X] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [X] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [X] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by classilla** [comment]
Note I still can't add labels ...

File: src/cpu/core_dynrec/risc_ppc64le.h [hunk 1]
```diff
@@ -564,10 +564,11 @@ static void inline gen_load_param_imm(Bitu imm, Bitu param)
 }
 
 // load an address as param'th function parameter
-// 32-bit
+// can be 64-bit, especially in PIE code
 static void inline gen_load_param_addr(Bitu addr, Bitu param)
 {
-	gen_load_param_imm(addr, param);
+	// "gen_mov_qword_to_reg"
+	gen_mov_qword_to_reg_imm(RegParams[param],(uint64_t)addr);
```
Comment (weirddan455) [inline src/cpu/core_dynrec/risc_ppc64le.h:571]: Very minor:  Do we need this comment?  It's basically just the name of the function.

**Comment by weirddan455** [comment]
I appreciate the fix @classilla 

Did you test this on a non-PIE build to make sure there's no regressions with our defaults?  If so, I can't think of a reason not to merge.

@johnnovak any comments?

**Comment by johnnovak** [comment]
> I appreciate the fix @classilla
> 
> Did you test this on a non-PIE build to make sure there's no regressions with our defaults? If so, I can't think of a reason not to merge.
> 
> @johnnovak any comments?

Well, it only affects PPC, and I can't test it, so I'll believe the PR author that this improves things and let's merge it 😆

**Review by johnnovak — APPROVED** [review]
Thanks @classilla, we can't test it so we'll trust you on this 👍🏻

**Comment by classilla** [comment]
> Did you test this on a non-PIE build to make sure there's no regressions with our defaults? 

Yes, there is no regression in the default non-PIE case. The code is obviously (now that I've found it) wrong on its face; it just happened to work there.

Thank you for the merge!

File: src/cpu/core_dynrec/risc_ppc64le.h (hunk 1 above)
Comment (classilla) [reply src/cpu/core_dynrec/risc_ppc64le.h:571]: It's just a mental note to myself since this was converted from x86_64 and the function names aren't quite the same. I may harmonize this later to get rid of the comments.

**Comment by classilla** [comment]
Weird, I'm not sure what happened there. I'll just manually resync my fork. Thank you for merging it.

**Comment by weirddan455** [comment]
Sorry I tried to fix it and it closed.

**Comment by classilla** [comment]
Do you need me to redo the pull request?

**Comment by weirddan455** [comment]
If you could re-push the commit to your branch, I think I can re-open this.  It looks like I messed up my git command and reset your branch back to `main`.  Sorry about that.  I was trying to just remove the merge commit.

**Comment by classilla** [comment]
Okay, I rebuilt my fork and pushed the single commit. I have it saved as a patch if needed.

**Comment by weirddan455** [comment]
Thank you.  I'll merge as soon as CI passes.

**Comment by classilla** [comment]
https://github.com/classilla/ppc-dbs/commit/943926569d6d72c9deb0e9db49437700917158df
