### PR TITLE
Don't save MP3 seek table to fastseek.lut file

### LINKED ISSUE #4301: MP3 decoder writes fastseek.lut file in current working directory
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

_No response_

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

There's a big block comment explaining the purpose of the lookup table in `src/libs/decoders/mp3_seek_table.cpp`.

My strong preference is to store this lookup table in memory and never write it out to disk. With my initial testing, the file is only 4KB and I see no reason why we can't just keep that in memory.

If we absolutely need to write it to disk for some reason I can't think of now, we should at the very least save it to a consistent location like `~/.cache/dosbox`, `~/.config/dosbox`, `AppData\local\dosbox`, etc...

Problems I've seen with current approach:

1. I really don't like littering files around. The file does not get removed on exit. I first noticed this because git found the file inside the build tree, which happened to be my CWD.
2. CWD can be anywhere. If the user runs Staging from a GUI shortcut, who knows where they've set it up.
3. User might not even have write permissions to their CWD. I tested this case and MP3 playback still seemed to work but unclear if there is a fallback method for seeking.

### Steps to reproduce the behaviour

Explain in detail how to reproduce the bug. Assume no familiarity with the software.
1. Mount a CDROM image .cue file with .mp3 audio tracks
2. `fastseek.lut` gets written and left on disk in the current working directory

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

We were previously saving a fastseek.lut file to the current working directory whenever a CD image using MP3 audio tracks was mounted.

It was intended to be used as a cache but due to a bug this was not working. Further benchmarking indicated it only takes around 100ms to build.

Going forward, we're always going to regenerate the table at imgmount time. This was the case before due to a bug. Now it's intentional.

## Related issues

Fixes #4301

# Release notes

Don't leave `fastseek.lut` files laying around on the drive.

# Manual testing

Tested Loom which uses seek pretty heavily. The working code path is pretty much the same as it was. Loading from the cache file didn't work properly anyway.

- [ ] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by weirddan455** [comment]
The new Sonar thing found some unused variables. Neat. Removed them.

File: src/libs/decoders/mp3_seek_table.cpp [hunk 1]
```diff
@@ -19,188 +19,22 @@
...
-    XXH64_freeState(state);
-
-    // restore the stream position and cleanup the hash
-    SDL_RWseek(context, original_pos, RW_SEEK_SET);
-    assert(SDL_RWtell(context) == original_pos);
-
-    return hash;
-}
-
 // This function generates a new seek-table for a given mp3 stream and writes
```
Comment (johnnovak) [inline src/libs/decoders/mp3_seek_table.cpp:33]: Could you update the date in the header comment to 2025?

File: src/libs/decoders/mp3_seek_table.h [hunk 2]
```diff
@@ -37,39 +37,21 @@
...
     drmp3* p_dr = nullptr;    // the actual drmp3 instance we open, read, and seek within
-    std::vector<drmp3_seek_point_serial> seek_points_vector = {};
+    std::vector<drmp3_seek_point> seek_points_vector = {};
 };
 
-uint64_t populate_seek_points(struct SDL_RWops* const context,
-                              mp3_t* p_mp3,
-                              const char* seektable_filename,
-                              bool &result);
+uint64_t populate_seek_points(mp3_t* p_mp3, bool &result);
```
Comment (johnnovak) [inline src/libs/decoders/mp3_seek_table.h:53]: Could you update the date in the header comment to 2025?

File: LICENSE [hunk 3]
```diff
@@ -26,7 +26,7 @@ GPL-2.0-or-later terms, however there are some exceptions:
   to the public domain.
 
 - Libraries in src/libs directory, are licensed as follows:
-   - decoders/archive.h, stb.h, and stb_vorbis.h: Public Domain
+   - stb.h and stb_vorbis.h: Public Domain
```
Comment (johnnovak) [inline LICENSE:29]: Nice attention to detail 👍🏻

**Review by johnnovak — APPROVED** [review]
Looking good! Good riddance! 😎

File: src/libs/decoders/mp3.cpp [hunk 4]
```diff
@@ -131,7 +129,7 @@ static int32_t MP3_open(Sound_Sample* const sample, const char* const ext)
 
     bool result;
     // Count the MP3's frames
-    const uint64_t num_frames = populate_seek_points(internal->rw, p_mp3, fast_seek_filename, result);
+    const uint64_t num_frames = populate_seek_points(p_mp3, result);
     if (!result) {
```
[the remark this answers is not in the document]
Comment (weirddan455) [reply src/libs/decoders/mp3.cpp:133]: Updated

File: src/libs/decoders/mp3_seek_table.cpp (hunk 1 above)
Comment (weirddan455) [reply src/libs/decoders/mp3_seek_table.cpp:33]: Updated

File: src/libs/decoders/mp3_seek_table.h (hunk 2 above)
Comment (weirddan455) [reply src/libs/decoders/mp3_seek_table.h:53]: Updated

File: LICENSE (hunk 3 above)
Comment (weirddan455) [reply LICENSE:29]: Thanks to grep
