### PR TITLE
Fix regression in VGA draw's wrapped line case

### LINKED ISSUE #2439: Hard crash on Windows when using QPEG with the latest dev build
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-windows-msys2-x86_64-v0.81.0-alpha-674-g3b349

### What Operating System are you using?

Windows 10

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

With the latest dev build, QPEG consistently hard-crashes the DOSBox process when attempting to display an image.

I can reproduce it 100% of the time on Windows using the MSYS2 dev build. The issue does not happen on macOS with a self-built build off `main`; QPEG works flawlessly there.

v0.80.1 also works flawlessly on Windows. So this is a weird regression, most likely memory corruption that manifests more easily on my Windows box. I suspect it has something to do with the double-scanning VGA changes.

### Steps to reproduce the behaviour.

Explain how to reproduce

1. Use my attached repro pack
2. Start with `dosbox -noprimaryconf`
3. After QPEG started, press Enter on `GODS.BMP` to view it---bamm, crash! It crashes in spectacular ways, every time a bit differently, but the process always exits after a few seconds of hanging...

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
After incorporating `vgaonly`'s features as well as using a 32-bit DAC palette, the `draw_linear_line_from_dac_palette`'s wrapped portion of the function was not updated in the same way as the unwrapped (or "whole-line") approach.

This commit moves the line-writing chunk into a lambda (to avoid code-repetition), which also ensures they all use the same writing logic.

Fixes #2439.

### CODE REVIEW

File: src/hardware/vga_draw.cpp [hunk 1]
```diff
@@ -353,42 +353,56 @@ static uint8_t * VGA_Draw_Linear_Line(Bitu vidstart, Bitu /*line*/) {
...
+
+	// Ensure the size of the palettized VGA line will fit
+	constexpr uint8_t bytes_per_palette_pixel = sizeof(palette_map[0]);
+	assert(pixels_per_line * bytes_per_palette_pixel <=
+	       static_cast<int>(templine_buffer.size()));
+
+	// Running write position for the palettized VGA pixels
+	auto target_addr = TempLine;
+
+	auto write_pixels_from = [&](const uint8_t* vga_line_start,
```
Comment (dreamer) [inline src/hardware/vga_draw.cpp:372]: I know it will be a bit worse on the eyes, but in this case I strongly suggest capturing references to `palette_map` and `target_addr` explicitly instead of all variables in context:

Replace `[&]` with `[&palette_map, &target_addr]`.

In this case I think it's reasonable because `target_addr` is de-facto in-out parameter for this lambda.

**Comment by dreamer** [comment]
Tested our QPEG testcase in debug build - works fine. Thanks @kcgen!

File: src/hardware/vga_draw.cpp (hunk 1 above)
Comment (kcgen) [reply src/hardware/vga_draw.cpp]: Looks good @dreamer; much clearer what's being scoped-in.

**Comment by dreamer** [comment]
Oh, compilers complain about `unused-lambda-capture`? Hmm, maybe `constexpr` variable does not need to be captured in this case?

**Comment by kcgen** [comment]
> Oh, compilers complain about `unused-lambda-capture`? Hmm, maybe `constexpr` variable does not need to be captured in this case?

Interesting; yes - looks like it's using the `map` by value without needing to be explicitly captured. Oh, this is also true for the `bytes_per_palette_pixel`, which is also a `constexpr` value.

(updated)

**Comment by kcgen** [comment]
> Oh, compilers complain about `unused-lambda-capture`? Hmm, maybe `constexpr` variable does not need to be captured in this case?

Tug-o'-war between compilers :-) clang is happy now, but MSVC is not:

D:\a\dosbox-staging\dosbox-staging\src\hardware\vga_draw.cpp(377,1): error C3493: 'palette_map' cannot be implicitly captured because no default capture mode has been specified [D:\a\dosbox-staging\dosbox-staging\vs\dosbox.vcxproj]

D:\a\dosbox-staging\dosbox-staging\src\hardware\vga_draw.cpp(378,1): error C3493: 'bytes_per_palette_pixel' cannot be implicitly captured because no default capture mode has been specified [D:\a\dosbox-staging\dosbox-staging

**Comment by kcgen** [comment]
Ok: trued using a reference and two values:

```c++
... = [&target_addr, palette_map, bytes_per_palette_pixel](...)
```

But now clang is complaining:

```
../../src/hardware/vga_draw.cpp:372:42: warning: lambda capture 'palette_map' is not required to be captured for this use [-Wunused-lambda-capture]
        auto write_pixels_from = [&target_addr, palette_map, bytes_per_palette_pixel](const uint8_t* vga_line_start,
                                              ~~^~~~~~~~~~~
../../src/hardware/vga_draw.cpp:372:55: warning: lambda capture 'bytes_per_palette_pixel' is not required to be captured for this use [-Wunused-lambda-capture]
        auto write_pixels_from = [&target_addr, palette_map, bytes_per_palette_pixel](const uint8_t* vga_line_start,
```

Going back to the single reference.

**Comment by kcgen** [comment]
Investigated the additional clang static analysis issue:



These turned out to be all voodoo-related:



I've added a commit to accommodate them so we can carry on.

Will merge once this is passing CI.

File: .github/workflows/analysis.yml [hunk 2]
```diff
@@ -125,7 +125,7 @@ jobs:
 
       - name: Summarize report
         env:
-          MAX_BUGS: 12
+          MAX_BUGS: 16
```
Comment (dreamer) [inline .github/workflows/analysis.yml:128]: Hmm, it was already accounted for in PR introducing Voodoo support in d2d2154413003d7a2be897d796aa3d26b3d48202. Maybe we get new warnings with new clang static analyser or something?

**Comment by dreamer** [comment]
> Investigated the additional clang static analysis issue:
> 
> These turned out to be all voodoo-related:

Yeah, this is weird... we already had 12 warnings with voodoo enabled and now it jumped back up…

Good call, let's keep the higher limit for now and limit it by fixing issues in voodoo code.

**Review by dreamer — APPROVED** [review]

**Comment by kcgen** [comment]
the warning bump was my fault in this PR.

I was testing some SIMD acceleration (both SSE and NEON) in the VGA draw function - and forgot to remove that GCC flag from Meson. 

This exposed 4 new warnings in libFLAC that I incorrectly believed were there all along.. I've snipped out that Meson SSE flag and we're back to 12 warnings.

**Comment by GranMinigun** [comment]
MSVC cannot into standards-conforming lambdas by default, I had it spew out a ton of errors on my branch because of that. You can just cherry-pick 1453a5b657ecee5879880dc09c55a4da87230a53 to make everyone happy.

**Comment by johnnovak** [comment]
@kcgen Just tested this on my end and now QPEG works fine without any crashes! Great quick fix! 🎉
