### PR TITLE
Fix writing entire autoexec description to config file. Refactor Config::WriteConfig()

### LINKED ISSUE #4769: Only the first line of [autoexec] section description is printed out
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

current GIT main - 9fadecb0a1b22aad60e3ca858c1388a3dc0f9d97

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

Issue noticed by @Kappa971

Despite the [autoexec] section description is 2 lines long (see `dosbox.cpp`):

```C++
	MSG_Add("AUTOEXEC_CONFIGFILE_HELP",
	        "Each line in this section is executed at startup as a DOS command.\n"
	        "Important: The [autoexec] section must be the last section in the config!");
```

only the first line is printed to the config file, for example:

```
[autoexec]

# Each line in this section is executed at startup as a DOS command.
@ECHO OFF
(...)
```

### Steps to reproduce the behaviour

1. Create/update the configuration file, for example with `config -wcd `command.

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by shermp**
# Description

While investigating #4769 I thought that the `Config::WriteConfig()` could use a little less C string manipulation, and be simplified a bit.

Note, the actual fix to the bug is the first commit (add a missing line terminator), even though the refactor of `Config::WriteConfig()` makes it unnecessary.

## Related issues

Fixes #4769

# Manual testing

I compared the output of `config -wcd` from `main` and this branch using a diff tool. The only change is the additional autoexec line that was missing in `main`.

The change has been manually tested on:

- [x] Windows
- [ ] macOS
- [ ] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/tools/compile-commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by shermp** [comment]
Note, SonarCloud is complaining about the use of `fprintf` instead of using `std::print`.

File: src/config/config.cpp [hunk 1]
```diff
@@ -80,47 +77,29 @@ bool Config::WriteConfig(const std_fs::path& path) const
...
-	for (auto section = sections.cbegin(); section != sections.cend(); ++section) {
-		// Print section header
-		safe_strcpy(temp, (*section)->GetName());
-		lowcase(temp);
-		fprintf(outfile, "[%s]\n\n", temp);
+	for (const auto section : sections) {
+		const std::string section_name = section->GetName();
+		const auto section_name_view = std::string_view(section_name);
+		const auto section_name_lower  = lowcase(section_name_view);
+		const auto section_name_upper  = upcase(section_name_view);
```
Comment (johnnovak) [inline src/config/config.cpp:84]: minor: Clang reformat the entire commit, that will most likely align the `=` signs 😎

**Review by johnnovak — APPROVED** [review]
Nice fix & cleanup @shermp 🎉 One very minor comment, feel free to merge after that.

File: src/config/config.cpp (hunk 1 above)
Comment (shermp) [reply src/config/config.cpp:84]: Should be fixed now.

**Comment by shermp** [comment]
> Nice fix & cleanup @shermp 🎉 One very minor comment, feel free to merge after that.

Thanks. I don't have permission to merge, so you'll need to do it.
