### PR TITLE
Fix test crash when using GLIBCXX_ASSERTIONS

### LINKED ISSUE #1085: tests/soft_limiter crashes if GLIBCXX_ASSERTIONS is enabled
**Describe the bug**
If dosbox-staging is compiled with `GLIBCXX_ASSERTIONS` in `CXXFLAGS`, test suite tests/soft_limiter` crashes with the following error during test case _SoftLimiter.InboundsProcessTooManyFrames_:

```
/usr/include/c++/11/bits/stl_vector.h:1063: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = short int; _Alloc = std::allocator<short int>; std::vector<_Tp, _Alloc>::const_reference = const short int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

**To Reproduce**
Configure, compile and run the test as follows:

```
CXXFLAGS='-Wp,-D_GLIBCXX_ASSERTIONS'
export CXXFLAGS
meson --buildtype=plain -Duse_mt32emu=false build
meson compile -C build -j 4
build/tests/soft_limiter
```

**Expected behaviour**
Test suite runs and passes.

**Environment (please complete the following information):**
- OS and version: Fedora 34 (originally encountered in the Fedora Rawhide package build environment)
- Relevant hardware info: x86_64

**Version of dosbox-staging:**
Commit b8efb8c842b7bbf9ec6ac94cf8c68000767e9660

**Configuration parameters:**
n/a, this is a build failure

**Additional context**
This was encountered when attempting to enable the test suite in Fedora package build.

### PR DESCRIPTION
**Pull request by oturpe**
Test case SoftLimiter.InboundsProcessTooManyFrames
tested that for certain invalid usage
that leads to an out-of-bound read from a container,
the debug build crashes because an assertion fails.
For release builds, the same test case expected no crash.
However, GLIBCXX_ASSERTIONS are used for release builds also,
so enabling them led the release build to crash
which the test case did not expect.

Fixed by conditionalizing the test
based on presence of GLIBCXX_ASSERTIONS.

Fixes #1085.

### CODE REVIEW

**Comment by kcgen** [comment]
Does this issue affect the other similar test cases? 

**`git grep DEBUG_DEATH`**

``` text
tests/rwqueue_tests.cpp:        EXPECT_DEBUG_DEATH({ RWQueue<int> q(0); }, "");
tests/rwqueue_tests.cpp:        EXPECT_DEBUG_DEATH({ RWQueue<container_t> q(0); }, "");
tests/soft_limiter_tests.cpp:   EXPECT_DEBUG_DEATH({ limiter.Process(in, frames + 1, out); }, "");
tests/string_utils_tests.cpp:   EXPECT_DEBUG_DEATH({ safe_strcpy(buf, nullptr); }, "");
tests/string_utils_tests.cpp:   EXPECT_DEBUG_DEATH({ safe_strcpy(buf, overlapping); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_8bit, 1); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_16bit, 1); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_32bit, 1); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_8bit, 7); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_16bit, 15); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_32bit, 31); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_8bit, 1); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_16bit, 1); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_32bit, 1); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_8bit, 8); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_16bit, 16); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_32bit, 32); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_8bit, -1); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_16bit, -100); }, "");
tests/support_tests.cpp:        EXPECT_DEBUG_DEATH({ left_shift_signed(var_32bit, -10000); }, "");
```

**Comment by oturpe** [comment]
> Does this issue affect the other similar test cases?

Good point. I was running only that one test. I'll try and see what happens if I attempt to run the whole test suite.

**Comment by oturpe** [comment]
> > Does this issue affect the other similar test cases?
> 
> Good point. I was running only that one test. I'll try and see what happens if I attempt to run the whole test suite.

Tested, that single place was the only one that was affected by GLICXX_ASSERTIONS. With this change, the whole test suite passes.

**Comment by kcgen** [comment]
On Ubuntu 21.04, I actually get severe link errors when trying to build with `D_GLIBCXX_ASSERTIONS`, so I haven't been able to try this on my side.



Unsetting `CXXFLAGS` allows the build to link properly. 

It appears `D_GLIBCXX_ASSERTIONS` someone prevents the `test/stubs.cpp` functions from blocking out the  functions coming from the main libraries. 

I'm using gcc 10.3.0, clang 12.0.1, and meson 0.57.1.

Will keep trying more ...

**Comment by kcgen** [comment]
What happens if you try a debug build with `D_GLIBCXX_ASSERTIONS` enabled?

```
CXXFLAGS='-Wp,-D_GLIBCXX_ASSERTIONS'
export CXXFLAGS
meson --buildtype=debug -Duse_mt32emu=false build
meson compile -C build -j 4
build/tests/soft_limiter
```

**Comment by oturpe** [comment]
> What happens if you try a debug build with `D_GLIBCXX_ASSERTIONS` enabled?

That compiles successfully as well, and all the tests pass.

I am on Fedora 34. Fedora build system uses `D_GLIBCXX_ASSERTIONS` by default (that is why this issue came up in the first place), so perhaps there is some default configuration in place that makes it work on Fedora but not on Ubuntu?

Here is verbose output for the part that fails for you, perhaps some difference can be seen there?

```
$ rm -r build/tests/fs_utils*
$ meson compile -C build -j 4 --verbose
Found runner: ['/usr/bin/ninja']
ninja: Entering directory `build'
[1/5] /usr/bin/meson --internal vcstagger ../src/version.cpp.in version.cpp 0.77.0 /home/otto/src/Ohjelmistot/dosbox-staging @VCS_TAG@ '(.*)' git describe --dirty=+
[2/3] c++ -Itests/fs_utils.p -Itests -I../tests -I../include -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -Weffc++ -Wextra-semi -Wp,-D_GLIBCXX_ASSERTIONS -DGTEST_HAS_PTHREAD=1 -MD -MQ tests/fs_utils.p/fs_utils_tests.cpp.o -MF tests/fs_utils.p/fs_utils_tests.cpp.o.d -o tests/fs_utils.p/fs_utils_tests.cpp.o -c ../tests/fs_utils_tests.cpp
[3/3] c++  -o tests/fs_utils tests/fs_utils.p/fs_utils_tests.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wp,-D_GLIBCXX_ASSERTIONS -Wl,--start-group src/misc/libmisc.a /usr/lib64/libgtest_main.so /usr/lib64/libgtest.so -lpthread /usr/lib64/libSDL2.so -Wl,--end-group
$
```

**Review by LowLevelMahn — COMMENTED** [review]
i would use a special EXPECT_DEATH macro - to prevent copies of the same assert expression

#ifdef _GLIBCXX_ASSERTIONS
#define DOSBOX_EXPECT_DEATH EXPECT_DEATH
#else
#define DOSBOX_EXPECT_DEATH EXPECT_DEBUG_DEATH
#endif

or something and use the special macro in all places

**Comment by oturpe** [comment]
> i would use a special EXPECT_DEATH macro - to prevent copies of the same assert expression
> 
> #ifdef _GLIBCXX_ASSERTIONS
> #define DOSBOX_EXPECT_DEATH EXPECT_DEATH
> #else
> #define DOSBOX_EXPECT_DEATH EXPECT_DEBUG_DEATH
> #endif
> 
> or something and use the special macro in all places

That makes sense, I'll create something like that. However, based on the discussion above, the codebase has assertions that check more than what `GLIBCXX_ASSERTIONS` do. So it should be a new macro for this case (and possible future cases that are like this). So:
1. `EXPECT_DEATH`: from gtest, should always crash
2. `EXPECT_DEBUG_DEATH`: from gtest, should crash on debug builds, but not otherwise
3. `EXPECT_DEBUG_OR_GLIBCXX_ASSERTIONS_DEATH`: new, should crash on debug builds or when the glibc assertions are enabled, but not otherwise

You could also imagine `EXPECT_GLIBCXX_ASSERTIONS_DEATH`, but I assume that the need for that would be fixed by adding more `assert` statements so that the case would become like the present one.

**Comment by kcgen** [comment]
@oturpe , @LowLevelMahn -- thanks for that discussion.

To answer your question,  @oturpe , _"The first question to ask is, it is intended that the test suite can be run for a release build as well as a debug build?"_, the answer is yes.  

Let's clear out mind of all this implementation baggage (NDEBUG, build-type=debug/release/plain, EXPECT_DEBUG_DEATH, DEBUG_DEATH, _GLIBCXX_ASSERTIONS, etc).

From a practical perspective, we want the unit test system to alert us when the code is behaving /differently/ than we expect.  That is:
 - Deliberately good scenarios that happen to crash? Yes, we want to know!
 - Deliberately bad scenarios that happen to succeed? Yes, we want to know!

In this case, we're deliberately "causing a crash", and we should expect that, regardless of how we're building the code.

Perhaps the bug here is my own misuse of the test - perhaps `EXPECT_DEATH` is really what we should be using?

@oturpe , can you try mass-replacing EXPECT_DEBUG_DEATH with DEBUG_DEATH? This should do it:

`git grep -l DEBUG_DEATH | xargs sed -i 's/EXPECT_DEBUG_DEATH/EXPECT_DEATH/g'`

Then try some variations.. 
 -  meson --buildtype=debug -Dunit_tests=enabled 
 -  meson --buildtype=plain -Dunit_tests=enabled 
 -  meson --buildtype=release -Dunit_tests=enabled 

With and without GLIBCXX_ASSERTIONS.  

I'm hopeful we can switch to `DEBUG_DEATH` across the board!

File: tests/soft_limiter_tests.cpp [hunk 1]
```diff
@@ -55,7 +55,11 @@ TEST(SoftLimiter, InboundsProcessTooManyFrames)
 	SoftLimiter limiter("test-channel");
 	const std::vector<float> in{-3, -2, -1, 0, 1, 2};
 	std::vector<int16_t> out(frames * 2);
+#ifdef _GLIBCXX_ASSERTIONS
+	EXPECT_DEATH({ limiter.Process(in, frames + 1, out); }, "");
+#else
 	EXPECT_DEBUG_DEATH({ limiter.Process(in, frames + 1, out); }, "");
+#endif
```
Comment (kcgen) [inline tests/soft_limiter_tests.cpp:62]: We expect death in every case:
 - If this is a build with all asserts off, then going beyond the vector should segfault/bus-error.
 - If this is a debug build, then the soft-limiter's bound assert(s) will terminate
 - If this is a non-debug build with a checked STL, then the vector's bound assert(s) will terminate

Therefore, we can have a single call to: EXPECT_DEATH, without the need for pre-processor branches.

**Review by kcgen — CHANGES_REQUESTED** [review]
Just one adjustment needed; thanks for this PR, @oturpe - and exercising the unit tests on your system!

File: tests/soft_limiter_tests.cpp (hunk 1 above)
Comment (oturpe) [reply tests/soft_limiter_tests.cpp:62]: > We expect death in every case:
>     * If this is a build with all asserts off, then going beyond the vector should segfault/bus-error.
>     * If this is a debug build, then the soft-limiter's bound assert(s) will terminate
>     * If this is a non-debug build with a checked STL, then the vector's bound assert(s) will terminate
> 
> Therefore, we can have a single call to `EXPECT_DEATH` without pre-processor branches.

Unfortunately, the first point does not hold. There are quite many things you can do with a `std::vector` that respond to out-of-bound with undefined behavior, which does not necessarily (or even usually) mean crashing — more likely adjacent memory is accessed like the vector extended there. Segfault only happens if said memory location is not allocated for the process at all.

So if you change this assertion to `EXPECT_DEATH`, compile with `buildtype=plain` and run the test, it fails and the test log contains this:

```
[ RUN      ] SoftLimiter.InboundsProcessTooManyFrames
../tests/soft_limiter_tests.cpp:58: Failure
Death test: { limiter.Process(in, frames + 1, out); }
    Result: failed to die.
 Error msg:
[  DEATH   ] 
[  FAILED  ] SoftLimiter.InboundsProcessTooManyFrames (0 ms)
```

Because it is undefined behavior, it depends on the compiler. I have GCC 11.1.1.

This is also exactly what `GLIBCXX_ASSERTIONS` changes. It sets the undefined behavior of certain operations to mean a crash.

If you really want no difference of behavior between debug and release builds, and it is ok to crash the program, `assert(condition)` statements could be replaced with this kind of code: `if (!condition) { abort() }`. Then there would be no undefined behavior. Calling `abort()` could be replaced with a graceful recovery action, but writing that action would need understanding of the soft limiter. That is beyond my abiility at the moment, but if you are content with crashing, I can rewrite the asserts into the form proposed above. What do you think?

Comment (kcgen) [reply tests/soft_limiter_tests.cpp:62]: We prefer assert checks as internal "checks-and-balances" when we know the condition is internally-controlled code/logic.  However when potentially bad data or conditions are outside of our control (system or user-data), we prefer non-asserts, such as a conditional+abort. 

This lets us be very liberal with asserting expected states, which also acts as self-describing code to readers. This is much more powerful than a comment like "// We expect the values to be positive at this point", while gaining the performance in release builds when those asserts disappear.

In this case, I was trying to avoid proliferation of pre-processor branches in our unit tests (perhaps Clang, VS2019, musl libc, etc.. have their own variations on this ifdef as well.. which would make our unit tests quite a mess).   

Given Fedora is using this flag by default, and Fedora is 1st-class certainly a supported system, we want to make sure all Fedora users can run unit tests - regardless of build-type.

@LowLevelMahn - I like your suggestion to abstract this behind a macro.  Right now, this is our only instance - so when the day comes that more of this is needed, then you're suggestion will be put into action :-)

Merging :rocket: 

Thank you,  @oturpe!

Comment (kcgen) [reply tests/soft_limiter_tests.cpp:62]: The test passes on Ubuntu using all build-types:

**Comment by oturpe** [comment]
Thank you @kcgen, I am really happy this issue was resolved so quickly.

Just a note, I would like to clarify that this was not a problem for users building dosbox-staging on Fedora machine, which worked with BUILD.md instructions just fine. Rather, the problem appeared when the official Fedora package for dosbox-staging was being built. There, GLIBCXX_ASSERTIONS are [mandatory](https://fedoraproject.org/wiki/Changes/HardeningFlags28) and running the test suite is [recommended](https://docs.fedoraproject.org/en-US/packaging-guidelines/).

I would also like to ping @dreamer who is the Fedora package maintainer. Please take a look at [Fedora issue 1960865](https://bugzilla.redhat.com/show_bug.cgi?id=1960865) — it is now finally possible to have a working dosbox in Fedora.

**Comment by kcgen** [comment]
> There, GLIBCXX_ASSERTIONS are mandatory and running the test suite is recommended.

@oturpe, thanks for the heads up that Fedora mandates  `GLIBCXX_ASSERTIONS` in their package repo. I unfortunately can't get this working on my Ubuntu 21.04 system without severe link errors; so need to figure out why.  I certainly would prefer to use this as another check, along-side our sanitizer builds when testing binaries.

Thanks for the PR! We're welcome to any other areas of interest or improvement you see :-)
