### PR TITLE
On Windows, clear the read-only attribute before removing a directory.

### LINKED ISSUE #4282: Read-only attribute on directories not being handled properly on POSIX
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

f1e7b17d75972d5943a7a13c7d62721d55afa7d4

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

Debian 12

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

When a DOS program calls `SetFileAttr()` for the read-only bit, we're setting that permission on the host file system. On POSIX, this prevents new files from being created in that directory. On MS-DOS and on Windows, it does not.

On Windows, we call `SetFileAttributesW()` setting `FILE_ATTRIBUTE_READONLY` which the Windows API docs state "This attribute is not honored on directories.": https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesw

Real program that's affected is DeuTex: https://doomwiki.org/wiki/DeuTex
Direct link: https://web.archive.org/web/20161211135229id_/http://www.teaser.fr/~amajorel/deutex/fungus/deutex-4.4.902.bin.dos.zip
Depends on CSWDPMI (extract only the .exe files into the DeuTex directory): https://sandmann.dotster.com/cwsdpmi/csdpmi7b.zip

### Steps to reproduce the behaviour

Simple repro case (doesn't need deutex). This works on real MS-DOS and DOSBox Staging under Windows but fails on Linux.
1. mkdir test
2. attrib +R test
3. cd test
4. echo blah > foo.txt

Using DeuTex:
1. Copy DOOM.WAD into the DeuTex directory.
2. deutex -xtract doom.wad

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

MS-DOS allows removal of read-only directories. Windows does not.
Implement a hack to remove the read-only bit if directory removal fails.

## Related issues

Fixes #4282

# Release notes

Allow read-only directories to be removed on Windows.

# Manual testing

```
mkdir blah
attrib +r blah
rmdir blah
```

Above has always worked on real MS-DOS and on Linux. This PR makes it work on Windows.

The change has been manually tested on:

- [x] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/dos/drive_local.cpp [hunk 1]
```diff
@@ -468,9 +468,12 @@ bool localDrive::RemoveDir(const char* dir)
 	safe_strcpy(newdir, basedir);
 	safe_strcat(newdir, dir);
 	CROSS_FILENAME(newdir);
-	int temp = rmdir(dirCache.GetExpandNameAndNormaliseCase(newdir));
-	if (temp==0) dirCache.DeleteEntry(newdir,true);
-	return (temp==0);
+
+	const bool success = local_drive_remove_dir(dirCache.GetExpandNameAndNormaliseCase(newdir));
```
Comment (johnnovak) [inline src/dos/drive_local.cpp:472]: minor: auto

**Comment by johnnovak** [comment]
Looks good, I'll test on macOS later. Backport material for 0.82.2

Could you include the info about what actual DOS program this fixes from https://github.com/dosbox-staging/dosbox-staging/issues/4282?

**Comment by weirddan455** [comment]
> Looks good, I'll test on macOS later.

Feel free but it should only affect Windows. POSIX only has a very small refactor.

> Could you include the info about what actual DOS program this fixes from https://github.com/dosbox-staging/dosbox-staging/issues/4282 in the release notes?

I don't have any known DOS programs that this fixes.

File: src/dos/drive_local.cpp (hunk 1 above)
Comment (weirddan455) [reply src/dos/drive_local.cpp]: changed

**Comment by johnnovak** [comment]
> > Looks good, I'll test on macOS later.
> 
> Feel free but it should only affect Windows. POSIX only has a very small refactor.

Okay, that's not necessary then.

> > Could you include the info about what actual DOS program this fixes from #4282 in the release notes?
> 
> I don't have any known DOS programs that this fixes.

You wrote this in the linked ticket, didn't you? 😆 

> Real program that's affected is DeuTex: https://doomwiki.org/wiki/DeuTex
Direct link: https://web.archive.org/web/20161211135229id_/http://www.teaser.fr/~amajorel/deutex/fungus/deutex-4.4.902.bin.dos.zip
Depends on CSWDPMI (extract only the .exe files into the DeuTex directory): https://sandmann.dotster.com/cwsdpmi/csdpmi7b.zip

**Review by johnnovak — APPROVED** [review]
Nice one 🎉

**Comment by weirddan455** [comment]
DeuTex was only broken on POSIX and is fixed by #4283

This is a separate Windows-only bug I discovered along the way.

**Comment by johnnovak** [comment]
> DeuTex was only broken on POSIX and is fixed by #4283
> 
> This is a separate Windows-only bug I discovered along the way.

Right, I guess I got a bit confused 😆
