### PR TITLE
Fix ppc64le backend and 64K page size support

### LINKED ISSUE #2789: Fail to build dosbox-staging on Fedora 39 (rawhide)
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

8270aad5b443b6deb10dd03331721419a3730378

### What Operating System are you using?

Other

### If Other OS, please describe

Fedora 39 Linux PPC64LE

### Relevant hardware info

IBM POWER9 CPU, Raptor Computing Blackbird workstation

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When run `meson compile -C build/release` I got [failed build](https://gist.github.com/runlevel5/e3ef97dfcf23c24b0f4f46ebf8327a4b)

```
../../src/cpu/core_dynrec/risc_ppc64le.h:755:28: error: invalid conversion from ‘const uint8_t*’ {aka ‘const unsigned char*’} to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
```

FYI gcc --version
gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. meson compile -C build/release

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

```text
https://gist.github.com/runlevel5/e3ef97dfcf23c24b0f4f46ebf8327a4b
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by classilla**
This fixes #2789 . Not sure how we got three commits out of one, but anyway.

- Fix `ppc64le` backend (`ppc64` and 32-bit PowerPC still broken)
- Autodetect 4K or 64K pages on `ppc64` and `ppc64le`
- Make `PAGESIZE` a `uint32_t` if defined (because 64K won't fit in `uint16_t`)
- Since `mmap` is page aligned by definition, don't try to realign allocations we get from it (the current alignment code strips the top word off 64-bit pointers)
- Alternate code for `dyn_mem_adjust` to properly handle 64K pages

### CODE REVIEW

**Comment by runlevel5** [comment]
Screenshot from 2023-09-04 18-09-44

34fps! That's even faster than the original patched dosbox.

File: src/cpu/core_dynrec/risc_ppc64le.h [hunk 1]
```diff
@@ -542,11 +542,11 @@ static void inline gen_call_function_raw(void *func, bool fastcall = true)
 // generate a call to a function with paramcount parameters
 // note: the parameters are loaded in the architecture specific way
 // using the gen_load_param_ functions below
-static uint64_t inline gen_call_function_setup(void *func,
+static inline const uint8_t* gen_call_function_setup(void *func,
```
Comment (runlevel5) [inline src/cpu/core_dynrec/risc_ppc64le.h:545]: Please excuse my lacking of understanding, why do we change `uint64_t` to `uint8_t`?

File: meson.build [hunk 2]
```diff
@@ -371,12 +371,20 @@ if host_machine.endian() == 'big'
...
-#endif
+# 64-bit Power ISA can run with either 4K or 64K page size.
+# (32-bit Power ISA and PowerPC are always 4K.)
+if host_machine.cpu_family() in ['ppc64', 'ppc64le']
+    pagesize_cmd = run_command('getconf', 'PAGESIZE', check: true)
+    if pagesize_cmd.returncode() != 0
+        error('''error executing getconf''')
+    else
+        pagesize = pagesize_cmd.stdout().strip().to_int()
+        if pagesize != 4096
```
Comment (kcgen) [inline meson.build:382]: suggest a second error pathway if the pagesize value is `< 4096`, just incase we _can_ execute `getconf` but the result is an empty string (or something converted to 0).

File: meson.build [hunk 3]
```diff
@@ -371,12 +371,20 @@ if host_machine.endian() == 'big'
...
+            warning('''using pagesize of '''+pagesize.to_string())
+            conf_data.set('PAGESIZE', pagesize)
```
Comment (kcgen) [inline meson.build:384]: Suggest avoiding using `warning`, because a > 4K page size is fine within the scope of the `if host_machine.cpu_family() in ['ppc64', 'ppc64le']` condition.

Suggest `summary('Host page size', size-as-string)`, which shows up in the summary block at the end of `meson setup` phase:

```
dosbox-staging 0.81.0-alpha

  Build Summary
    Build type          : debug
    Install prefix      : /usr/local
    ...
    ManyMouse support   : Enabled
    Byte order          : little-endian
    Per-page W^X        : True
    CPU dynamic core    : optimized for x86/x86_64 (dyn-x86)
    CPU core target arch: X86_64
```

It's OK if the `summary()` is just added for this != 4096 scenario, just to highlight to the user at the end.

File: src/cpu/core_dynrec/risc_ppc64le.h (hunk 1 above)
Comment (kcgen) [reply src/cpu/core_dynrec/risc_ppc64le.h:545]: The `*` after the `uint8_t` indicates the returned value is a pointer (or the memory address of) a unsigned 8-bit value.  The cache is a byte stream (unsigned 8-bits).

This is the new API return type (that other dynrec cores), and was the source of why the 64-bit PPC dynrec code build broke in the first place.

File: src/cpu/core_dynrec/risc_ppc64le.h [hunk 4]
```diff
@@ -542,11 +542,11 @@ static void inline gen_call_function_raw(void *func, bool fastcall = true)
...
                                              Bitu paramcount,
                                              bool fastcall = false)
 {
-	uint64_t proc_addr=(uint64_t)cache.pos;
+	const uint8_t* proc_addr=(const uint8_t*)cache.pos;
```
Comment (kcgen) [inline src/cpu/core_dynrec/risc_ppc64le.h:549]: Can avoid the C-cast because the `cache.pos` is already this type, and use `const auto` instead.

dyn_cache.h:

```c++
static struct {
    ...
	const uint8_t* pos = {}; // position in the cache block
} cache = {};
```

Comment (kcgen) [reply src/cpu/core_dynrec/risc_ppc64le.h:549]: Same comment for all below `(const uint8_t*)` casts of `cache.pos` (and cache.pos - 4).

File: src/cpu/core_dynrec/risc_ppc64le.h [hunk 5]
```diff
@@ -641,30 +642,30 @@ static void gen_fill_branch(DRC_PTR_SIZE_IM data)
...
-	return ((uint64_t)cache.pos-4);
+	return ((const uint8_t*)(cache.pos-4));
 }
 
 // calculate long relative offset and fill it into the location pointed to by data
-static void gen_fill_branch_long(uint64_t data)
+static void gen_fill_branch_long(const uint8_t* udata)
 {
-	return gen_fill_branch((DRC_PTR_SIZE_IM)data);
+	return gen_fill_branch(udata);
```
Comment (kcgen) [inline src/cpu/core_dynrec/risc_ppc64le.h:668]: (minor: please `data`; the coding style doesn't use type-or-signedness prefix-notation in variable names, like uname or sname).

File: src/cpu/core_dynrec/risc_ppc64le.h [hunk 6]
```diff
@@ -752,7 +754,7 @@ static void gen_run_code(void)
 	IMM_OP(19, 0x14, 0, 16<<1);          // blr
 
 	// trampoline to call get_CF()
-	getCF_glue = cache.pos;
+	getCF_glue = (uint8_t*)cache.pos;
```
Comment (kcgen) [inline src/cpu/core_dynrec/risc_ppc64le.h:757]: Suggest updating `getCF_glue` type to:

```
static const uint8_t* getCF_glue = nullptr;
```

So this is a 1:1 assignment without needing to strip-the-const from the pointer.

File: src/cpu/core_dynrec/risc_ppc64le.h [hunk 7]
```diff
@@ -766,7 +768,7 @@ static void gen_return_function(void)
 // call to a simpler function
 // these must equal the length of a branch stanza (see
 // do_gen_call)
-static void gen_fill_function_ptr(uint8_t *pos, void *fct_ptr, Bitu flags_type)
+static void gen_fill_function_ptr(const uint8_t *pos, void *fct_ptr, Bitu flags_type)
```
Comment (kcgen) [inline src/cpu/core_dynrec/risc_ppc64le.h:771]: :+1:

File: src/cpu/dyn_cache.h [hunk 8]
```diff
@@ -920,16 +939,18 @@ static void cache_init(bool enable) {
...
 			cache_code_start_ptr=static_cast<uint8_t *>(malloc(cache_code_size));
 			if (!cache_code_start_ptr) {
 				E_Exit("DYNCACHE: Failed allocating cache memory because: %s", strerror(errno));
 			}
-#endif
 			// align the cache at a page boundary
 			cache_code = reinterpret_cast<uint8_t *>(
 			    (reinterpret_cast<uintptr_t>(cache_code_start_ptr) +
 			    host_pagesize - 1) & ~(host_pagesize - 1));
+#endif
```
Comment (kcgen) [inline src/cpu/dyn_cache.h:953]: :+1:

**Review by kcgen — COMMENTED** [review]
Thanks for this PR @classilla ; looks good and only have minor DOSBox Staging-type style/standard suggestions.

**Comment by kcgen** [comment]
Sorry for not mentioning it sooner; but we try to avoid adding merge-commits to the main branch:



Seeing how you've nicely structured the code to avoid regressions on the non-PPC64le paths, I think it can safely go in as one commit, if you're OK with that.  If you're OK that, I can squash and rebase at merge time.

File: src/cpu/core_dynrec/risc_ppc64le.h [hunk 9]
```diff
@@ -737,7 +739,7 @@ static void gen_run_code(void)
 	IMM_OP(19, 0x14, 0, 528<<1);     // bctr
 
 	// epilog
-	epilog_addr = cache.pos;
+	epilog_addr = (void*)cache.pos;
```
[the remark this answers is not in the document]
Comment (classilla) [reply src/cpu/core_dynrec/risc_ppc64le.h:742]:
```
../../src/cpu/core_dynrec/risc_ppc64le.h:742:23: error: invalid ‘static_cast’ from type ‘const uint8_t*’ {aka ‘const unsigned char*’} to type ‘void*’
  742 |         epilog_addr = static_cast<void*>(cache.pos);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

[the remark this answers is not in the document]
Comment (classilla) [reply src/cpu/core_dynrec/risc_ppc64le.h:742]: For that matter,

```
../../src/cpu/core_dynrec/risc_ppc64le.h:742:23: error: ‘reinterpret_cast’ from type ‘const uint8_t*’ {aka ‘const unsigned char*’} to type ‘void*’ casts away qualifiers
  742 |         epilog_addr = reinterpret_cast<void*>(cache.pos);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

So I'll address this by changing `gen_function()` which takes `void*`.

File: meson.build [hunk 10]
```diff
@@ -371,12 +371,20 @@ if host_machine.endian() == 'big'
...
-#      disabled because SVN r4424 broke compilation of ppc backends
-#if host_machine.cpu_family() in ['ppc64', 'ppc64le']
-#  conf_data.set('PAGESIZE', 65536)
-#endif
+# 64-bit Power ISA can run with either 4K or 64K page size.
+# (32-bit Power ISA and PowerPC are always 4K.)
+if host_machine.cpu_family() in ['ppc64', 'ppc64le']
+    pagesize_cmd = run_command('getconf', 'PAGESIZE', check: true)
+    if pagesize_cmd.returncode() != 0
+        error('''error executing getconf''')
```
[the remark this answers is not in the document]
Comment (classilla) [reply meson.build:379]: done

File: meson.build (hunk 2 above)
Comment (classilla) [reply meson.build:382]: done

File: src/cpu/core_dynrec/risc_ppc64le.h (hunk 5 above)
Comment (classilla) [reply src/cpu/core_dynrec/risc_ppc64le.h:668]: done

File: meson.build (hunk 3 above)
Comment (kcgen) [reply meson.build:384]: Even better, @classilla!

Can do the summary at the end (value from the conf) so will also show up as 16K for Apple ARM64, too. Everbody can see this improvement now :-)

File: src/cpu/core_dynrec/risc_ppc64le.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (kcgen) [reply src/cpu/core_dynrec/risc_ppc64le.h:742]: Oof. Sorry.

Hmm.. let's try bringing `epilog_addr` in line too (similar to PPC 32bit):

```
static const uint8_t* epilog_addr = nullptr;
```

Then just a 1:1 assignment (I hope :sweat_smile:)

File: meson.build (hunk 3 above)
Comment (classilla) [reply meson.build:384]: done (hopefully in an acceptable fashion)

File: src/cpu/core_dynrec/risc_ppc64le.h (hunk 4 above)
Comment (classilla) [reply src/cpu/core_dynrec/risc_ppc64le.h:549]: done

File: src/cpu/core_dynrec/risc_ppc64le.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (classilla) [reply src/cpu/core_dynrec/risc_ppc64le.h:742]: It was cleaner to change `gen_function()` anyway (see upcoming diff).

File: src/cpu/core_dynrec/risc_ppc64le.h (hunk 6 above)
Comment (classilla) [reply src/cpu/core_dynrec/risc_ppc64le.h:757]: done

**Comment by classilla** [comment]
> Seeing how you've nicely structured the code to avoid regressions on the non-PPC64le paths, I think it can safely go in as one commit, if you're OK with that. (If so, I can squash and rebase at merge time, which will strip out these merge commits).

That's fine. Sorry, forgot to use rebase.

**Comment by classilla** [comment]
Revision patch up.

**Review by kcgen — APPROVED** [review]
Thanks for getting ppc64le working again, @classilla ! All looks good.

**Comment by kcgen** [comment]
@runlevel5, when you have a chance to do a fresh `meson setup` and build with with @classilla's update in latest `main`, curious how your benchmarks run!

**Comment by MasterO2** [comment]
@kcgen, with all the features Staging is adding this year, do you have a rough idea for when 0.81 will be released?

**Comment by runlevel5** [comment]
@kcgen I got 41fps with `./build/release/dosbox -set core=dynamic -set cycles=max`

Screenshot from 2023-09-05 09-34-14

**Comment by kcgen** [comment]
Now you're cooking with gas! Very nice, @classilla and @runlevel5 🚀

**Comment by kcgen** [comment]
> @kcgen, with all the features Staging is adding _this year_, do you have a rough idea for when 0.81 will be released?

The timeframe is in your question 👍!

**Comment by runlevel5** [comment]
@kcgen unrelated to this PR, I find the running with Wayland (`SDL_VIDEODRIVER=wayland `) is much slower than with X11. I guess it is not related to DosBox as I find similarly poor performance on other SDL-based Linux games.

**Comment by kcgen** [comment]
Yup, both @GranMinigun (on Arch x86-64) and myself (on Ubuntu x86-64) are both using Xorg X11 due to various miscellaneous Wayland issues. 

In my case, after some hours I lose the ability to click tabs in Firefox and have to logout and back in to bring it back, which is a total fail. Works fine in X11 thought 😅.

A couple things to try:
 - in your conf, set `output = texture` (or `texturenb`) to use SDL's own output method.

- Next, try passing `--noprimaryconf` as a CLI argument, which ignores any old/stale conf settings and uses 100% built-in defaults.

@GranMinigun, anything you can think of to try?

@johnnovak , I see the CRT auto shader. In action above. Looks great, and performance is solid!

**Comment by kcgen** [comment]
@weirddan455 , @rderooy : do you guys know of some tips for performance improvements under Wayland?

**Comment by GranMinigun** [comment]
> anything you can think of to try?

A different Wayland compositor. Which boils down to changing DE/WM.

No, really. The implementations vary significantly. It can easily be a problem in Gnome/Mutter (I assume that's Gnome on the screenshot). I doubt that's something on SDL's side, because it only abstracts GLX/EGL interfaces in OpenGL renderer, which do the actual talking.

**Comment by weirddan455** [comment]
Yeah, what @GranMinigun said.  It also depends on graphics driver.  I'm on X11 because my GPU needs old Nvidia drivers to work correctly and those aren't compatible with KDE on Wayland.

I did try Wayland out briefly on nouveau open source drivers but it has bad 3D performance all around and no Vulkan support.  Dosbox and KDE worked on it though.

Alternatively, you can just keep using SDL's X11 driver on Wayland.  There's a thing called XWayland that gives you compatibility with X11 programs.

**Comment by kcgen** [comment]
Improve your Wayland experience through avoidance techniques. Sounds like a Linux users' self-help seminar! (Hey.. I'd be the first in line)

Talking about APIs, pipewire rocks, and you can skip the pulse audio wrapper with: 

(in your dot profile)
```
export SDL_AUDIODRIVER=pipewire
```

**Comment by johnnovak** [comment]
> Improve your Wayland experience through avoidance techniques. Sounds like a Linux users' self-help seminar! (Hey.. I'm there 🤘)

Hey, but you are excercising your freedom of choice to tinker with if for a week and still not get it quite right after that... 😅 

Or you can join the dark side and use proprietary closed-source solutions from EvilCompanies(tm) that JustWork(tm) 😆 I have succumbed to the temptations of evil... and I'm fine with that 😎 :met

**Comment by kcgen** [comment]
e755c11a82cfc3c32c3c5ca09510ead4

I've got complaints about all of 'em! These operating systems aren't loyal. 

That's why we're here.. still rocking DOS; the golden era of gaming! 👑

**Comment by runlevel5** [comment]
> Alternatively, you can just keep using SDL's X11 driver on Wayland. There's a thing called XWayland that gives you compatibility with X11 programs.

Yes XWayland runs fine. It is 1 to 2 fps slower than native X11.

> No, really. The implementations vary significantly. It can easily be a problem in Gnome/Mutter (I assume that's Gnome on the screenshot). I doubt that's something on SDL's side, because it only abstracts GLX/EGL interfaces in OpenGL renderer, which do the actual talking.

I am using GNOME Shell 45 (and Mutter 45 that comes along with it). As of now GNOME 45 has not released so I will test again once the final version is out.

**Comment by weirddan455** [comment]
Actually, thinking about this more, it must be something in SDL's code slowing this down.  I'm not talking about the renderer here.  Just the SDL Wayland code.

XWayland is running DosBox inside of an X server inside of Wayland.  You would think cutting out the middle man (X server) should not hurt performance.  Also, how much slower are we talking about exactly?

**Comment by runlevel5** [comment]
> XWayland is running DosBox inside of an X server inside of Wayland. You would think cutting out the middle man (X server) should not hurt performance. Also, how much slower are we talking about exactly?

On X11, I get 41fps and 42fps
On Wayland driver, I only can achieve like 20fps.
On XWayland, I get 39fps and sometimes 38fps. Interestingly lots of frames dropped randomly happening now and then

**Comment by kcgen** [comment]
> On XWayland, I get 39fps and sometimes 38fps. Interestingly lots of frames dropped randomly happening now and then

@runlevel5 , can you paste your full console log output? (I'm assuming you're seeing the pacer reporting long rendering times and needing to skip frames?)

**Comment by rderooy** [comment]
I have been running Wayland exclusively for the last 3+ years, amongst others because it is the only way to have per-display scaling. But since I use Fedora with Gnome, it works pretty well.

What has worked less well is some applications. Mostly running applications via XWayland works fine, including web browsers and SDL. Wayland native Firefox has been working reasonably well for the last year, but Chrome has been more of a headache, and is only recently starting to work reasonably. Not helped that Chrome is basically the kitchen-sink and does everything itself instead of delegating things to the window manager and system libraries.

Wayland native with SDL2 has also been a rocky road. Even with fairly recent SDL2 versions, I could easily trigger various issues until the most recent versions, which is why for instance, until late last year, I had the flatpak version of dosbox-staging default to X11 even on Wayland.

Having said that, I have not done any speed tests with SDL2 on Wayland vs XWayland, and there may still be some issues there. But from (non-SDL2) benchmarks I have seen on phoronix.com, it would appear that with recent distros Wayland performs generally slightly better than X11

**Comment by classilla** [comment]
`output=texture` definitely helped here, even on X11. Got at least another 3-4fps with that alone.

**Comment by runlevel5** [comment]
```
# Wayland / output=texture texture_renderer=opengl
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=wayland ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture texture_renderer=opengl --noprimaryconf # => 43.5fps
# Wayland / output=texturenb texture_renderer=opengl
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=wayland ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texturenb texture_renderer=opengl --noprimaryconf # => 43.2fps
# Wayland / output=texture texture_renderer=software
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=wayland ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture texture_renderer=software --noprimaryconf # => 20.1fps
# Wayland / output=texturenb texture_renderer=software
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=wayland ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texturenb texture_renderer=software --noprimaryconf # => 39.8fps
# Wayland / output=opengl
SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=wayland ./build/release/dosbox -set core=dynamic -set cycles=max -set output=opengl --noprimaryconf # => 16.2fps SLLLLLLOOOOOWWW!!
# Wayland / output=openglnb
SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=wayland ./build/release/dosbox -set core=dynamic -set cycles=max -set output=openglnb --noprimaryconf # => 15.8fps SLLLLLLOOOOOWWW!!
# Wayland / output=versus
SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=wayland ./build/release/dosbox -set core=dynamic -set cycles=max -set output=versus --noprimaryconf #=> 21.9fps
```
```
# XWayland / output=texture texture_renderer=opengl
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture texture_renderer=opengl --noprimaryconf # => 42.2fps
# XWayland / output=texturenb texture_renderer=opengl
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texturenb texture_renderer=opengl --noprimaryconf # => 40.8fps
# XWayland / output=texture texture_renderer=software
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture texture_renderer=software --noprimaryconf # => 18.8fps
# XWayland / output=texturenb texture_renderer=software
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture texture_renderer=software --noprimaryconf # => 37.4fps


# XWayland / output=opengl
SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=opengl --noprimaryconf #=> 41.1fps
# XWayland / output=openglnb
SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=openglnb --noprimaryconf #=> 41.2fps
# Wayland / output=versus
SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=versus --noprimaryconf #=> 28.3
```
```
# native X11 / output=texture texture_renderer=opengl
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture -set texture_renderer=opengl --noprimaryconf # ==> 42.9fps
# native X11 / output=texturenb texture_renderer=opengl
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture -set texture_renderer=opengl --noprimaryconf # ==> 41.1fps

# native X11 / output=texture texture_renderer=software
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texture -set texture_renderer=software --noprimaryconf # ==> 21.2fps
# native X11 / output=texturenb texture_renderer=software
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=texturenb -set texture_renderer=software --noprimaryconf # ==> 38.8fps

# native X11 / output=opengl
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=opengl --noprimaryconf # ==> 42.4fps
# native X11 / output=openglnb
$ SDLAUDIODRIVER=pipewire SDL_VIDEODRIVER=x11 ./build/release/dosbox -set core=dynamic -set cycles=max -set output=openglnb --noprimaryconf # ==> 43.3fps
```

**Comment by runlevel5** [comment]
The best FPS is around 43fps. What's your max FPS @classilla?
