### PR TITLE
Implement Voodoo usability fixes

### LINKED ISSUE #2803: Voodoo usability fixes
Extracted the low-hanging fruit fixes from https://github.com/dosbox-staging/dosbox-staging/issues/2770#issuecomment-1697213334 for you @kcgen if you happen to have the capacity to fix these for 0.81.0.

- Make `dos_rate = auto` set 60 Hz in Voodoo rendering mode.
- If the user customizes `dos_rate`, then the Voodoo rendering should run at that rate too.
- Set `voodoo_memsize = 4` as default to avoid crashes in some games (e.g., Carmageddon, Screamer Rally)
 - standardize voodoo conf settings:

    ```ini
    [voodoo]
    voodoo = on(*) / off
    voodoo_memsize = 4(*) / 12
    # emulate either 4 MB or 12 MB of combined memory allocated
    # to The frame buffer processor (FBI) and texture mapping
    # unit(s) (TMU), as follows:
    #   - 4 MB = 2 MB FBI and one 2 MB TMU
    #   - 12 MB => 4 MB FBI and two 4 MB TMUs
  
    voodoo_multi_threaded = on(*) / off
    # use multiple threads to improve performance.
  
    voodoo_texture_smoothing = on / off(*) 
    # use bi-linear filtering to emulate the 3dfx's
    # texture smoothing effect. Recommended for fast
    # desktop-class CPUs otherwise framerate might suffer.
    ```

### PR DESCRIPTION
**Pull request by kcgen**
# Description

1. Standardizes the conf settings (defaults shown):

    ```ini
    [voodoo]
    voodoo                    = on
    voodoo_memsize            = 4
    voodoo_multithreading     = true
    voodoo_bilinear_filtering = false
    ```

3. Handles the Voodoo's default 60 Hz refresh rate.
4. Honors any custom `dos_rate` refresh rate while Voodoo is active.
5. ~~Includes the known-compatible `glide2x.ovl` in the Y: resources.~~

## Related issues

Fixes #2803

# Manual testing

- Tested all conf settings: valid and invalid.
- Confirmed Voodoo's 60 Hz refresh rate is used when the voodoo is overriding the VGA card's output.
- Confirmed custom `dos_rate` are honored by the Voodoo output
- Confirmed the bundled OVL is working as expected and being picked up by games, without any interaction on behalf of the user.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by shermp** [comment]
A quick test of Descent II seems to work ok. Settings appear to do what they should.

**Comment by Kappa971** [comment]
>     4. Includes the known-compatible glide2x.ovl in the Y: resources.

I don't know if this is necessary, every game seems to ship with its own `glide2x.ovl` driver (for Voodoo 1).

File: src/dosbox.cpp [hunk 1]
```diff
@@ -704,23 +704,32 @@ void DOSBOX_Init()
...
+	        "  12: 4 MB for the FBI and two TMUs, each with 4 MB.");
+
+	pbool = secprop->Add_bool("voodoo_multi_threaded", only_at_start, true);
+	pbool->Set_help("Use threads to improve 3dfx Voodoo performance (enabled by default).");
+
+	pbool = secprop->Add_bool("voodoo_texture_smoothing", only_at_start, false);
+	pbool->Set_help(
+	        "Use bi-linear filtering to emulate the 3dfx Voodoo's texture\n"
+	        "smoothing effect. Only suggested if you have a fast desktop-class\n"
+	        "CPU, as it can imapact framerates on slower systems (disabled by default).");
```
Comment (johnnovak) [inline src/dosbox.cpp:732]: Impact

File: contrib/resources/drives/y/3dfx/license.txt [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+right to install the enclosed software and related documentation (collectively,
+the "Materials") onto a single computer for your personal use.  You may not use,
+copy, modify, sell, transfer or disclose any part of the Materials except as
+provided in this Agreement. You may only use the Materials in connection with
+3dfx products.
+ 
+RESTRICTIONS:  You may not:
+1.	Sublicense the Materials;
+2.	Reverse engineer, decompile, or disassemble the enclosed software;
+3.	Use the Materials for any platform or products other
```
Comment (FeralChild64) [inline contrib/resources/drives/y/3dfx/license.txt:13]: > You may only use the Materials in connection with 3dfx products
> You may not (…) Use the Materials for any platform or products other than 3dfx products

Please do not include anything with such a restrictive license, or we will get kicked out of every single Linux distro, not to mention there is a non-zero chance of legal problems for the project.

If you really want to ship Glide with DOSBox, the best way would be to compile it from the sources https://github.com/sezero/glide - after studying the license https://github.com/sezero/glide/blob/glide-devel-sezero/LICENSE

Comment (Kappa971) [reply contrib/resources/drives/y/3dfx/license.txt:13]: If you install a 3DFX compatible DOS game from the CD-ROM (ISO, BIN CUE or original disc), it usually has the Voodoo 1 compatible `glide.ovl` driver, so you may not need all this.

Comment (kcgen) [reply contrib/resources/drives/y/3dfx/license.txt:13]: > we will get kicked out of every single Linux distro

DOSBox-X encodes glide2x.ovl [in a header](https://github.com/joncampbell123/dosbox-x/blob/master/src/builtin/glide2x.h).

This hasn't stopped the [AUR](https://aur.archlinux.org/packages/dosbox-x), [Debian](https://sources.debian.org/src/dosbox-x/2023.10.06+dfsg-1/), [FreeBSD](https://www.freshports.org/emulators/dosbox-x), [Gentoo overlays](https://gpo.zugaina.org/Overlays/guru/games-emulation/dosbox-x), [Homebrew](https://formulae.brew.sh/formula/dosbox-x), [MacPorts](https://ports.macports.org/port/dosbox-x/summary/), [NixOS](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/emulators/dosbox-x/default.nix), [Mandrake](https://github.com/OpenMandrivaAssociation/dosbox-x/tree/master), Raspbian (via Debian), [Slack](https://slackbuilds.org/repository/15.0/system/dosbox-x/), and [Termux](https://github.com/termux/termux-packages/tree/51a389360/x11-packages/dosbox-x) repository maintainers from bundling DOSBox-X:

But more specifically, repo maintainers will kick-out content they they don't like to keep a package.

For example, Debian's maintainer has 11 code patches that strip various features from DOSBox-X including: playing MIDI through the bundled FluidSynth, using the handful of freeDOS binaries, and even using FLAC and Opus audio tracks :grimacing: 

---

Even if we're OK with the above approach, I don't want fearful repo maintainers crippling the user experience, so I will attempt the compiled approach.

Thanks @FeralChild64!

Comment (kcgen) [reply contrib/resources/drives/y/3dfx/license.txt]: Dropped, will re-add using the compiled approach.

Comment (johnnovak) [reply contrib/resources/drives/y/3dfx/license.txt]: Distro maintainers need bigger balls 😎

**Comment by kcgen** [comment]
> I don't know if this is necessary, every game I've tested seems to ship with its own glide2x.ovl driver (for Voodoo 1).

It's possible that web-hosted games have simply stuffed these OVL files into zips so they work out-of-the-box in emulation environments.

In a real DOS environment, users installed and managed their board's specific drivers. The driver installation was for the entire PC (not just per-game), and the location was added it to `PATH`. This allowed all 3dfx games to find and use the user's one and only driver.

At the time, vendors were constantly pushing out updates to BBSes and services like AOL and the early web.  Keen users kept their drivers up to date because there were plenty of bugs in those early versions.

Some vendors were worse than others (and had terrible drivers) - so those users often turned to 3dfx's reference drivers or modded drivers. (I owned a Monster Voodoo 2 back then and did all of the above).

> I see the Voodoo 2 driver is included in this PR, but DOSBox Staging emulates Voodoo 1 (right?) and DOS games are typically for Voodoo 1.

The DOSBox Staging Voodoo implementation identifies itself to the drivers as Voodoo 1, however at the time drivers could check for features - and there [were hardware modifications](https://www.voodooalert.de/board/forum/index.php?thread/23413-custom-voodoo-1-with-2x-tmus-and-sli-capabilities/) to augment the Voodoo 1 with a second texture unit (TMU). 

When you select 12 MB in the configuration, it creates this "super Voodoo 1" board with dual TMUs.

**Comment by kcgen** [comment]
3dfx's Voodoo 1 and 2 drivers kept improving with bug fixes and performance improvement, and were common for the Voodoo 1 and 2 up through version 2.43, which was basically the pinnacle (or end-of-the-line) in terms of Voodoo 1 support:

[:file_folder: **glide2x-dos-driver-2.43.zip** ](https://github.com/dosbox-staging/dosbox-staging/files/13301734/glide2x-dos-driver-2.43.zip)

With @GranMinigun and @Grounded0's help, countless subsequent versions (2.46, 2.48, 2.50, 2.56, etc..) were downloaded and checked, only to see that they are unable to initialize the voodoo 1 board or simply have the games transparently fallback to software rendering.

2.43 is basically like service pack 3 for Windows XP : it has all the last-stage fixes.

**Comment by kcgen** [comment]
Here's 3dfx's April 1998 website snapshot:

https://web.archive.org/web/19980421230254/http://www.3dfx.com/download/sdk/index.html

Less that 3 years later, to stay afloat, 3dfx sold its assets to NVidia, however 3dfx still was trying to trying to support their aging product line. They eventually stopped supporting them early 2001 and filed for bankruptcy late 2002. So that was the end of the line, 21 years ago!

**Comment by Kappa971** [comment]
> It's possible that web-hosted games have simply stuffed these OVL files into zips so they work out-of-the-box in emulation environments.

I downloaded the images of the games from the Myrient site (Screamer Rally, Screamer 2 and Carmageddon). Screamer Rally detects 3DFX Voodoo 1 during installation (it doesn't recognize Voodoo 2) and installs the necessary files in the installation folder (including `glide.ovl` for Voodoo 1, I don't know which version). It also contains the 3dfx patch for Screamer 2 which installs the 3dfx executable and `glide.ovl.`
I don't know if it was a coincidence with these two games, but I would think that all 3dfx DOS games could locally install the 3dfx driver included on the CDROM for Voodoo 1 in the game folder.
Just so you know, maybe someone else could confirm with other games.

I imagine the 90's (in the Voodoo 1 era 1996-1998) where few people had internet, maybe people had outdated drivers in their systems (installed from the video card CD) and maybe game developers wanted to make sure they were using a 3dfx driver that would work fine with their game (but this is just my guess).

> 3dfx kept improving the Voodoo 1 drivers through release 2.43, which was basically the pinnacle (or 
> end-of-the-line) in terms of Voodoo 1 support: 📁 glide2x-dos-driver-2.43.zip

>With @GranMinigun and @Grounded0's help, countless subsequent versions (2.46, 2.48, 2.50, 2.56, >etc..) were downloaded and checked, only to see that they are unable to initialize the voodoo 1 board >or simply have the games transparently fallback to software rendering.
>
>So 2.43 is basically like service pack 3 for Windows XP : it has all the late-stage fixes.

If this driver doesn't cause problems with games (and improves performance), I'm in favor of including it. I guess the driver included in the game folder needs to be removed, right?

However I noticed on 86Box that these games seem to be a bit fussy with the drivers, so perhaps this version 2.43 should be tested with the games first to see if it causes crashes, but if someone confirms that all 3dfx game CDROMs also include the driver, maybe it would be a waste of time, I don't know...

**Comment by kcgen** [comment]
> perhaps this version 2.43 should be tested with the games first to see if it causes crashes

I've tested it 2.43 specifically with all the DOS Voodoo games and demos, and confirmed there are no issues. These are screenshots using 2.43:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/0eaff1e6-80b6-4a93-81ed-f60857d84116

image0033-rendered
image0032-rendered
image0031-rendered
image0030-rendered
image0029-rendered
image0028-rendered
image0027-rendered
image0026-rendered
image0025-rendered
image0024-rendered
image0023-rendered
image0022-rendered
image0021-rendered
image0020-rendered
image0019-rendered
image0018-rendered
image0017-rendered
image0016-rendered
image0015-rendered
image0014-rendered
image0013-rendered
image0012-rendered
image0011-rendered
image0010-rendered
image0009-rendered
image0008-rendered
image0006-rendered
image0007-rendered
image0004-rendered
image0005-rendered
image0003-rendered
image0002-rendered
image0001-rendered

**Comment by kcgen** [comment]
@FeralChild64, 

I've got the glide DOS building working using 

```text
i586-pc-msdosdjgpp-gcc -o ../../../swlibs/newpci/pcilib/fxpci.o -Wall -I. -I../../incsrc -I../../init -I../../init/initvg -I../../../swlibs/fxmisc -I../../../swlibs/newpci/pcilib -I../../../swlibs/fxmemmap -D__DOS__ -D__DOS32__ -DINIT_DOS -DGLIDE_HARDWARE -DGLIDE_DEFAULT_GAMMA=1.3f -DGLIDE_LIB=1 -DSST1 -DGL_X86 -O1 -ffast-math -mtune=pentium -c ../../../swlibs/newpci/pcilib/fxpci.c
i586-pc-msdosdjgpp-gcc -o ../../../swlibs/newpci/pcilib/fxdpmi2.o -Wall -I. -I../../incsrc -I../../init -I../../init/initvg -I../../../swlibs/fxmisc -I../../../swlibs/newpci/pcilib -I../../../swlibs/fxmemmap -D__DOS__ -D__DOS32__ -DINIT_DOS -DGLIDE_HARDWARE -DGLIDE_DEFAULT_GAMMA=1.3f -DGLIDE_LIB=1 -DSST1 -DGL_X86 -O1 -ffast-math -mtune=pentium -c ../../../swlibs/newpci/pcilib/fxdpmi2.c
i586-pc-msdosdjgpp-ar rus ../../lib/sst1/libglide2x.a gsplash.o g3df.o gu.o guclip.o gpci.o gump.o diglide.o disst.o ditex.o gbanner.o gerror.o gmovie.o digutex.o ddgump.o gaa.o gdraw.o gglide.o glfb.o gsst.o gtex.o gtexdl.o gutex.o gxdraw.o cpuid.o xdraw.o ../../init/init.o ../../init/gdebug.o ../../init/vgdrvr.o ../../init/initvg/gamma.o ../../init/initvg/dac.o ../../init/initvg/video.o ../../init/initvg/parse.o ../../init/initvg/sli.o ../../init/initvg/util.o ../../init/initvg/info.o ../../init/initvg/print.o ../../init/initvg/sst1init.o ../../../swlibs/newpci/pcilib/sst1_pci.o ../../../swlibs/newpci/pcilib/fxmsr.o ../../../swlibs/newpci/pcilib/fxpci.o ../../../swlibs/newpci/pcilib/fxdpmi2.o
dxe3gen -o ../../lib/sst1/glide2x.dxe -Y ../../lib/sst1/libglide2i.a -E _gr -E _gu  -E _ConvertAndDownloadRle -U gsplash.o g3df.o gu.o guclip.o gpci.o gump.o diglide.o disst.o ditex.o gbanner.o gerror.o gmovie.o digutex.o ddgump.o gaa.o gdraw.o gglide.o glfb.o gsst.o gtex.o gtexdl.o gutex.o gxdraw.o cpuid.o xdraw.o ../../init/init.o ../../init/gdebug.o ../../init/vgdrvr.o ../../init/initvg/gamma.o ../../init/initvg/dac.o ../../init/initvg/video.o ../../init/initvg/parse.o ../../init/initvg/sli.o ../../init/initvg/util.o ../../init/initvg/info.o ../../init/initvg/print.o ../../init/initvg/sst1init.o ../../../swlibs/newpci/pcilib/sst1_pci.o ../../../swlibs/newpci/pcilib/fxmsr.o ../../../swlibs/newpci/pcilib/fxpci.o ../../../swlibs/newpci/pcilib/fxdpmi2.o
rm fxgasm.exe
make[1]: Leaving directory '/nvme1/src/glide/glide2x/sst1/glide/src'
```

It runs clean without errors, and produces:

```
sst1/lib/
└── sst1
    ├── glide2x.dxe
    ├── keep.me
    ├── libglide2i.a
    └── libglide2x.a
```

Unfortunately the `glide2x.dxe` isn't  files aren't named `glide2x.ovl`

**Comment by kcgen** [comment]
Ready for review/merge.

If and how we give users the recommended 2.43 driver (or if we build our own), will have to be a separate topic.

**Comment by Grounded0** [comment]
At least we managed to hunt down those great Glide 2.43 DOS drivers. This can now progress.

**Comment by Kappa971** [comment]
Bilinear texture filtering no longer works on my system (Windows 11).

**Comment by kcgen** [comment]
@Kappa971 
> Bilinear texture filtering no longer works on my system (Windows 11).

Thanks for testing - fix inbound.

**Comment by Kappa971** [comment]
> @Kappa971
> 
> > Bilinear texture filtering no longer works on my system (Windows 11).
> 
> Thanks for testing - updated pushed.

It works now, thanks.

I tried a PS1 emulator that uses the GPU to apply some improvements to games such as True Color 24 bit (removal of dithering, even in movies), Image scaling (e.g. 5x is 1080p) in 3D games, Hack Widescreen to display the game in 16:9 or other aspect ratios (but this is not stable yet and I don't know if it ever will be), Antialiasing, things that would also look very nice in DOSBox Staging for 3DFX games (would bring these games into the 21st century, which I think isn't possible with 2D or software rendering games) as well as performance improvements. 

I hope someone will work on it one day.

**Comment by MasterO2** [comment]
So @kcgen, is this PR ready to go?

**Comment by kcgen** [comment]
> So @kcgen, is this PR ready to go?

Yup, it's ready.

**Review by Kappa971 — APPROVED** [review]
Thanks @kcgen 🙂

One last thing, I noticed that CD Audio playback is related to emulation speed. You can easily hear it in the Carmageddon menu, the music slows down and returns to normal speed.
Maybe it's something to improve for 0.82

File: src/hardware/voodoo.cpp [hunk 3]
```diff
@@ -7791,7 +7765,11 @@ void VOODOO_Init(Section* sec)
 	voodoo_current_lfb = PciVoodooLfbBase;
 	voodoo_pagehandler = &voodoo_init_pagehandler;
 
-	vperf = static_cast<PerformanceFlags>(section->Get_int("voodoo_perf"));
-
 	PCI_AddDevice(new PCI_SSTDevice());
+
+	// Log the startup
+	LOG_MSG("VOODOO: Initialized with %s MB of RAM, %smulti-threading, and %stexture smoothing",
```
Comment (johnnovak) [inline src/hardware/voodoo.cpp:7771]: multithreading (no dash, one word)

https://en.wikipedia.org/wiki/Multithreading_(computer_architecture)

File: src/dosbox.cpp [hunk 4]
```diff
@@ -704,23 +704,32 @@ void DOSBOX_Init()
...
-	               "   3:  All optimizations (both 1 and 2).\n"
-	               "Note: Voodoo emulation is software-based and does not use host-level\n"
-	               "      OpenGL calls.");
+	        "Set the amount of video memory for 3dfx Voodoo graphics, either 4 or 12 megabytes.\n"
+	        "The memory is used by the Frame Buffer Interface (FBI) and Texture Mapping Unit (TMU)\n"
+	        "as follows:\n"
+	        "   4: 2 MB for the FBI and one TMU with 2 MB (default)\n"
+	        "  12: 4 MB for the FBI and two TMUs, each with 4 MB.");
+
+	pbool = secprop->Add_bool("voodoo_multi_threaded", only_at_start, true);
```
Comment (johnnovak) [inline src/dosbox.cpp:725]: We have `voodoo_texture_smoothing`, so let's do `voodoo_multithreading` ([multithreading](https://en.wikipedia.org/wiki/Multithreading_(computer_architecture)) is one word)

File: src/hardware/voodoo.cpp [hunk 5]
```diff
@@ -3003,33 +3004,9 @@ iterated W    = 18.32 [48 bits]
...
-	case PerformanceFlags::All:
-		return ", multi-threading, and no biliear filtering";
-	}
-	assert(false);
-	return "unknown performance flag";
-}
-
-static PerformanceFlags vperf = {};
+static auto vtype = VOODOO_1;
+static auto voodoo_multi_threaded    = true;
```
Comment (johnnovak) [inline src/hardware/voodoo.cpp:3008]: `voodoo_multithreading`

File: include/vga.h [hunk 6]
```diff
@@ -274,6 +274,12 @@ struct VgaDraw {
 
 	double host_refresh_hz    = RefreshRateHostDefault;
 	double dos_refresh_hz     = RefreshRateDosDefault;
+
+	// The override rate corresponds to the override VGA mode where another
+	// device can takeover video output in place of the VGA card, such as
```
Comment (johnnovak) [inline include/vga.h:279]: take over

File: src/dosbox.cpp [hunk 7]
```diff
@@ -704,23 +704,32 @@ void DOSBOX_Init()
...
+	pbool->Set_help("Use threads to improve 3dfx Voodoo performance (enabled by default).");
+
+	pbool = secprop->Add_bool("voodoo_texture_smoothing", only_at_start, false);
+	pbool->Set_help(
+	        "Use bi-linear filtering to emulate the 3dfx Voodoo's texture\n"
```
Comment (johnnovak) [inline src/dosbox.cpp:730]: bilinear (no dash, on word)

File: src/dosbox.cpp [hunk 8]
```diff
@@ -704,23 +704,32 @@ void DOSBOX_Init()
...
+	        "smoothing effect. Only suggested if you have a fast desktop-class\n"
+	        "CPU, as it can impact framerates on slower systems (disabled by default).");
```
Comment (johnnovak) [inline src/dosbox.cpp:732]: frame rate (two words)

File: src/hardware/vga.cpp [hunk 9]
```diff
@@ -262,7 +262,10 @@ double VGA_GetPreferredRate()
 {
 	switch (vga.draw.dos_rate_mode) {
 	case VgaRateMode::Default:
-		return vga.draw.dos_refresh_hz;
+		// If another device is overriding our VGA card, then use it's
```
Comment (johnnovak) [inline src/hardware/vga.cpp:265]: its (no hyphen)

File: src/hardware/vga_draw.cpp [hunk 10]
```diff
@@ -2877,12 +2877,14 @@ void VGA_KillDrawing(void) {
 	if (!vga.draw.vga_override) RENDER_EndUpdate(true);
 }
 
-void VGA_SetOverride(bool vga_override) {
+void VGA_SetOverride(bool vga_override, const double override_refresh_hz)
```
Comment (johnnovak) [inline src/hardware/vga_draw.cpp:2880]: const bool?

File: src/hardware/voodoo.cpp [hunk 11]
```diff
@@ -3003,33 +3004,9 @@ iterated W    = 18.32 [48 bits]
...
-		return " and no bilinear filtering";
-	case PerformanceFlags::All:
-		return ", multi-threading, and no biliear filtering";
-	}
-	assert(false);
-	return "unknown performance flag";
-}
-
-static PerformanceFlags vperf = {};
+static auto vtype = VOODOO_1;
```
Comment (johnnovak) [inline src/hardware/voodoo.cpp:3007]: voodoo_type ?

File: src/hardware/voodoo.cpp [hunk 12]
```diff
@@ -7291,15 +7268,15 @@ static bool Voodoo_GetRetrace() {
 static double Voodoo_GetVRetracePosition() {
 	// TODO proper implementation
 	const auto time_in_frame = PIC_FullIndex() - v->draw.frame_start;
-	const auto vfreq         = v->draw.vfreq;
-	if (vfreq <= 0) {
+	const auto frame_period_ms = v->draw.frame_period_ms;
+	if (frame_period_ms <= 0) {
```
Comment (johnnovak) [inline src/hardware/voodoo.cpp:7272]: Nice, `frame_period_ms` tells me exactly what I'm dealing with, as opposed to the vague unknown quantity called `vfreq` 😄

File: src/hardware/voodoo.cpp [hunk 13]
```diff
@@ -7336,18 +7313,28 @@ static void Voodoo_UpdateScreen()
...
+		// rendering. This is equivalent to when the Voodoo card
+		// switched from passive pass-thru mode to active output mode.
+		//
+		VGA_SetOverride(true, VoodooDefaultRefreshRateHz);
+
+		v->draw.frame_period_ms = 1000.0 / VGA_GetPreferredRate();
+		//
+		// The user's 'dos_rate' preference controls the preferred rate.
+		// When set to 'auto', we'll get back the Voodoo default rate.
+		// Otherwise we'll get the user;'s custom rate.
```
Comment (johnnovak) [inline src/hardware/voodoo.cpp:7335]: user's (remove ;)

File: src/dosbox.cpp (hunk 7 above)
Comment (johnnovak) [reply src/dosbox.cpp:730]: I'm wondering if this should be simply called `voodoo_bilinear_filtering` instead of introducing our own more abstract name to hide this technical term?

Comment (kcgen) [reply src/dosbox.cpp:730]: Yup; let's go w/ `voodoo_bilinear_filtering`!

File: src/hardware/voodoo.cpp (hunk 11 above)
Comment (kcgen) [reply src/hardware/voodoo.cpp:3007]: Gonna leave it for now :-)

**Comment by kcgen** [comment]
Thanks for the detailed review, @johnnovak! Updates in and tested.
Also updated the PR text body to reflect the new conf settings.

File: src/dosbox.cpp (hunk 7 above)
Comment (johnnovak) [reply src/dosbox.cpp]: Sounds good!

**Review by johnnovak — APPROVED** [review]
Nice one @kcgen 🚀

**Comment by Torinde** [comment]
> One last thing, I noticed that CD Audio playback is related to emulation speed. You can easily hear it in the Carmageddon menu, the music slows down and returns to normal speed. Maybe it's something to improve for 0.82 (if possible).

If CD Audio is being reworked - maybe a good opportunity to add multithreading for it? 

In general, I would like to track somewhere which code parts already have multithreading, which will benefit from that, for which that's irrelevant, e.g. screenshot, video/audio recording, OPL3, disk I/O, OSD, 3dfx, SVGA, etc.

**Comment by weirddan455** [comment]
> > One last thing, I noticed that CD Audio playback is related to emulation speed. You can easily hear it in the Carmageddon menu, the music slows down and returns to normal speed. Maybe it's something to improve for 0.82 (if possible).
> 
> If CD Audio is being reworked - maybe a good opportunity to add multithreading for it?
> 
> In general, I would like to track somewhere which code parts already have multithreading, which will benefit from that, for which that's irrelevant, e.g. screenshot, video/audio recording, OPL3, disk I/O, OSD, 3dfx, SVGA, etc.

This sounds very strange to me.  CD Audio should not have the ability to "speed up" or "slow down".  On DOS-era computers, CD Audio is not even processed by the CPU.  There's an analogue audio cable that runs from the CD drive to the sound card.  The game can issue start/stop/pause commands to the CD drive but that's about it.

Multithreading CD Audio could be helpful but I don't think it would solve this particular problem.  When you have problems with audio code getting stalled (which threading could help with), it leads to gaps in the audio which present as very noticeable stutters and pops.  The only way you should get audio playing "too fast" or "too slow" is if you get the sample rate incorrect.

@Kappa971 If you could create an issue for this I'll look into it.  I need reproduction steps and also need to know what type of files you are using for CD audio.

**Comment by kcgen** [comment]
Voodoo is unfortunately the only emulated device that can can block the 1ms tick loop for the entire 1ms (and more). 

All the devices consume just a small fraction of the 1ms pie, leaving the remaining portion for CPU emulation.

So I think you're right, @weirddan455 , that it's like repeated drop out and gaps that are the cause.

@Kappa971 , if you incrementally dial down cycles (say in the 10k or 20k range), can you find a point where CDDA is able to "keep up" with real-time? Yes.. 3dfx performance will suffer badly, but this is just for testing. 

@Kappa971 , in your ticket, can you also make a desktop recording using 3rd party capture software - like nividia or OBS?

This should be able to capture it.

**Comment by weirddan455** [comment]
>  So I think you're right, @weirddan455 , that it's likely repeated drop out and gaps that are the cause.

@Kappa971 was saying the issue is the music playing too quickly/slowly.  That's very different than audio drop out which sounds more like popping/stuttering.  But yeah, a recording and more details on a separate issue would be helpful.  This isn't related to this PR as far as I can tell.

**Comment by Kappa971** [comment]
Let me explain in a simpler way what happens:
If the 3dfx emulation is at full speed (60 fps) the CD Audio (music) runs at normal speed. If the emulation drops below 60 fps, the music slows down. That's all.
I'm using audio files in OGG format, I haven't tried with WAV files. It could be that this behavior is unavoidable, I don't know, but I've reported it here in case something can be done about it.

With my CPU I can set around 140-150k cycles with the 3dfx emulation to play at full speed with decent performance, but I noticed that in the Carmageddon menu the emulation drops below 100% (50-55 fps) and the music slows down. The same thing sometimes happens with the pause menu of Screamer Rally. In practice it seems that the game menus are more challenging to emulate than the actual game 😆

**Comment by Grounded0** [comment]
We recently introduced a fix to make sure Carmageddon doesn't stop playing its CD audio soundtrack. Probably good idea to look at it. This can be merged.

**Comment by weirddan455** [comment]
Ok fine, I'll make the issue thread myself.  #3110

These "drive by comments" in completely unrelated issues and PRs are not the way to get things fixed.  This PR is about to get merged and these comments will be forgotten.  In my opinion, if there's no issue ticket, there's no issue.

**Comment by johnnovak** [comment]
Note for the future @Kappa971: please raise separate issue tickets for new issues and include all relevant detail there.
