### PR TITLE
Fix console color after restart

### LINKED ISSUE #3346: Restart facility is unstable when launched from Windows GUI
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1, 0.81-RC1, 0.81-RC2

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

AMD Ryzen 9 3900X, NVidia GeForce RTX 3070, 32GB RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using the provided Restart feature (default [Ctrl]+[Alt]+[Home]) results in undesirable behaviour should DOSBox Staging be launched directly from the Windows GUI. It does not seem to make any difference whether it is launched directly via the executable or through a shortcut, or whether this is done using the Explorer or the "Run" command.

On the first attempt it presents the following error in the client:

> Illegal command: dosbox.exe
> Preventing an early 'exit' call from terminating.

An accompanying warning in the console indicates:

> SHELL: Exit blocked because program quit after only 0.5 seconds

Any subsequent attempt to Restart will result in client exiting entirely, with the following error in the console (before it also closes):

> ABORT: Restarting failed

Also worth mentioning is that the inclusion of @ symbols or ECHO OFF in the [autoexec] section of the config file can result in the first Restart no longer showing system text, with ECHO OFF having a 100% chance of this occurring. A caret is present, all user-entered text works correctly and the environment itself appears otherwise unaffected, including text-based software (such as the exit screen on many Shareware titles), but no text-based feedback is presented from the DOS environment. This also appears to suppress the Shell warning.

Note that launching from a console (such as Windows Terminal) does _not_ exhibit this (mis)behaviour - including the missing text feedback - and will happily Restart as many times as you care to try. Execution via a batch file also works as expected, even when invoked via the Windows GUI. Both of these must take the current directory into consideration when relative paths are used in the DOSBox config, however.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch DOSBox Staging from the Windows GUI.
2. Trigger the Restart feature ([Ctrl]+[Alt]+[Home]).
3. <optional> Trigger the Restart feature a second time.

### Download URL of affected game or software

_No response_

### Your configuration

```ini
Configuration used is the default, as generated by the respective versions of DOSBox Staging.
```

### Provide a Log

```text
https://gist.github.com/Asterchades/7c9f0c2e7ae57c40c8c4ab494d6aa4fd
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

Regression from PR #3349 I was under the incorrect assumption that the Windows console was being created via an `AllocConsole` call here:

https://github.com/dosbox-staging/dosbox-staging/blob/0d3c555cb16028face41c0546326503b0a409229/src/gui/sdlmain.cpp#L4841-L4864

It turns out this is not the case.  Staging is being built as a console app meaning Windows creates a console for us before we even get to main.  This means on first run, the `AllocConsole` call fails because we already have a console.  After restart, we were successfully creating a console here but it was probably not using the correct mode for handling color escape codes (https://learn.microsoft.com/en-us/windows/console/setconsolemode).  There's also the issue that we're creating this console after Loguru initializes so the beginning of the logs are never visible.

We probably want to re-visit the above code in the future but the simple fix is to just use the `CREATE_NEW_CONSOLE` flag instead of `DETACHED_PROCESS`.  This both does not inherit the old console and creates a new one for the child process to use.

## Related issues

Fixes #3346

# Manual testing

Used Ctrl + Alt + Home to restart and verified the console has color afterwards.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]

File: src/gui/sdlmain.cpp [hunk 1]
```diff
@@ -4567,8 +4567,9 @@ void restart_program(std::vector<std::string> & parameters) {
 
 	const WINBOOL inherit_handles = FALSE;
 
-	// DETACHED_PROCESS fixes https://github.com/dosbox-staging/dosbox-staging/issues/3346
-	const DWORD creation_flags = DETACHED_PROCESS;
+	// CREATE_NEW_CONSOLE fixes a bug where the parent process exiting kills the child process.
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:4570]: Very economical with words, @weirddan455 😄 Can you add this at least to explain the "why" behind it?

```
This can manifest when you use the "restart" hotkey action to restart DOSBox.
```

Comment (johnnovak) [reply src/gui/sdlmain.cpp:4570]: Thanks man 😄 Just thinking of future maintainers, that's all.
