### PR TITLE
Replace use of `stat` in imgmount

### LINKED ISSUE #3464: imgmount (-fs none) is broken in clang-cl (and maybe msvc)
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.82.0-alpha-232-gf4452209a

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When running `main` compiled with Visual Studio (clang-cl), an imgmount command like `imgmount 2 "C:\DiskImages\db-staging-98se.img" -fs none -t hdd -size 512,63,255,1023` fails with the following message in dosbox: `The image must be on a host or local drive`.

CD images mount correctly.

This does not happen when dosbox-staging is compiled with MSYS2. 

I'm pretty sure I've narrowed this down to lines 294-296 of `program_imgmount.cpp`:
```cpp
// Test if input is file on virtual DOS drive.
constexpr int posix_success = 0;
struct stat test;
if (posix_success != stat(temp_line.c_str(), &test)) {
```

It appears that the MSYS2 clang version of `stat.h` includes a typedef for `stat` from `_stat64`, whereas the VS `stat.h` does not. This *might* only be an issue for large files, I haven't tested with smaller images.

### Steps to reproduce the behaviour.

1. Run Dosbox-staging compiled with VS clang-cl
2. Attempt to mount a raw disk image with  `imgmount 2 "C:\DiskImages\db-staging-98se.img" -fs none -t hdd -size 512,63,255,1023`
3. The image fails to mount with the `The image must be on a host or local drive`

### Download URL of affected game or software

_No response_

### Your configuration

```ini
N/A
```

### Provide a Log

```text
2024-03-02 11:27:27.373 | IMGMOUNT: Path 'C:\DiskImages\db-staging-98se.img' found
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by shermp**
# Description

Replace use of `stat` in `imgmount` with `path_exists` and `is_directory`, which fixes mounting large disk image files with Visual Studio builds.

## Related issues
Fixes #3464 

# Manual testing

If you don't already have one, create a large `img` file (tested with 8GB image).

Start Dosbox-Staging, and enter the following imgmount command:
```
imgmount 2 "<path-to-disk-image>" -fs none -t hdd -size <size-for-disk-image>
```
Dosbox should show the message `Drive number 2 mounted as <image-path>`.

Also check the non existing file case:
```
imgmount 2 "<path-to-nonexisting-file>" -fs none -t hdd -size 512,63,255,1023
```
Dosbox should show an error message.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by shermp** [comment]
This whole bit of code could probably use a refactor at some point, but this at least fixes the linked issue.

File: src/dos/program_imgmount.cpp [hunk 1]
```diff
@@ -342,7 +340,7 @@ void IMGMOUNT::Run(void)
 				        drive_letter(dummy));
 			}
 		}
-		if (S_ISDIR(test.st_mode)) {
+		if (is_directory(temp_line)) {
 			WriteOut(MSG_Get("PROGRAM_IMGMOUNT_MOUNT"));
 			return;
 		}
```
Comment (weirddan455) [inline src/dos/program_imgmount.cpp:346]: Looks like you fixed a bug here too.  Before, if that first `stat` call failed, the value of `struct stat test` is possibly undefined (we didn't zero clear it).

**Review by weirddan455 — APPROVED** [review]
Looks like a good change to me.  Yeah this whole function is kind of hard to read but it doesn't have to be refactored right now if you don't feel like it.

**Comment by shermp** [comment]
Um... Oops, I think I got this wrong, and I'm not sure how this works. Give me a few minutes to fix my boo-boo's.

**Comment by weirddan455** [comment]
Oh you got the conditions inverted.  I missed that too.  Should be checking if the path doesn't exist.

**Comment by shermp** [comment]
Ok, I've fixed my conditions. I've also tested the file not exist path (I updated the PR description).

@weirddan455 can you please test on Linux to make sure nothing has broken there?

**Comment by weirddan455** [comment]
Tested `imgmount` command on Linux and it looks good.

**Comment by shermp** [comment]
> Tested `imgmount` command on Linux and it looks good.

Thanks. Merging.

**Comment by shermp** [comment]
Actually, someone else needs to merge. I do not have permissions to do so.

**Comment by weirddan455** [comment]
You pushed again, restarting CI.  The button is grayed out for me too until that finishes.
