### PR TITLE
Retain CD-ROM behaviour for directories mounted with `-t cdrom`

### LINKED ISSUE #4831: `MOUNT` regression when mounting directories as CD-ROMs
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

_No response_

### What operating system are you using?

macOS (Apple Silicon)

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

I've noticed a `MOUNT` regression with my existing Discworld installation that has been running fine until now. After some bisecting it turns out the culprit is @dividebysandwich's `MOUNT` & `IMGMOUNT` merging work:

```
commit 7bb519bc8f604c54361ffeadf5cf1a9fcd501215 (HEAD)
Author: dividebysandwich <josef.jahn@gmail.com>
Date:   Tue Jan 6 14:02:58 2026 +0100

    Implement unified mount command
```

@dividebysandwich Would you please be able to take a look and fix the regression? I've included detailed repro steps and I've tested them on Windows and macOS. Please follow them to the letter.

### Steps to reproduce the behaviour

1. Download the Discworld CD image [from here](https://archive.org/details/discworld-usa/) (probably any Discworld CD image will do, but I've tested with this one).
2. Create the following directory structure:
```
  discworld-test
    +-- drives
    |     +-- c
	|
    +-- cd
```

3. Move the Discworld CUE/BIN pair into `discworld-test`.
4. Start Staging from `discworld-test`, then mount `cd` as D: (`-freesize 1000` is important), mount the disk image as E:, and copy its contents into D:

```
imgmount e *.cue -t iso
mount d cd -freesize 1000
xcopy e: d: /s
```

5. Now install Discworld to drive C:. Select **No Sound / No Midi Music** — it doesn't matter for the test.

```
d:
disc.bat
```

6. Exit Staging, then create a local `dosbox.conf` with the following content:

```ini
[autoexec]
mount d cd -t cdrom
c:
cd discwld.cd
call disc
```

7. Start Staging again — the game should start up.
  - With 0.82.2 and prior to 7bb519bc8f604c54361ffeadf5cf1a9fcd501215 it does
  - Starting from 7bb519bc8f604c54361ffeadf5cf1a9fcd501215 (the commit that merges MOUNT with IMGMOUNT) and on `main`, it doesn't — it just displays the following error:

Image

### Download URL of affected game or software

https://archive.org/details/discworld-usa/

### Your configuration

```ini
[autoexec]
mount d cd -t cdrom
c:
cd discwld.cd
call disc
```

### Provide a log

N/A

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by dividebysandwich**
# Description

Fixed CD-ROM images not being registered with MSCDEX, and initialized MediaId for iso images.

## Related issues

Fixes #4831

# Manual testing

* Follow reproduction steps in #4831
* ```mount d cd -t cdrom``` --> directory --> cdromDrive registered with MSCDEX → Discworld will detect the CD
* ```mount d cd -t iso``` --> directory --> same cdromDrive path
* ```mount d game.iso -t iso``` --> file --> unchanged, goes through MountImageIso as before
* ```mount d game.iso -t cdrom``` --> file --> unchanged (cdrom / iso alias), goes through MountImageIso

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [X] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [X] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [X] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [X] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [X] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/tools/compile-commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [X] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/dos/programs/mount.cpp [hunk 1]
```diff
@@ -595,7 +595,8 @@ bool MOUNT::ParseGeometry(MountParameters& params)
 			}
 		}
 	} else if (params.type == "iso") {
-		str_size = "2048,1,65535,0";
+		str_size       = "2048,1,65535,0";
+		params.mediaid = MediaId::HardDisk;
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:604]: This seemed weird to me to use `MediaId::HardDisk` for the `iso` type, so I compared it against the old `MOUNT` implementation and it's the same there.

Could you put a comment there that we're carrying this weirdness over from the old `MOUNT` implementation and we'll need to investigate this deeper in the future.? HDD media ID doesn't make much logical sense for the "iso" type.

File: src/dos/programs/mount.cpp [hunk 2]
```diff
@@ -1045,6 +1046,38 @@ void MOUNT::MountLocal(MountParameters& params, const std::string& local_path)
 			safe_strcpy(newdrive->curdir, ldp->curdir);
 		}
 		Drives.at(drive_index(params.drive)) = nullptr;
+	} else if (params.type == "iso") {
+		// Mount a host directory as a CD-ROM drive. This is used for
+		// the legacy "mount X dir -t cdrom" syntax, and also when the
+		// user passes "-t iso" with a directory path instead of an
+		// image file.
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Cannot this comment be simplified?

> This is used for the legacy "mount X dir -t cdrom" syntax (or "-t iso") when we mount a directory instead of a disk image.

File: src/dos/programs/mount.cpp [hunk 3]
```diff
@@ -1045,6 +1046,38 @@ void MOUNT::MountLocal(MountParameters& params, const std::string& local_path)
...
+		switch (error) {
+		case 0: msg_id = "MSCDEX_SUCCESS"; break;
+		case 1: msg_id = "MSCDEX_ERROR_MULTIPLE_CDROMS"; break;
+		case 2: msg_id = "MSCDEX_ERROR_NOT_SUPPORTED"; break;
+		case 3: msg_id = "MSCDEX_ERROR_PATH"; break;
+		case 4: msg_id = "MSCDEX_TOO_MANY_DRIVES"; break;
+		case 5: msg_id = "MSCDEX_LIMITED_SUPPORT"; break;
+		default: msg_id = "MSCDEX_UNKNOWN_ERROR"; break;
+		}
+		WriteOut(MSG_Get(msg_id));
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: In `MountImageIso()` in this same file we have this:

```cpp
		// Error handling switch
		const char* msg_id = nullptr;
		switch (error) { //-V785
		case 0: break;
		case 1: msg_id = "MSCDEX_ERROR_MULTIPLE_CDROMS"; break;
		case 2: msg_id = "MSCDEX_ERROR_NOT_SUPPORTED"; break;
		case 3: msg_id = "MSCDEX_ERROR_OPEN"; break;
		case 4: msg_id = "MSCDEX_TOO_MANY_DRIVES"; break;
		case 5: msg_id = "MSCDEX_LIMITED_SUPPORT"; break;
		case 6: msg_id = "MSCDEX_INVALID_FILEFORMAT"; break;
		default: msg_id = "MSCDEX_UNKNOWN_ERROR"; break;
		}

		if (msg_id) { //-V547
			NOTIFY_DisplayWarning(Notification::Source::Console,
			                      "MOUNT",
			                      msg_id);
		}
```

Can you please extract the error code to message ID conversion to a static function, and reference it in both places?

Also, can you use `NOTIFY_DisplayInfoMessage()` (for response code 0) and `NOTIFY_DisplayWarning()` (for response codes 1–6) instead of `WriteOut()` in this function?

File: src/dos/programs/mount.cpp [hunk 4]
```diff
@@ -1083,7 +1116,8 @@ void MOUNT::MountLocal(MountParameters& params, const std::string& local_path)
 	// check if volume label is given and don't allow it to updated in the
 	// future
 	if (!params.label.empty()) {
-		newdrive->dirCache.SetLabel(params.label.c_str(), false, false);
+		const bool is_cdrom = (params.type == "iso");
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: `const auto`

**Comment by johnnovak** [comment]
Thanks for the quick fix @dividebysandwich , great stuff! 💯 The problem is gone now with Discworld. I've tested this with a few other games, and it seems to be solid.

I've left a few comments to improve things a little bit. Also, would be nice to change the commit title to the PR title (I've renamed it) and perhaps include the commit hash in the regression that introduced the regression.

I'm looking into the PVS-Studio failure; that's unrelated to your PR.

File: src/dos/programs/mount.cpp [hunk 5]
```diff
@@ -350,6 +350,22 @@ bool MOUNT::MountImageFat(MountParameters& params)
 	return true;
 }
 
+// Return string representation of MSCDEX_AddDrive error code
+static const char* MscdexErrorToMessageId(const int error, const bool is_image_file)
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Static functions are lower_snake_case

**Comment by MasterO2** [comment]
@dividebysandwich and @johnnovak: 

I have a question about mounting directories as CDROMs:

Dosbox 0.74, Dosbox-X, and Dosbox-Staging all print a warning message saying that mounting directories as CDROMs has limited support.

As far as Dosbox-Staging is concerned, does that mean Staging fully supports mounting directories as CDROMs, making that warning message no longer necessary?

**Comment by weirddan455** [comment]
> I have a question about mounting directories as CDROMs:
>
> Dosbox 0.74, Dosbox-X, and Dosbox-Staging all print a warning message saying that mounting directories as CDROMs has limited support.
>
> As far as Dosbox-Staging is concerned, does that mean Staging fully supports mounting directories as CDROMs, making that warning message no longer necessary?

Nothing has changed in that regard. Limited support means we can't play CDROM audio or handle low-level CDROM commands such as listing the table of contents. Those things simply don't make sense when all you have is a directory.

You would also get that same message if you have a physical CDROM but Staging is unable to access the actual device (perhaps due to permission issues but that should be uncommon).

Also tested and, as of this PR, we are correctly generating that message in both logs and console: `MOUNT: MSCDEX: Mounted subdirectory: limited support.`

**Comment by johnnovak** [comment]
@dividebysandwich PVS-Studio fix should go in shortly, then you'll need to rebase this.

Can you please address that last style comment and these further points?

- In `mount_common.cpp`, drop the trailing `\n` from `MSG_Add("MSCDEX_LIMITED_SUPPORT", ...)`
- Change the commit description to this? (I'm picky, I know 😎)

    ```
    Restore CD-ROM behaviour for directories mounted with '-t cdrom'

    Fixes regression introduced in 7bb519b
    ```

**Review by johnnovak — APPROVED** [review]
Nice job @dividebysandwich 🎉
