### PR TITLE
Make the PC Speaker's DC-offset correction optional

### LINKED ISSUE #619: High-pitched Whine from PC speaker sounds
**Describe the bug**
As the title suggests. Noticed it when fiddling around with the SETUP.EXE for Heretic, which uses PC speaker sounds when moving through the different options in the menu. It does eventually fade away, but it is a little irritating. Something to note is that in the 0.76 alpha version, the whine fades away much quicker, in as little as a quarter of a second.

**Environment (please complete the following information):**
- Windows 10 20H2
- Relevant hardware info: i7 9750H, RTX 2060, 16 GB RAM

**Version of dosbox-staging:**
All current versions have the issue, but the 0.76 alpha has lessened the issue albeit not entirely.

**Configuration parameters:**
Share the config file(s) you've been using to run the program.

**Additional context**
Add any other context or details about the problem you might found relevant
(e.g. screenshots, other dosbox versions impacted, etc).

### PR DESCRIPTION
**Pull request by kcgen**
In addition to some RealTek audio manager drivers, Windows 10 appears to have also started performing its own mandatory audio post processing, including a poor(*) form of DC-offset correction.

Thanks to @OpenRift412 for reporting this in https://github.com/dosbox-staging/dosbox-staging/issues/619, and to @NicknineTheEagle for confirming and testing various work-arounds. 

(*) The Window 10 post-processor introduces a lagging positive bias in the signal, which influence any subsequent signal, as flagged by audacity users who say their wavforms _"go astray"_: 

Tape Hiss Macro View
Tape Hiss Micro- View- +10db

In our case, the DC silencer's waveform goes from being neutrally-offset around zero to instead being positively offset (as seen the right-hand-side of the image below), resulting in becoming audible instead of silent:

Because this occurs downstream from dosbox, we have no way of either detecting it at runtime or compensating for it; therefore we instead provide an option to disable DC-offset correction.

Fixes #619 

@OpenRift412 and @NicknineTheEagle -- can you test this branch?
In your `dosbox.conf`, add `neutralize_dc_offset = false` under your `[speaker]` section.

### CODE REVIEW

**Comment by NicknineTheEagle** [comment]
Looks like this fixed the bug: [speaker.zip](https://github.com/dosbox-staging/dosbox-staging/files/5286966/speaker.zip)

**Comment by kcgen** [comment]
Thanks for the fast confirmation @NicknineTheEagle!

@OpenRift412, if you have time to also weight in on the proposed solution then here's a Windows x64-64 binary to test:

https://github.com/dosbox-staging/dosbox-staging/suites/1251967661/artifacts/19078180

**Comment by dreamer** [comment]
@kcgen I keep putting a review of this PR off, sorry.

My first impression was: I am ok with the change, code looks good. I am not fond of having different defaults on Windows and other systems - if we have no other choice but to make different default, then we should have tri-state `enable/disable/auto`.

That being said - perhaps DC-offset correction should be simply disabled by default on every OS? We do not *know* if offset correction is a feature built-in Windows or some drivers (which drivers?); it might be also already supported by other OSes, or maybe even audio hardware.

And it will be even hard to decide if OS-level offset correction is there or not - it won't be recorded via Ctrl+F6 after all, so only people who can hear it can decide if they want the feature tweaked.

**Comment by kcgen** [comment]
No worries regarding the review @dreamer; it's not holding anything up.

I'm OK with either approach; even with it disabled by default.  As for `auto` -- I suppose this is where we would include the Windows vs Linux behavior toggle?

I'm guess this is extremely Windows-specific; the fact the audio driver is bending the wave form (even when input samples are no longer a flat-line) is a *major* problem and surely a bug. If we wait long enough, it might fix itself.  I also can't see Linux or macOS ever allowing such non-sense. There are lots of DJ's on macOS who's phat beats would be destroyed by this :-)

There is a performance benefit to having it enabled, and that's because as soon as the offset is zeroed the channel is halted. So our implementation is very low-overheard and only processes `(pcrate)  x (16bit)` samples per second when actual audio is being played.  Once halted, the PC Speaker channel awaits any positive or negative change and reactivates on-demand (without audible impact).

**Comment by kcgen** [comment]
Implemented `auto` (the new default), and tightened up the description:

**Comment by kcgen** [comment]
@NicknineTheEagle , @OpenRift412:

Windows build for latest change is here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/316145236

If you run on Window and leave `pc_zero_offset = auto` per its default, then DOSBox Staging will simply leave the DC offset as-is and Windows can bend the waveform however it feels.

Thanks for the help in testing; drop a note if this works for you!  
(Coming up on a month now for this PR, so will be nice to have this merged and behind us).

File: src/dosbox.cpp [hunk 1]
```diff
@@ -712,9 +712,17 @@ void DOSBOX_Init(void) {
...
-	secprop->AddInitFunction(&TANDYSOUND_Init,true);//done
-	const char* tandys[] = { "auto", "on", "off", 0};
-	Pstring = secprop->Add_string("tandy",Property::Changeable::WhenIdle,"auto");
+	const char *pc_zero_offset_opts[] = {"auto", "true", "false", 0};
+	pstring = secprop->Add_string("pc_zero_offset", when_idle, pc_zero_offset_opts[0]);
+	pstring->Set_values(pc_zero_offset_opts);
+	pstring->Set_help(
+	        "Neutralizes and prevents the PC speaker's DC-offset from harming other sources.\n"
+	        "'auto' enables this for non-Windows systems and disables it on Windows.\n"
+	        "If your OS perform its own DC correction, then set this to 'false'.");
```
Comment (dreamer) [inline src/dosbox.cpp:721]: Typo: If your OS perform**s** (…)

File: src/dosbox.cpp [hunk 2]
```diff
@@ -712,9 +712,17 @@ void DOSBOX_Init(void) {
...
+
+	secprop->AddInitFunction(&TANDYSOUND_Init, true); // done
```
Comment (dreamer) [inline src/dosbox.cpp:723]: If touching this line, let's remove pointless `done` comment :)

**Review by dreamer — COMMENTED** [review]
Looks great, only 2 nitpicks :)

I will test this in the evening on Linux and Windows and hopefully, we can get this over with.

**Comment by kcgen** [comment]
Thanks for the review @dreamer; last touch-ups inbound.
(Hopefully the CI chain doesn't hang this time!)

**Review by dreamer — APPROVED** [review]
Thank you, @kcgen I will merge this in momentarily :)
