### PR TITLE
Fix icache flush incorrectly tied to W^X policy

### LINKED ISSUE #4791: Icache flush incorrectly tied to W^X policy — disabling per_page_w_or_x crashes dynrec on PPC64LE
## Bug Description

`dyn_cache_invalidate()` in `src/cpu/dyn_cache.h` wraps the entire instruction cache flush inside `#if defined(C_PER_PAGE_W_OR_X)`. This couples two independent concerns:

- **W^X memory protection** (security policy — toggling write/execute page permissions)
- **I/D cache coherency** (architectural requirement on CPUs with split caches)

When building with `-Dper_page_w_or_x=disabled` (as `meson_options.txt` lines 145-147 suggest for PowerPC to reduce `mprotect` overhead), the icache flush is completely skipped. On PPC64LE — which has split I/D caches — the CPU executes stale instructions and crashes.

With **default settings** (`auto`), W^X is enabled for PPC64LE and the icache flush runs correctly, so this only affects users who follow the documented advice to disable W^X for performance.

There is also a secondary `#if defined()` vs `#if` mismatch: `dyn_mem_execute()` and `dyn_mem_write()` use `#if defined(C_PER_PAGE_W_OR_X)`, but meson's `set10()` always defines the symbol (to `0` when disabled), so the check passes even when W^X is supposed to be off. This causes unnecessary `mprotect` calls on every JIT block when W^X is explicitly disabled.

## Steps to Reproduce

Build on PPC64LE with the documented performance optimization:
```
meson setup build -Dper_page_w_or_x=disabled
ninja -C build dosbox
```
Run any DOS program that triggers the dynrec JIT → crash.

## Suggested Fix

Two changes in `src/cpu/dyn_cache.h`:

1. **Decouple icache flush from W^X policy**: Remove the `#if defined(C_PER_PAGE_W_OR_X)` wrapper around the `__builtin___clear_cache()` / `sys_icache_invalidate()` / `FlushInstructionCache()` calls in `dyn_cache_invalidate()`, so the flush always runs. This is a no-op on x86/x86_64 (coherent I/D caches) and necessary on PPC64/ARM.

2. **Fix preprocessor check**: Change `#if defined(C_PER_PAGE_W_OR_X)` to `#if C_PER_PAGE_W_OR_X` in `dyn_mem_execute()` and `dyn_mem_write()` so the value is checked, not just existence.

I have a fix ready — would you be open to a PR from me for this?

## Environment

- Platform: Fedora 43, PPC64LE (POWER9)
- dosbox-staging: main branch at `38da983f8`
- GCC 15.2.1

### PR DESCRIPTION
**Pull request by runlevel5**
Fixes #4791. More details in the issue.

### CODE REVIEW

**Comment by johnnovak** [comment]
Paging our local CPU code expert @kklobe 😆 

Fix seems reasonable otherwise, and I like this option better than the first one you proposed.

File: src/cpu/dyn_cache.h [hunk 1]
```diff
@@ -940,11 +942,6 @@ static inline void dyn_cache_invalidate([[maybe_unused]] void *ptr,
 	        if (CPU_UseRwxMemProtect)
 		return;
 	FlushInstructionCache(GetCurrentProcess(), ptr, size);
-#else
-#error "Don't know how to clear the cache on this platform: please report this"
```
Comment (kklobe) [inline src/cpu/dyn_cache.h:944]: Keep this check in the event of a compiler config that doesn't catch the existing tests.

**Comment by runlevel5** [comment]
Amended

**Comment by dux119-cmd** [comment]
Happy to test on my arm64 batocera build of dosbox-staging. @runlevel5 , are there any build options I should use or will a default cmake release build suffice?

Also, I saw your large contribution to the Intel compiler, and some mention of a CEO giving latest gen POWER9/10 light weight desktops to open source devs. Amazing work.

**Comment by runlevel5** [comment]
@dux119-cmd 

Thanks for the offer to test! A default cmake release build should work fine for validating this — the fix decouples the icache flush from the W^X policy, so it takes effect regardless of build options.

That said, if you want to specifically exercise the bug path that was crashing on PPC64LE, you could also test with `-Dper_page_w_or_x=disabled` (this is a meson option though, not cmake). With this PR applied, dynrec should work correctly either way — with W^X enabled or disabled.

The simplest test is just running any DOS program that triggers the dynamic recompiler (i.e., most games). If it doesn't crash, the fix is working.

**Comment by runlevel5** [comment]
@johnnovak I am unsure why the Windows build failed. I think it is unrelated to this change
