### PR TITLE
Auto enable shell variable expansion for DOS >=7

### LINKED ISSUE #2279: Echo environment variable does not work
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

latest git

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

You should be able to echo environment variables, but this does not work in DOSBox Staging. It does work in DOSBox-X.

Current behaviour:
```dos
Z:\>echo %PATH%
%PATH$
Z:\>echo %BLASTER%
%BLASTER%
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by rderooy**
Automatically enable shell variable expansion when DOS version is set to >= 7.0

closes #2279

### CODE REVIEW

File: src/dosbox.cpp [hunk 1]
```diff
@@ -1125,9 +1125,11 @@ void DOSBOX_Init()
 	               "formats. If set to 0, the country code corresponding to the selected keyboard\n"
 	               "layout will be used.");
 
-	Pbool = secprop->Add_bool("expand_shell_variable", when_idle, false);
-	Pbool->Set_help("Enable expanding environment variables such as %PATH% in the DOS command shell\n"
-	                "(disabled by default).\n"
+	Pstring = secprop->Add_string("expand_shell_variable", when_idle, "auto");
+	const char *expand_shell_variable_choices[] = {"auto", "true", "false"};
```
Comment (kcgen) [inline src/dosbox.cpp:1129]: Close the setup list by adding a `, 0};` as the last element (another nuance of the setup class taking in literal arrays of  pointers; another thing for future refactoring).

File: src/shell/shell_misc.cpp [hunk 2]
```diff
@@ -420,9 +420,12 @@ void DOS_Shell::InputCommand(char * line) {
...
 	/* DOS %variable% substitution */
-	const auto dos = static_cast<Section_prop *>(control->GetSection("dos"));
-	assert(dos);
-	if (dos->Get_bool("expand_shell_variable"))
+	const auto dos_section = static_cast<Section_prop *>(control->GetSection("dos"));
+	assert(dos_section);
+	if (strcmp(dos_section->Get_string("expand_shell_variable"), "true") == 0)
+		ProcessCmdLineEnvVarStitution(line);
+	else if (strcmp(dos_section->Get_string("expand_shell_variable"), "auto") == 0 
+					&& dos.version.major >= 7)
```
Comment (kcgen) [inline src/shell/shell_misc.cpp:428]: Suggest assigning the `dos_section->Get_string("expand_shell_variable")` to a temporary string_view:

```c++
std::string_view expand_shell_variable_pref = 
                 dos_section->Get_string("expand_shell_variable");
```

This will allow for natural comparisons:

``` c++
if (expand_shell_variable_pref == "true") {
   ...
} else if (expand_shell_variable_pref == "auto"
           && dos.version.major >= 7) {
   ...
}
```

Comment (kcgen) [reply src/shell/shell_misc.cpp:428]: Last point - it would be nice to move this cong-setting-checking up to the point where the `[dos]` section is parsed (so it's done only once, and saved in a static bool, like `should_expand_variables`, which we could use here instead). 

Because this a lot of repeat logic to run through for every `%variable%` the shell encounters.  (I'm not not worried about performance, more about putting things where they logically belong).

That would be a very nice refactoring, if you can do it!

**Review by kcgen — COMMENTED** [review]
Just some minor suggestions - logic all looks good, @rderooy !

File: src/shell/shell_misc.cpp (hunk 2 above)
Comment (rderooy) [reply src/shell/shell_misc.cpp]: I'm not quite sure where to move the check to. The other changes were made.

Comment (kcgen) [reply src/shell/shell_misc.cpp]: Can wait for a future refactoring; thanks @rderooy !
