### PR TITLE
Reset OpenGL attributes before creating the mapper's renderer

### LINKED ISSUE #4627: Mapper fails to exit
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

_No response_

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

Arch Linux

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

The mapper is failing to exit. It's logging some OpenGL errors. See repro steps + logs below. I'm pretty sure this is a recent regression but don't have time to bisect it right now.

### Steps to reproduce the behaviour

Explain in detail how to reproduce the bug. Assume no familiarity with the software.
1. Launch with `dosbox --startmapper`
2. Press exit button
3. UI becomes non-responsive and stuck on the mapper screen

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text
2025-12-10 13:01:57.416 | MAPPER: No joysticks found
2025-12-10 13:01:57.417 | MAPPER: Loaded default key bindings
2025-12-10 13:01:58.366 | MAPPER: Failed to restore OpenGL context: Unable to make EGL context current (call to eglMakeCurrent failed, reporting an error of EGL_BAD_CONTEXT)
2025-12-10 13:01:58.366 | RENDER: Auto-switched to shader 'crt/vga-1080p'
2025-12-10 13:01:58.370 | OPENGL: Error compiling vertex shader
2025-12-10 13:01:58.371 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz, scaled to 1067x800 pixels with 1:1.35 (20:27) pixel aspect ratio
2025-12-10 13:01:58.371 | DISPLAY: Presenting at DOS rate without vsync
```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

This fixes an issue where the mapper would fail to exit due to failing to restore our regular renderer's OpenGL context.

## Related issues

Fixes #4627

# Manual testing

Mapper now closes correctly

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/gui/mapper.cpp [hunk 1]
```diff
@@ -3053,6 +3053,16 @@ void MAPPER_DisplayUI() {
...
 		}
 
+		// Since our OpenGL renderer started requesting a version 3.3 context,
+		// the call to SDL_GL_MakeCurrent() when exiting the mapper started failing.
+		//
+		// This is a bit of hack (but so is a lot of this mapper code).
+		// Resetting attributes to default before creating the mapper's render fixes the problem.
+		//
+		// As far as I know, attributes are only evalutated before window and/or context creation
+		// so this should not affect our regular (non-mapper) OpenGL renderer.
```
Comment (johnnovak) [inline src/gui/mapper.cpp:3063]: Yeah, that's correct.
