### PR TITLE
Fix file creation regression on case sensitive file systems

### LINKED ISSUE #2965: Cannot save in Sid Meier's Civilization
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

git main 

### What Operating System are you using?

None

### If Other OS, please describe

Arch

### Relevant hardware info

Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 16GB RAM, OLAND GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When saving in CIV, error occurs with dialog saying that there was an error saving map file, and the terminal output includes the filename as a warning

git bisect results in this:

144783113f8f44a5c449ae7737b6ebb625104d84 is the first bad commit
commit 144783113f8f44a5c449ae7737b6ebb625104d84
Author: FeralChild64 <...>
Date:   Thu Aug 31 22:23:15 2023 +0200

    Implement Hidden/System/Archive attributes in local file system

    Co-authored-by: NicknineTheEagle <...>

 include/cross.h             |   6 +-
 include/dos_system.h        |  21 +++-
 include/drives.h            |   3 +-
 include/fs_utils.h          |  14 +++
 include/string_utils.h      |   2 +-
 src/dos/drive_fat.cpp       |  66 ++++++-----
 src/dos/drive_local.cpp     | 283 ++++++++++++++++++++++++--------------------
 src/dos/drive_overlay.cpp   | 100 ++++++++++------
 src/misc/cross.cpp          |  10 +-
 src/misc/fs_utils.cpp       |  12 ++
 src/misc/fs_utils_posix.cpp | 192 +++++++++++++++++++++++++++++-
 src/misc/fs_utils_win32.cpp |  57 +++++++++
 src/misc/string_utils.cpp   |   7 +-
 13 files changed, 563 insertions(+), 210 deletions(-)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. load civilization
2. save game

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

```text
[magamo@beast build]$ ./dosbox
date       time         |
2023-09-27 20:04:32.174 | arguments: ./dosbox
2023-09-27 20:04:32.174 | Current dir: /home/magamo/Projects/dosbox-staging/build
2023-09-27 20:04:32.174 | stderr verbosity: 0
2023-09-27 20:04:32.174 | -----------------------------------
2023-09-27 20:04:32.174 | dosbox-staging version 0.81.0-alpha-1697-gf9538c688
2023-09-27 20:04:32.174 | ---
2023-09-27 20:04:32.174 | LOG: Loguru version 2.1.0 initialised
2023-09-27 20:04:32.299 | SDL: version 2.28.3 initialised (x11 video and pulseaudio audio)
2023-09-27 20:04:32.299 | CONFIG: Deprecated option 'captures'
2023-09-27 20:04:32.302 | CONFIG: Moved to [capture] section and renamed to 'capture_dir'.
2023-09-27 20:04:32.302 | CONFIG: Unknown option 'force_vga_single_scan'
2023-09-27 20:04:32.302 | CONFIG: Unknown option 'voodoo'
2023-09-27 20:04:32.302 | CONFIG: Unknown option 'voodoo_perf'
2023-09-27 20:04:32.302 | CONFIG: 'mt32' is an invalid value for 'model', using the default: 'auto'
2023-09-27 20:04:32.302 | CONFIG: Loaded primary config file '/home/magamo/.config/dosbox/dosbox-staging.conf'
2023-09-27 20:04:32.302 | LANG: Using internal English language messages
2023-09-27 20:04:32.302 | DISPLAY: Initialised 1067x800 windowed mode using bilinear scaling on display-0
2023-09-27 20:04:32.349 | OPENGL: Vendor: AMD
2023-09-27 20:04:32.349 | OPENGL: Version: 4.6 (Compatibility Profile) Mesa 23.1.8-arch1.1
2023-09-27 20:04:32.349 | OPENGL: GLSL version: 4.60
2023-09-27 20:04:32.349 | OPENGL: Pixel buffer object available
2023-09-27 20:04:32.349 | OPENGL: NPOT textures supported
2023-09-27 20:04:32.350 | RENDER: Using shader 'crt/vga-1080p-fake-double-scan'
2023-09-27 20:04:32.350 | VGA: Pixel-doubling enabled
2023-09-27 20:04:32.350 | VIDEO: Using the DOS video mode's frame rate
2023-09-27 20:04:32.357 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0x7ff32a7fe010
2023-09-27 20:04:32.357 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2023-09-27 20:04:32.360 | CAPTURE: Image capturer started
2023-09-27 20:04:32.369 | MIXER: Negotiated 2-channel 44100 Hz audio in 1024-frame blocks
2023-09-27 20:04:32.369 | MIXER: Master compressor enabled
2023-09-27 20:04:32.406 | MT32: Initialised CM-32L/LAPC-I Control v1.02 from /home/common/Roms/Roland
2023-09-27 20:04:32.417 | MT32: Operating at 44100 Hz without resampling
2023-09-27 20:04:32.417 | MIDI: Opened device: mt32
2023-09-27 20:04:32.417 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-09-27 20:04:32.417 | OPL: Operating at 44100 Hz without resampling
2023-09-27 20:04:32.417 | OPL: Running OPL3 on ports 220h and 388h
2023-09-27 20:04:32.417 | SB16: Sound Blaster 16 OPL output filter enabled
2023-09-27 20:04:32.417 | DMA: Initialised primary controller
2023-09-27 20:04:32.417 | DMA: Initialised secondary controller
2023-09-27 20:04:32.417 | SB: Operating at 22050 Hz and upsampling to the output rate
2023-09-27 20:04:32.417 | SB16: Modern DAC output filter enabled
2023-09-27 20:04:32.417 | SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
2023-09-27 20:04:32.417 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2023-09-27 20:04:32.417 | PCSPEAKER: Operating at 44100 Hz without resampling
2023-09-27 20:04:32.417 | PCSPEAKER: Initialised discrete model
2023-09-27 20:04:32.417 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-09-27 20:04:32.417 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-09-27 20:04:32.417 | DMA: Shutting down secondary controller
2023-09-27 20:04:32.417 | DMA: Shutting down SB16 on 16-bit DMA channel 5
2023-09-27 20:04:32.417 | OPL: Shutting down OPL3
2023-09-27 20:04:32.417 | SB16: Shutting down
2023-09-27 20:04:32.417 | TANDYDAC: Operating at 44100 Hz without resampling
2023-09-27 20:04:32.417 | TANDYDAC: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-09-27 20:04:32.417 | TANDYDAC: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-09-27 20:04:32.417 | TANDY: Operating at 44100 Hz without resampling
2023-09-27 20:04:32.417 | TANDY: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-09-27 20:04:32.417 | TANDY: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-09-27 20:04:32.419 | TANDY: Initialised audio card with a TI NCR 8496 PSG and 8-bit DAC
2023-09-27 20:04:32.419 | DISNEY: Operating at 44100 Hz without resampling
2023-09-27 20:04:32.419 | DISNEY: Highpass filter enabled (12 dB/oct at 100 Hz)
2023-09-27 20:04:32.419 | DISNEY: Lowpass filter enabled (12 dB/oct at 2000 Hz)
2023-09-27 20:04:32.419 | LPT_DAC: Initialised Disney Sound Source on LPT port 378h
2023-09-27 20:04:32.419 | MOUSE: Will be captured after the first left or right button click
2023-09-27 20:04:32.419 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2023-09-27 20:04:32.419 | MOUSE (PS/2): Standard, 3 buttons
2023-09-27 20:04:32.421 | SLIRP: Slirp version: 4.7.0
2023-09-27 20:04:32.421 | SLIRP: Successfully initialized
2023-09-27 20:04:32.421 | NE2000: Initialised on port 300h and IRQ 3
2023-09-27 20:04:32.421 | CONFIG: Loaded auto-mounted drive config file 'resources/drives/y.conf'
2023-09-27 20:04:32.452 | MAPPER: No joysticks found
2023-09-27 20:04:32.452 | MAPPER: Failed loading mapperfile 'mapper-sdl2-git.map' directly and from resources
2023-09-27 20:04:32.452 | MAPPER: Loaded default key bindings
2023-09-27 20:04:32.453 | SHELL: Redirecting output to NUL
2023-09-27 20:04:32.453 | MOUNT: Path 'resources/drives/y' found
2023-09-27 20:04:32.454 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2023-09-27 20:04:32.505 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 1067x800 with 1:1.35 (20:27) pixel aspect ratio
2023-09-27 20:04:34.711 | MOUNT: Path '/home/magamo' found
2023-09-27 20:04:39.972 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz VFR, scaled to 1067x800 with 1:1.2 (5:6) pixel aspect ratio
2023-09-27 20:04:40.317 | MT32: LCD-Message: [MPS  Civilization]
2023-09-27 20:04:40.334 | MT32: LCD-Message: [MPS  Civilization]
2023-09-27 20:05:02.461 | Warning: file creation failed: /home/magamo/GAMES/MPS/CIV/CIVIL1.MAP
2023-09-27 20:05:12.948 | MT32: LCD-Message: [MPS  Civilization]
2023-09-27 20:05:12.987 | MT32: LCD-Message: [MPS  Civilization]
2023-09-27 20:05:13.190 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 1067x800 with 1:1.35 (20:27) pixel aspect ratio
2023-09-27 20:05:15.197 | DISNEY: Shutting down DAC
2023-09-27 20:05:15.197 | TANDY: Shutting down
2023-09-27 20:05:15.197 | PCSPEAKER: Shutting down discrete model
2023-09-27 20:05:15.197 | MPU-401: Shutting down
2023-09-27 20:05:15.197 | MT32: Shutting down
2023-09-27 20:05:15.197 | CAPTURE: Image capturer shutting down
2023-09-27 20:05:15.197 | DMA: Shutting down primary controller
2023-09-27 20:05:15.257 | atexit
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

This is a regression from https://github.com/dosbox-staging/dosbox-staging/commit/144783113f8f44a5c449ae7737b6ebb625104d84

The above commit removed a call to `dirCache.GetExpandName`

That function does a lot of stuff I didn't fully follow but one of those things is getting the real casing of the directory as the OS sees it.  This is important for case sensitive file systems like Linux typically uses, otherwise the file creation fails.

## Related issues

Fixes #2965

# Manual testing

- Installed Civilization into C:\MPS\CIV
- Try saving game, it works
- In Linux, rename the real directory from MPS to MpS
- Try saving game, it fails
- Make this change
- Saving the game now works regardless of casing

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by kcgen — APPROVED** [review]
Great catching finding this accidental removal, @weirddan455 !

**Comment by kcgen** [comment]
(Markdown lint was updated and is catching a couple new table formatting issues; PR inbound to fix that up)

File: src/dos/drive_local.cpp [hunk 1]
```diff
@@ -61,12 +61,13 @@ bool localDrive::FileCreate(DOS_File** file, char* name, FatAttributeFlags attri
 	safe_strcpy(newname, basedir);
 	safe_strcat(newname, name);
 	CROSS_FILENAME(newname);
+	char* expanded_name = dirCache.GetExpandName(newname); //Can only be used in till a new drive_cache action is preformed */
```
Comment (johnnovak) [inline src/dos/drive_local.cpp:64]: I recommend to rename this to something that reflects the functionality better. It's tricky because you don't wanna put a novel into the function names, but this is on the too short side that hides the actual action performed by the function.

If I read this name, I have no reason to believe it does case normalisation. The word "expand" in the name gives me a "false sense" of understanding what it does and look no further, but actually this tricks the reader and leads them astray...

Suggest to rename it to `ExpandNameAndNormaliseCase` or something (if that's what it's doing), and also comment the behaviour in its header file. Or just `Normalise` which is so abstract that it will force the reader to look up the documentation of the function.

Comment (weirddan455) [reply src/dos/drive_local.cpp]: I've renamed it as you suggested.  Also made a copy of the string to not have to worry about the lifetime of the static local pointer that function returns.  I noticed I actually was making another dirCache call while still holding onto that pointer so that could have been a bug.

I had another look at the function and I still don't fully grasp exactly what it does.  It gets passed in a path with all uppercase (I assume that's how the DOS side sees the file since DOS is case insensitive).  It then does a lookup in some cache and eventually returns the path as the host OS sees it.

It's a lot of hard to read C-style string manipulation.  There's also a vector of `CFileInfo` (whatever that is) and a hash function taken from WINE for some reason.

I'd be tempted to rename it to `ManipulateString` or `DoMagic` but your suggestion seems a bit better.

Comment (johnnovak) [reply src/dos/drive_local.cpp]: Yeah, many times I'm faced with similar decisions and I'm not always prepared to spend days getting to the bottom of things. As long as we're making improvements, every little incremental change that helps cleaning up this mess is welcome 😅

**Comment by kcgen** [comment]
Tested and working (in the CIV scenario); let's get this merged!
