### PR TITLE
Fix Sound Blaster DMA ADPCM frame count assertion error

### LINKED ISSUE #2256: Duke Nukem 2 triggers assertion in Sound Blaster
Running Duke Nukem 2 triggers the following assertion: ```dosbox: ../src/hardware/sblaster.cpp:940: void PlayDMATransfer(uint32_t): Assertion `((void)"Frames should never exceed samples", frames <= samples)' failed.```

To reproduce, just watch the intro (where it shows Neo LA) or load into gameplay. If it doesn't trigger, make sure Sound Blaster sounds are enabled in the options menu (accessible via the game's main menu).

### PR DESCRIPTION
**Pull request by kcgen**
Suggestion reviewing commit-by-commit (only two).

Fixed #2256

### CODE REVIEW

File: src/hardware/sblaster.cpp [hunk 1]
```diff
@@ -699,12 +696,12 @@ static uint8_t decode_ADPCM_3_sample(const int val)
...
-	const auto i = std::min(sample + scale, 39);
+	const auto i = std::clamp(three_bit_portion + scale, 0, 39);
 	scale = (scale + adjustMap[i]) & 0xff;
 
-	auto &ref = sb.adpcm.reference;
-	ref = static_cast<uint8_t>(clamp(ref + scaleMap[i], 0, 255));
-	return ref;
+	auto &sample = sb.adpcm.reference;
+	sample = static_cast<uint8_t>(clamp(sample + scaleMap[i], 0, 255));
+	return sample;
```
Comment (johnnovak) [inline src/hardware/sblaster.cpp:704]: Nice cleanup 👍🏻

File: src/hardware/sblaster.cpp [hunk 2]
```diff
@@ -766,59 +766,68 @@ static void PlayDMATransfer(uint32_t bytes_requested)
...
-			frames = check_cast<uint16_t>(samples / channels);
-			sb.chan->AddSamples_m8(frames, maybe_silence(samples, MixTemp));
-			samples = 0;
+			constexpr uint8_t num_decoded = ARRAY_LEN(decoded);
+			sb.chan->AddSamples_m8(num_decoded, maybe_silence(num_decoded, decoded));
+			samples += num_decoded;
 			++i;
 		}
+		frames = check_cast<uint16_t>(samples / channels);
+
```
Comment (johnnovak) [inline src/hardware/sblaster.cpp:830]: So what fixed the bug? I'm sure you tested it and it works, I'm just not seeing it from these changes, so just curious :)

Comment (kcgen) [reply src/hardware/sblaster.cpp:830]: (oh; I forgot to flag it!) 
In the three while loops, previously the `samples = ` were reset to zero instead of holding the total for the given DMA transfer, which is where the accounting fell apart. `frames`, on the other hand, were correctly tallied based on the intermediate `samples` count, and so that's why frames was larger than samples.

File: src/hardware/sblaster.cpp [hunk 3]
```diff
@@ -769,59 +766,68 @@ static void PlayDMATransfer(uint32_t bytes_requested)
...
-			MixTemp[samples++] = decode_ADPCM_3_sample((sb.dma.buf.b8[i] >> 2) & 0x7);
-			MixTemp[samples++] = decode_ADPCM_3_sample((sb.dma.buf.b8[i] & 0x3) << 1);
-
-			frames = check_cast<uint16_t>(samples / channels);
-			sb.chan->AddSamples_m8(frames, maybe_silence(samples, MixTemp));
-			samples = 0;
+			const uint8_t decoded[] = {
+			        decode_ADPCM_3_sample((sb.dma.buf.b8[i] >> 5) & 0x7),
+			        decode_ADPCM_3_sample((sb.dma.buf.b8[i] >> 2) & 0x7),
+			        decode_ADPCM_3_sample((sb.dma.buf.b8[i] & 0x3) << 1)};
```
Comment (GranMinigun) [inline src/hardware/sblaster.cpp:800]: "Implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char')"

Would that pacify compiler and not break everything? `decode_ADPCM_3_sample((sb.dma.buf.b8[i] << 1) & 0b110)};`

File: src/hardware/sblaster.cpp (hunk 2 above)
Comment (johnnovak) [reply src/hardware/sblaster.cpp]: Makes sense, i suspected something like that.

File: src/hardware/sblaster.cpp (hunk 3 above)
Comment (kcgen) [reply src/hardware/sblaster.cpp]: Rewrote it to move all the ADPCM decoded inside functions (and de-duped all the code). Looks like it's passing now.

**Comment by johnnovak** [comment]
Looking good, that was fast! 🚀

**Review by GranMinigun — APPROVED** [review]
