### PR TITLE
Fix images sometimes not found on DOS filesystem

### LINKED ISSUE #4795: Mounting disk images does not always work
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

current main (37fe8321fb3367932aabe9baac2c114912629bff)

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

Gentoo, KDE

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

I have a lot of .BAT scripts to change DOSBox configuration, mount images, launch games, etc. On the current main, mounting disk images sometimes fail - for example, one of the script has two lines, one after another:

```bat
IMGMOUNT E C:\DOS\ISO\WIN98SE.ISO -t cdrom
IMGMOUNT F C:\DOS\IMG\WIN98.IMG -size 512,63,64,1023
```

The first command works, the second one prints an error message, _C:\DOS\IMG\WIN98.IMG isn't a directory or valid image file_. Both files do exist - DOSBox 0.82.2 is able to mount them both. Changing the command to `MOUNT` does not help (I prefer to keep `IMGMOUNT` for now, so that I can easily compare the `main` branch behavior against the latest release).

[edit] Just noticed that command:

```bat
IMGMOUNT 2 C:\DOS\IMG\WIN98.IMG -size 512,63,64,1023
```

reports success - so it can find the file if I ask to mount it as a physical device #2, but I can't if I want to mount it as drive F:

### Steps to reproduce the behaviour

See the description. It ifs not yet clear to me why sometimes mounting images works, and sometimes it fails.

### Download URL of affected game or software

_No response_

### Your configuration

```ini

```

### Provide a log

```text
The log contains:

2026-03-03 18:30:41.771 | MOUNT: C:\DOS\IMG\WIN98.IMG isn't a directory or valid image file.
```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by dividebysandwich**
# Description

Fixes drive letter mode mounting of images not checking the DOS filesystem.

## Related issues

Fixes #4795, #4786

# Manual testing

```
mount c /home/user/dos-root
mount f /home/user/dos-root/diskimage.img -size 512,63,72,900
mount -u f
mount f C:\diskimage.img -size 512,63,72,900
mount -u f
mount 3 /home/user/dos-root/diskimage.img -size 512,63,72,900
mount -u d
mount d C:\diskimage.img -size 512,63,72,900
```

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [X] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [X] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [X] performed a self-review of my code.
- [X] commented on the particularly hard-to-understand areas of my code.
- [X] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [X] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [X] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/tools/compile-commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [X] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/dos/programs/mount.cpp [hunk 1]
```diff
@@ -693,10 +693,37 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
...
-	auto target_is_dir = stat_ok && S_ISDIR(test.st_mode);
+
+	// If not found on the host, check if it is a mounted DOS path
+	if (!stat_ok) {
+		char tmp_dos[CROSS_LEN];
+		char fullname_dos[CROSS_LEN];
+		safe_strcpy(tmp_dos, path_arg_1.c_str());
+		uint8_t drive_idx;
+
+		if (DOS_MakeName(tmp_dos, fullname_dos, &drive_idx)) {
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Can't you just pass in `path_arg_1.c_str()` directly as the first arg?

File: src/dos/programs/mount.cpp [hunk 2]
```diff
@@ -693,10 +693,37 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
...
+			if (Drives.at(drive_idx) &&
+			    Drives.at(drive_idx)->GetType() == DosDriveType::Local) {
+				const auto ldp = std::dynamic_pointer_cast<localDrive>(
+				        Drives.at(drive_idx));
+				if (ldp) {
+					std::string mapped_host_path = ldp->MapDosToHostFilename(
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: `const auto mapped_host_path`?

File: src/dos/programs/mount.cpp [hunk 3]
```diff
@@ -693,10 +693,37 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
...
+	if (!stat_ok) {
+		char tmp_dos[CROSS_LEN];
+		char fullname_dos[CROSS_LEN];
+		safe_strcpy(tmp_dos, path_arg_1.c_str());
+		uint8_t drive_idx;
+
+		if (DOS_MakeName(tmp_dos, fullname_dos, &drive_idx)) {
+			if (Drives.at(drive_idx) &&
+			    Drives.at(drive_idx)->GetType() == DosDriveType::Local) {
+				const auto ldp = std::dynamic_pointer_cast<localDrive>(
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: `const auto drive` ?

File: src/dos/programs/mount.cpp [hunk 4]
```diff
@@ -693,10 +693,37 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
...
+					// If the mapped file exists, update our
+					// stat struct so auto-detection works
+					if (stat(mapped_host_path.c_str(),
+					         &test) == 0) {
+						stat_ok = true;
+					}
+				}
+			}
+		}
+	}
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:732]: Can we extract this whole thing out into `is_mounted_dos_path()` or something? That will also reduce the quite horrible "re-use" of vars in this 200+ line function (existing code, I know it's not your fault 😆).

File: src/dos/programs/mount.cpp (hunk 1 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp]: Mea culpa. During testing I thought I had broken something so I had some temporary string changes in there and forgot to remove them.

File: src/dos/programs/mount.cpp (hunk 3 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp]: I don't see drive. If you mean drive_idx, that can't be const.

File: src/dos/programs/mount.cpp (hunk 4 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp:732]: Sure. In fact some of the handling between normal and image mounts is still duplicated because I was being conservative with changing existing code. But I'll look what I can consolidate hopefully without breaking stuff.

File: src/dos/programs/mount.cpp (hunk 1 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp]: In fact let me replace those buffers with std::array

**Comment by FeralChild64** [comment]
I confirm this fixes my problem.

File: src/dos/programs/mount.h [hunk 5]
```diff
@@ -56,6 +56,12 @@ class MOUNT final : public Program {
 	                    bool& path_relative_to_last_config);
 	void ParseGeometry(MountParameters& params);
 	bool ParseDrive(MountParameters& params, bool explicit_fs);
+
+	std::string ApplyRelativePath(const std::string& path, bool is_relative) const;
```
Comment (johnnovak) [inline src/dos/programs/mount.h]: You'll need to rename `is_relative` to `is_relative_to_last_config`, otherwise this signature doesn't even make sense 😄 (Apply**Relative**Path... then pass in an `is_relative` flag? 🤔 😆 )

File: src/dos/programs/mount.cpp [hunk 6]
```diff
@@ -656,35 +656,63 @@ bool MOUNT::ParseDrive(MountParameters& params, bool explicit_fs)
 	return true;
 }
 
+std::string MOUNT::ApplyRelativePath(const std::string& path, bool is_relative) const
+{
+	if (is_relative && !control->config_files.empty() &&
+	    !std_fs::path(path).is_absolute()) {
+		auto lastconfigdir = control->config_files.back();
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: last_config_dir

File: src/dos/programs/mount.cpp [hunk 7]
```diff
@@ -656,35 +656,63 @@ bool MOUNT::ParseDrive(MountParameters& params, bool explicit_fs)
...
+		if (out_fullname) {
+			*out_fullname = fullname_buf.data();
+		}
+		if (out_drive_idx) {
+			*out_drive_idx = drive_idx;
+		}
+
+		if (Drives.at(drive_idx) &&
+		    Drives.at(drive_idx)->GetType() == DosDriveType::Local) {
+			if (const auto ldp = std::dynamic_pointer_cast<localDrive>(
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Yeah, so i meant rename `const auto ldp` to `const auto drive` or `local_drive`.

File: src/dos/programs/mount.cpp [hunk 8]
```diff
@@ -656,35 +656,63 @@ bool MOUNT::ParseDrive(MountParameters& params, bool explicit_fs)
...
+                                        std::string* out_fullname,
+                                        uint8_t* out_drive_idx) const
+{
+	// DOS_MakeName requires a writable buffer
+	auto fullname_buf = std::array<char, CROSS_LEN>{};
+	auto drive_idx    = uint8_t{0};
+
+	if (DOS_MakeName(dos_path.data(), fullname_buf.data(), &drive_idx)) {
+		if (out_fullname) {
+			*out_fullname = fullname_buf.data();
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: I _think_ this might be safe because a new string is constructed, but I'm not 100% sure, and it's really confusing.

We should really stop using pointers for optional values, so please use `std::optional`. 1 minute LLM-assisted cleanup; it's way cleaner this way and all ambiguity is removed:

```cpp
std::string MOUNT::GetDosMappedHostPath(const std::string& dos_path,
                                         std::optional<std::string>& out_fullname,
                                         std::optional<uint8_t>& out_drive_idx) const
{
    auto fullname_buf = std::array<char, CROSS_LEN>{};
    uint8_t drive_idx = 0;

    if (DOS_MakeName(dos_path.data(), fullname_buf.data(), &drive_idx)) {
        const auto fullname = std::string(fullname_buf.data());

        out_fullname  = fullname;
        out_drive_idx = drive_idx;

        if (Drives.at(drive_idx) &&
            Drives.at(drive_idx)->GetType() == DosDriveType::Local) {

            if (const auto drive = std::dynamic_pointer_cast<localDrive>(
                        Drives.at(drive_idx))) {
                return drive->MapDosToHostFilename(fullname);
            }
        }
    }
    return {};
}
```

File: src/dos/programs/mount.cpp [hunk 9]
```diff
@@ -749,50 +757,20 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
 
 	if (is_image_mode) {
 		// Loop through all remaining arguments
-		uint16_t arg_idx = 2;
-		std::string cur_arg;
+		auto arg_idx = 2;
+		auto cur_arg = std::string{};
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: `std::string cur_arg = ""` is more straightforward if you want to be explicit about the type.

File: src/dos/programs/mount.cpp [hunk 10]
```diff
@@ -803,39 +781,29 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
...
-								        host_name);
-								found_on_virtual = true;
-								LOG_MSG("IMGMOUNT: Path '%s' found on virtual drive %c:",
-								        fullname,
-								        drive_letter(dummy));
-							}
-						}
-					}
+				auto found_on_virtual = false;
+				auto fullname         = std::string{};
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: Yeah so when we must specify a type, `std::string fullname = ""` is less awkward.

File: src/dos/programs/mount.cpp [hunk 11]
```diff
@@ -803,39 +781,29 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
...
+				auto dummy_idx        = uint8_t{0};
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: Same here: `uint8_t dummy_dx = 0;`

**Comment by johnnovak** [comment]
Thanks for cleaning this up @dividebysandwich . See my further comments. Once addressed, can @FeralChild64 please re-test, then merge time 🚀 Thanks all 🙏🏻 😎

File: src/dos/programs/mount.cpp (hunk 8 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp]: Hmm. I analyzed your proposed patch and it is subtly changing how the function behaves - you modify out_fullname and out_drive_idx in every case. Also, the entire reason for modifying these two parameters is to then print a log message that says "I found the image you wanted to mount on your DOS filesystem", in addition to the regular log message that gives the path.

I propose to remove that log message and thus the need for this entire song and dance. Makes for much simpler code. 

EDIT: See simplified function in latest commit.

File: src/dos/programs/mount.cpp (hunk 11 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp]: Deleting that code is even better :)

File: src/dos/programs/mount.cpp (hunk 8 above)
Comment (johnnovak) [reply src/dos/programs/mount.cpp]: Yeah the new version is fine. I did not analyze this too deeply, just some obvious issues with it, that's all 😄

**Comment by johnnovak** [comment]
@FeralChild64 Can you re-test, please?

**Comment by FeralChild64** [comment]
Re-tested - the fix works correctly.

File: src/dos/programs/mount.cpp [hunk 12]
```diff
@@ -693,21 +718,28 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
...
 #endif
 
-	// Check first path
-	struct stat test;
-	auto stat_ok       = (stat(path_arg_1.c_str(), &test) == 0);
-	auto target_is_dir = stat_ok && S_ISDIR(test.st_mode);
-	auto explicit_image_type = (params.type == "hdd" || params.type == "iso" ||
-	                            params.type == "floppy");
+	// Check first path on the host OS
+	struct stat test{};
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: minor: looks super weird; we usually do `struct stat test = {}`;

File: src/dos/programs/mount.cpp [hunk 13]
```diff
@@ -820,16 +807,16 @@ bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_con
 
 			// Auto-detect type from FIRST valid file if generic "dir"
 			if (params.paths.empty() && params.type == "dir") {
-				// Check if actually file
-				struct stat t2;
-				if (stat(final_path.c_str(), &t2) == 0 &&
+				struct stat t2{};
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: `struct state t2 = {};` please. There's value in using a non-surprising style, and keeping it simple.

File: src/dos/programs/mount.cpp [hunk 14]
```diff
@@ -656,35 +656,60 @@ bool MOUNT::ParseDrive(MountParameters& params, bool explicit_fs)
...
+		if (!last_config_dir.empty()) {
+			return last_config_dir + CROSS_FILESPLIT + path;
+		}
+	}
+	return path;
+}
+
+// Translates a DOS path to a host path if the DOS path is currently mapped as a
+// drive. Returns an empty string if it cannot be translated.
+std::string MOUNT::GetDosMappedHostPath(const std::string& dos_path) const
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp:677]: Yeah, let's do string_view here as Sonar says. Not because of the performance difference, but that's one less Sonar warning at least. You can ignore the rest of the warnings, I don't agree with those (sadly, we can't customise Sonar with the free tier we're using).

File: src/dos/programs/mount.cpp [hunk 15]
```diff
@@ -656,35 +656,60 @@ bool MOUNT::ParseDrive(MountParameters& params, bool explicit_fs)
...
+	}
+	return "";
+}
+
 // Returns true if processed successfully (even if it means it found an image
 // and decided to mount it) Returns false on failure.
 bool MOUNT::ProcessPaths(MountParameters& params, bool path_relative_to_last_config)
 {
-	std::string final_path;
+	auto final_path = std::string{};
```
Comment (johnnovak) [inline src/dos/programs/mount.cpp]: `std:string final_path = {};` for the least surprise 😄

**Comment by johnnovak** [comment]
Thanks for fixing this promptly @dividebysandwich 🎖️ 

A few minor style things @dividebysandwich and we're good to go.

Also, we don't say "implement/address review/PR comments" in commit descriptions, so I'd suggest to rename your last commit to `Simplify GetDosMappedHostPath() & cleanup`. You can squash the minor things I've commented on into it, then merge time 🚀

File: src/dos/programs/mount.cpp (hunk 14 above)
Comment (dividebysandwich) [reply src/dos/programs/mount.cpp:677]: It's funny that it didn't have the same complaint about ApplyRelativePath.

Comment (dividebysandwich) [reply src/dos/programs/mount.cpp:677]: Actually, after some testing, I will not use string_view here as it's incorrect and breaks the entire thing. Getting rid of the resulting segfaults would mean rewriting several functions, just to please Sonar's regexp.

Comment (johnnovak) [reply src/dos/programs/mount.cpp:677]: Yeah, if it's not a drop-in replacement, we almost never do it. Silly comment from Sonar then.
