### PR TITLE
Fix choice /t repeatedly pressing default key

### LINKED ISSUE #4708: Choice with timeout creating stuck key
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

0.82.2

### What operating system are you using?

Windows 11

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

Surface Pro 10

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

this is on the portable version. 
using /t option results in the default options being selected and passed to the keyboard with the shift key stuck pressed. 

Image

### Steps to reproduce the behaviour

Explain in detail how to reproduce the bug. Assume no familiarity with the software.
1. choice /tn,2 blabla

### Download URL of affected game or software

_No response_

### Your configuration

```ini
this is with the default config.
```

### Provide a log

```text
help choice
choice /c:Yn /n /t:n,2 wait
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN♥
choice  /t:n,5 w
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

It's a regression from 393e3923bb6af6a89f83692de23b5e91e18a4bfd but I think that commit is solid overall for Autotype's intended usecase.

Autotype leaves the key pressed for 50ms before releasing the key but `CMD_CHOICE` calls `MAPPER_StopAutoTyping()` immediately after reading the key which stops the key from ever being released.

I could write some extra logic into `MAPPER_StopAutoTyping()` or introduce a 50ms delay in `CMD_CHOICE` but I think the use of Autotype here is really just a hack.

Instead I'm using INT16 in a loop to check if a key has been pressed and break out early if a timeout is requested.

## Related issues

Fixes #4708

# Release notes

Fix choice /t repeating the default key if timeout is reached.

# Manual testing

`choice /t:n,2` and wait 2 seconds. The N key no longer goes on repeat.

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/tools/compile-commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/shell/shell_cmds.cpp [hunk 1]
```diff
@@ -103,6 +104,33 @@ static char *ExpandDot(const char *args, char *buffer, size_t bufsize)
...
+	// Blocks until a key is pressed and removes the key from buffer.
+	reg_ah = is_machine_ega_or_better() ? 0x10 : 0x0;
+	CALLBACK_RunRealInt(0x16);
+	return reg_al;
+}
+
+static char read_from_keyboard_with_timeout(double timeout_ms, char default_key)
+{
+	const auto start = PIC_FullIndex();
+	while (!DOSBOX_IsShutdownRequested()) {
```
Comment (johnnovak) [inline src/shell/shell_cmds.cpp]: You should use `CALLBACK_Idle()` in new code. There are plenty of examples in the PR where I introduced it, e.g. for the `MORE` command:

https://github.com/dosbox-staging/dosbox-staging/pull/4629/changes#diff-1951e055b1f7dacd00f0f3e0f2859f9721f16017122beae1f9296262b98e6fb9

File: src/shell/shell_cmds.cpp [hunk 2]
```diff
@@ -103,6 +104,33 @@ static char *ExpandDot(const char *args, char *buffer, size_t bufsize)
...
+{
+	// Blocks until a key is pressed and removes the key from buffer.
+	reg_ah = is_machine_ega_or_better() ? 0x10 : 0x0;
+	CALLBACK_RunRealInt(0x16);
+	return reg_al;
+}
+
+static char read_from_keyboard_with_timeout(double timeout_ms, char default_key)
+{
+	const auto start = PIC_FullIndex();
```
Comment (johnnovak) [inline src/shell/shell_cmds.cpp]: `start_ms`

File: src/gui/mapper.cpp [hunk 3]
```diff
@@ -1238,7 +1238,7 @@ void MAPPER_AutoType(std::vector<std::string>& buttons, uint32_t wait_ms,
 	}
 }
 
-void MAPPER_StopAutoTyping()
+static void MAPPER_StopAutoTyping()
```
Comment (johnnovak) [inline src/gui/mapper.cpp]: Private function, so `stop_auto_typing()`.

File: src/shell/shell_cmds.cpp (hunk 1 above)
Comment (weirddan455) [reply src/shell/shell_cmds.cpp]: What would be the purpose of using `CALLBACK_Idle()` here? You made that function more ergonomic to use but I need to actually call an interrupt with `CALLBACK_RunRealInt(0x16)`, not just idle. None of the functions you refactored in that commit are doing this.

File: src/shell/shell_cmds.cpp (hunk 2 above)
Comment (weirddan455) [reply src/shell/shell_cmds.cpp]: changed

File: src/gui/mapper.cpp (hunk 3 above)
Comment (weirddan455) [reply src/gui/mapper.cpp]: changed

File: src/shell/shell_cmds.cpp (hunk 1 above)
Comment (johnnovak) [reply src/shell/shell_cmds.cpp]: It's the more correct way to do this kind of wait. You explicitly executing some interrupt calls alright, but my understanding is this way you're blocking other IRQ executions for the wait duration which can be significant. Could not matter in the general case, but maybe some TSR is running in the background that would be blocked by this.

It's a small thing, but we have a pattern, so I'd prefer applying it consistenly when we're waiting for "significant" durations, regardless whether it's a pure busy wait or if we happen to execute something during waiting.

Pure busy wait example from `mouse_manymouse.cpp`:

```cpp
	// Wait a little to speedup screen update
	constexpr uint32_t ticks_threshold = 50; // time to wait idle in PIC ticks
	const auto pic_ticks_start = PIC_Ticks;
	while (PIC_Ticks >= pic_ticks_start &&
	       PIC_Ticks - pic_ticks_start < ticks_threshold) {
		if (CALLBACK_Idle()) {
			return false;
		}
	}
```

Wait + some code execution example from `ipx.cpp`:

```cpp
				while ((GetTicksSince(ticks)) < 1500) {
					if (CALLBACK_Idle()) {
						return;
					}
					if(pingCheck(&pingHead)) {
						WriteOut(
						        "Response from %d.%d.%d.%d, port %d time=%lldms\n",
						        CONVIP(pingHead.src.addr.byIP.host),
						        SDLNet_Read16(&pingHead.src.addr.byIP.port),
						        GetTicksSince(ticks));
					}
				}
```

Comment (weirddan455) [reply src/shell/shell_cmds.cpp]: `CALLBACK_Idle()` and `CALLBACK_RunRealInt()` both call `DOSBOX_RunMachine()` which should run IRQs. It's needed in all the examples you've given because you're never yielding control back to the main emulator loop but I am in my code.

That said, putting `CALLBACK_Idle()` here does fix a timing problem I just now noticed while testing. If I set `cpu_cycles = 100,000`, the timeout ends up being twice the time it should be in real wall-clock time. Putting the idle callback in there fixes it and makes the timeout consistent regardless of how high I set the cycles.

Not sure why that is but thanks for pointing that out.

Comment (johnnovak) [reply src/shell/shell_cmds.cpp]: > `CALLBACK_Idle()` and `CALLBACK_RunRealInt()` both call `DOSBOX_RunMachine()` which should run IRQs

Cool, wasn't aware `CALLBACK_RunRealInt()` does that, but it makes sense.
 
> That said, putting `CALLBACK_Idle()` here does fix a timing problem I just now noticed while testing. If I set `cpu_cycles = 100,000`, the timeout ends up being twice the time it should be in real wall-clock time. Putting the idle callback in there fixes it and makes the timeout consistent regardless of how high I set the cycles.
> 
> Not sure why that is but thanks for pointing that out.

Heh, cool, but also worrying a bit when things get fixed "by magic" 😆

File: src/shell/shell_cmds.cpp [hunk 4]
```diff
@@ -103,6 +104,36 @@ static char *ExpandDot(const char *args, char *buffer, size_t bufsize)
...
+	return reg_al;
+}
+
+static char read_from_keyboard_with_timeout(double timeout_ms, char default_key)
+{
+	const auto start_ms = PIC_FullIndex();
+	while (true) {
+		if (CALLBACK_Idle()) {
+			break;
+		}
```
Comment (johnnovak) [inline src/shell/shell_cmds.cpp]: Replace with `while (CALLBACK_Idle())` ?

Comment (weirddan455) [reply src/shell/shell_cmds.cpp]: It would be `while (!CALLBACK_Idle())` but sure I changed it.
