### PR TITLE
Fix a regression in the discrete PC Speaker

### LINKED ISSUE #1906: Monkey Island PC Speaker missing notes
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

During the "Chapter One" screen of the beginning of Monkey Island there is a short song heard that is called 'Interlude'.
There are notes missing in that song on DOSBox Staging that are heard on a real hardware recording.

Bildschirmfoto 2022-09-06 um 09 47 22

Bildschirmfoto 2022-09-06 um 09 39 48

### Audio Samples:
[3 audio samples.zip](https://github.com/dosbox-staging/dosbox-staging/files/9494469/3.audio.samples.zip)

Source of the hardware recording: https://www.zeitgestalten.org/somi_monophony.html

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch Monkey Island EN VGA on DOSBox Staging with `monkey i` to select internal speaker.
2. Record using CTRL/CMD+F6.
3. Compare the recorded file to the hardware recording.

### Your configuration

```ini
default
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
fixes #1906.

Thanks for the careful listening and detailed report, @Burrito78.

Audacity screenshots taken using the PR branch, with default settings except for adjusting the `pcspeaker = discrete vs. impulse`:

### CODE REVIEW

File: src/hardware/pcspeaker_discrete.h [hunk 1]
```diff
@@ -52,7 +52,7 @@ class PcSpeakerDiscrete final : public PcSpeaker {
 	static constexpr char device_name[] = "PCSPEAKER";
 	static constexpr char model_name[]  = "discrete";
 
-	static constexpr float pwm_scalar = 0.5f; // accomodate a full doubling
+	static constexpr float pwm_scalar = 0.72f;
```
Comment (johnnovak) [inline src/hardware/pcspeaker_discrete.h:55]: That seems oddly specific... not just 0.7, but 0.7**2**! 😂 I think it warrants a comment? Was it derived from a decibel scale factor perhaps?

File: src/hardware/pcspeaker_impulse.h [hunk 2]
```diff
@@ -52,7 +52,9 @@ class PcSpeakerImpulse final : public PcSpeaker {
 	static constexpr char device_name[] = "PCSPEAKER";
 	static constexpr char model_name[]  = "impulse";
 
-	static constexpr int16_t positive_amplitude = 20000;
+	// Amplitude constants
+	static constexpr float pwm_scalar = 0.5f; // accomodate a full doubling
```
Comment (johnnovak) [inline src/hardware/pcspeaker_impulse.h:56]: So `pwm_scalar` was change to 0.72 above, why not here as well?

**Comment by Burrito78** [comment]
@kcgen Is this the correct build for testing again?
https://github.com/dosbox-staging/dosbox-staging/actions/runs/3005209584

**Comment by kcgen** [comment]
> @kcgen Is this the correct build for testing again? https://github.com/dosbox-staging/dosbox-staging/actions/runs/3005209584

Yes- exactly 👍.

**Comment by Burrito78** [comment]
There are still a lot of non-trivial differences in hardware recording (above) and PR build (below):

Bildschirmfoto 2022-09-07 um 19 55 38
Bildschirmfoto 2022-09-07 um 19 56 11
Bildschirmfoto 2022-09-07 um 19 56 47
Bildschirmfoto 2022-09-07 um 19 57 01
Bildschirmfoto 2022-09-07 um 19 57 12
Bildschirmfoto 2022-09-07 um 19 58 03

**Comment by Burrito78** [comment]
Lets add 0.78.1 into the mix and we can see why the notes are missing in current versions:

Top is the HW recording.
Middle is this PR.
Bottom is 0.78.1.

Bildschirmfoto 2022-09-07 um 20 35 43

File: src/hardware/pcspeaker_discrete.h (hunk 1 above)
Comment (kcgen) [reply src/hardware/pcspeaker_discrete.h]: Good point; added a comment and reference to the hardware capture.

File: src/hardware/pcspeaker_impulse.h (hunk 2 above)
Comment (kcgen) [reply src/hardware/pcspeaker_impulse.h]: The impulse PC Speaker code produces louder samples - but the adjustment was also made to match the hardware levels (comment also added).

**Comment by kcgen** [comment]
Thanks @Burrito78. I'm reverting the workaround for paratrooper, which will be a known regression against it. Your issue confirms that the work-around had  side-effects (beyond just paratrooper), so I think it's an acceptable tradeoff  to revert it - given a general solution isn't obvious.

**Comment by kcgen** [comment]
@Burrito78 , when you have a chance to try the new binary: https://github.com/dosbox-staging/dosbox-staging/actions/runs/3010021510, very curious how it goes on your side.

**Comment by kcgen** [comment]
@johnnovak , for the discrete PC Speaker, when I relax its default HPF down to 2nd order and 30 Hz (and leave the LPF per default), I can get very close to @Burrito78's hardware recording.

Just thinking out loud if we should consider switching to it: I would assume if @Burrito78's recording were captured digitally (or using a very high performance DAC, we wouldn't see an filtering), so maybe this 30 Hz is actually modelling the DAC of the recording equipment, as opposed the physical PC speaker - if it was a diaphram->microphone recording?

**Comment by Burrito78** [comment]
Just to clarify, it's not my hardware recording but a recording i got from here:
https://www.zeitgestalten.org/somi_monophony.html

I just asked the author how he did it exactly, maybe we get an answer.

My guess would be that the signal is recorded at line level, parallel to a working PC speaker. Otherwise it would just be square waves. 
And if he used a microphone it propably wouldn't look as clean and don't be as noise free.

**Comment by johnnovak** [comment]
> @johnnovak , for the discrete PC Speaker used above, when I relax its default HPF down to 2nd order and 30 Hz (and leave the LPF per default), I can get very close to @Burrito78's hardware recording.
> 
> Just thinking out loud if we should consider updating its HPF properties.
> 
> If @Burrito78's recording was captured digitally (or using a very high performance DAC), we wouldn't (or shouldn't) see an filtering effects - so I don't think that's the case.
> 
> So I suspect the recording was done using a lower performance DAC (and this 30 Hz is actually capturing the lower bound of its own performance limits), or from a physical speaker -to- microphone (but if so, were PC speakers actually capable of such low frequencies?).

There will be definitely significant differences with no HPF (or very low HPF) vs HPF @ 120 Hz at the waveform level. By the way, there's a master HPF @ 20 Hz in the mixer that cannot be turned off; that gets rid of DC globally.

My view is that comparing the raw waveforms is of limited usefulness if we don't know the exact recording method. E.g. the guy could have used a mixer to record, which might have its own built-in HPF (quite common). Clearly, there was at least some DC blocking going on. If you really want to compare waveforms, you must use a line-out recording that only uses DC blocking or a HPF with a low frequency (20-30 Hz or less).

The HPF @ 120 Hz is meant to emulate how a tiny PC speaker would sound in real life. Combined with the `tiny` reverb preset that adds room ambience, it's a fairly good emulation of the sound of a PC speaker in a computer case about a meter away from you. I would argue that setting 120 Hz is quite generous and low already; I think most of those tiny PC speakers would cut the lows from around 200-250 Hz. So this is quite "hi-fi" already, and I did that on purpose :)

Using lower HPF values or removing the per-channel HPF altogether (the master HPF @ 20 Hz would be still in effect to remove DC and subsonic rumble) is quite a niche use case in my opinion. How many people are using the line-out PC speaker mod to listen to PC speaker audio on big loudspeakers? However, the option is there to emulate that, but I'd very much like to default to something that sounds like an actual PC speaker. Also, in many PC speaker and Tandy game soundtracks the quick toggling of the audio volumes ("staccato" notes) causes low-frequency pops that are quite audible in good headphones and annoy me to no end. Clearly, these artifacts were not audible back in the day on those small integrated speakers, and a HFP from about 80 Hz upwards gets rid of them completely.

**Comment by Burrito78** [comment]
100% agree @johnnovak!

There is a very extensive video by Jim Leonard/Trixter/Mobygames about PC speaker recordings here:
https://www.youtube.com/watch?v=wi2tW23qb9c&t=1788s

As seen in this video, hooking the speaker up to line-in sounds very nice but produces too much bass response. Its cool but unrealistic.

**Comment by Burrito78** [comment]
@kcgen The new build is perfect, thanks!

I checked the first and second song and they are identical except for a small part in the original recording but that was a 30Hz tone so of course its filtered out and thats ok.

After the explanation of @johnnovak i didn't check the `pcspeaker_filter = hpf 2 30 lpf 2 4800`setting as i agree it's pointless to optimize for something synthetic that we also don't know how it was recorded.

**Comment by kcgen** [comment]
Thanks for the detailed explanation, @johnnovak (always learning something from your detailed posts!), and I fully agree. 

It was quite fascinating landing on filter setting that quite closely approximated the recordings - as we were visually comparing the waveforms (I suppose we were lucky in that regard that it was even possible). I suppose the square-wave and digital (full-positive voltage or full-negative voltage) nature of the source waveform makes that a bit more likely. 

Very happy we're back to baseline, and roughly matching upstream as well.
