### PR TITLE
Halt playback by stopping each channel's notes and controllers

### LINKED ISSUE #913: Dosbox should stop midi output on exit.
**Describe the bug**
If the user is using the system synth (or at least alsa) and closes dosbox rather than cleanly exiting the game, whatever notes were playing will play indefinitely.

**To Reproduce**
If DOSBOX is using the system synth, hit alt+f4 to close it.

**Expected behaviour**
I have a script that uses [mido](https://github.com/mido/mido) to reset everything, but it's probably not reasonably to expect every user to be able to do that. I think turning off the notes should be part of the cleanup and shutdown behavior of dosbox.

Grepping around the mido source, it looks like you do this by sending the all notes off and reset all controllers message to every channel. A google search points to that translating to "00 B(0-F) 7B 00" and "00 B(0-F) 79 00" in midi's native language.

Actually just the first one works fine in a test I did with amidi, but mido sends both so that's probably the correct thing to do for whatever reason I don't understand.

**Environment (please complete the following information):**
Arch Linux with alsa.

**Version of dosbox-staging:**

0.77.0-alpha-566-g761cb2db

Though this has been an issue since the beginning of time afaik

**Configuration parameters:**
[midi]
mididevice = alsa
midiconfig = 130:0
mpu401     = intelligent

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #913, which causes MIDI notes to continue playing when DOSBox is closed while MIDI is currently playing.

Thanks to @BPaden for reporting this and providing the MIDI message sequences to properly stop each channel's notes and controllers.

Ref: Mido - MIDI Objects for Python, https://github.com/mido/mido

### CODE REVIEW

File: src/midi/midi_mt32.cpp [hunk 1]
```diff
@@ -367,6 +367,8 @@ void MidiHandler_mt32::Close()
 	if (!is_open)
 		return;
 
+	HaltSequence();
```
Comment (dreamer) [inline src/midi/midi_mt32.cpp:370]: I don't think we need this sequence for a built-in mt32emu.

File: src/midi/midi_fluidsynth.cpp [hunk 2]
```diff
@@ -313,6 +313,8 @@ void MidiHandlerFluidsynth::Close()
 	if (!is_open)
 		return;
 
+	HaltSequence();
```
Comment (dreamer) [inline src/midi/midi_fluidsynth.cpp:316]: I don't think we need this for built-in FluidSynth.

File: src/midi/midi_handler.h [hunk 3]
```diff
@@ -47,6 +48,24 @@ class MidiHandler {
 
 	virtual void Close() {}
 
+	void HaltSequence()
+	{
+		uint8_t message[MIDI_MSG_SIZE] = {};
```
Comment (dreamer) [inline src/midi/midi_handler.h:53]: Do we really need MIDI_MSG_SIZE here? We use only 2 bytes.

File: src/midi/midi_handler.h [hunk 4]
```diff
@@ -26,7 +26,8 @@
 
 #include <cstdint>
 
-#define SYSEX_SIZE 8192
+constexpr auto MIDI_MSG_SIZE = 8;
+constexpr auto MIDI_SYSEX_SIZE = 8192;
```
Comment (dreamer) [inline src/midi/midi_handler.h:30]: I think MIDI_MSG_SIZE does not need to be exposed.

MIDI_SYSEX_SIZE - maybe it should be transferred from midi_handler.h to midi.h? (I'm not sure).

**Review by dreamer — CHANGES_REQUESTED** [review]

File: src/midi/midi_mt32.cpp (hunk 1 above)
Comment (kcgen) [reply src/midi/midi_mt32.cpp:370]: In theory mt32emu and FluidSynth gracefully halt their in-progress sequence (so the last notes are played followed by silence) when we shut them down. 

But in practice, we stop the mixer channel first before the request to close them, so the music is abruptly stopped.  Which is fine.. and it works 100% of the time.  But I was hoping by adding this message before stopping the channel, we could get a more graceful close of the actual audio stream before the channel's cutoff. 

But it's perhaps just wishful thinking, and we can. Just terminate it hard like we currently do.

File: src/midi/midi_fluidsynth.cpp (hunk 2 above)
Comment (kcgen) [reply src/midi/midi_fluidsynth.cpp:316]: (same answer above; I'm inclined to agree, but curious what you think about my reason).

File: src/midi/midi_handler.h (hunk 3 above)
Comment (kcgen) [reply src/midi/midi_handler.h:53]: Unlike PlaySyse(*, len), the PlayMsg(*) API takes in a buffer (pointer) but doesn't let you specify the buffer length. 

The current MIDI structure uses a fixed message buffer of eight characters, and that's proven to work cross-platform with all kinds of different MIDI players. So that's what I'm using here too.

But you're right: the MIDI spec says messages can be two or three byte sequences, and they don't even mention providing a terminatinf character (such as 0x0).  So I could try a strict 2-byte array, and if the MIDI software tries reading the 3rd byte (it will bus error?).

File: src/midi/midi_handler.h (hunk 4 above)
Comment (kcgen) [reply src/midi/midi_handler.h:30]: Yes, if we try a three-byte message length, then the concept of MSG_SIZE being a constant magic number goes away.  In which case the need to refactor the SYSEX_SIZE as a "sister-value" also goes away in this PR.. unless we want to include it still, which I'm happy doing. 

I know you want to do some heavier MIDI refactoring with the handlers anyway, before we take on the sf2-load-in-parallel PR. So maybe can do this in the refactoring PR?

File: src/midi/midi_mt32.cpp (hunk 1 above)
Comment (dreamer) [reply src/midi/midi_mt32.cpp:370]: I agree. We shouldn't try to fix something that's not really broken. Future maintainers might think there's some deeper meaning behind injecting this halting sequence.

*IF* abrupt closing of mixer is going to be a problem, then we should implement the adjustment in mixer (so it could be shared for pc-speaker, sblaster, and other channels). However, I don't think we have a problem at all - OS-level mixer (PulseAudio, PipeWire, etc) is probably dealing with this already.

For ALSA, win32, CoreMIDI, etc - we do need to do this because (some) MIDI synthesisers don't detect the MIDI channel going completely dark (hardware generally can't, external FluidSynth 1.1 couldn't, external Timidity was detecting it and stopping the audio 2-3s after no new MIDI instructions arrived).

File: src/midi/midi_handler.h (hunk 3 above)
Comment (dreamer) [reply src/midi/midi_handler.h:53]: Yeah, I don't understand why there are 8 bytes in there…

I am perfectly OK with having 3 bytes ending with 0-byte :) I think all our backends only look up up to 3 bytes at a time.

File: src/midi/midi_handler.h (hunk 4 above)
Comment (kcgen) [reply src/midi/midi_handler.h]: > maybe it should be transferred from midi_handler.h to midi.h

I think so too.
- `MIDI_SYSEX_SIZE` defines a size for a struct defined in `midi.cpp`, so logically it should live in either the cpp or header
- `MIDI_SYSEX_SIZE` is used by other classes that include `midi.h`, so needs to go up in the header.

File: src/midi/midi_handler.h (hunk 3 above)
Comment (kcgen) [reply src/midi/midi_handler.h]: More digging into how the MIDI device knows out when to stop reading this buffer.

Turns out the first byte is looked-up in a length table:

```

uint8_t MIDI_evt_len[256] = {
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x00
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x10
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x20
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x30
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x40
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x50
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x60
  0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,  // 0x70

  3,3,3,3, 3,3,3,3, 3,3,3,3, 3,3,3,3,  // 0x80
  3,3,3,3, 3,3,3,3, 3,3,3,3, 3,3,3,3,  // 0x90
  3,3,3,3, 3,3,3,3, 3,3,3,3, 3,3,3,3,  // 0xa0
  3,3,3,3, 3,3,3,3, 3,3,3,3, 3,3,3,3,  // 0xb0

  2,2,2,2, 2,2,2,2, 2,2,2,2, 2,2,2,2,  // 0xc0
  2,2,2,2, 2,2,2,2, 2,2,2,2, 2,2,2,2,  // 0xd0

  3,3,3,3, 3,3,3,3, 3,3,3,3, 3,3,3,3,  // 0xe0

  0,2,3,2, 0,0,1,0, 1,0,1,1, 1,0,1,0   // 0xf0
};
```

Our halt sequence always starts with `0xb`, so our buffer should be three bytes. 

Also double checked that `PlayMsg(*)` implementations will indeed expect to read `message[2]` (in this case), but no further.

``` c++
void MidiHandler_oss::PlayMsg(const uint8_t *msg)
{
	const uint8_t len = MIDI_evt_len[*msg];
	uint8_t buf[128];
	assert(len * 4 <= sizeof(buf));
	size_t pos = 0;
	for (uint8_t i = 0; i < len; i++) {
		buf[pos++] = SEQ_MIDIPUTC;
		buf[pos++] = *msg;
		buf[pos++] = device_num;
		buf[pos++] = 0;
		msg++;
	}
	write(device, buf, pos);
}
```

**Review by dreamer — APPROVED** [review]
@kcgen Thanks! Looks great now :)

I managed to reproduce the bug using external FluidSynth 2.1 - and confirm your fix properly stops the MIDI music :)
