### PR TITLE
Only process MT-32 debug messages in debug builds

### LINKED ISSUE #3096: Ghost Busters II w/ MT-32 crashes Dosbox
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-1907-g256822025

### What Operating System are you using?

macOS (Apple Silicon)

### If Other OS, please describe

MacOS Sonoma 14.0

### Relevant hardware info

Macbook Air M1

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Story Mode:
Vigo may be the scourge of Carpathia, but this game is the scourge of my existence. I had this game on my 286 back in the day. There was a bug in it that would cause it to lock up after playing digital sounds, either to the PC speaker, or the sound blaster, depending what it felt like doing that day. Low and behold Dosbox’s emulation is so good that the same thing happens. Fortunately Creative Labs created a patch for the game that fixes the issue, but now I’ve run into another problem. Once the game is patched it runs smoothy unless you are using MT-32 music on MacOS (0.81.0-alpha-1907-g256822025) (Arm) Dosbox crashes out when you get to the lab. It does not crash on Win x64 (0.81.0-alpha-1907-g25682) though.

TLDR: Ghost Busters II crashes on MacOS (0.81.0-alpha-1907-g256822025) but not Win x64 (0.81.0-alpha-1907-g25682) If you are using MT-32 music.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Obtain game from link
2. Extract all 5 ZIPs into folder
3. run GB2FIX.EXE to patch sound blaster issues.
4. (Configure Dosbox to use MT-32)
5. run command:  "GBII.COM EGA MT-32 MOUSE"
6. 

### Download URL of affected game or software

http://www.abandonia.com/en/downloadgame/326

### Your configuration

```ini
https://file.io/j76SKATbfkfd
```

### Provide a Log

```text
https://file.io/Ch4WHBTt4D5f
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
# Description

Skips processing MT-32 debug messages in release builds because it can be excessive:

Also changes the logic slight to let Loguru process the variable list directly, which fixes #3096.

## Related issues

Fixes #3096, both in release and debug builds.

# Manual testing

Tested MT-32 in release, debug, and sanitizer builds.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/midi/midi_mt32.cpp [hunk 1]
```diff
@@ -527,11 +527,17 @@ static mt32emu_report_handler_i get_report_handler_interface()
...
-			safe_sprintf(msg, fmt, list);
-			LOG_DEBUG("MT32: %s", msg);
+#if !defined(NDEBUG)
+			// Skip processing MT-32 debug output in release builds
+			// because it can be bursty
+			char msg[1024] = "MT32: ";
+			assert(fmt);
+			safe_strcat(msg, fmt);
+			LOG_DEBUG(msg, list);
+#endif
```
Comment (johnnovak) [inline src/midi/midi_mt32.cpp:540]: So do we understand how the debug logging resulted in a crash? Can't be a buffer overflow because of `safe_strcat`, can it?

Comment (kcgen) [reply src/midi/midi_mt32.cpp:540]: Yes; the VA list contained some symbols and junk values that weren't handled properly. I could have added more error checking, but in the end we had two formatting passes here (our own then logurus); so I opted to let Loguru do the VA list formatting (as it has all the return values checks from vsnprintf).

Comment (johnnovak) [reply src/midi/midi_mt32.cpp:540]: Thanks for the explanation @kcgen 👍🏻

**Review by johnnovak — APPROVED** [review]
Nice one @kcgen
