### PR TITLE
Fix a regression in the composite color palette calculation

### LINKED ISSUE #1874: PC_Jr Composite no longer working in 0.1153
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

_No response_

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This works fine in the last version I downloaded 0.561
The latest version gives me only shades of blue when I hit F12 to enter composite mode with the game (Below the Root).
I'm not sure how long this has been broken, I haven't tried several versions.

The Reverb and Chorus sound nice though...

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load Below the Root
2. Press F12
3.

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
When built with optimizations, the red composite 8-bit palette index could rollover from 255 to 0 as a result of prior floating point calculations.

In tracking this down, I also added checks for type narrowing, so this PR includes those cleanups as well (most of which involve loss-of-precision warnings when performing bit operations on 8-bit values).

Thanks to @jkapp76 for flagging this!

Fixes #1874.

### CODE REVIEW

File: src/hardware/vga_other.cpp [hunk 1]
```diff
@@ -559,9 +566,16 @@ static void update_cga16_color_pcjr()
...
-				const auto without_gamma = clamp(powf(v, 1 / gamma), 0.0f, 1.0f);
-				return static_cast<uint8_t>(255 * without_gamma);
+			auto to_8bit_without_gamma = [=](const float v) -> uint8_t {
+				// Only operate on reasonably positive v-values
+				if (!isnormal(v) || v <= 0.0f)
+					return 0;
+
+				// Remove gamma and scale the result to the 8-bit range
+				constexpr int max_8bit = UINT8_MAX;
+				const auto no_gamma = powf(v, 1.0f / gamma) * max_8bit;
```
Comment (johnnovak) [inline src/hardware/vga_other.cpp:576]: picky: maybe instead of "removing the gamma" you could use the terms "gamma decoding" or "linear RGB".

Comment (kcgen) [reply src/hardware/vga_other.cpp:576]: Thanks @johnnovak ; also renamed the lamda function to `to_linear_rgb`.

**Comment by kcgen** [comment]
Not much more to review, and the PR has been tested.
Going ahead w/ the merge.
