### PR TITLE
Limit consecutive duplicate frames in VFR presentation mode

### LINKED ISSUE #2993: Switching between fullscreen/windowed sometimes results in a black screen.
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

macOS (Apple Silicon)

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Switching between fullscreen/windowed sometimes results in a (temporary, up to 1 second) black screen.

The issue is cycles dependent! Witch cycles=30000 you barely notice it, with cycles=1000 the screen stays black for longer periods.

Also it's not consistent, so sometimes the screen comes back instantly, sometimes it takes longer.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install latest DEV version of Staging.
2. Use eXoDOS v5 version of Falcon A.T. or download the repro pack.
3. Launch with efalcon.exe
4. Switch between windowed and fullscreen.

[EFalcon.zip](https://github.com/dosbox-staging/dosbox-staging/files/12880752/EFalcon.zip)

This is the screen i'm testing with:
Bildschirmfoto 2023-10-12 um 13 14 45

### Download URL of affected game or software

_No response_

### Your configuration

```ini
default config
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
# Description

VFR mode could previously have a presentation rate of 0 fps leading
to a blank screen across fullscreen-window mode switches.

This commit ensures a lower-bound of 10 fps (at all DOS rates),
even if all frames are duplicates.

Thanks to:
- @GranMinigun for explaining the root cause is due to tearing down and re-instanting the rendering stack across FS and window-mode switches.
- @johnnovak for the suggestion to re-instate a minimum configurable rate for the VFR presentation modes

## Related issues

Fixes #2993

# Manual testing

Tested with Falcon AT, static CLI screens, and ran benchmarks, along with a  a range of allowable `dos_rate` values from 30 to 1000 Hz.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by FeralChild64** [comment]
Is there any good reason to make it configurable instead of hardcoded to some sane value? I'm afraid at some point we will end up overwhelming the users with configuration which is too detailed and technical.

**Comment by johnnovak** [comment]
> [edit] How about fixing the original problem by enforcing new frame if view is resized or when switched between window or fullscreen?

It's more than that; we're not just fixing the missed frame issue when a resize or fullscreen/windowed switch happens (see next point).

> Is there any good reason to make it configurable instead of hardcoded to some sane value? I'm afraid at some point we will end up overwhelming the users with configuration which is too detailed and technical.

Unfortunately, it's impossible to guess a good low FPS cap for VRR. The 10% thing @kcgen introduced (so we got 7 FPS for 70 Hz VGA games) was just something random and that would cause problems for many VRR monitors in some circumstances. E.g., some VRR monitors require min 48 FPS, some maybe 30-35, then some others can go lower maybe to a single digit range, but you actually need a much higher minimum FPS to minimise jerky motion, etc. I don't actually have a VRR display, but that's my understanding; it's still the wild west, there are many competing and incompatible standards, so you need to configure this by hand.

File: src/gui/sdlmain.cpp [hunk 1]
```diff
@@ -1040,9 +1024,10 @@ static void setup_presentation_mode(FrameMode &previous_mode)
 	VGA_SetHostRate(host_rate);
 	const auto dos_rate = VGA_GetPreferredRate();
 
-	// Update the VFR duplicate countdown based on the DOS rate to produce a
-	// fixed lower-bound dupe refresh rate.
-	set_vfr_dupe_countdown_from_rate(dos_rate);
+	// Calculate the maximum number of skippable frames before presenting
+	const auto max_skippable = std::ceil(dos_rate / sdl.frame.vfr_min_rate);
+	sdl.frame.vfr_max_skippable = check_cast<int16_t>(iround(max_skippable));
+	assert(sdl.frame.vfr_max_skippable > 0);
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:1030]: Hmm, can't we just maintain a fractional max skippable value and check against that? Is there something to gain here by rounding up?

File: src/gui/sdlmain.cpp [hunk 2]
```diff
@@ -2352,19 +2337,26 @@ void GFX_EndUpdate(const uint16_t *changedLines)
 		// capture modes.
 		sdl.frame.present();
 	} else {
-		const auto frame_is_new = sdl.updating;
+		auto is_new_or_unskippable = []() {
+			static auto remaining_skips = sdl.frame.vfr_max_skippable;
+			if (sdl.updating || --remaining_skips == 0) {
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:2342]: Could just check if it goes below zero if we kept it fractional?

File: src/gui/sdlmain.cpp [hunk 3]
```diff
@@ -3527,6 +3519,10 @@ static void GUI_StartUp(Section *sec)
 		            presentation_mode_pref.c_str());
 	}
 
+	const auto vfr_min_rate = section->Get_int("vfr_minimum_rate");
+	assert(vfr_min_rate > 0 && vfr_min_rate <= RefreshRateMax);
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:3523]: Should this rather be an actual runtime check? In that case, we should document that valid values are in the 1 to 1000 Hz range, and if the provided value is outside of this range, we should default to 7 and log an error.

File: src/gui/sdlmain.cpp [hunk 4]
```diff
@@ -4223,6 +4219,12 @@ static void config_add_sdl() {
 	        "  vfr:   Always present changed DOS frames at a variable frame rate.");
 	pstring->Set_values(presentation_modes);
 
+	pint = sdl_sec->Add_int("vfr_minimum_rate", always, 7);
+	pint->Set_help(
+	        "Set VFR presentation mode's minimum refresh rate, in Hz (7 by default).\n"
+	        "Note the DOS rate determines the maximum VFR rate; this does not override it.");
+	pint->SetMinMax(1, RefreshRateMax);
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:4226]: Ah, ok, so we've already provided a valid value range here. Then we should perhaps document it in the description?

**Review by johnnovak — COMMENTED** [review]
Looks good @kcgen, that was quick 🎉 Just minor comments/questions.

**Comment by Kappa971** [comment]
> Unfortunately, it's impossible to guess a good low FPS cap for VRR. The 10% thing @kcgen introduced (so we got 7 FPS for 70 Hz VGA games) was just something random and that would cause problems for many VRR monitors in some circumstances. E.g., some VRR monitors require min 48 FPS, some maybe 30-35, then some others can go lower maybe to a single digit range, but you actually need a much higher minimum FPS to minimise jerky motion, etc. I don't actually have a VRR display, but that's my understanding; it's still the wild west, there are many competing and incompatible standards, so you need to configure this by hand.

You can safely avoid a new setting and insert a minimum value in the code. For VRR users there is the CFR presentation mode, created especially for them by @kcgen (maybe it should be specified somewhere, also for future developers).

**Comment by johnnovak** [comment]
> You can safely avoid (I think) a new setting and insert a minimum value in the code. For VRR users there is the CFR presentation mode, created especially for them by @kcgen (maybe it should be specified somewhere, also for future developers), so anything related to VFR presentation mode should not apply to variable refresh rate monitors.

@0mnicydle mentioned he needed such a min threshold for his VRR monitor, but he was doing some custom hackery that involved `dos_rate`.

But you're right, being able to auto-sync to any PC, console and home computer refresh rate (including fractional ratios) is one of the huge selling points of VRR displays.

I guess @kcgen 's other point was energy consumption when using DOS applications. That's a fair point, but uncommon for emulators to do this -- all I know of send frames all the time.

Personally, I'd set this to some high value when using VRR, so just a bit below 50, say 45. Another interesting question, what would happen in the scenario if we always auto-set this to the minimum of the host rate or the DOS screen mode's refresh rate? Or we could use a multiplier and set it to DOS refresh rate / 2.

**Comment by 0mnicydle** [comment]
> @0mnicydle mentioned he needed such a min threshold for his VRR monitor, but he was doing some custom hackery that involved `dos_rate`.

Normally I use 70Hz CFR on my 144Hz VRR monitor, as that provides the best experience under normal circumstances imo, and makes DOSBox frame delivery like every other emulator I use. However, when forcing `dos_rate` to 1000Hz I don't want 1000Hz of mostly duplicates sent to the monitor as it would oversaturate the refresh rate and fail to engage VRR. If I could configure the minimum in this scenario between 1-1000, I would probably set it to 1Hz as it doesn't create major problems for me on my hardware to have no floor (og DOSBox VFR). Other monitors might need a higher floor to avoid the shortcomings of some of the other VRR implementations.

The reason I prefer 70Hz CFR to 70Hz VFR on my VRR monitor under normal circumstances is because low incoming rates can result in very slight but perceptible flicker as the refresh rate swings wildly between extreme low and nominal rates. It's a sacrifice I'm willing to make for 1000Hz, but something I'd rather avoid when I can.

**Comment by johnnovak** [comment]
Thanks @0mnicydle for the further info, now it makes complete sense.

Look guys, I'm not againt this extra config option. It's a bit like an advanced option such as `dos_rate`. Regular user should never ever touch it, but it's there for power users. I have no problems with such extra setting (but agree in general that we should do our best to keep the number of settings we add to a minimum)

**Comment by Kappa971** [comment]
> Thanks @0mnicydle for the further info, now it makes complete sense.
> 
> Look guys, I'm not againt this extra config option. It's a bit like an advanced option such as `dos_rate`. Regular users should never ever touch it, but it's there for power users. I have no problems with such extra setting (but agree in general that we should do our best to keep the number of settings we add to a minimum)

I think, in fact, an option like this is useless except for rare use cases like for @0mnicydle. I would opt to insert a minimum frequency in the code and avoid further setting. This is just my opinion but whatever decision is made, it will be fine.

**Comment by kcgen** [comment]
I'll knock out the conf setting in favour of a ~10 Hz guaranteed rate in the VFR modes, regardless of the DOS rate. 

I just remembered we discussed making this configurable some months back, but I'm glad it really has no benefit (even when DOS rate == 1000 Hz, this is still only going to be a 10 Hz minimum, just filling in when existing new frames don't exist).

**Comment by johnnovak** [comment]
> I'll knock out the conf setting in favour of a ~10 Hz guaranteed rate in the VFR modes, regardless of the DOS rate.
> 
> I just remembered we discussed making this configurable some months back, but I'm glad it really has no benefit (even when DOS rate == 1000 Hz, this is still only going to be a 10 Hz minimum, just filling in when existing new frames don't exist).

How about setting the "dupe rate to" `min(dos_rate, host_rate)` and be done with it? Ideally, that's what I want from a VFR mode when we need to somehow display 70Hz rate content on a 60Hz display—drop frames when needed, but adhere to the host rate. Like I said many times, I don't really like this present-on-demand business, it just leads to complications, so ideally I'd take it out of the equation by always presenting a frame at `min(dos_rate, host_rate)`

Then @0mnicydle will cope with it when using 1000 Hz refresh rates 😎 Sorry man 😄

**Comment by 0mnicydle** [comment]
> Then @0mnicydle will cope with it when using 1000 Hz refresh rates 😎 Sorry man 😄

Oof yeah, I think that might render 1000Hz unworthy to me at that point, sadly. The whole Idea is to leave as many possible refresh cycles for unique frames available as possible.

**Comment by johnnovak** [comment]
> > Then @0mnicydle will cope with it when using 1000 Hz refresh rates 😎 Sorry man 😄
> 
> Oof yeah, I think that might render 1000Hz unworthy to me at that point, sadly. The whole Idea is to leave as many refresh cycles available for unique frames as possible.

Config option then (I'm easy 😎) and default to the min solution @kcgen ? Any drawbacks to that? Good defaults combined with full manual control?

File: src/gui/sdlmain.cpp (hunk 1 above)
Comment (kcgen) [reply src/gui/sdlmain.cpp:1030]: With a fixed min rate, this rounding will go away :slightly_smiling_face:

File: src/gui/sdlmain.cpp (hunk 3 above)
Comment (kcgen) [reply src/gui/sdlmain.cpp:3523]: conf setting is being knocked out

File: src/gui/sdlmain.cpp (hunk 4 above)
Comment (kcgen) [reply src/gui/sdlmain.cpp:4226]: (ditto as above; conf setting being knocked out)

**Comment by kcgen** [comment]
Additional testing.. VFR should still be very smooth in these:
- [dangerous_dave.zip](https://github.com/dosbox-staging/dosbox-staging/files/12912561/dangerous_dave.zip)
- [Keen1.zip](https://github.com/dosbox-staging/dosbox-staging/files/12912562/Keen1.zip)

The game have their own `dosbox.conf`.
Just unzip, `cd` inside the game directory, and launch this PR executable.
Then watch the intro sequences; the scrolling should be butter smooth.

File: src/gui/sdlmain.cpp [hunk 5]
```diff
@@ -1040,9 +1024,9 @@ static void setup_presentation_mode(FrameMode &previous_mode)
 	VGA_SetHostRate(host_rate);
 	const auto dos_rate = VGA_GetPreferredRate();
 
-	// Update the VFR duplicate countdown based on the DOS rate to produce a
-	// fixed lower-bound dupe refresh rate.
-	set_vfr_dupe_countdown_from_rate(dos_rate);
+	// Calculate the maximum number of duplicate frames before presenting
+	constexpr int8_t min_rate = 10;
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:1028]: auto?

File: src/gui/sdlmain.cpp [hunk 6]
```diff
@@ -2352,19 +2336,26 @@ void GFX_EndUpdate(const uint16_t *changedLines)
...
 	} else {
-		const auto frame_is_new = sdl.updating;
+		auto is_new_or_unskippable = []() {
+			static int16_t dupe_tally = 0;
+			if (sdl.updating || ++dupe_tally > sdl.frame.max_dupe_frames) {
+				dupe_tally = 0;
+				return true;
+			}
+			return false;
+		};
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:2346]: Am I reading this correct, so say if we're in a 70 Hz DOS mode, max dupe frames will be 7.0. So if the program is displaying a still image, we're counting frames, then at the 8th frame we present the frame anyway? So we're effectively maintaining a steady 10 FPS even for still images, no matter what.

Also, I'm not sure what `unskippable` refers to here.

**Comment by kcgen** [comment]
@FeralChild64,

> How about fixing the original problem by enforcing new frame if view is resized or when switched between window or fullscreen?

The root cause is that we're tearing down the entire renderer and context across the fullscreen-to-window (and vice-versa) transitions, and re-creating it has some undefined host-side lag and so rendering immediately after isn't a guaranteed fix.

@GranMinigun's sdl rework retains the rendering stack, and so we'll be able to re-drop this then. 

Image another scenario where we outright kill and recreate the mixer mid-playback, resulting in an audible gaps and pops. One approach might be to pre-ramp down and ramp-up across the mixer-kill events; and then some users might complain about those volume ramps.. 

I think the best approach is to treat the mid-game destruction of the rendering and context as a design bug in sdlmain; but that's a more involved fix.

File: src/gui/sdlmain.cpp (hunk 5 above)
Comment (kcgen) [reply src/gui/sdlmain.cpp:1028]: `auto` will make it an `int` which (just as a type size) is too big to perfectly divide a `float`, so this will generate a precision loss warning (depending on flags). I've made it an `uint16_t`, which more accurately spans the allowable Hz range (0 Hz to 1000 Hz).

**Comment by Burrito78** [comment]
> @Burrito78 , can you confirm w/ the latest CI image, as well as check the two test-case zips above?

Testing kc/vfr-minimum-rate-1 using build
Bildschirmfoto 2023-10-16 um 21 28 08

PHM Pegasus switching between fullscreen/windowed = OK

Smooth scrolling test for Dangerous Dave = Buttery smooth using MacBook Air internal screen. 
Log:

```
Last login: Mon Oct 16 21:35:45 on ttys000
alex@AirvonAlexander ~ % /Users/alex/Games/dangerous_dave/Start\ DOSBox\ Staging\ \(logging\).command ; exit;
date       time         | 
2023-10-16 21:35:45.417 | arguments: /Applications/DOSBox\ Staging.app/Contents/MacOS/dosbox --working-dir /Users/alex/Games/dangerous_dave
2023-10-16 21:35:45.417 | Current dir: /Users/alex
2023-10-16 21:35:45.417 | stderr verbosity: 0
2023-10-16 21:35:45.417 | -----------------------------------
2023-10-16 21:35:45.417 | dosbox-staging version 0.81.0-alpha-1781-g9a563f786
2023-10-16 21:35:45.417 | ---
2023-10-16 21:35:45.417 | LOG: Loguru version 2.1.0 initialised
2023-10-16 21:35:45.509 | SDL: version 2.28.2 initialised (cocoa video and coreaudio audio)
2023-10-16 21:35:45.510 | CONFIG: Loaded primary config file '/Users/alex/Library/Preferences/DOSBox/dosbox-staging.conf'
2023-10-16 21:35:45.510 | CONFIG: Loaded local config file 'dosbox.conf'
2023-10-16 21:35:45.511 | LANG: Loaded language file: /Applications/DOSBox Staging.app/Contents/MacOS/../Resources/translations/de.lng
2023-10-16 21:35:45.511 | DISPLAY: Accepted window resolution 1440x1080 despite exceeding the 1470x956 display
2023-10-16 21:35:45.511 | DISPLAY: Initialised 1440x1080 windowed mode using bilinear scaling on display-0
2023-10-16 21:35:45.533 dosbox[2664:6220740] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2023-10-16 21:35:45.873 | OPENGL: Vendor: Apple
2023-10-16 21:35:45.873 | OPENGL: Version: 2.1 Metal - 86
2023-10-16 21:35:45.873 | OPENGL: GLSL version: 1.20
2023-10-16 21:35:45.873 | OPENGL: Pixel buffer object available
2023-10-16 21:35:45.873 | OPENGL: NPOT textures supported
2023-10-16 21:35:45.873 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
2023-10-16 21:35:45.882 | RENDER: Auto-switched to shader 'crt/hercules'
2023-10-16 21:35:45.882 | VGA: Pixel-doubling enabled
2023-10-16 21:35:45.882 | VIDEO: Using a custom DOS graphical frame rate of 60 Hz
2023-10-16 21:35:45.886 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0x129004000
2023-10-16 21:35:45.887 | CAPTURE: Image capturer started
2023-10-16 21:35:45.946 | MIXER: Negotiated 2-channel 48000 Hz audio in 512-frame blocks
2023-10-16 21:35:45.946 | MIXER: Master compressor enabled
2023-10-16 21:35:45.946 | MIDI: MIDI device set to 'none'; disabling MIDI output
2023-10-16 21:35:45.946 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-10-16 21:35:45.946 | PCSPEAKER: Operating at 48000 Hz without resampling
2023-10-16 21:35:45.946 | PCSPEAKER: Initialised discrete model
2023-10-16 21:35:45.946 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-10-16 21:35:45.946 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-10-16 21:35:45.946 | MOUSE: Will be captured after the first left or right button click
2023-10-16 21:35:45.946 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2023-10-16 21:35:45.946 | MOUSE (PS/2): Standard, 3 buttons
2023-10-16 21:35:45.958 | RENDER: Auto-switched to shader 'crt/ega-1440p'
2023-10-16 21:35:45.959 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2023-10-16 21:35:46.173 | DISPLAY: EGA 640x350 16-colour text mode 03h at 60 Hz VFR, scaled to 2333x1750 with 1:1.37143 (35:48) pixel aspect ratio
2023-10-16 21:35:46.506 | LAYOUT: Loaded codepage 850 for detected language de
2023-10-16 21:35:46.509 | CONFIG: Loaded auto-mounted drive config file '/Applications/DOSBox Staging.app/Contents/MacOS/../Resources/drives/y.conf'
2023-10-16 21:35:46.509 | AUTOEXEC: Using autoexec from one or more joined sections
2023-10-16 21:35:46.517 | MAPPER: joystick subsystem disabled
2023-10-16 21:35:46.518 | MAPPER: Loaded default key bindings
2023-10-16 21:35:46.518 | SHELL: Redirecting output to NUL
2023-10-16 21:35:46.519 | MOUNT: Path '/Applications/DOSBox Staging.app/Contents/Resources/drives/y' found
2023-10-16 21:35:46.520 | MOUNT: Path '.' found
2023-10-16 21:35:47.723 | RENDER: Auto-switched to shader 'crt/ega-4k'
2023-10-16 21:35:47.756 | DISPLAY: EGA 320x200 16-colour graphics mode 0Dh at 60 Hz VFR, scaled to 2133x1600 with 1:1.2 (5:6) pixel aspect ratio
2023-10-16 21:35:52.740 | DISPLAY: EGA 320x200 16-colour graphics mode 0Dh at 60 Hz VFR, scaled to 2400x1800 with 1:1.2 (5:6) pixel aspect ratio
2023-10-16 21:36:21.761 | DISPLAY: EGA 320x200 16-colour graphics mode 0Dh at 60 Hz VFR, scaled to 2133x1600 with 1:1.2 (5:6) pixel aspect ratio
```

Smooth scrolling test for Keen 1 = MINIMAL jerkiness as expected, but super subtle.

```
Last login: Mon Oct 16 21:39:08 on ttys000
alex@AirvonAlexander ~ % /Users/alex/Games/Keen1/Start\ DOSBox\ Staging\ \(logging\).command ; exit;
date       time         | 
2023-10-16 21:39:08.285 | arguments: /Applications/DOSBox\ Staging.app/Contents/MacOS/dosbox --working-dir /Users/alex/Games/Keen1
2023-10-16 21:39:08.286 | Current dir: /Users/alex
2023-10-16 21:39:08.286 | stderr verbosity: 0
2023-10-16 21:39:08.286 | -----------------------------------
2023-10-16 21:39:08.286 | dosbox-staging version 0.81.0-alpha-1781-g9a563f786
2023-10-16 21:39:08.286 | ---
2023-10-16 21:39:08.286 | LOG: Loguru version 2.1.0 initialised
2023-10-16 21:39:08.381 | SDL: version 2.28.2 initialised (cocoa video and coreaudio audio)
2023-10-16 21:39:08.382 | CONFIG: Loaded primary config file '/Users/alex/Library/Preferences/DOSBox/dosbox-staging.conf'
2023-10-16 21:39:08.382 | CONFIG: Loaded local config file 'dosbox.conf'
2023-10-16 21:39:08.383 | LANG: Loaded language file: /Applications/DOSBox Staging.app/Contents/MacOS/../Resources/translations/de.lng
2023-10-16 21:39:08.383 | DISPLAY: Accepted window resolution 1440x1080 despite exceeding the 1470x956 display
2023-10-16 21:39:08.383 | DISPLAY: Initialised 1440x1080 windowed mode using bilinear scaling on display-0
2023-10-16 21:39:08.405 dosbox[2914:6224294] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2023-10-16 21:39:08.742 | OPENGL: Vendor: Apple
2023-10-16 21:39:08.742 | OPENGL: Version: 2.1 Metal - 86
2023-10-16 21:39:08.742 | OPENGL: GLSL version: 1.20
2023-10-16 21:39:08.742 | OPENGL: Pixel buffer object available
2023-10-16 21:39:08.742 | OPENGL: NPOT textures supported
2023-10-16 21:39:08.742 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
2023-10-16 21:39:08.752 | RENDER: Auto-switched to shader 'crt/hercules'
2023-10-16 21:39:08.752 | VGA: Pixel-doubling enabled
2023-10-16 21:39:08.752 | VIDEO: Using the DOS video mode's frame rate
2023-10-16 21:39:08.756 | MEMORY: Using 1024 DOS memory pages (4 MB) at address: 0x1115f0000
2023-10-16 21:39:08.756 | VGA: Double-scanning VGA video modes enabled
2023-10-16 21:39:08.756 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2023-10-16 21:39:08.758 | CAPTURE: Image capturer started
2023-10-16 21:39:08.814 | MIXER: Negotiated 2-channel 48000 Hz audio in 512-frame blocks
2023-10-16 21:39:08.815 | MIXER: Master compressor enabled
2023-10-16 21:39:08.815 | MIDI: MIDI device set to 'none'; disabling MIDI output
2023-10-16 21:39:08.815 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-10-16 21:39:08.815 | OPL: Operating at 48000 Hz without resampling
2023-10-16 21:39:08.815 | OPL: Running OPL3 on ports 220h and 388h
2023-10-16 21:39:08.815 | SBPRO2: Sound Blaster Pro 2 OPL output filter enabled
2023-10-16 21:39:08.815 | OPL: Lowpass filter enabled (6 dB/oct at 8000 Hz)
2023-10-16 21:39:08.815 | DMA: Initialised primary controller
2023-10-16 21:39:08.815 | SB: Operating at 22050 Hz and upsampling to the output rate
2023-10-16 21:39:08.815 | SBPRO2: Modern DAC output filter enabled
2023-10-16 21:39:08.815 | SBPRO2: Setting 'BLASTER' environment variable to 'A220 I7 D1 T4'
2023-10-16 21:39:08.815 | SBPRO2: Running on port 220h, IRQ 7, and DMA 1
2023-10-16 21:39:08.815 | PCSPEAKER: Operating at 48000 Hz without resampling
2023-10-16 21:39:08.815 | PCSPEAKER: Initialised discrete model
2023-10-16 21:39:08.815 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-10-16 21:39:08.815 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-10-16 21:39:08.815 | MOUSE: Will be captured after the first left or right button click
2023-10-16 21:39:08.815 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2023-10-16 21:39:08.815 | MOUSE (PS/2): Standard, 3 buttons
2023-10-16 21:39:08.827 | RENDER: Auto-switched to shader 'crt/vga-4k'
2023-10-16 21:39:08.828 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2023-10-16 21:39:09.056 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 2133x1600 with 1:1.35 (20:27) pixel aspect ratio
2023-10-16 21:39:09.117 | LAYOUT: Loaded codepage 850 for detected language de
2023-10-16 21:39:09.118 | CONFIG: Loaded auto-mounted drive config file '/Applications/DOSBox Staging.app/Contents/MacOS/../Resources/drives/y.conf'
2023-10-16 21:39:09.118 | AUTOEXEC: Using autoexec from one or more joined sections
2023-10-16 21:39:09.123 | MAPPER: joystick subsystem disabled
2023-10-16 21:39:09.123 | MAPPER: Loaded default key bindings
2023-10-16 21:39:09.123 | SHELL: Redirecting output to NUL
2023-10-16 21:39:09.124 | MOUNT: Path '/Applications/DOSBox Staging.app/Contents/Resources/drives/y' found
2023-10-16 21:39:09.124 | MOUNT: Path '.' found
2023-10-16 21:39:10.341 | RENDER: Auto-switched to shader 'crt/ega-4k'
2023-10-16 21:39:10.341 | VGA: Forcing single-scanning of double-scanned VGA video modes
2023-10-16 21:39:10.373 | DISPLAY: EGA 320x200 16-colour graphics mode 0Dh at 70.086 Hz VFR, scaled to 2133x1600 with 1:1.2 (5:6) pixel aspect ratio
2023-10-16 21:39:11.290 | DISPLAY: EGA 320x200 16-colour graphics mode 0Dh at 70.086 Hz VFR, scaled to 2400x1800 with 1:1.2 (5:6) pixel aspect ratio
2023-10-16 21:39:56.677 | DISPLAY: EGA 320x200 16-colour graphics mode 0Dh at 70.086 Hz VFR, scaled to 2133x1600 with 1:1.2 (5:6) pixel aspect ratio
```

**Review by Burrito78 — APPROVED** [review]

**Comment by kcgen** [comment]
Thanks @Burrito78. Not much left here (just a tiny bit of code), but will hold on merge till others can review and test.

File: src/gui/sdlmain.cpp (hunk 5 above)
Comment (johnnovak) [reply src/gui/sdlmain.cpp]: Uh... that's a bit of misguided warning but whatever. You almost always lose precision with floats.

**Comment by johnnovak** [comment]
> Thanks @Burrito78. Not much left here (just a tiny bit of code), but will hold on merge till others can review and test.

Don't wait for me, I'm busy with lots of stuff. If you guys have done the Pinball Dreams test, that's good enough for me 😎

File: src/gui/sdlmain.cpp (hunk 5 above)
Comment (kcgen) [reply src/gui/sdlmain.cpp]: (late follow up); I think the reason for the precision warnings when using `int` with `float` is that `float`'s 23 mantissa bits can't perfectly represent `int32_t` and greater types (well, specifically values > 23 bits in size, because then it needs to use the exponent, so loses some precision).

Where as for `int16_t` and smaller, they can always losslessly fit into a `float`.
