### PR TITLE
Increase processing tempo of events

### LINKED ISSUE #1128: Left mouse click sometimes not registered in Doom on macOS
**Describe the bug**
Left mouse click in Doom is sometimes not registered (Fire weapon).
Happens windowed and full screen.

**To Reproduce**
Install Doom Shareware or Ultimate Doom. 
Configure for Keyboard + Mouse.
Use left mouse button to fire your pistol.

**Expected behaviour**
Every mouse click should fire the pistol.

**Environment (please complete the following information):**
macOS Catalina
Mac mini

**Version of dosbox-staging:**
0.77.0-2-gc7f51b07

**Configuration parameters:**
Fresh installed Doom Shareware 1.9 from Doomworld
Fresh dosbox-staging.conf

**Additional context**
I tried my Logitech G305 with installed Logitech Gaming Software.
Also disconnected the BT dongle and closed the Logitech software and connected a standard Logitech M100 wired mouse.

### PR DESCRIPTION
**Pull request by kcgen**
This change updates the frequency at which events are processed from SDL's event queue to 200 Hz, which is the maximum polling rate possible on original DOS hardware, and thus provides the DOS application with a realistic number of interrupts as experienced on original hardware.

This also fixes #1128, a regression discovered on macOS when the 'Magnet' application is managing the DOSBox window.

### CODE REVIEW

**Review by Burrito78 — APPROVED** [review]
This PR fixes the problems with Magnet app on macOS that were introduced in 0.77.0.

The updates/polling rates are fine-tuned to be as low as possible and still not miss any mouse clicks.

File: src/ints/mouse.cpp [hunk 1]
```diff
@@ -524,6 +524,7 @@ void Mouse_ButtonPressed(Bit8u button) {
 	case 0:
 		if (mouse.buttons&1) return;
 		mouse.buttons|=1;
+		LOG_MSG("Mouse_AddEvent(MOUSE_LEFT_PRESSED)");
```
Comment (bmunger) [inline src/ints/mouse.cpp:527]: Should this log always be on?  I can see in some games this could fill up the console window.  One of the things I think could be improved overall are logging controls both in release builds and debug builds.  Easy to lose track of information if there are too many things logging.

File: src/ints/mouse.cpp [hunk 2]
```diff
@@ -555,6 +556,7 @@ void Mouse_ButtonReleased(Bit8u button) {
 	case 0:
 		if (!(mouse.buttons&1)) return;
 		mouse.buttons&=~1;
+		LOG_MSG("Mouse_AddEvent(MOUSE_LEFT_RELEASED)");
```
Comment (bmunger) [inline src/ints/mouse.cpp:559]: Same with this log.

File: src/ints/mouse.cpp (hunk 1 above)
Comment (Wengier) [reply src/ints/mouse.cpp:527]: I agree that it could be changed to the LOG_MOUSE type to reduce log message flooding in such case.

File: src/ints/mouse.cpp (hunk 2 above)
Comment (kcgen) [reply src/ints/mouse.cpp:559]: Thanks for catching this @bmunger !
These logs were added to help @Burrito78 and I debug the the lost clicks problem. It helped indicate when clicks were registered from the OS into SDL. 
The plan was to knock these out in the release version; so will do that shortly 👍

**Comment by kcgen** [comment]
Thanks for the testing, @Burrito78 and reviews, @bmunger and @Wengier.
Merging.
