### PR TITLE
Initialise the OPL operators per the Adlib's v1.51 driver

### LINKED ISSUE #3504: Silmarils games with missing intro tone
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

During the intro logo for the listed Silmaril games there is a tone played (OPL channel I think) that doesnt happen when using Staging 81.0

While the single tone itself isnt a big deal, the question is raised, if this tone isnt playing what else might not be playing due to whatever is causing the issue.

Its also odd in that Staging is the only fork that seems to have this issue, 0.74, ECE, Daum, and X all play the sound.

Of the other forks when comparing and investigating, X plays the tone best as there is some pitch change to the note, the other forks just play one constant sound.

The games are:

Transantartica (1993)
Ishar 2 (1993)
Ishar 1 (1992)
Bunny Bricks (1993)
Storm Master (1992)
Boston Bomb Club (1991)
Metal Mutant (1991)
Crystals of Arborea (1990)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start game
2. Watch intro and listen for tone
3. Compare to X to hear the tone that should be there

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by interloper98**
# Description

This PR initialises the OPL card's operators with Adlib's v1.51 driver startup values, which can be considered a reasonable starting point for the OPL chips.

Unlike the original DOSBox OPL implementation(s), Nuked OPL starts up with the card state almost fully zeroed out, just like a real card.

This ultra bare-bones starting point is fine 99.9% of the time because games will fully reset and overwrite the card with whatever state they needed, but it turns out the Silmarils games need some of these "reasonable starting" values to already be in-play on the card.

## Related issues

Fixes #3504

https://github.com/dosbox-staging/dosbox-staging/assets/165201780/60d84f42-e5a3-4031-a350-99d5c5c5d9eb

# Manual testing

Tested all the affected Silmarils games:
- Set various Sound Blaster types
- Configured the games with the Sound Blaster (for those that allowed it):

    2024-Jun-15_20-48-45

- Disabled the `BLASTER` environment variable like @madbrain76 [recommended](https://github.com/dosbox-staging/dosbox-staging/discussions/3467#discussioncomment-9600999), which lets the game auto-detect the SB card (instead of getting confused by the environment variable).
- Made a couple other Silmarils-specific autoexec tweaks, like bumping up the mouse sensitivity with `mousectl` and upping the volume with the mixer.
- Here's my Silmarils template:
    
    ```ini
    [sblaster]
    sbtype = sb2

    [autoexec]
    @echo off
    set blaster=
    mixer opl 200 r15 c25 sb 200
    mousectl -s 200 200
    mount c .
    c:
    start.exe
    ```

---

Regression tested lots of other SB and OPL games, like Blues Brother, Stunts, AdLib Tracker 2, Dune 2, Rescue Rover 2, Wolf 3D, Titus games, the Rocketeer, Lemmings, Albion, Alone in the Dark (and some others).

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/hardware/opl.cpp [hunk 1]
```diff
@@ -57,6 +57,55 @@ static const char* to_string(const OplMode opl_mode)
...
+//
+// - Boston Bomb Club (1991),
+// - Bunny Bricks (1993),
+// - Crystals of Arborea (1990),
+// - Ishar 1 (1992),
+// - Ishar 2 (1993),
+// - Metal Mutant (1991),
+// - Storm Master (1992), and
+// - Transantartica (1993).
+
```
Comment (johnnovak) [inline src/hardware/opl.cpp:73]: 🥇 for the nice explanatory comment!

**Review by johnnovak — APPROVED** [review]
Thanks for this @interloper98, very nice! 🎉  It all makes sense, and given DOSBox defaulted to these initial settings before the introduction of NukedOPL, this is a very safe change. And, as you noted, 99% of programs do their own init anyway.

File: src/hardware/opl.cpp (hunk 1 above)
Comment (interloper98) [reply src/hardware/opl.cpp:73]: thanks :-)
