### PR TITLE
Fix byte calculation overflow using pages per MB

### LINKED ISSUE #3940: Crash when setting high `memsize` values on macOS
Setting `memsize` to high values (~2500 and above) results in weird recursive exception throwing and an eventual crash, apparently only on macOS:

image

Reproduce with the following config:

```ini
[dosbox]
memsize = 2500
```

This is a regression; values up to 3072 were working fine on 0.81.2.

Well, and very it's low priority because even server-grade Socket 5 and 7 motherboards only support up to 512 or 1024 MB of memory. More than 64 MB for DOS is rather pointless (that's the limitation of MS-DOS 6.22 via HIMEM.SYS).

I was happy with 64 MB of RAM in my first Celeron 350 Win95/98 box I bought in 1999, so... 😄 It was even fine for Windows 2000.

### PR DESCRIPTION
**Pull request by interloper98**
# Description

The calculation from megabytes to pages results in a large peak byte value causing an overflow of the `int`.

This uses a pages-per-megabyte variable to let the calculations read more naturally and also vastly reduces the peak value used when converting megabytes to pages.

## Related issues

Fixes #3940 

# Manual testing

Tested with large memory sizes up to 3000 MB, including sanitizer builds.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/hardware/memory.cpp [hunk 1]
```diff
@@ -30,6 +30,8 @@
 
 constexpr auto megabyte = 1024 * 1024;
 
+constexpr auto PagesPerMegabyte = megabyte / dos_pagesize;
```
Comment (johnnovak) [inline src/hardware/memory.cpp:33]: While you're at it: `Megabyte`

File: src/hardware/memory.cpp [hunk 2]
```diff
@@ -158,7 +160,8 @@ PageHandler * MEM_GetPageHandler(Bitu phys_page) {
 		return memory.lfb.handler;
 	}
 
-	constexpr uint32_t pages_in_16mb = {0x01000000u / dos_pagesize};
+	constexpr uint32_t pages_in_16mb = 16 * PagesPerMegabyte;
```
Comment (johnnovak) [inline src/hardware/memory.cpp:163]: `PagesIn16Mb`

**Review by johnnovak — APPROVED** [review]
This fixes the problem @interloper98! 🎉 Thanks for jumping on this so quickly 🏃🏻‍♂️ 🎖️
