### PR TITLE
Skip removal of already absent files

### LINKED ISSUE #683: Game Wizard 32 = File Access Denied
**Describe the bug**
When I want to start looking for cheats, I can't as it gives me this error: File Access Denied.

**To Reproduce**
Run the program and go to the first option which is "Memory Address Search" (it is the option to start a search).

**Expected behaviour**
It doesn't have to give that error and a screen with options should appear to start looking for cheats.

**Version of dosbox-staging:**
With the latest git: v0.76.0-alpha-870-ga3848.
It also did not work with gits prior to the last one, but it does work with version 0.75.1

**Additional context**

vc_000

### PR DESCRIPTION
**Pull request by kcgen**
Fixes a regression caught in GameWizard 32 Pro 3.0a when it tries to delete temporary files, which may not exist (GW.SC1 and GW.SCH), prior to performing a memory scan.

```
FS: Skipping removal of GW\GW.SC1 because it doesn't exist
FS: Skipping removal of GW\GW.SCH because it doesn't exist
```

Fixes #683.

### CODE REVIEW

**Comment by kcgen** [comment]
To prevent GameWizard from hanging on startup, use:

``` 
[dos]
xms=true
ems=emsboard
```

Thanks to ripsaw8080 for this information reported in this thread: https://www.vogons.org/viewtopic.php?t=30322

File: src/dos/drive_local.cpp [hunk 1]
```diff
@@ -218,6 +218,12 @@ bool localDrive::GetSystemFilename(char *sysName, char const * const dosName) {
 
 // Attempt to delete the file name from our local drive mount
 bool localDrive::FileUnlink(char * name) {
+	if (!FileExists(name)) {
+		DEBUG_LOG_MSG("FS: Skipping removal of %s because it doesn't exist",
+		              name);
+		return true;
+	}
+
```
Comment (kcgen) [inline src/dos/drive_local.cpp:226]: @dreamer , with this initial check added here, it makes the `DOS_SetError(DOSERR_ACCESS_DENIED)` at the end of this function perfectly appropriate.
1.  If this new initial check fails, then we know the file exists. 
2. If all attempts to remove the existing file still fail, then there's something beyond our control blocking it - so an access denied code would be the most appropriate response. 

(And so far everything I've thrown at this has passed testing)

File: src/dos/drive_local.cpp [hunk 2]
```diff
@@ -218,6 +218,12 @@ bool localDrive::GetSystemFilename(char *sysName, char const * const dosName) {
 
 // Attempt to delete the file name from our local drive mount
 bool localDrive::FileUnlink(char * name) {
+	if (!FileExists(name)) {
+		DEBUG_LOG_MSG("FS: Skipping removal of %s because it doesn't exist",
+		              name);
```
Comment (kcgen) [inline src/dos/drive_local.cpp:223]: https://dos4gw.org/41h_65_Delete_File_UNLINK

Although I haven't tested it yet, I will try returning false with a FILE_NOT_FOUND code set, which is more correct.

**Review by dreamer — APPROVED** [review]
@kcgen Thank you for fixing this!

I have an idea on how to write automatic tests (but not unit tests, as wouldn't be able to verify them on real DOS) to handle such regressions. Added a task for 0.77.0 release for myself to address it.

When testing other options in GW I stumbled upon an assertion in cpu code (the one I added when refectoring code in there), but it's unrelated to this PR.
