### PR TITLE
Remove std_fs::path and explicitly convert to UTF-16 on Windows

### LINKED ISSUE #4703: TFX CD 2.05 detecting only Soundblaster and crashing with SB16
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

0.83.0alpha

### What operating system are you using?

Windows 10

### If other OS or Linux, please describe

_No response_

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Are you able to trigger the issue with our official DOSBox Staging release?

- [x] I am running an official Staging release, not a release installed by my operating system's package manager, or a version repackaged by an external team.

### Relevant hardware info

R5 2600x, 16GB ram DDR4, 1060 3gb

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

Testing the latest Alpha build with TFX and seems the game isn't detecting SB16 as default as the latest stable build and is defaulting as Soundblaster, trying to load the game with SB16 causes the game to crash.

### Steps to reproduce the behaviour

Explain in detail how to reproduce the bug. Assume no familiarity with the software.
1. Install TFX CD 2.05 release or Install the Floppy or Old CD release and patch to 2.05 using the 3 patches in  sequence
2. Config the game to run per https://www.tales-from-darkenedroom.com/post/tfx-tactical-fighter-experiment-in-dosbox-staging
3. Run the game after it and see crashing

### Download URL of affected game or software

_No response_

### Your configuration

```ini
https://gist.github.com/Bittermens/01e788bf16a3632053d69480c6c7fa80
```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

I detailed my plan in a long comment here: https://github.com/dosbox-staging/dosbox-staging/issues/4703#issuecomment-3886531304

This is the first part and this will stay mostly as-is for part 2 (probably after next release).

In addition to removing std_fs::path usage in local_drive functions, I also did a bit of cleanup. I removed all the weird underscored POSIX functions from the Windows path. I feared they would have the same issue where they would be attempting to convert from UTF-8 at some point. Also POSIX functions don't always work the way you expect on Windows. So now it's all native Win32 API in `fs_utils_win32.cpp`.

## Related issues

Fixes #4703

# Release notes

Probably nothing needed. The regression was only in the dev branch.

# Manual testing

- Tested on Linux and Windows
- TFX exception crash has been fixed
- Doom still works
- Basic file operations work

The change has been manually tested on:

- [x] Windows
- [ ] macOS
- [x] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/tools/compile-commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [x] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: src/utils/fs_utils.h [hunk 1]
```diff
@@ -22,6 +23,45 @@
...
+	template <int out_length>
+	static bool codepage437_to_utf16(const char *in_string, wchar_t (&out_string)[out_length])
+	{
+		constexpr UINT Codepage = 437;
+		constexpr DWORD Flags = 0;
+		// -1 means read the entire null terminated string
+		constexpr int InLength = -1;
+		const auto num_chars = MultiByteToWideChar(Codepage, Flags, in_string, InLength, out_string, out_length);
+		if (num_chars >= out_length) {
+			LOG_ERR("codepage437_to_utf16: Insufficient output buffer length");
```
Comment (johnnovak) [inline src/utils/fs_utils.h]: Prefix with `FS: `, please (we're already using that log prefix for filesystem stuff).

File: src/utils/fs_utils.h [hunk 2]
```diff
@@ -22,6 +23,45 @@
...
+		if (FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
+							lpSource,
+							error,
+							LANG_USER_DEFAULT,
+							error_message,
+							sizeof(error_message),
+							Arguments)) {
+			// Just in case Windows does something dumb I'm sticking a null terminator on the end :)
+			error_message[sizeof(error_message) - 1] = 0;
+			LOG_ERR("MultiByteToWideChar failed with error code %lu: %s", error, error_message);
```
Comment (johnnovak) [inline src/utils/fs_utils.h]: Prefix with `FS: `, please.

File: src/utils/fs_utils.h [hunk 3]
```diff
@@ -22,6 +23,45 @@
...
+		} else {
+			LOG_ERR("MultiByteToWideChar failed with error code %lu: FormatMessageA also failed", error);
```
Comment (johnnovak) [inline src/utils/fs_utils.h]: Prefix with `FS: `, please.

**Review by johnnovak — APPROVED** [review]
Outstanding work @weirddan455, extra 🥇 for separating the changes into well-defined, small commits 💯 

Skimmed through it and nothing jumped out. Left a few very minor comments, otherwise good to go!

**Comment by vladkosi** [comment]
This PR fixes Descent II installation that was crashing with the same error as https://github.com/dosbox-staging/dosbox-staging/issues/4703.

But now the 1.2 patch is failing:


The patch works in the latest dev build.

**Comment by weirddan455** [comment]
I'll give that Descent 2 patch a test before merging. @vladkosi You're on Windows I presume? Any new error messages in the logs?

**Comment by vladkosi** [comment]
Windows 10, no log messages.

File: src/dos/drive_local.cpp
Comment (weirddan455) [inline src/dos/drive_local.cpp]: I appreciate the testing @vladkosi 

Bug was here. `local_drive_rename_file_or_directory` returns a boolean where 0 means failure. Before it was directly calling POSIX `rename` where 0 means success. I forgot to update the call site here but it's an easy fix I'll push in just a minute.

File: src/utils/fs_utils.h [hunk 4]
```diff
@@ -22,6 +23,45 @@
 	// Cannot be constexpr due to Win32 macro
 	#define InvalidNativeFileHandle INVALID_HANDLE_VALUE
 
+	template <int out_length>
+	static bool codepage437_to_utf16(const char *in_string, wchar_t (&out_string)[out_length])
```
Comment (FeralChild64) [inline src/utils/fs_utils.h]: Instead of implementing a Windows-specific `codepage437_to_utf16`, wouldn't it be more elegant to implement `std::u16string dos_437_to_fs_utf16(const std::string& str)` in `unicode.h|cpp`?

Look at `dos_437_to_fs_utf8` implementation; replacing `dos_to_utf8(...)` with `wide_to_utf16(dos_to_wide(...))` should do the job.

File: src/utils/fs_utils.h (hunk 1 above)
Comment (weirddan455) [reply src/utils/fs_utils.h]: Fixed

File: src/utils/fs_utils.h (hunk 4 above)
Comment (weirddan455) [reply src/utils/fs_utils.h]: I think it is a bit risky to do that here as our internal Unicode functions have not been tested in filesystem code. The main reason for this PR is to solve a specific regression before release. Using Microsoft's conversion functions should always produce an identical result to setting the program's default codepage to 437 (what it was before we switched it to UTF-8 and caused the `std_fs::path` regression crash).

On my planned 2nd PR (which will be after 0.83.0 release), I will be using your `dos_437_to_fs_utf8` function on Linux and Mac and at that time I will probably also do as you suggest and use our internal functions on Windows to minimize cross-platform differences. I think it is best to wait until then though since release is just around the corner.

Sidenote: Should I be using `inline` instead of `static` since this function is in a header file?

Comment (johnnovak) [reply src/utils/fs_utils.h]: Yeah, screw elegance for now, we need to release in a month or so, so do whatever is the safest 😆 That cleanup can come later but if it's risky, let's defer to the 0.84 timeframe. Fully agree with your approach @weirddan455

Comment (FeralChild64) [reply src/utils/fs_utils.h]: @weirddan455 OK for me then.

**Comment by weirddan455** [comment]
> now the 1.2 patch is failing

I hid this in a code comment but this bug is fixed now. I'm going to give this a quick self review and then merge.
