### PR TITLE
Manage sdlmain's DOS video mode as an `<optional>`

### LINKED ISSUE #3314: Assert failure when launching debug build fullscreen
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82-alpha

### What Operating System are you using?

Linux x86

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

An assert failure occurs when launching a debug build fullscreen on Linux.

- Doesn't occur on macOS.
- Haven't tested Windows.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Perform a debug build on Linux: `meson --buildtype=debug build`
2. launch with: `dosbox --fullscreen`

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

```text
2024-01-09 20:35:13.177 | CONFIG: Loaded auto-mounted drive config file '/usr/src/dosbox-staging/build/resources/drives/y.conf'
2024-01-09 20:35:13.618 | MAPPER: Found one joystick
2024-01-09 20:35:13.619 | MAPPER: Initialised Logitech Gamepad F310 with 6 axes, 11 buttons, and 1 hat(s)
2024-01-09 20:35:13.621 | MAPPER: Loaded default key bindings
dosbox: ../include/fraction.h:43: constexpr Fraction::Fraction(int64_t, int64_t): Assertion `d != 0' failed.

Thread 1 "dosbox" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff763c3b6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff762287c in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff762279b in __assert_fail_base (fmt=0x7ffff77b9f68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555562c6e95 "d != 0", file=file@entry=0x5555562c6e7f "../include/fraction.h", line=line@entry=43, 
    function=function@entry=0x5555562c6e50 "constexpr Fraction::Fraction(int64_t, int64_t)") at ./assert/assert.c:92
#6  0x00007ffff7633b66 in __assert_fail (assertion=0x5555562c6e95 "d != 0", file=0x5555562c6e7f "../include/fraction.h", line=43, function=0x5555562c6e50 "constexpr Fraction::Fraction(int64_t, int64_t)") at ./assert/assert.c:101
#7  0x0000555555d18f6e in Fraction::Fraction (this=0x7fffffffacf0, n=1, d=0) at ../include/fraction.h:43
#8  0x0000555555d190b1 in Fraction::Inverse (this=0x5555583e32b0 <sdl+80>) at ../include/fraction.h:75
#9  0x0000555555fc256d in log_display_properties (render_width_px=640, render_height_px=480, video_mode=..., rendering_backend=RenderingBackend::OpenGl) at ../src/gui/sdlmain.cpp:797
#10 0x0000555555fcbf64 in GFX_Events () at ../src/gui/sdlmain.cpp:3847
#11 0x0000555555be7b95 in Normal_Loop () at ../src/dosbox.cpp:157
#12 0x0000555555be8256 in DOSBOX_RunMachine () at ../src/dosbox.cpp:322
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
# Description

The execution sequence starts by initializing SDL followed by starting the DOS normal loop, which eventually sets the DOS video mode.
    
This PR makes sdlmain's DOS video mode optional because (with respect to sdlmain), the DOS video mode doesn't exist (and may not exist) until the DOS side successfully sets the video mode through the emulated video card.
    
In terms of order of operations, Both the SDL and DOS side can drive mode changes that involve switching the GL Shader as well as logging the SDL window size or DOS display mode; this commit lets those play out as-is.

## Related issues

Fixes #3314 

# Manual testing

Tested debug and sanitizer builds on Linux and macOS starting up in windowed and fullscreen modes.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

File: include/sdlmain.h [hunk 1]
```diff
@@ -195,7 +195,8 @@ struct SDL_Block {
 		bool height_was_doubled = false;
 	} draw = {};
 
-	VideoMode video_mode = {};
+	// The DOS video mode is populated after we setup the SDL window.
```
Comment (johnnovak) [inline include/sdlmain.h:198]: Minor: "set up"

File: src/gui/render.cpp [hunk 2]
```diff
@@ -593,17 +593,11 @@ bool RENDER_MaybeAutoSwitchShader([[maybe_unused]] const DosBox::Rect canvas_siz
                                   [[maybe_unused]] const VideoMode& video_mode,
                                   [[maybe_unused]] const bool reinit_render)
 {
-	if (GFX_GetRenderingBackend() != RenderingBackend::OpenGl) {
-		return false;
-	}
+	// We always expect a valid canvas and DOS video mode
+	assert(!canvas_size_px.IsEmpty());
```
Comment (johnnovak) [inline src/gui/render.cpp:597]: 👍🏻

File: src/gui/render.cpp [hunk 3]
```diff
@@ -593,17 +593,11 @@ bool RENDER_MaybeAutoSwitchShader([[maybe_unused]] const DosBox::Rect canvas_siz
...
+	assert(video_mode.width > 0 && video_mode.height > 0);
 
-	// Currently, the init sequence is slightly different on Windows, macOS,
-	// and Linux. The first call to this function on Windows receives an
-	// uninitialised VideoMode param with width and height set to 0 which
-	// results in a crash. The proper fix is to make the init sequence 100%
-	// identical on all platforms, but in the interim this workaround will do.
-	if (canvas_size_px.IsEmpty() || video_mode.width == 0 ||
-	    video_mode.height == 0) {
+	if (GFX_GetRenderingBackend() != RenderingBackend::OpenGl) {
```
Comment (johnnovak) [inline src/gui/render.cpp:600]: Glad to see my dirty hack gone 🗑️ 😅

File: src/gui/sdlmain.cpp [hunk 4]
```diff
@@ -2520,6 +2527,14 @@ static void update_frame_texture([[maybe_unused]] const uint16_t *changedLines)
 
 static std::optional<RenderedImage> get_rendered_output_from_backbuffer()
 {
+	// This should be impossible, but maybe the user is hitting the screen
+	// capture hotkey on startup even before DOS comes alive.
+	if (!sdl.maybe_video_mode) {
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:2532]: "Never say something is idiot-proof. That's underestimating your user base." 😅

File: src/gui/sdlmain.cpp [hunk 5]
```diff
@@ -3733,20 +3750,26 @@ static void finalise_window_state()
...
 	const auto canvas_size_px = get_canvas_size_in_pixels(sdl.rendering_backend);
-	constexpr auto reinit_render = true;
+	if (canvas_size_px.IsEmpty()) {
+		return false;
+	}
+
+	// The shaders need the DOS mode to be set as their source resolution
+	if (!sdl.maybe_video_mode) {
+		return false;
+	}
```
Comment (johnnovak) [inline src/gui/sdlmain.cpp:3767]: Nice helpful comments 👍🏻

**Review by johnnovak — APPROVED** [review]
Nice one @kcgen. I think this is the way, to do the init the "systemd way", assuming no particular init order (well, at least until the first frame gets rendered... this approach can quickly get out of hand too).

**Comment by kcgen** [comment]
Also tested hitting Ctrl+Enter as fast as possible, and couldn't trip an assert issues, even after > 60+ seconds (testing on macOS and Linux).

**Comment by kcgen** [comment]
Ok! merging; ready for backport.
