### PR TITLE
Fix Opus mounting on Windows and add some size checks

### LINKED ISSUE #849: Opus audio tracks don't mount under Windows
Using both the Windows latest and 0.76.0 release binaries (and accompanying DLLs), attempting to mount an ISO/CUE + Opus tracks combination will fail to mount the Opus tracks.

The error reported is generated from `cdrom_image.cpp` and mentions being unable to seek to a byte-offset that's greater than the reported track length. The error provides the seek offset and track length in PCM-equivalent bytes.

Initial testing with various Opus files shows the track length as being artificially tiny (ranging from hundreds of bytes up to thousands of bytes), and the seek offset typically around the 32k mark. 

I haven't had time to look at this, but will in the coming days.

Assuming this is a small and understandable fix, suggest we backport it to 0.76.1.

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #849 

Although only the first commit is needed (yes, Opus was simply de-activated!), the remaining commits:
 - cleanup the warnings in the Opus decoders verbose mode (which activates the `SNDDBG` calls)
 - ensure the tracks' reported size can be safely down-cast (in DEBUG builds) to meet the API types
 - These were critical to let the build pass the CI warning limits so I could test the Windows release build on hardware and Wine

CI release build was confirmed working on Windows (wine64, VirtualBox, and hardware), as well as on Linux x86 and ARM.

### CODE REVIEW

File: src/libs/decoders/opus.cpp [hunk 1]
```diff
@@ -137,12 +137,13 @@ static int32_t RWops_opus_seek(void * stream, const opus_int64 offset, const int
...
     assertm(stream, "OPUS: Input is not initialized");
+    assertm(offset <= INT32_MAX, "OPUS: requested offset beyond 2 GiB limit");
     assertm(whence == SEEK_SET || whence == SEEK_CUR || whence == SEEK_END,
             "OPUS: The position from where to seek is invalid");
 
-    const int64_t offset_after_seek = SDL_RWseek(static_cast<SDL_RWops*>(stream),
-                                                 static_cast<int32_t>(offset),
-                                                 whence);
+    const auto offset_after_seek = SDL_RWseek(static_cast<SDL_RWops*>(stream),
+                                              static_cast<int32_t>(offset),
```
Comment (dreamer) [inline src/libs/decoders/opus.cpp:145]: This static cast is unnecessary for SDL2 (it was likely needed for SDL1). Does it mean assert is not needed either?

Using auto is not needed either in this case - SDL2 returns Sint64 here, which is the same type as int64_t, so the code was good already (except %ld in SNDDBG below, but using auto does not solve that).

File: src/platform/visualc/config.h [hunk 2]
```diff
@@ -42,6 +42,9 @@
 /* Define to 1 to enable FluidSynth MIDI synthesizer */
 #define C_FLUIDSYNTH 1
 
+/* Define to 1 to use Opus-encoded CD-audio tracks, requires opusfile */
+#define USE_OPUS 1
```
Comment (dreamer) [inline src/platform/visualc/config.h:46]: Good job figuring it out… This means I am likely missing this define on `meson` branch as well - thanks!

File: src/libs/decoders/opus.cpp [hunk 3]
```diff
@@ -179,7 +179,7 @@ static opus_int64 RWops_opus_tell(void * stream)
 
     const int64_t current_offset = SDL_RWtell(static_cast<SDL_RWops*>(stream));
     SNDDBG(("Opus ops tell:          "
-            "%ld\n", current_offset));
+            "%ld\n", static_cast<long int>(current_offset)));
```
Comment (dreamer) [inline src/libs/decoders/opus.cpp:182]: On Windows `long int` is the same as `int` - I doubt it will cause problems, but I you want to stay on the safe side, use `PRIu64` instead of `ld` and avoid down-casting in this case.

**Review by dreamer — COMMENTED** [review]
Good cleanup, thanks - I have only a few small comments.

File: src/libs/decoders/opus.cpp (hunk 3 above)
Comment (kcgen) [reply src/libs/decoders/opus.cpp]: Thanks; this worked as you predicted!

File: src/platform/visualc/config.h (hunk 2 above)
Comment (kcgen) [reply src/platform/visualc/config.h:46]: It was a bit of a nightmare because the track opening was failing but I couldn't figure out why (despite all the effort on the debugging front).
I eventually inspected the array-of-array `decoders` objects and saw the Opus callback object wasn't in the list when I iterated through them.

File: src/libs/decoders/opus.cpp (hunk 1 above)
Comment (kcgen) [reply src/libs/decoders/opus.cpp]: `offset` is a long long int at least Ubuntu 18.04:

`opus.cpp:148:38: warning: format '%ld' expects argument of type 'long int', but argument 2 has type 'long long int' [-Wformat=]`

So needed to retain one cast down to `int64_t`:

``` patch
     SNDDBG(("Opus ops seek:          "
-            "requested: %" PRId64 " and got: %" PRId64"\n",
-            offset, offset_after_seek));
+            "requested: %" PRId64 " and got: %" PRId64 "\n",
+            static_cast<int64_t>(offset), offset_after_seek));
```

**Comment by kcgen** [comment]
> Fixed

**Review by dreamer — APPROVED** [review]
Clean changes, nice :) @kcgen do you plan to cherry-pick these changes to `release/0.76.x` branch?

**Comment by kcgen** [comment]
> Clean changes, nice :) @kcgen do you plan to cherry-pick these changes to `release/0.76.x` branch?

Thanks @dreamer. Regarding 0.76.x; will do!

**Comment by kcgen** [comment]
> Clean changes, nice :) @kcgen do you plan to cherry-pick these changes to `release/0.76.x` branch?

CI failed on the macOS release build for the same reasons that started hitting runs a weeks ago (broken SDL2 static link errors), that we fixed w/ https://github.com/dosbox-staging/dosbox-staging/pull/836

So I've cherry-picked those two commits as well.
