### PR TITLE
Accumulate GUS frames accross each voice instead of per-sample (#2696)

### LINKED ISSUE #2696: Gravis Ultrasound sound effects fuzzy/crackly in DUKE3D when set to 44kHz
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-v0.81.0-alpha-1149-g09ee

### What Operating System are you using?

Windows 10

### If Other OS, please describe

_No response_

### Relevant hardware info

i5-4590/r9 290, i7-8650u/UHDgraphics620

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Sound effects exhibit significant distortion in DUKE3D when the game setup options are set to use the GUS at 44kHz. 22kHz and below sounds normal. GUS music sounds correct.

The current release version of DosBox-Staging exhibits similar distortions in several additional games (A Final Unity, Heretic, Doom) at any sample rate setting, but they all sound correct in the latest Dev build, so the latest patches must have fixed them.

The latest release build of DOSBox-X using the original GUS implementation isn't exhibiting the distortion at 44kHz.

[DUKE3D-44kHz-GUS.zip](https://github.com/dosbox-staging/dosbox-staging/files/12135197/DUKE3D-44kHz-GUS.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. with fresh config file using known working mounted C:\ with \ULTRASND\ and \DUKE3D\ directory, disable sound blaster (this actually didn't seem to affect it, just removing a variable) and enable GUS
2.  set sound device in duke3d setup to GUS, 44kHz mixing rate, disable music to hear SFX more clearly (number of voices doesn't seem to affect it, music sounds correct either way when enabled)
3. start duke3d, the initial radiation logo animation and main menu demo will show obvious sound distortion

### Download URL of affected game or software

Atomic Edition of DUKE3D from GOG

### Your configuration

```ini
https://gist.github.com/x73rmin8r/36c2d6569e31d5df5f617231c7d7c275
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
Previously when rendering frames in the GUS, we iterated one sample at a time, gathering the next panned sample from each voice into the resulting frame before moving onto the next frame (and again, gathering the next sample from all the voices).

```
         start
          i=0,     i=1,    i=2, .. for N frames
           |        |       |
           V        V       V
voice 1  [v1s0]   [v1s1]   ...
voice 2 +[v2s0]  +[v2s1]   ...
voice 3 +[v3s0]  +[v3s1]   ...
...
output = {summed-s0, summed-s1, summed-s2 ... }
```

Rendering samples from the GUS changes its state, and in the case of Duke 3D, the above approach doesn't traverse all of the available samples in all the populated voices before a state change halts one or more of the voices, resulting in essentially a truncated sequence.

This change switches back to how the original SVN and X GUS rendering loops work, which is to gather samples per-voice first, summing all of the samples across an array. This ensures that we gather all the requested samples from each voice before moving onto the next voice.

```
start
i=1 ->  voice 1   [v1s0]   [v1s1]   ... for N frames
i=2,    voice 2  +[v2s0]  +[v2s1]   ... for N frames
i=3,    voice 3  +[v3s0]  +[v3s1]   ... for N frames
...
output = {summed-s0, summed-s1, summed-s2 ... }
```

The sub-millisecond rendering prior to port and register writes is still in place, as is the use of the mixer's floating-point compressor.

Fixes #2696 ; thanks for reporting @x73rmin8r!

### CODE REVIEW

File: src/hardware/gus.cpp [hunk 1]
```diff
@@ -441,21 +445,25 @@ float Voice::GetSample(const ram_array_t &ram) noexcept
 	return sample;
 }
 
-AudioFrame Voice::RenderFrame(const ram_array_t &ram,
-                              const vol_scalars_array_t &vol_scalars,
-                              const pan_scalars_array_t &pan_scalars)
+void Voice::RenderVoiceToFrames(const ram_array_t& ram,
+                                const vol_scalars_array_t& vol_scalars,
+                                const pan_scalars_array_t& pan_scalars,
+                                std::vector<AudioFrame>& frames)
```
Comment (johnnovak) [inline src/hardware/gus.cpp:451]: It's in the `Voice` class, so RenderVoice is redundant. Call it `RenderFrames` or just `Render`?

File: src/hardware/gus.cpp [hunk 2]
```diff
@@ -665,27 +673,37 @@ void Gus::ActivateVoices(uint8_t requested_voices)
 	}
 }
 
-AudioFrame Gus::RenderFrame()
+const std::vector<AudioFrame>& Gus::GetFrames(const int num_requested_frames)
```
Comment (johnnovak) [inline src/hardware/gus.cpp:676]: Perhaps keep this `RenderFrames` so it's consistent with all the other audio device implementations (well, MT-32 and FluidSynth had only `Render`, but the rest `RenderFrames`). The fact that this function forwards the rendering job to the `Voice` classes is an implementation details, it should not be reflected in the function's name.

File: src/hardware/gus.cpp [hunk 3]
```diff
@@ -665,27 +673,37 @@ void Gus::ActivateVoices(uint8_t requested_voices)
...
 {
-	AudioFrame accumulator = {};
+	// use a static vector to avoid re-allocating each millisecond
+	static std::vector<AudioFrame> frames = {};
```
Comment (johnnovak) [inline src/hardware/gus.cpp:679]: How about storing this in the `Gus` class instead? Would be a bit cleaner that way, no?

File: src/hardware/gus.cpp (hunk 1 above)
Comment (kcgen) [reply src/hardware/gus.cpp:451]: Yup.. before I was called 'RenderFrame' (in the voice class), and we also had 'RenderFrame' in the Gus class; I was worried they were confusing or ambiguous, so renamed them.. but with your comments here I think they originals were fine :-)  Will rename them back.

File: src/hardware/gus.cpp (hunk 3 above)
Comment (kcgen) [reply src/hardware/gus.cpp:679]: Yup.. will make it a member.

File: src/hardware/gus.cpp [hunk 4]
```diff
@@ -665,27 +673,37 @@ void Gus::ActivateVoices(uint8_t requested_voices)
...
-
-		while (voice < voice_end && *voice) {
-			const auto voice_frame = voice->get()->RenderFrame(
-			        ram, vol_scalars, pan_scalars);
-
-			accumulator.left += voice_frame.left;
-			accumulator.right += voice_frame.right;
-
+		const auto last_voice = voice + active_voices;
+		while (voice < last_voice && *voice) {
```
Comment (johnnovak) [inline src/hardware/gus.cpp:690]: Related: can't we move this into `Gus` and remove the `unique_ptr` cruft?

```cpp
using voice_array_t = std::array<std::unique_ptr<Voice>, MAX_VOICES>;
```

File: src/hardware/gus.cpp [hunk 5]
```diff
@@ -665,27 +673,37 @@ void Gus::ActivateVoices(uint8_t requested_voices)
...
+			// Render all of the requested frames from each voice
+			// before moving onto the next voice. This ensures each
+			// voice can deliver all its samples without being
+			// affected by state changes that (might) occur when
+			// rendering subsequence voices.
```
Comment (johnnovak) [inline src/hardware/gus.cpp:695]: subsequent

File: src/hardware/gus.cpp [hunk 6]
```diff
@@ -698,33 +716,45 @@ void Gus::RenderUpToNow()
...
-	// Keep rendering until we're current
-	while (last_rendered_ms < now) {
-		last_rendered_ms += ms_per_render;
-		fifo.emplace(RenderFrame());
+
+	const auto elapsed_ms = now - last_rendered_ms;
+	if (elapsed_ms > ms_per_render) {
+		// How many frames have elapsed since we last rendered?
+		const auto num_elapsed_frames = iround(
+		        std::floor(elapsed_ms / ms_per_render));
```
Comment (johnnovak) [inline src/hardware/gus.cpp:724]: Are you sure we aren't swallowing/skipping sample frames sometimes because of the rounding?

File: src/hardware/gus.cpp (hunk 1 above)
Comment (johnnovak) [reply src/hardware/gus.cpp:451]: Yeah I think that's better 😄 The scope is still very clear, e.g. `voice->RenderFrames(...)`.

**Comment by johnnovak** [comment]
Nice quick fix @kcgen , will test shortly with a few demos and mod players as well 👍🏻

File: src/hardware/gus.cpp (hunk 4 above)
Comment (kcgen) [reply src/hardware/gus.cpp:690]: willsnip the `unique_ptr` and moves to full objects.

**Review by johnnovak — APPROVED** [review]
The issue in Duke3D is now gone. I've also tried FastTracker II, CapaMod and a few demos—all good :tada: Feel free to merge @kcgen once you've addressed those minor issues.

File: src/hardware/gus.cpp (hunk 6 above)
Comment (kcgen) [reply src/hardware/gus.cpp:724]: Yes; this errs on the side of whole frames only for the sub-millisecond chunk of time, because the game or program at a minimum needs to make sure at least that many samples have been DMA'd into the card - if we round up, then we might go beyond what's available.

But to to sure - no matter what, during the audio callback where the mixer pulls frames, it gets all the frames at that point.  So no frames are dropped or lost.

**Comment by kcgen** [comment]
> The issue in Duke3D is now gone. I've also tried FastTracker II, CapaMod and a few demos—all good tada Feel free to merge @kcgen once you've addressed those minor issues.

Thanks for the bisect, review, and test feedback @johnnovak !

**Comment by johnnovak** [comment]
> > The issue in Duke3D is now gone. I've also tried FastTracker II, CapaMod and a few demos—all good tada Feel free to merge @kcgen once you've addressed those minor issues.
> 
> Thanks for the bisect, review, and test feedback @johnnovak !

Nice one! You're back and you're solving issues in a swift manner on day 1! 🚀 😎 🤘🏻
