### PR TITLE
Fix regression when pixel-perfect scaling low-res VGA modes (#1526)

### LINKED ISSUE #1526: Vgaonly broken in v.0.78.1? [BUG]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

_No response_

### If Other OS, please describe

_No response_

### Relevant hardware info

RTX 2070, i7 processor, Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi guys, sorry to bother you again after that other issue  :-P https://github.com/dosbox-staging/dosbox-staging/issues/1485
but I think "vgaonly" setting isn't working properly in v.0.78.1. I don't know if this is related to the aspect ratio problem we discussed, but check these screens I took.
You need the "vgaonly" setting to show some scanlines effects in some games (the water in **Sleepwalker** was and still is glitchy with "svga_s3") and some demos (**Copper** by Surprise Team needs "vgaonly" for the majority of its effects, except wobbling, which only works under Dosbox-X, as far as I'm aware, so don't consider that one).
Anyway, as you may see, something strange is happening in version 0.78.1. I don't know if this may help, but I noticed that screenshots taken under v.0.78.1 ("vgaonly" enabled) are **lowres**. Now, usually vgaonly Dosbox screenshots have always been **hires**, because vgaonly actually renders VGA 320x200 as 640x400 (I think the reason is covering all the scanlines of the original VGA hardware). Screens still were hires in v.0.77.1 and v.0.78, but now they're lowres as in "svga_s3" setting. Could there be a connection between the malfunctioning and the screenshot grabbing system?

copper_vgaonly_right
copper_vgaonly_wrong

sleepwalker_vgaonly_right
sleepwalker_vgaonly_wrong

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
Pixel-perfect scaling could require a larger canvas size than necessary to integer-scale low-resolution VGA modes, such as mode 13h 320x200. Thanks to @diduz for reporting this.

Fixes #1526.

### CODE REVIEW

File: src/gui/sdlmain.cpp [hunk 1]
```diff
@@ -251,6 +251,55 @@ enum PRIORITY_LEVELS {
 	PRIORITY_LEVEL_HIGHEST
 };
 
+class pp_scale_t {
```
Comment (shermp) [inline src/gui/sdlmain.cpp:254]: I usually associate names like `some_thing_t` as a typedef, not class names.

Perhaps `pp_scale` (or `PPScale`) would be more appropriate.

File: src/gui/sdlmain.cpp [hunk 2]
```diff
@@ -251,6 +251,55 @@ enum PRIORITY_LEVELS {
...
+public:
+	pp_scale_t(const int source_w,
+	           const int source_h,
+	           const double aspect_ratio,
+	           const bool source_is_doubled,
```
Comment (shermp) [inline src/gui/sdlmain.cpp:259]: Is the `is` necessary? Perhaps just `source_doubled`?

**Comment by shermp** [comment]
Can't say much about the logic itself, but just a couple of very minor naming nits/queries.

File: src/gui/sdlmain.cpp (hunk 2 above)
Comment (kcgen) [reply src/gui/sdlmain.cpp:259]: Bool is the one unique type that holds metadata about something instead of the actual thing. One of the styles we've tried to add is always including a boolean-ess adjective to functions and variables that are or return book (instead of the actual thing). 

Take these:

- aspect_ratio
- doubled_source

You can't tell if those hold the actual aspect ratio and actual 'source' or if they're bools. But then.. 

- have_aspect_ratio
- source_is_doubled

Immediately disambiguates them.  Just a few extra characters might a big difference.

Comment (kcgen) [reply src/gui/sdlmain.cpp:259]: Lots of words can be used to add this booleaness and some even help add intent as well: have, should, wants, is, prefers,  ... (Surely lots more)

Comment (shermp) [reply src/gui/sdlmain.cpp]: Fair enough. Carry on.

File: src/gui/sdlmain.cpp (hunk 1 above)
Comment (kcgen) [reply src/gui/sdlmain.cpp]: Switched.

**Review by shermp — APPROVED** [review]
