### PR TITLE
Fix regression in palettized VGA line draw function

### LINKED ISSUE #2488: Commander Keen 4 flickering pixel lines
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using latest DEV version this happen right in the first level when walking up the little hill.

Bildschirmfoto 2023-05-16 um 17 40 36

Bildschirmaufnahme 2023-05-16 um 17 28 00

Doesn't happen in 0.74-3 vanilla or 0.80.1 Staging.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install Commander Keen 4 (eXoDOS version)
2. Run in DOSBox Staging 0.81.0 alpha DEV.
3. Walk up the small hill in first level.

### Download URL of affected game or software

_No response_

### Your configuration

```ini
default
```

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #2488. Thanks for flagging this @Burrito78.

Had to revert to the `vgaonly` instance of this function (where it contains separate code paths for the wrapped and unwrapped portions), and then re-added the address and palette iterators like in the (now gone) lamda version.

Included notes on how the code can be exercised in case this code gets touched again.

### CODE REVIEW

File: src/hardware/vga_draw.cpp [hunk 1]
```diff
@@ -351,42 +351,45 @@ static uint8_t * VGA_Draw_Linear_Line(Bitu vidstart, Bitu /*line*/) {
...
-
-	const auto copy_palette = [&](auto pos, auto len) {
-		auto line_addr      = vga.draw.linear_base + pos;
-		const auto line_end = line_addr + len;
-		while (target_addr < target_end && line_addr < line_end) {
-			memcpy(target_addr, palette_map + *line_addr++, bytes_per_pixel);
-			target_addr += bytes_per_pixel;
+	const auto offset = vidstart & vga.draw.linear_mask;
+	const uint8_t *ret = &vga.draw.linear_base[offset];
+	const auto palette_map = vga.dac.palette_map;
```
Comment (johnnovak) [inline src/hardware/vga_draw.cpp]: very minor: clang reformat

**Review by johnnovak — APPROVED** [review]
I'm not close enough to this to understand it, and don't want to spend the time to get into the details... so if it works, it works 😄 Hopefully it won't cause regressions in other games. The comments are nice 👍🏻

File: src/hardware/vga_draw.cpp (hunk 1 above)
Comment (kcgen) [reply src/hardware/vga_draw.cpp]: (yup - that's the reverted content), the next commit fixes it up.
